<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis simplifyMaxScale="1" styleCategories="AllStyleCategories" hasScaleBasedVisibilityFlag="0" version="3.14.1-Pi" simplifyDrawingHints="0" simplifyLocal="1" simplifyAlgorithm="0" simplifyDrawingTol="1" readOnly="0" labelsEnabled="0" maxScale="0" minScale="100000000">
  <flags>
    <Identifiable>1</Identifiable>
    <Removable>1</Removable>
    <Searchable>1</Searchable>
  </flags>
  <temporal durationField="" durationUnit="min" accumulate="0" fixedDuration="0" startField="" endField="" startExpression="" endExpression="" mode="0" enabled="0">
    <fixedRange>
      <start></start>
      <end></end>
    </fixedRange>
  </temporal>
  <renderer-v2 toleranceUnitScale="3x:0,0,0,0,0,0" forceraster="0" tolerance="20" toleranceUnit="MM" enableorderby="0" type="pointCluster">
    <renderer-v2 forceraster="0" enableorderby="0" type="singleSymbol" symbollevels="0">
      <symbols>
        <symbol alpha="1" name="0" clip_to_extent="1" type="marker" force_rhr="0">
          <layer pass="0" locked="0" class="SvgMarker" enabled="1">
            <prop k="angle" v="0"/>
            <prop k="color" v="231,113,72,255"/>
            <prop k="fixedAspectRatio" v="0"/>
            <prop k="horizontal_anchor_point" v="1"/>
            <prop k="name" v="base64:PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIGlkPSJteVN2ZyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+Cgk8aW1hZ2UgaGVpZ2h0PSIxNjAiIHdpZHRoPSIxNjAiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBS0FBQUFDZ0NBWUFBQUNMejJjdEFBQUFDWEJJV1hNQUFBN0VBQUFPeEFHVkt3NGJBQUFnQUVsRVFWUjRuTzJkVzVBYzEzbmZmMTlQeit3RnQrVml0UVJCQ2x5Qm9DUkROSU1vamxKeGtncFRLVnVTeTRSb2wweUhMcHVrb3FwY0hseDVTWlhMRHlsSGVVZ3FUeW1YSzJYbllnRVU1VlFjVnlJQm9FVEpwUXVMU1dpVlE2dW9tQUloQ0tRUUVpVEJKYkJZQUl1OXpPVjhlVGpuOUdXbTU3WXpPOU83MjMvVW9udiszWDNPNmRPbnYrLzh6NjFGVmRsVk9QdkZ3d0ExRFk0cmNoeEE0QUVBVktlQmFRQUM1dDBWMHlEVEFFYVpjK2RQSSs0OE5VWkVVTlZWa0ZYTGNVMUVVSFFWa1JWM3pUVnNWcStxc2k2Q1FmUXZBUkE1WDU2YVBvOHEvTnpqdDBRa1VGWGp0L2FVbmNrRnczdXlCUXIwRCtsa0FaTWxkOXZnN0JjbkZTb0FkUWtlQXNBd0I4NmlDUjhEUUprRDhWWnV4bTYwQW9UdXZMM3VXQWhTQVZCMVZnOE5SV3djZ0hISDZrRFZYaXFyTGxlckNIWEw0YTFqRlN3SHVvZ0FLbGVCUlh1WUh5SUVLSXNpc29oQ2VYcnFBcUtnVXBlZmY5emt6WW9Od29XZG51VzJLM3dXRmJDRlIrRVRsdEtQaVhPM0lEL3JPSkNtS3hXUUpsTGo4NkpEQ2hHcEdpQ0NvQ0VpazZnQ3VsOUU3TFg0clE5QTdUWjY4UVZRb3lwMUVVRDRscVBQQTM5cG85RTMzSG5nQ3ZsT1FlR0NDNHdWSFYxdzNsRTllK3JqZ253Y0FKWFBBeWpjSjhKOXFSTlYyMWkySVhDYXNHalNaTzJHektucUplQWlRQ2tJZnQrbDVtSjQ4cWxMZVhPdHZYSWRYWERlSVdrZjZxeTVjM3NGdGdXMmpRV3NubnRtSGk4a0dqd0NnT2lESWh3RlVPVUVnQ0Q3RWZhbkx0NDVGbkFKV0xJLzVXV1htamVBMTIxMm1HKzU2MjZWSC91SHQvSm03Yks0YldRQmRSNG5KRlQwTndFRW1RTm1JU2tRZHE0RkZKaEZaQlpWVUQzbWJ2b0s2SnRXN0hEQkZscXVBTGZHbk55ZXNJMEtZRnlvUktXWjJzVkl2SEJDdHNYT01YTHBndXZubmwwQWpnQ29tdDkxOUNIM0YyTXJYV3V2M0FoZGNCK3UraUlpRjBHaFZQcHRsK3JGaVY5ODhscmVYSERSREZOZ3JCaS9CWHorK1VBaEVLQldmZStrVFpWOEdQaUlPK05UQUdvYmwvZW1yczJxN28yYXk1OEJSSlVsSk9wNy9oWTJ1VDhVZUJVZ3JFNy9MMzhyOHZqajdHb1I0Z3BmWURzWDVKZGNhLy9EN2krQ1pOWnRjbElDRVNTMVpkemNMTWlzUzlzeGQrQUZoUm1YNnFnQWpodUZDeTR3Vm96UEJYL3QxRkdBV2tOK1RWV2VjTWJ0ZU52ejh5QTRzcmdjaXBDdW5QQ2lNNXgvVW1iaXZ3Rnc4b25GUW9RVTJIVVlxUVdzbm4zbUVNbzhBcUw2RzQ0K2djZ0pBSVU1SWE1aHBWS1doK3BlRnJjZERhRG9tMnJUL2dvaWZ3RVF3SmZjSFMyWFAvUDB5SHBSUmlwQ0ZPWkY5Q0ZGRU9TZk9McmkvcUpuMnJ5TnJoNTdhY3ZpY2lsQ09uUEtFUkZCaFZuOGtEWGxCVGZtRUViWWkxSzQ0QUpqeGRhNTRPZWZEelZ1My90REc1czhERHdjdjVldDdyWnd3ZVBTSlhaa044b0xJbndiSVB6TVUvOTYyN3JnbGtMa1ZHTW5BZG1PczlkblJKSUh6dTFMMDNiYmNVcExwamNYRmhFSkFJYkpEZDBDVnMrY2N2TXNnb2RFZU1qUm53ZEFPWVF3WDFqQVBISzJaZzVjeGswQk1NSXBkMzhYS3BRdm9BS2ZlV0lsN3had0hqQ2dmeGZrczQ0NzNxdTFLeXpndUxqb3dBTElBZ0JLMVozekZUdkVTNDJJckE3VEFtNUZBVFEwaVJ0MU41bmMwZ2NYQjlJVVV4NjRIV01CTTdqNGQ0QmdVR2twUVBtemdDSmZjRVhuT0hCOGl5Uk9nUkZBbEUvWndxajdxMVEvQkZDQjN4cG1IRnRnQVRXeUVKdHh0NFVMemgrWHhMQ0Z5VkJFU1BYTXFXTlJ2VUh3QTBqbkJabnJWM0JrY1pBZzg4YnRaQmNjY1hvRmVCT0FnSC9zbnM3aXhNblBEVHpBZFVnV1VCYUFud01RWkNEQlVWakFQSEp5SDlpcHJob05HQkZVZFRFbklpUTJDWU1LamtLRTVKeVQyRDhOUTRRTTVJSWJaNzcwV1FDRC9pckNaNVBQWnJQdXRuREIrZVlFMXUxOTZ4Y1YvVStDVUg3czZWZHlvNEtGd2R4dDRZSnp6aVdzZ2w4WVlCQmgwcmNGckQzMzVYaHVScVB4N3h6OUVLN1hvN0NBN2o1MkxsZTN6MGEvaC9JOWdFbzQ4VHN1TityeTZLL1Z0OW9DN29WbzhjYkgzRFlLcDdDQWlVTTdrN1BQV25sWWhhTmlPeDcrclhzclYxVzFPZ29SMHRyVGtkeVg5SllCdVpaSThzVHRQZ3NZRjBnd2pncEFVaFl1dVQ5Y0M5aW8vekx3VDExS0p2dSt2c0FPZ2V3WFlUOEt0Y2JHN3pueVQ0RC8wVThvUXhFaHpSNnBjTUc3ak5PbzFyNTFJcVI2NXJTZnAvc2JBays2Mk9jaHd3VTNiUm1RU3dVOGFrNEViTjRSVEZ2dHBkVjF0TG9SWFpNMzl6ajZwaGs5NzdMaUdRaStoRURsNUpOWGgrdUNKWm95ZVpSNGJXVjNLTDIvc3l4Z0FLV1MzZDkzd0ZLM0FWOEFDd3NJMGZMSFBBQTZqeEtJeU9Kd1JValNSR1VjU2xsQTJVRWlKSUVnT2szanRCVVdNT0lBZzBxQVlIb2R0dFdsQUg0aFZydHkvNzl4T3pPZHI5bFpDT1lQRTl4ekJBQ3R1ZlhCNjNWWTJSYkw3NDBXcWorUG1xUHVMZjVrTDVjVXMrSUtqQlVkUlVqdHVWT0hjV3Z5cVFtK0RZRHFwRUNxK2NYT0p0QjRmOGptUGNtbkVqOENMcmh2Z2VEd2dyMjNrbXVEZmZzbm1MY3YyMnRNbzBWNGtkamZUUnlxeTdnbGhBUGw3Mk1OM0hMNDJOTkx0RUZuRjZ4eUNMZEtsYmlQdVdoS0dTUWgyVCt6aE1RbU9GVmFvaGdGUjFDQzhvUk56dlFlZTk3RVZDUk10TkhJWFYxc2JCd3lJOEtNNVhUQjVhQVJrZVYyZGNEQ0JSY1lLekl0b0Q3L2ZFVUFWWGtFNVRjUjdTUU9kelpXYnNKN2J3RVFmT3l2QXlCSGY0cmczZzhCWUY0L2o0allkc0Y2elE2WHExU3NSYmk5ak81U3NhSUJYMUJiSVR0RnZPNU1Dd29MV0dDc3lMU0E5ZnFpKzhZYUR5TE1RTEoyN3F1ZlNTUTVTZGRRbXkvYkRNZjRSSWl1cldLV0Z1MFB0NVZ5Qlptd09zdzMwWWp2SFZFdzcvNEVFTFJXamRvMDhiY2w3Qlp1d1ZXb0g2aWRPWFcwZnZaMEVKNTgrcUt2Qy9wdHRndkcvSXdnaU8zMXNPMStLZkdSNVpCM3BnalJ0VlYwM1g3b1VwYXZXWEptam1DZnl4YmZScmkraW15c293cDY2Vlg3empZYVVjOFE1RkEwYkNrblIyeVIwYU1veDF5K1hpeEVTSUZjSWRNQ2lwRW5BTlIrK0srQXgvWDNBTkNnaEptY0FzQzg5RTFBMEdvVjZ0WFdtc3B1enovbGhFTG9xbFBmYUQ1Y1dNQUNZMFhjRS9MMTB4WDFYeHF2OFNQMzh1Nm42ZHNjeVY2UExHNm45WVRJNUNReVlhMWQ4T0JQVzNMUFBtVGFmZyt4OGRwZldHTjNhd2x6ODRiTkIyTnkxMHN4Tms3MUt2QU9RUG0rNnQvQXIwUDQxLzVSa3doUktpSnFDNXNFaHp0N2p0MGpRbVJpQ3BrNUNCQzEvU1VSekI4R3hBcU9sVnMyakVZMVIySmd2QnoyWTVMVGNTWVRJaGdSdTlCUjRZSUxqQldSQmF3MU9JNy8rdmh1UmFrVTlmR0d4MjJ2QnpPekJBZG0yMTRTM0hNL0FITHdFSHowQkFxWVAvK09mZjNYVjJGamZhdFRuV3NvVWhHaG9ncjF0eXAvMjlHWGNXdk5GQmF3d0ZnUldVQlZab0dmQWxwRVJocStxdG1PazNSdE5LdFpvbCtPclJVY01tbDdOV1RmWGVBYW1KbXhWcy8zZUNTaHFvaXI0RVQ3cFFDb0lLSUVDL1k3aTNwekNiMTF3OTdLamZmejFFc3hGczRveDl5dlc2cDZHZEx0Z1BQQVI2T24weEU3UzRUSXBLMGp5OEY1NUpEdDJlamtkaVdSUDM1ZlNpRzRxU1BpQ3FCWmZOdnlxdFNYM3MrZFFCZzVKenpvTXYxeTBSTlNJQmNJT2Z1SGV3R0Uwa2NVZVdUTTZSa1paSEl5c256aDMzVFRGeElpWkJnSTV1K0YrWHR0SFB2dkFoSE11MitpYm5qWGJvUENZNjVtOVJid0hTaEVTSUV4STZ3U2ZOVHR6d25xRjU3cGdLMFhJUkpZU3lSS05CTnQ2SUpqOW02Q1dUZTkyUSt2RjJtcDNTWUZSeGJuOTVOYkcyZWFrd096SUlMVXFuRVdYWDFyYXlyK2dialprUnIzeXVSQWhLRE11WHYvZ0o0N05jdHpwd2tCKzBWdFlRNi9CRUJYYkxFSUtaV1Fjc1hlUk4wV3dHRUxqbUIybnVDRHg2TDRNdTdBY2htQ0xGT0VORzFiT05lYkltRHZUWlg2dTI5dFRjVmZBcVJVeW1HdmpNeTYxM1lPbUlQQ0JSY1lNMEpVL3FyYlB6VHVvVU9sdVVNb0VCeGVzUDJ1Q3VaSFB3REEzRmpFK0FHaEF5QTQ4YmNBYlB0ZXBUSndlSDNIZjJBV1hCTlA4TjRWYXgyR05IY2svT2dKdTNQWEhNRmRId0NGK2t2ZnNDWW9SNzB5Q29lcWhoT29GaGF3d0hnUkVrOHlEMXRxNzVrWXJnaVJxYjNJOUY1Yk4vcmdBNGlDN0oreDgzRUI3ajVzVDUyb0VMaGhVZWI5ZHl5bkJqWHB0R1NLa0lrSnBPTG05dnFlamJEY2NtZmRCRWNXMTZzSXllTHNTQnBRWTlDVlcvMVY2SVBBRG4zYk40UHNuN0g1ZHZCdWUvTGtOQVFsbExoWHhpeGZoNXZYYlVnM2I0eFZtQUFWMEwwSVFTakpBdGkxQjhSamVDSkVwdmNTekIwQ05CWUZDUVN1SGMxTVRDRVRkbUs0V1hJamt4dUFORkxuWnc2cHFrd2dmZzdINURUdDBFMXdaSEU5aTVBTVR1ZnZ0VW05ZmRPK2wvMVU2QVA3dUdUbUlLVjdQNFNpeU55aGREb0IzeXZEdTIraUtLaGlsbStNVlpnQUZSWDJDbEs0NEFMalJhaWk3cldSdmFQVUlPRURka2s1K2NCaHhGbTVUa2hXM2tzTjF6VHozdHVSTys2SS9iUElmUXViVHV0V3dTOTRHZXc3Z0Rrd2k2aGlidDdvNmRyd0U0OGdDRXpIVlppT2NkMXpCTndNdm5xdE5sVHgweTlVMll2S1BVclJERk5nekFoUjhYTStLcTNpSWd0REVpRXpjNWJ2VUNkTElsbnhGM2V0M3I0Wmk1V0dyUXRtaVJDQ0FKclc0dHlNNE1qaUJoRWhuaU1Nd1Frc3VkVkJJSVFoaEdVRVJhYjIyb05PVFBVbGZtYm5RRUZydGY3Rnp4QTQ3TnlqdlFDaHhKT09LaU1WSVhmTldSY1M5dFlXbHl3RXZndE5yNzhYRHg0d3RnQm1pUkJFNG9LYUVkNGczQ0FpSkVLcGpFeE9vYXFwU250TDVUME1rY2twVUVYMjdPczVUYzJjenN6WjN5dWJFRDlENEpDNEFCWXV1TUJZRWFwYmdCSVlxUWdKd2dscnFZTE5EMytTVW9uQTlSa2J2M3h1RnNJS3VMWDljb2x5R2FiMjBLMEtKS1VRS1ZkNmE2N3RoQ0hrL1NDd0lrUVBJVVV6VElFeEl5UlpCeHhoVDRoWlc3SDB4QlJTbXVvYWE2cmlYM1hOTUxWcXRFOVR2U01GMDRCYXJXMTRnM0JERVNIR1FITFlXZE0ydWozM2FRaFZSUnQxQkxGRHlJS2d2M2pYVm15ajlKaFc3OEoyZWt3Q2hDSlJBUXl6eFVVV2hpQkMxbTdiblZJSjZGNEFrNFZBNis1QlZLdlJjQzBmZHFZSU1ZM29BV2VGTndnM0ZCSFNhRUM5QmwxRWlOWnFVSy9aWXcxRE5IYXl6M2dicTdmdDcxcDFQQ0lrMFFWY3VPQUNZMFdJNHNmb1RJTDIwQ1l5SEJkYy8vNUx0blhrMkVPVS9Kb3JIWkIwZStiVmx5MjNzdHlTbEN3WHJPdHJtSnZYQVZ5L2M4NWM4T29LZXUwcW9CMWRjSkl6RjM5Z3M5cjFKSFdOdDFGSEdnWVZSUy8rQUlNZ2pmcTRSa2xIRmpERVdVSDFtZEVGa3ZnL2k0dThyS1MzTFZ4V09lNFViOHFkSkdKdVNyS1NqdE9mMzN4dnVYTEJpZnRKdnJjZDN0L1dHayszZUYxZWlZb2RSUU9KYlpzNHRvaExJbFRVZFFiS2ZyUzdCUnphNmxodUg5TndILzRUcE1NQTBaVFZjU3VXcXFzUEpaRXBRdFpXWWVsOXUzKy9hN0IybGZkMmNmVEtEV1FCMTFZQVFkZlgzTndYYlhsb1B1Wm16dHhac2ZrWDFlTzZ4RnV2T1JHanp2S0pIYzdXSVk2dDRsRFdFWmJCcXBFVmQyeXl0WHkyWXVnVzBGZkFvZU1JNVZRaDhDTjdHL1VXYTVkbEFWbGZoVWJkN3JzZUU4bG9BeHUxQlRTcmQrd0xzN0VXS1ZMb3packkyb3JkUnVxNWk1VnQxS0c2aGlxb01TT3pkcG1jc0E2K0FDYlJRelBNc0MyZ1JtRjBMdjVwU3hSZjFZc0Z0R25UMUtWSzY2Y25SbTBCQlVWVld1Ni9WMnZTbktaTzhmcThrajZzN0ZaeEpQWkRZQkZBbEVuc1dtNmpnWnVleU1hYWRVV3FNTDIzNjJVQTVzNGRJTVBTdFkycmhxbGFLMXYvNFo4REVCdzZFaTB3UGxLWUJqUU1pTko0NVg4RGd0WTIrZzVHYnk3WkI3dXgxdHY1cXl2bzlmZmM2cERqaFNncndGWEJEa2F3YVpMb3Y4NFhKLzdQNG5wMndjbHJOZHZWcGVMSUVDRlo3clliRjRXVEVkMUlYSEJDRENSeWErQUtmVmNYbkJBNHBzODR0b29EMnd6ajY0RFZ0SUhNeHRDWDZIV3BzaTZwUTd3cHQ1Y09NNGx1bkM3YjVoajI3RWYzdTk0WS95WDBVYmpnMVJXNGN4TVVaL2tFZkhOSWxKK2JjR2M5dU9BczF6c21GMXhWV0FFbEJGc0FGYW9qYllaSlhqdENDNmkzM0lqakE3Tk9oUks1L2xGWVFOYXNLd1RRV20xZ2E5SkxtdnpadWJHQVFoVllBU0ZNSFJxbENQRmNGUFZvTEdERWtiQWFHWEZreFp1ZGx2NHNZQnpJY0N4Uk1rMmQ0ODJWQll6MlF4VzVpajFob1FjUFBEeVVLelpWRTFNdzFadjQ4QWoydU0rbTFxcFFyWFU1TzEvUUlFREQ4c0JaTFFkbUVZaFc4Tzk2L3RSZU9DZ0VLUFVCNHg0VVlyM3V1NElWSVlrakkzVEI3dFdJenU4V2I1TTc4ZHQrWFhEN01FZmtnb2ZrQ3B0VDFiMjNSZXhpVDlKSGI4c1djVW1FS0t0dWY3UWl4TzlIWVhRdWhBTzFBeWE0WU01TzNwYjlzeTJXZHhRdVdLYjNFR0RuUWN2VUhodE9kUU90MS9welo3NGhQWkdPVHZFU0JHaWxncWphNFZ1NG5wQkUxV2VFYnRuVkFhMEZ2T2tPVkhlREJmU1R0K1hBYktSK3MrUG9qZXU3R1daNkh6SnQ1M1Bvbm4zeHc2blgrckltUWFsa2o3bnV4SzRXTUhDanFWRzBGTnB3R2lEYUdJY0ZyQWFCSzRBa3NWTjdRaEtjNG9WSDY3Mk91aWZFNTRkUjdkdWErR3Y5YlhTMWdLTDQzaDl4ZTBMLzhRNkw4d2dSWG5IN1B6MVNFVExLbnBBZENMMStGUU9VL0hvdzNWQ3J3dW9kUUZ0R2g0OEJWMG9CMzRObUN6aEtGNXk4VnJOZFhUcHBTUmRqdDcwS2pwUUw3dUQwUitLQ0U1ejNBSkUxVGFTczN3cDlMK0xIZW9KOGlCQlZBaEZNaUhMWmNkZEEvYmoxdHNOUzh0QU9HSHprcjNRNHN6UDhDbEtTTVV1dVp4ZmNxTnYrWElCeWVkTXVXTzU3d09aQnRZclVPOHpxNjNnLzhRRGJUdkg2NnNwNEJ5T28rL1E4MTBWWUFVd1lWdmU4QVZBcjMza2YyMElOSW0wTFlCNHNZT2tqSnpxZXUxbjBhZ0ZwR0hBRnhvOWgzSlFGUE5LNkd0aG1zUjBzb01CVmQyaUpYM2o2RmtDZ3FvR3ErcEdaQmpDbzB1N1BDb2oyWEZUWlQydzdjaTZsL20xdGg2emo0K0pzaGQ2bTNSOVBidlBJZGJPQW8rQ3lFTXJqajl2Um5XZE9Yd0IxWDdTV3g5dWN2L3ZnaDA4QjVzZFdyNW1sYXhnM3dqcDg0RGdxSUxOM3c4RkRJTnJ6Y2lPN0RhcDh3eFhIUzU0TFJDUVFrUUFJb3JJcjdmOXNHMTU3cnRuTit0UGFjdEMzQ3g0cGg4U3ZkTHdUMzBOVTU3Qi9vcElwVE1iTlJTNlliQmM4Q3E3VlNVT29xZ2FnZHViME5jQ1d6QTd1TUE4aVpDU2NXMjFMbDY5RlE3ak1rcTFENjlwcWRBL2VFa3F0aHF5dTJKZHA0Y05zZXRMNEZuSGRYREFqNEJSNXpSNlJhTFg1MEZrL3FtZFBMUU0vdGxlMkx3cVMrRCtMaTk2M0pxdlhsbk1welowRjlLdHQzYnlPdWZLNjIxL0NKVGU2QjNQamZadTVxeXVJbS9vWmZ2Q1l0WWFibURTK1ZWeGtBY2ZaREJOd3dlMUhCVEJRVmFPcUJzVjQwMW1JRUdJLzBuUnYxb3FRM28vdnhPNkpnb0x2ZFNsRVNDdm5FVFZFbDRQZ0RWekpyT1ZpNWtBUHFGY3h2bFhmclJFams1TTlMM3JaTWVpZi9CQUF2ZlllMnN1eXVSdnJtSTExQkdpODhack44SU4zSTNQM0RKd1diaTVoUkpDd0RPVUp0cFBRVVR2aWZrVlZxVHoyOVBlYWowY2l4RmRwQUxOZFJBZ3EwWnNWaHprY0Z5elJ2OVpzVUpyMnlkNUcxWklCaFVUMERUc1JOaXQwSWhjOFloR1N5TnlXL0lhRUNPRzVMMFZEWkZCOXh3V3duM2oxTEhzb0J5SWttcGgrNHhybWhwdHc3dWJIQmpNSFViZUVyLy9vOUtZR0dheTZyS2hWV3pSWjFqMmtIc0RxaXIyWC9kVW9YSHR1SDBJaStyS1JZaTVmdEh3WVFxa01Bc0g5SDdheGhTRVNsbk1yUWtDWGdUZHBnMGlFWU1kb1ZRR3FYLzNpRmZmTzNZZElxZ0JLNHY4c0xucmZtcXhlVzg2bHRDOEw2Q2FtbTJ0WFVTY1FmQUUwR3g4azhDc2V1QUs0S1F1NFpnYzhVSysxR0ZWdkFhUDlwbTJ3ZHNmK3J2YzJhVHhUTkd5c283ZXM2REgvN3lJQ21LQmtQMElJeUtFakxsbFRkdDNvbklvUWhDVjg2MG9HSWhHUytrdWVrVU1SRWwwdkxVbnhaeVN5SVR2c2Jsd2NwcmJFSVRUdDA3VFYrTVh5NFc1R05IakVZV3UwRlkwa1RzL2hqVU9FZEVPWXlZcDh3MTM4aUNpSGV3aG5wS2kvOUUwQXhDUUdCVGpvMWJlb3YydS9TQjRldEFKQXlxN3l2aDJ3dG1JcjRtKzlqbkZpSm9JeFlLeFZyZi9aTjFHRVVvK3JpNDBMYXEzZjgrMEtZeVJDa24rcGszTW9RbUlCSUIwRmduOFRzOW8xdTdyZ0tNek9jV1M1czJUZDFvZmJzK0FBSzMwUzFqVXJEaVg5Y2UyOGk1QjJUemNXSVFsVXp6N3pQOTN1WVlXSEFVUjFodWpHMCtWNUpDS2t0aEVOcEZUL1RSQTFIUVdDV2JrSlFMQm5YOHZDUjExRlNNcDl0bzhqc3hDNisweTZZSHR1RHlMazlrM3JKR3NiblN2NWJvVXJxdXRPTUNsTTdjMlJDTkUzM2UxZkJGN1ZOb3VoSmtWSUJQM2ExMTVFaEdwdDhXRlZYWFlXYm9ZbzhQU0RrNWIvVzYxZVc4Nmx2cHNGcEZhTEpwS0w3NlZvQ3F1RmN3VlF5eFdrYWZoZkx4WXcydWtRUjliYkgwajZuSDVFaUxsenk1YmI2bnJuU3I1ZjRhcTZZU2U3S3dSdXJra2VSSWpBWlJmN2o4b25uMzZWTnNnVUlVaHM0K3hOU0ZUckhwY0lzVyt3LzZORkRHUnpyaEsrclVSSUluemlha1J6SE1tSDd5MWJua1JJcjhnV0laLytkRlVBT1hmNk93cExMak5QOVJGdVB1QkhHWnRHNS9QeWhPMlk1Z3hJRVB5VzI3M1M2YnhNRVNLSklWcFJhUjZ6Q0xFdXhQOGw2bDdwcERTSmtLZ3ZvelcwbklxUUxNdVNGVWZTMHNTQ3JIMGNrUXNla1FnaHNlMkVUQkhpVVh2dTFOWG9oN0hyQ0tyOW9sS3FzM1VVSXNTN1lHZ05NNGtrTjhnVXpIR0pFQitHU1lRSHJYSFFISi9MbjNHS0VOQWxqVWE2eUJWM3JPUDNZRE5GaUlmcXY3eUtHOGRmTzNPL1hjalMzbEdxQUVyTC82MVdyeTNuVXQrckJVeGVyNlREYXVZR21RRTNMaEdTL1dDekxVektBcW9RWkZqQXhOMk5Rb1JjQXk0QWhMLzRaRWZYNjVIZEUrTEZTQXJlMkJMWHdQTXVRdHkvTEdlUVd4R1NDTXZ2WjhXUmNuVUpDOWd1am00V2NCaGMvS1I2UjdZSWlmQTdVU0VNU3FmL0JZQXhQSUZTekJrcEVFTXhyamgraTRCLzM4MlhKZEZSaERRSmtoaUZDQ2xFU0lwTDljdjA5Zld0amlJa2ljWnpweSs0M1V1b0gxNmpSNERCUk1pZDI1ajMzN2FGME0ycGFLa0lnUjBkRW4yc0x4MW1FaWtSNG9iUTAyaEVIMGVNMEJ4K0U5ZnJ0MGl5Q3FGWlg3VTVjbjNSRHUzdG8wSVZEZnZmV090TkROeTVqVm0wK1dkV1Y5ckhzYkZ1ZTVQYVZCczZ4dEdGVStVVkZUWEFqMEg4NVBPZTBGR0VOT0VpUVBYTTZkY1JYd0RsaUwrLzlQK3RWcThkcDNkdXV5OC9Bc3ZYMnBZL2JUVGliM3o0UXRJVVZndm5sdVBWdFR1d2ZJMStvRzdJbHpZYUhlUElzZ2pSZDB5V0Z0SFYyLzA5WURjT01mb0FqVHV2YmRtOWN6ditCa3FiL0ZPd2s2eVNQVWp0d3RzRUo4TEw3dENsOHFOUDlWVUFPNHFRYkdHU01BZERFQ0c0U3JHLzFyMVJMUUtqT2I1ZVJFanNORnFGUks5L2tuRnRNbzRzYStLSFRmblZxSnF2NjhURithdUo4TExpOEdmR3o2TlRIRWwwQ204ejNDRG9Ja0phVVNiOEt2QWlRRTBhZitib2FaUk5UY1RROVhYckhwSXVUVnZkYTVhNzdZWjRGYTA3SGQxb3h6ZzJrOE4rbmtxdFNtUGxWaFNFWHhIVmI5dHhmVDNZeEZ5VWJuRU1vOEI0S0xvRUxDbFFNY0Z2TzNxOXd5V1o2Rm1FUkVPMU1rcUJBSnNXSVQxd1BRbU9NWEZaN213M2NNTkN6eUlrd3RrdnJ3T3VkcS8vMVc3NGhNTFBXRTZDdmtSSUQxeVNUeUlQWEZZaGhCM05PWFhHOTRHWEhPa3RYOS9ybi9jalFqeldmWVFiWjAvOUVZQ29Ub0o4SEVERXl2QmVSVWpQWXFYcGQxNjRMQ3ZCRHViRUZVQVIrWDZaMHJOQXdDLzl1bDludkcvMExVS3llMHJpMXJaK1JVZ3ZYQytDWTF4Y3hnUGEwVnh6K1dtbCtvTjA3d0xyanRxNTB5ZUFFd0JxNUZUaGduY1lwMW9Ic2U0MTBML25qbDhwUC9wMFQvMjluZEMzQ01rVUpzUlBxQkFoTzVHTGJWL3krRERRdndqSlFPM2M2YXRnRnp0WDFSZGRlaGNFT1ZKWXdKM0E2UVhnLzJMNUsrNTR4MkZXdldJeklpUUxpKzZQalRPblhuRGNJOENSUW9Sc2Z3N2hmSUQrZDREU281OGIyTzBtTVpBSWFTTk1iSUYyZDFDSWtPM1B4V2g2RTRlQW9ZaVFsa0JGZ28ydm5Qb3N5SytDZ3NndkZ5NTQrM0VHL1ZmdTkzY25Uajc5QWx1QW9ZaVFqTjRTdDhJV0lJUDNqdVJGY093MkVlSUw1dkR0WG95aGlKQm1PQXQ0SHVTUHJRVzAvY1NxSEJQa21POW1MeXhnampqVnVodlZkeDdoVlZIRkNOOTE1N1JkM1dwUURFdUVwS0NxUmtUT3ErcXJJaEpVejU2YXQ1T081Tk9vSGhWckhmdnFNZEdtMzNuaHNpd0gyNUFUcE81dTZaVUEvV05FS0o5ODZnVzJHRU1YSWE3d0JjbHQycDdiblVLRTVJdExJOFBzYnhHMlRJU2tDcURqYXVkT0xZQXNnS0pHdnVKT253UXFoUXNlUFlmcUxZVmx5d1dQdXBNV0s1OTVNcDZPdThYWU1oR1MzTVlGTVRLRFBoTUNFZyt5RUNHajVVaHdUWTltWk5neUVkTEdBaTZEWEhaWjhKOEZVT0VFOExBMUtUSlhXTUN0NXhSOVJ4RUR2QXo2ZjhTZXRPZ09OazJlMlZwc3BRaUpDbUdDVzFiVkpSRUo5TXl6L3dHZ1N1TWZBSWNSUVdBT1dpMGh4RlluRlU4T3VDd0xRODQ1UWQ1MEI3NWRuakQvQllCUGZtNkpNV0FrSWlSVG1DVGdNNm9RSWFQaFFJZHVkRGFMa1lxUVRPN2NINFFnSVNqMXh1US9CMUQwN3lEOExJQ3FYUVlrRCs0Mmk4dTlDMWIxbHUwRkF2MHVDdVg5SC9xRDZHWWVlYVR2VWN6RHhFaEZTRS9DcE9scDUwbHdiRWNSMGdLWDNlN1kyTDlJTkZJUjBzWUNHcEM2eTVJWFJRUVZmUWY0UG9BcUoxMndjK3JxaUhFOGhRVnM0b3lpb0x3RHZPUE9jcC9nNWNmQVJWL3lKQWVGRDBZdlFySTRWTFh1dUJkVjFlalh2L3lLaU94VlZXcTFoditzK0hHUmRBSDBsbWljWER1ck14Wk9NUzVaVjRDWEJTaFBtdDkxcDYvenljOXZldTdHVm1Gc0lxUVRKODZzaURjMWFoM011QVZIN2tXSVFHcVZ4VXdmbkMrTVg0VDB3QUhVeno2ekFCd0JNT2p2QVFnY1VwWDVkTnk3eXdWanY4TnhDYUJDNlorNVEwdWMvUFgrMWlJWkU4WXVRbnJobXFzSjNnSkFaNEd3RzBRSTJycUM2M2JDK0VWSTd4WncyZThyL0Q2QUtBOEN4eXluRHdFSXpDcjJreEp4ZXJhN0JkUzZpMjVKa1dWN24yb1hCQkl1aWYvUWVMUmdBTG1yNjdWREhrUklWODd4eXlMaUo4TDhSNERxVjA4L3JPZ0pBSkY0YlJxQlZBSHNKaVFHNGJLc0UwUG1CS3F1M3JtSThJYXI2VDNyenIwVW5ueXE3Y2NBODQ1Y2lwQm16bHZDNW5nQTRrVW9MWlNkSjBMUzhHdHV4Yzl3MEVJd1Rtd2JFZEl6L3ZUWkNtN1ZyOFo2NDFNQVJ2WERpRHdJb01ndnVEUDNvdWx2SVkvTEJlTldtc0x5WDhjV3F0Y0V2UWhDdUxIblJYZTY0VmQrWmF3OUY4UEd0aEloemZHMDQxcVE4S0crQXUvcFBJaVE1bWRDMUVnY08rYXRNQlI1d0xZUklXQmRjSE5jTGR5ZlBtdUlWMm02NEU1YVJPUThnTUJyN3RoQmZGMVJtYlhITkVUd1h6VzBmZEJLQlNTMHArbTB1OEdLK3JVVk5Wb1hvbzdZdWhySXFydTJpcXUvSWF5NkFsY0hyYnBxZzI4cVdRS3V1LzFMMkFLNFpDMmpHTUNJZllseTBYc3hUQWhiVUlmWUloRmltaTNjSUZ6MTNMUHpvSWNBZ29ZdUFCak1ORTdNaURBUG9JWjlpa3c2Ymc1c1FZd0dTUkM5QU9zaWZpeWRYTU1PdGwwUjVEYUFCbW9MbTdJYU9KVmFvblFCVzZpV3QwdTczYkN4OHl4Z2oxenQzTE1nNHJpTzdzMUlzaTRZUVhnQUFBQVpTVVJCVk1KbmQyTGZtVnlLdE9tNlRvRW1zSzFGeEtENC84VExVa3l6UWtVekFBQUFBRWxGVGtTdVFtQ0MiPjwvaW1hZ2U+Cjwvc3ZnPgo="/>
            <prop k="offset" v="0,0"/>
            <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="offset_unit" v="MM"/>
            <prop k="outline_color" v="35,35,35,255"/>
            <prop k="outline_width" v="0"/>
            <prop k="outline_width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="outline_width_unit" v="MM"/>
            <prop k="scale_method" v="diameter"/>
            <prop k="size" v="40"/>
            <prop k="size_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="size_unit" v="Pixel"/>
            <prop k="vertical_anchor_point" v="1"/>
            <data_defined_properties>
              <Option type="Map">
                <Option name="name" value="" type="QString"/>
                <Option name="properties"/>
                <Option name="type" value="collection" type="QString"/>
              </Option>
            </data_defined_properties>
          </layer>
        </symbol>
      </symbols>
      <rotation/>
      <sizescale/>
    </renderer-v2>
    <symbol alpha="1" name="centerSymbol" clip_to_extent="1" type="marker" force_rhr="0">
      <layer pass="0" locked="0" class="SvgMarker" enabled="1">
        <prop k="angle" v="0"/>
        <prop k="color" v="245,75,80,255"/>
        <prop k="fixedAspectRatio" v="0"/>
        <prop k="horizontal_anchor_point" v="1"/>
        <prop k="name" v="base64:PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIGlkPSJteVN2ZyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+Cgk8aW1hZ2UgaGVpZ2h0PSIxNjAiIHdpZHRoPSIxNjAiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBS0FBQUFDZ0NBWUFBQUNMejJjdEFBQUFDWEJJV1hNQUFBN0VBQUFPeEFHVkt3NGJBQUFnQUVsRVFWUjRuTzJkVzVBYzEzbmZmMTlQeit3RnQrVml0UVJCQ2x5Qm9DUkROSU1vamxKeGtncFRLVnVTeTRSb2wweUhMcHVrb3FwY0hseDVTWlhMRHlsSGVVZ3FUeW1YSzJYbllnRVU1VlFjVnlJQm9FVEpwUXVMU1dpVlE2dW9tQUloQ0tRUUVpVEJKYkJZQUl1OXpPVjhlVGpuOUdXbTU3WXpPOU83MjMvVW9udiszWDNPNmRPbnYrLzh6NjFGVmRsVk9QdkZ3d0ExRFk0cmNoeEE0QUVBVktlQmFRQUM1dDBWMHlEVEFFYVpjK2RQSSs0OE5VWkVVTlZWa0ZYTGNVMUVVSFFWa1JWM3pUVnNWcStxc2k2Q1FmUXZBUkE1WDU2YVBvOHEvTnpqdDBRa1VGWGp0L2FVbmNrRnczdXlCUXIwRCtsa0FaTWxkOXZnN0JjbkZTb0FkUWtlQXNBd0I4NmlDUjhEUUprRDhWWnV4bTYwQW9UdXZMM3VXQWhTQVZCMVZnOE5SV3djZ0hISDZrRFZYaXFyTGxlckNIWEw0YTFqRlN3SHVvZ0FLbGVCUlh1WUh5SUVLSXNpc29oQ2VYcnFBcUtnVXBlZmY5emt6WW9Od29XZG51VzJLM3dXRmJDRlIrRVRsdEtQaVhPM0lEL3JPSkNtS3hXUUpsTGo4NkpEQ2hHcEdpQ0NvQ0VpazZnQ3VsOUU3TFg0clE5QTdUWjY4UVZRb3lwMUVVRDRscVBQQTM5cG85RTMzSG5nQ3ZsT1FlR0NDNHdWSFYxdzNsRTllK3JqZ253Y0FKWFBBeWpjSjhKOXFSTlYyMWkySVhDYXNHalNaTzJHektucUplQWlRQ2tJZnQrbDVtSjQ4cWxMZVhPdHZYSWRYWERlSVdrZjZxeTVjM3NGdGdXMmpRV3NubnRtSGk4a0dqd0NnT2lESWh3RlVPVUVnQ0Q3RWZhbkx0NDVGbkFKV0xJLzVXV1htamVBMTIxMm1HKzU2MjZWSC91SHQvSm03Yks0YldRQmRSNG5KRlQwTndFRW1RTm1JU2tRZHE0RkZKaEZaQlpWVUQzbWJ2b0s2SnRXN0hEQkZscXVBTGZHbk55ZXNJMEtZRnlvUktXWjJzVkl2SEJDdHNYT01YTHBndXZubmwwQWpnQ29tdDkxOUNIM0YyTXJYV3V2M0FoZGNCK3UraUlpRjBHaFZQcHRsK3JGaVY5ODhscmVYSERSREZOZ3JCaS9CWHorK1VBaEVLQldmZStrVFpWOEdQaUlPK05UQUdvYmwvZW1yczJxN28yYXk1OEJSSlVsSk9wNy9oWTJ1VDhVZUJVZ3JFNy9MMzhyOHZqajdHb1I0Z3BmWURzWDVKZGNhLy9EN2krQ1pOWnRjbElDRVNTMVpkemNMTWlzUzlzeGQrQUZoUm1YNnFnQWpodUZDeTR3Vm96UEJYL3QxRkdBV2tOK1RWV2VjTWJ0ZU52ejh5QTRzcmdjaXBDdW5QQ2lNNXgvVW1iaXZ3Rnc4b25GUW9RVTJIVVlxUVdzbm4zbUVNbzhBcUw2RzQ0K2djZ0pBSVU1SWE1aHBWS1doK3BlRnJjZERhRG9tMnJUL2dvaWZ3RVF3SmZjSFMyWFAvUDB5SHBSUmlwQ0ZPWkY5Q0ZGRU9TZk9McmkvcUpuMnJ5TnJoNTdhY3ZpY2lsQ09uUEtFUkZCaFZuOGtEWGxCVGZtRUViWWkxSzQ0QUpqeGRhNTRPZWZEelZ1My90REc1czhERHdjdjVldDdyWnd3ZVBTSlhaa044b0xJbndiSVB6TVUvOTYyN3JnbGtMa1ZHTW5BZG1PczlkblJKSUh6dTFMMDNiYmNVcExwamNYRmhFSkFJYkpEZDBDVnMrY2N2TXNnb2RFZU1qUm53ZEFPWVF3WDFqQVBISzJaZzVjeGswQk1NSXBkMzhYS3BRdm9BS2ZlV0lsN3had0hqQ2dmeGZrczQ0NzNxdTFLeXpndUxqb3dBTElBZ0JLMVozekZUdkVTNDJJckE3VEFtNUZBVFEwaVJ0MU41bmMwZ2NYQjlJVVV4NjRIV01CTTdqNGQ0QmdVR2twUVBtemdDSmZjRVhuT0hCOGl5Uk9nUkZBbEUvWndxajdxMVEvQkZDQjN4cG1IRnRnQVRXeUVKdHh0NFVMemgrWHhMQ0Z5VkJFU1BYTXFXTlJ2VUh3QTBqbkJabnJWM0JrY1pBZzg4YnRaQmNjY1hvRmVCT0FnSC9zbnM3aXhNblBEVHpBZFVnV1VCYUFud01RWkNEQlVWakFQSEp5SDlpcHJob05HQkZVZFRFbklpUTJDWU1LamtLRTVKeVQyRDhOUTRRTTVJSWJaNzcwV1FDRC9pckNaNVBQWnJQdXRuREIrZVlFMXUxOTZ4Y1YvVStDVUg3czZWZHlvNEtGd2R4dDRZSnp6aVdzZ2w4WVlCQmgwcmNGckQzMzVYaHVScVB4N3h6OUVLN1hvN0NBN2o1MkxsZTN6MGEvaC9JOWdFbzQ4VHN1TityeTZLL1Z0OW9DN29WbzhjYkgzRFlLcDdDQWlVTTdrN1BQV25sWWhhTmlPeDcrclhzclYxVzFPZ29SMHRyVGtkeVg5SllCdVpaSThzVHRQZ3NZRjBnd2pncEFVaFl1dVQ5Y0M5aW8vekx3VDExS0p2dSt2c0FPZ2V3WFlUOEt0Y2JHN3pueVQ0RC8wVThvUXhFaHpSNnBjTUc3ak5PbzFyNTFJcVI2NXJTZnAvc2JBays2Mk9jaHd3VTNiUm1RU3dVOGFrNEViTjRSVEZ2dHBkVjF0TG9SWFpNMzl6ajZwaGs5NzdMaUdRaStoRURsNUpOWGgrdUNKWm95ZVpSNGJXVjNLTDIvc3l4Z0FLV1MzZDkzd0ZLM0FWOEFDd3NJMGZMSFBBQTZqeEtJeU9Kd1JValNSR1VjU2xsQTJVRWlKSUVnT2szanRCVVdNT0lBZzBxQVlIb2R0dFdsQUg0aFZydHkvNzl4T3pPZHI5bFpDT1lQRTl4ekJBQ3R1ZlhCNjNWWTJSYkw3NDBXcWorUG1xUHVMZjVrTDVjVXMrSUtqQlVkUlVqdHVWT0hjV3Z5cVFtK0RZRHFwRUNxK2NYT0p0QjRmOGptUGNtbkVqOENMcmh2Z2VEd2dyMjNrbXVEZmZzbm1MY3YyMnRNbzBWNGtkamZUUnlxeTdnbGhBUGw3Mk1OM0hMNDJOTkx0RUZuRjZ4eUNMZEtsYmlQdVdoS0dTUWgyVCt6aE1RbU9GVmFvaGdGUjFDQzhvUk56dlFlZTk3RVZDUk10TkhJWFYxc2JCd3lJOEtNNVhUQjVhQVJrZVYyZGNEQ0JSY1lLekl0b0Q3L2ZFVUFWWGtFNVRjUjdTUU9kelpXYnNKN2J3RVFmT3l2QXlCSGY0cmczZzhCWUY0L2o0allkc0Y2elE2WHExU3NSYmk5ak81U3NhSUJYMUJiSVR0RnZPNU1Dd29MV0dDc3lMU0E5ZnFpKzhZYUR5TE1RTEoyN3F1ZlNTUTVTZGRRbXkvYkRNZjRSSWl1cldLV0Z1MFB0NVZ5Qlptd09zdzMwWWp2SFZFdzcvNEVFTFJXamRvMDhiY2w3Qlp1d1ZXb0g2aWRPWFcwZnZaMEVKNTgrcUt2Qy9wdHRndkcvSXdnaU8zMXNPMStLZkdSNVpCM3BnalJ0VlYwM1g3b1VwYXZXWEptam1DZnl4YmZScmkraW15c293cDY2Vlg3empZYVVjOFE1RkEwYkNrblIyeVIwYU1veDF5K1hpeEVTSUZjSWRNQ2lwRW5BTlIrK0srQXgvWDNBTkNnaEptY0FzQzg5RTFBMEdvVjZ0WFdtc3B1enovbGhFTG9xbFBmYUQ1Y1dNQUNZMFhjRS9MMTB4WDFYeHF2OFNQMzh1Nm42ZHNjeVY2UExHNm45WVRJNUNReVlhMWQ4T0JQVzNMUFBtVGFmZyt4OGRwZldHTjNhd2x6ODRiTkIyTnkxMHN4Tms3MUt2QU9RUG0rNnQvQXIwUDQxLzVSa3doUktpSnFDNXNFaHp0N2p0MGpRbVJpQ3BrNUNCQzEvU1VSekI4R3hBcU9sVnMyakVZMVIySmd2QnoyWTVMVGNTWVRJaGdSdTlCUjRZSUxqQldSQmF3MU9JNy8rdmh1UmFrVTlmR0d4MjJ2QnpPekJBZG0yMTRTM0hNL0FITHdFSHowQkFxWVAvK09mZjNYVjJGamZhdFRuV3NvVWhHaG9ncjF0eXAvMjlHWGNXdk5GQmF3d0ZnUldVQlZab0dmQWxwRVJocStxdG1PazNSdE5LdFpvbCtPclJVY01tbDdOV1RmWGVBYW1KbXhWcy8zZUNTaHFvaXI0RVQ3cFFDb0lLSUVDL1k3aTNwekNiMTF3OTdLamZmejFFc3hGczRveDl5dlc2cDZHZEx0Z1BQQVI2T24weEU3UzRUSXBLMGp5OEY1NUpEdDJlamtkaVdSUDM1ZlNpRzRxU1BpQ3FCWmZOdnlxdFNYM3MrZFFCZzVKenpvTXYxeTBSTlNJQmNJT2Z1SGV3R0Uwa2NVZVdUTTZSa1paSEl5c256aDMzVFRGeElpWkJnSTV1K0YrWHR0SFB2dkFoSE11MitpYm5qWGJvUENZNjVtOVJid0hTaEVTSUV4STZ3U2ZOVHR6d25xRjU3cGdLMFhJUkpZU3lSS05CTnQ2SUpqOW02Q1dUZTkyUSt2RjJtcDNTWUZSeGJuOTVOYkcyZWFrd096SUlMVXFuRVdYWDFyYXlyK2dialprUnIzeXVSQWhLRE11WHYvZ0o0N05jdHpwd2tCKzBWdFlRNi9CRUJYYkxFSUtaV1Fjc1hlUk4wV3dHRUxqbUIybnVDRHg2TDRNdTdBY2htQ0xGT0VORzFiT05lYkltRHZUWlg2dTI5dFRjVmZBcVJVeW1HdmpNeTYxM1lPbUlQQ0JSY1lNMEpVL3FyYlB6VHVvVU9sdVVNb0VCeGVzUDJ1Q3VaSFB3REEzRmpFK0FHaEF5QTQ4YmNBYlB0ZXBUSndlSDNIZjJBV1hCTlA4TjRWYXgyR05IY2svT2dKdTNQWEhNRmRId0NGK2t2ZnNDWW9SNzB5Q29lcWhoT29GaGF3d0hnUkVrOHlEMXRxNzVrWXJnaVJxYjNJOUY1Yk4vcmdBNGlDN0oreDgzRUI3ajVzVDUyb0VMaGhVZWI5ZHl5bkJqWHB0R1NLa0lrSnBPTG05dnFlamJEY2NtZmRCRWNXMTZzSXllTHNTQnBRWTlDVlcvMVY2SVBBRG4zYk40UHNuN0g1ZHZCdWUvTGtOQVFsbExoWHhpeGZoNXZYYlVnM2I0eFZtQUFWMEwwSVFTakpBdGkxQjhSamVDSkVwdmNTekIwQ05CWUZDUVN1SGMxTVRDRVRkbUs0V1hJamt4dUFORkxuWnc2cHFrd2dmZzdINURUdDBFMXdaSEU5aTVBTVR1ZnZ0VW05ZmRPK2wvMVU2QVA3dUdUbUlLVjdQNFNpeU55aGREb0IzeXZEdTIraUtLaGlsbStNVlpnQUZSWDJDbEs0NEFMalJhaWk3cldSdmFQVUlPRURka2s1K2NCaHhGbTVUa2hXM2tzTjF6VHozdHVSTys2SS9iUElmUXViVHV0V3dTOTRHZXc3Z0Rrd2k2aGlidDdvNmRyd0U0OGdDRXpIVlppT2NkMXpCTndNdm5xdE5sVHgweTlVMll2S1BVclJERk5nekFoUjhYTStLcTNpSWd0REVpRXpjNWJ2VUNkTElsbnhGM2V0M3I0Wmk1V0dyUXRtaVJDQ0FKclc0dHlNNE1qaUJoRWhuaU1Nd1Frc3VkVkJJSVFoaEdVRVJhYjIyb05PVFBVbGZtYm5RRUZydGY3Rnp4QTQ3TnlqdlFDaHhKT09LaU1WSVhmTldSY1M5dFlXbHl3RXZndE5yNzhYRHg0d3RnQm1pUkJFNG9LYUVkNGczQ0FpSkVLcGpFeE9vYXFwU250TDVUME1rY2twVUVYMjdPczVUYzJjenN6WjN5dWJFRDlENEpDNEFCWXV1TUJZRWFwYmdCSVlxUWdKd2dscnFZTE5EMytTVW9uQTlSa2J2M3h1RnNJS3VMWDljb2x5R2FiMjBLMEtKS1VRS1ZkNmE2N3RoQ0hrL1NDd0lrUVBJVVV6VElFeEl5UlpCeHhoVDRoWlc3SDB4QlJTbXVvYWE2cmlYM1hOTUxWcXRFOVR2U01GMDRCYXJXMTRnM0JERVNIR1FITFlXZE0ydWozM2FRaFZSUnQxQkxGRHlJS2d2M2pYVm15ajlKaFc3OEoyZWt3Q2hDSlJBUXl6eFVVV2hpQkMxbTdiblZJSjZGNEFrNFZBNis1QlZLdlJjQzBmZHFZSU1ZM29BV2VGTndnM0ZCSFNhRUM5QmwxRWlOWnFVSy9aWXcxRE5IYXl6M2dicTdmdDcxcDFQQ0lrMFFWY3VPQUNZMFdJNHNmb1RJTDIwQ1l5SEJkYy8vNUx0blhrMkVPVS9Kb3JIWkIwZStiVmx5MjNzdHlTbEN3WHJPdHJtSnZYQVZ5L2M4NWM4T29LZXUwcW9CMWRjSkl6RjM5Z3M5cjFKSFdOdDFGSEdnWVZSUy8rQUlNZ2pmcTRSa2xIRmpERVdVSDFtZEVGa3ZnL2k0dThyS1MzTFZ4V09lNFViOHFkSkdKdVNyS1NqdE9mMzN4dnVYTEJpZnRKdnJjZDN0L1dHayszZUYxZWlZb2RSUU9KYlpzNHRvaExJbFRVZFFiS2ZyUzdCUnphNmxodUg5TndILzRUcE1NQTBaVFZjU3VXcXFzUEpaRXBRdFpXWWVsOXUzKy9hN0IybGZkMmNmVEtEV1FCMTFZQVFkZlgzTndYYlhsb1B1Wm16dHhac2ZrWDFlTzZ4RnV2T1JHanp2S0pIYzdXSVk2dDRsRFdFWmJCcXBFVmQyeXl0WHkyWXVnVzBGZkFvZU1JNVZRaDhDTjdHL1VXYTVkbEFWbGZoVWJkN3JzZUU4bG9BeHUxQlRTcmQrd0xzN0VXS1ZMb3packkyb3JkUnVxNWk1VnQxS0c2aGlxb01TT3pkcG1jc0E2K0FDYlJRelBNc0MyZ1JtRjBMdjVwU3hSZjFZc0Z0R25UMUtWSzY2Y25SbTBCQlVWVld1Ni9WMnZTbktaTzhmcThrajZzN0ZaeEpQWkRZQkZBbEVuc1dtNmpnWnVleU1hYWRVV3FNTDIzNjJVQTVzNGRJTVBTdFkycmhxbGFLMXYvNFo4REVCdzZFaTB3UGxLWUJqUU1pTko0NVg4RGd0WTIrZzVHYnk3WkI3dXgxdHY1cXl2bzlmZmM2cERqaFNncndGWEJEa2F3YVpMb3Y4NFhKLzdQNG5wMndjbHJOZHZWcGVMSUVDRlo3clliRjRXVEVkMUlYSEJDRENSeWErQUtmVmNYbkJBNHBzODR0b29EMnd6ajY0RFZ0SUhNeHRDWDZIV3BzaTZwUTd3cHQ1Y09NNGx1bkM3YjVoajI3RWYzdTk0WS95WDBVYmpnMVJXNGN4TVVaL2tFZkhOSWxKK2JjR2M5dU9BczF6c21GMXhWV0FFbEJGc0FGYW9qYllaSlhqdENDNmkzM0lqakE3Tk9oUks1L2xGWVFOYXNLd1RRV20xZ2E5SkxtdnpadWJHQVFoVllBU0ZNSFJxbENQRmNGUFZvTEdERWtiQWFHWEZreFp1ZGx2NHNZQnpJY0N4Uk1rMmQ0ODJWQll6MlF4VzVpajFob1FjUFBEeVVLelpWRTFNdzFadjQ4QWoydU0rbTFxcFFyWFU1TzEvUUlFREQ4c0JaTFFkbUVZaFc4Tzk2L3RSZU9DZ0VLUFVCNHg0VVlyM3V1NElWSVlrakkzVEI3dFdJenU4V2I1TTc4ZHQrWFhEN01FZmtnb2ZrQ3B0VDFiMjNSZXhpVDlKSGI4c1djVW1FS0t0dWY3UWl4TzlIWVhRdWhBTzFBeWE0WU01TzNwYjlzeTJXZHhRdVdLYjNFR0RuUWN2VUhodE9kUU90MS9welo3NGhQWkdPVHZFU0JHaWxncWphNFZ1NG5wQkUxV2VFYnRuVkFhMEZ2T2tPVkhlREJmU1R0K1hBYktSK3MrUG9qZXU3R1daNkh6SnQ1M1Bvbm4zeHc2blgrckltUWFsa2o3bnV4SzRXTUhDanFWRzBGTnB3R2lEYUdJY0ZyQWFCSzRBa3NWTjdRaEtjNG9WSDY3Mk91aWZFNTRkUjdkdWErR3Y5YlhTMWdLTDQzaDl4ZTBMLzhRNkw4d2dSWG5IN1B6MVNFVExLbnBBZENMMStGUU9VL0hvdzNWQ3J3dW9kUUZ0R2g0OEJWMG9CMzRObUN6aEtGNXk4VnJOZFhUcHBTUmRqdDcwS2pwUUw3dUQwUitLQ0U1ejNBSkUxVGFTczN3cDlMK0xIZW9KOGlCQlZBaEZNaUhMWmNkZEEvYmoxdHNOUzh0QU9HSHprcjNRNHN6UDhDbEtTTVV1dVp4ZmNxTnYrWElCeWVkTXVXTzU3d09aQnRZclVPOHpxNjNnLzhRRGJUdkg2NnNwNEJ5T28rL1E4MTBWWUFVd1lWdmU4QVZBcjMza2YyMElOSW0wTFlCNHNZT2tqSnpxZXUxbjBhZ0ZwR0hBRnhvOWgzSlFGUE5LNkd0aG1zUjBzb01CVmQyaUpYM2o2RmtDZ3FvR3ErcEdaQmpDbzB1N1BDb2oyWEZUWlQydzdjaTZsL20xdGg2emo0K0pzaGQ2bTNSOVBidlBJZGJPQW8rQ3lFTXJqajl2Um5XZE9Yd0IxWDdTV3g5dWN2L3ZnaDA4QjVzZFdyNW1sYXhnM3dqcDg0RGdxSUxOM3c4RkRJTnJ6Y2lPN0RhcDh3eFhIUzU0TFJDUVFrUUFJb3JJcjdmOXNHMTU3cnRuTit0UGFjdEMzQ3g0cGg4U3ZkTHdUMzBOVTU3Qi9vcElwVE1iTlJTNlliQmM4Q3E3VlNVT29xZ2FnZHViME5jQ1d6QTd1TUE4aVpDU2NXMjFMbDY5RlE3ak1rcTFENjlwcWRBL2VFa3F0aHF5dTJKZHA0Y05zZXRMNEZuSGRYREFqNEJSNXpSNlJhTFg1MEZrL3FtZFBMUU0vdGxlMkx3cVMrRCtMaTk2M0pxdlhsbk1welowRjlLdHQzYnlPdWZLNjIxL0NKVGU2QjNQamZadTVxeXVJbS9vWmZ2Q1l0WWFibURTK1ZWeGtBY2ZaREJOd3dlMUhCVEJRVmFPcUJzVjQwMW1JRUdJLzBuUnYxb3FRM28vdnhPNkpnb0x2ZFNsRVNDdm5FVFZFbDRQZ0RWekpyT1ZpNWtBUHFGY3h2bFhmclJFams1TTlMM3JaTWVpZi9CQUF2ZlllMnN1eXVSdnJtSTExQkdpODhack44SU4zSTNQM0RKd1diaTVoUkpDd0RPVUp0cFBRVVR2aWZrVlZxVHoyOVBlYWowY2l4RmRwQUxOZFJBZ3EwWnNWaHprY0Z5elJ2OVpzVUpyMnlkNUcxWklCaFVUMERUc1JOaXQwSWhjOFloR1N5TnlXL0lhRUNPRzVMMFZEWkZCOXh3V3duM2oxTEhzb0J5SWttcGgrNHhybWhwdHc3dWJIQmpNSFViZUVyLy9vOUtZR0dheTZyS2hWV3pSWjFqMmtIc0RxaXIyWC9kVW9YSHR1SDBJaStyS1JZaTVmdEh3WVFxa01Bc0g5SDdheGhTRVNsbk1yUWtDWGdUZHBnMGlFWU1kb1ZRR3FYLzNpRmZmTzNZZElxZ0JLNHY4c0xucmZtcXhlVzg2bHRDOEw2Q2FtbTJ0WFVTY1FmQUUwR3g4azhDc2V1QUs0S1F1NFpnYzhVSysxR0ZWdkFhUDlwbTJ3ZHNmK3J2YzJhVHhUTkd5c283ZXM2REgvN3lJQ21LQmtQMElJeUtFakxsbFRkdDNvbklvUWhDVjg2MG9HSWhHUytrdWVrVU1SRWwwdkxVbnhaeVN5SVR2c2Jsd2NwcmJFSVRUdDA3VFYrTVh5NFc1R05IakVZV3UwRlkwa1RzL2hqVU9FZEVPWXlZcDh3MTM4aUNpSGV3aG5wS2kvOUUwQXhDUUdCVGpvMWJlb3YydS9TQjRldEFKQXlxN3l2aDJ3dG1JcjRtKzlqbkZpSm9JeFlLeFZyZi9aTjFHRVVvK3JpNDBMYXEzZjgrMEtZeVJDa24rcGszTW9RbUlCSUIwRmduOFRzOW8xdTdyZ0tNek9jV1M1czJUZDFvZmJzK0FBSzMwUzFqVXJEaVg5Y2UyOGk1QjJUemNXSVFsVXp6N3pQOTN1WVlXSEFVUjFodWpHMCtWNUpDS2t0aEVOcEZUL1RSQTFIUVdDV2JrSlFMQm5YOHZDUjExRlNNcDl0bzhqc3hDNisweTZZSHR1RHlMazlrM3JKR3NiblN2NWJvVXJxdXRPTUNsTTdjMlJDTkUzM2UxZkJGN1ZOb3VoSmtWSUJQM2ExMTVFaEdwdDhXRlZYWFlXYm9ZbzhQU0RrNWIvVzYxZVc4Nmx2cHNGcEZhTEpwS0w3NlZvQ3F1RmN3VlF5eFdrYWZoZkx4WXcydWtRUjliYkgwajZuSDVFaUxsenk1YmI2bnJuU3I1ZjRhcTZZU2U3S3dSdXJra2VSSWpBWlJmN2o4b25uMzZWTnNnVUlVaHM0K3hOU0ZUckhwY0lzVyt3LzZORkRHUnpyaEsrclVSSUluemlha1J6SE1tSDd5MWJua1JJcjhnV0laLytkRlVBT1hmNk93cExMak5QOVJGdVB1QkhHWnRHNS9QeWhPMlk1Z3hJRVB5VzI3M1M2YnhNRVNLSklWcFJhUjZ6Q0xFdXhQOGw2bDdwcERTSmtLZ3ZvelcwbklxUUxNdVNGVWZTMHNTQ3JIMGNrUXNla1FnaHNlMkVUQkhpVVh2dTFOWG9oN0hyQ0tyOW9sS3FzM1VVSXNTN1lHZ05NNGtrTjhnVXpIR0pFQitHU1lRSHJYSFFISi9MbjNHS0VOQWxqVWE2eUJWM3JPUDNZRE5GaUlmcXY3eUtHOGRmTzNPL1hjalMzbEdxQUVyTC82MVdyeTNuVXQrckJVeGVyNlREYXVZR21RRTNMaEdTL1dDekxVektBcW9RWkZqQXhOMk5Rb1JjQXk0QWhMLzRaRWZYNjVIZEUrTEZTQXJlMkJMWHdQTXVRdHkvTEdlUVd4R1NDTXZ2WjhXUmNuVUpDOWd1am00V2NCaGMvS1I2UjdZSWlmQTdVU0VNU3FmL0JZQXhQSUZTekJrcEVFTXhyamgraTRCLzM4MlhKZEZSaERRSmtoaUZDQ2xFU0lwTDljdjA5Zld0amlJa2ljWnpweSs0M1V1b0gxNmpSNERCUk1pZDI1ajMzN2FGME0ycGFLa0lnUjBkRW4yc0x4MW1FaWtSNG9iUTAyaEVIMGVNMEJ4K0U5ZnJ0MGl5Q3FGWlg3VTVjbjNSRHUzdG8wSVZEZnZmV090TkROeTVqVm0wK1dkV1Y5ckhzYkZ1ZTVQYVZCczZ4dEdGVStVVkZUWEFqMEg4NVBPZTBGR0VOT0VpUVBYTTZkY1JYd0RsaUwrLzlQK3RWcThkcDNkdXV5OC9Bc3ZYMnBZL2JUVGliM3o0UXRJVVZndm5sdVBWdFR1d2ZJMStvRzdJbHpZYUhlUElzZ2pSZDB5V0Z0SFYyLzA5WURjT01mb0FqVHV2YmRtOWN6ditCa3FiL0ZPd2s2eVNQVWp0d3RzRUo4TEw3dENsOHFOUDlWVUFPNHFRYkdHU01BZERFQ0c0U3JHLzFyMVJMUUtqT2I1ZVJFanNORnFGUks5L2tuRnRNbzRzYStLSFRmblZxSnF2NjhURithdUo4TExpOEdmR3o2TlRIRWwwQ204ejNDRG9Ja0phVVNiOEt2QWlRRTBhZitib2FaUk5UY1RROVhYckhwSXVUVnZkYTVhNzdZWjRGYTA3SGQxb3h6ZzJrOE4rbmtxdFNtUGxWaFNFWHhIVmI5dHhmVDNZeEZ5VWJuRU1vOEI0S0xvRUxDbFFNY0Z2TzNxOXd5V1o2Rm1FUkVPMU1rcUJBSnNXSVQxd1BRbU9NWEZaN213M2NNTkN6eUlrd3RrdnJ3T3VkcS8vMVc3NGhNTFBXRTZDdmtSSUQxeVNUeUlQWEZZaGhCM05PWFhHOTRHWEhPa3RYOS9ybi9jalFqeldmWVFiWjAvOUVZQ29Ub0o4SEVERXl2QmVSVWpQWXFYcGQxNjRMQ3ZCRHViRUZVQVIrWDZaMHJOQXdDLzl1bDludkcvMExVS3llMHJpMXJaK1JVZ3ZYQytDWTF4Y3hnUGEwVnh6K1dtbCtvTjA3d0xyanRxNTB5ZUFFd0JxNUZUaGduY1lwMW9Ic2U0MTBML25qbDhwUC9wMFQvMjluZEMzQ01rVUpzUlBxQkFoTzVHTGJWL3krRERRdndqSlFPM2M2YXRnRnp0WDFSZGRlaGNFT1ZKWXdKM0E2UVhnLzJMNUsrNTR4MkZXdldJeklpUUxpKzZQalRPblhuRGNJOENSUW9Sc2Z3N2hmSUQrZDREU281OGIyTzBtTVpBSWFTTk1iSUYyZDFDSWtPM1B4V2g2RTRlQW9ZaVFsa0JGZ28ydm5Qb3N5SytDZ3NndkZ5NTQrM0VHL1ZmdTkzY25Uajc5QWx1QW9ZaVFqTjRTdDhJV0lJUDNqdVJGY093MkVlSUw1dkR0WG95aGlKQm1PQXQ0SHVTUHJRVzAvY1NxSEJQa21POW1MeXhnampqVnVodlZkeDdoVlZIRkNOOTE1N1JkM1dwUURFdUVwS0NxUmtUT3ErcXJJaEpVejU2YXQ1T081Tk9vSGhWckhmdnFNZEdtMzNuaHNpd0gyNUFUcE81dTZaVUEvV05FS0o5ODZnVzJHRU1YSWE3d0JjbHQycDdiblVLRTVJdExJOFBzYnhHMlRJU2tDcURqYXVkT0xZQXNnS0pHdnVKT253UXFoUXNlUFlmcUxZVmx5d1dQdXBNV0s1OTVNcDZPdThYWU1oR1MzTVlGTVRLRFBoTUNFZyt5RUNHajVVaHdUWTltWk5neUVkTEdBaTZEWEhaWjhKOEZVT0VFOExBMUtUSlhXTUN0NXhSOVJ4RUR2QXo2ZjhTZXRPZ09OazJlMlZwc3BRaUpDbUdDVzFiVkpSRUo5TXl6L3dHZ1N1TWZBSWNSUVdBT1dpMGh4RlluRlU4T3VDd0xRODQ1UWQ1MEI3NWRuakQvQllCUGZtNkpNV0FrSWlSVG1DVGdNNm9RSWFQaFFJZHVkRGFMa1lxUVRPN2NINFFnSVNqMXh1US9CMUQwN3lEOExJQ3FYUVlrRCs0Mmk4dTlDMWIxbHUwRkF2MHVDdVg5SC9xRDZHWWVlYVR2VWN6RHhFaEZTRS9DcE9scDUwbHdiRWNSMGdLWDNlN1kyTDlJTkZJUjBzWUNHcEM2eTVJWFJRUVZmUWY0UG9BcUoxMndjK3JxaUhFOGhRVnM0b3lpb0x3RHZPUE9jcC9nNWNmQVJWL3lKQWVGRDBZdlFySTRWTFh1dUJkVjFlalh2L3lLaU94VlZXcTFoditzK0hHUmRBSDBsbWljWER1ck14Wk9NUzVaVjRDWEJTaFBtdDkxcDYvenljOXZldTdHVm1Gc0lxUVRKODZzaURjMWFoM011QVZIN2tXSVFHcVZ4VXdmbkMrTVg0VDB3QUhVeno2ekFCd0JNT2p2QVFnY1VwWDVkTnk3eXdWanY4TnhDYUJDNlorNVEwdWMvUFgrMWlJWkU4WXVRbnJobXFzSjNnSkFaNEd3RzBRSTJycUM2M2JDK0VWSTd4WncyZThyL0Q2QUtBOEN4eXluRHdFSXpDcjJreEp4ZXJhN0JkUzZpMjVKa1dWN24yb1hCQkl1aWYvUWVMUmdBTG1yNjdWREhrUklWODd4eXlMaUo4TDhSNERxVjA4L3JPZ0pBSkY0YlJxQlZBSHNKaVFHNGJLc0UwUG1CS3F1M3JtSThJYXI2VDNyenIwVW5ueXE3Y2NBODQ1Y2lwQm16bHZDNW5nQTRrVW9MWlNkSjBMUzhHdHV4Yzl3MEVJd1Rtd2JFZEl6L3ZUWkNtN1ZyOFo2NDFNQVJ2WERpRHdJb01ndnVEUDNvdWx2SVkvTEJlTldtc0x5WDhjV3F0Y0V2UWhDdUxIblJYZTY0VmQrWmF3OUY4UEd0aEloemZHMDQxcVE4S0crQXUvcFBJaVE1bWRDMUVnY08rYXRNQlI1d0xZUklXQmRjSE5jTGR5ZlBtdUlWMm02NEU1YVJPUThnTUJyN3RoQmZGMVJtYlhITkVUd1h6VzBmZEJLQlNTMHArbTB1OEdLK3JVVk5Wb1hvbzdZdWhySXFydTJpcXUvSWF5NkFsY0hyYnBxZzI4cVdRS3V1LzFMMkFLNFpDMmpHTUNJZllseTBYc3hUQWhiVUlmWUloRmltaTNjSUZ6MTNMUHpvSWNBZ29ZdUFCak1ORTdNaURBUG9JWjlpa3c2Ymc1c1FZd0dTUkM5QU9zaWZpeWRYTU1PdGwwUjVEYUFCbW9MbTdJYU9KVmFvblFCVzZpV3QwdTczYkN4OHl4Z2oxenQzTE1nNHJpTzdzMUlzaTRZUVhnQUFBQVpTVVJCVk1KbmQyTGZtVnlLdE9tNlRvRW1zSzFGeEtENC84VExVa3l6UWtVekFBQUFBRWxGVGtTdVFtQ0MiPjwvaW1hZ2U+Cjwvc3ZnPgo="/>
        <prop k="offset" v="0,0"/>
        <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="offset_unit" v="MM"/>
        <prop k="outline_color" v="35,35,35,255"/>
        <prop k="outline_width" v="0"/>
        <prop k="outline_width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="outline_width_unit" v="MM"/>
        <prop k="scale_method" v="diameter"/>
        <prop k="size" v="40"/>
        <prop k="size_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="size_unit" v="Pixel"/>
        <prop k="vertical_anchor_point" v="1"/>
        <data_defined_properties>
          <Option type="Map">
            <Option name="name" value="" type="QString"/>
            <Option name="properties"/>
            <Option name="type" value="collection" type="QString"/>
          </Option>
        </data_defined_properties>
      </layer>
      <layer pass="0" locked="0" class="SimpleMarker" enabled="1">
        <prop k="angle" v="0"/>
        <prop k="color" v="33,150,243,255"/>
        <prop k="horizontal_anchor_point" v="1"/>
        <prop k="joinstyle" v="bevel"/>
        <prop k="name" v="circle"/>
        <prop k="offset" v="0,0"/>
        <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="offset_unit" v="MM"/>
        <prop k="outline_color" v="255,255,255,255"/>
        <prop k="outline_style" v="solid"/>
        <prop k="outline_width" v="0"/>
        <prop k="outline_width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="outline_width_unit" v="MM"/>
        <prop k="scale_method" v="diameter"/>
        <prop k="size" v="25"/>
        <prop k="size_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="size_unit" v="Pixel"/>
        <prop k="vertical_anchor_point" v="1"/>
        <data_defined_properties>
          <Option type="Map">
            <Option name="name" value="" type="QString"/>
            <Option name="properties"/>
            <Option name="type" value="collection" type="QString"/>
          </Option>
        </data_defined_properties>
      </layer>
      <layer pass="0" locked="0" class="FontMarker" enabled="1">
        <prop k="angle" v="0"/>
        <prop k="chr" v="A"/>
        <prop k="color" v="255,255,254,255"/>
        <prop k="font" v="Arial"/>
        <prop k="font_style" v=""/>
        <prop k="horizontal_anchor_point" v="1"/>
        <prop k="joinstyle" v="miter"/>
        <prop k="offset" v="0,-0.40000000000000002"/>
        <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="offset_unit" v="MM"/>
        <prop k="outline_color" v="255,255,255,255"/>
        <prop k="outline_width" v="0"/>
        <prop k="outline_width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="outline_width_unit" v="MM"/>
        <prop k="size" v="11.8"/>
        <prop k="size_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="size_unit" v="Pixel"/>
        <prop k="vertical_anchor_point" v="1"/>
        <data_defined_properties>
          <Option type="Map">
            <Option name="name" value="" type="QString"/>
            <Option name="properties" type="Map">
              <Option name="char" type="Map">
                <Option name="active" value="true" type="bool"/>
                <Option name="expression" value="@cluster_size" type="QString"/>
                <Option name="type" value="3" type="int"/>
              </Option>
            </Option>
            <Option name="type" value="collection" type="QString"/>
          </Option>
        </data_defined_properties>
      </layer>
    </symbol>
  </renderer-v2>
  <customproperties>
    <property value="fid" key="dualview/previewExpressions"/>
    <property value="0" key="embeddedWidgets/count"/>
    <property key="variableNames"/>
    <property key="variableValues"/>
  </customproperties>
  <blendMode>0</blendMode>
  <featureBlendMode>0</featureBlendMode>
  <layerOpacity>1</layerOpacity>
  <SingleCategoryDiagramRenderer attributeLegend="1" diagramType="Histogram">
    <DiagramCategory height="15" sizeType="MM" width="15" rotationOffset="270" penWidth="0" backgroundColor="#ffffff" penColor="#000000" spacingUnit="MM" enabled="0" backgroundAlpha="255" lineSizeScale="3x:0,0,0,0,0,0" spacingUnitScale="3x:0,0,0,0,0,0" showAxis="0" opacity="1" barWidth="5" sizeScale="3x:0,0,0,0,0,0" penAlpha="255" maxScaleDenominator="1e+08" direction="1" diagramOrientation="Up" minScaleDenominator="0" spacing="0" minimumSize="0" labelPlacementMethod="XHeight" scaleDependency="Area" lineSizeType="MM" scaleBasedVisibility="0">
      <fontProperties style="" description="MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0"/>
      <attribute field="" color="#000000" label=""/>
      <axisSymbol>
        <symbol alpha="1" name="" clip_to_extent="1" type="line" force_rhr="0">
          <layer pass="0" locked="0" class="SimpleLine" enabled="1">
            <prop k="capstyle" v="square"/>
            <prop k="customdash" v="5;2"/>
            <prop k="customdash_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="customdash_unit" v="MM"/>
            <prop k="draw_inside_polygon" v="0"/>
            <prop k="joinstyle" v="bevel"/>
            <prop k="line_color" v="35,35,35,255"/>
            <prop k="line_style" v="solid"/>
            <prop k="line_width" v="0.26"/>
            <prop k="line_width_unit" v="MM"/>
            <prop k="offset" v="0"/>
            <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="offset_unit" v="MM"/>
            <prop k="ring_filter" v="0"/>
            <prop k="use_custom_dash" v="0"/>
            <prop k="width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <data_defined_properties>
              <Option type="Map">
                <Option name="name" value="" type="QString"/>
                <Option name="properties"/>
                <Option name="type" value="collection" type="QString"/>
              </Option>
            </data_defined_properties>
          </layer>
        </symbol>
      </axisSymbol>
    </DiagramCategory>
  </SingleCategoryDiagramRenderer>
  <DiagramLayerSettings linePlacementFlags="18" placement="0" zIndex="0" dist="0" obstacle="0" showAll="1" priority="0">
    <properties>
      <Option type="Map">
        <Option name="name" value="" type="QString"/>
        <Option name="properties"/>
        <Option name="type" value="collection" type="QString"/>
      </Option>
    </properties>
  </DiagramLayerSettings>
  <geometryOptions removeDuplicateNodes="0" geometryPrecision="0">
    <activeChecks/>
    <checkConfiguration/>
  </geometryOptions>
  <referencedLayers/>
  <referencingLayers/>
  <fieldConfiguration>
    <field name="fid">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="osm_id">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="name">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="amenity">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="hstore_to_json">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
  </fieldConfiguration>
  <aliases>
    <alias name="" field="fid" index="0"/>
    <alias name="" field="osm_id" index="1"/>
    <alias name="" field="name" index="2"/>
    <alias name="" field="amenity" index="3"/>
    <alias name="" field="hstore_to_json" index="4"/>
  </aliases>
  <excludeAttributesWMS/>
  <excludeAttributesWFS/>
  <defaults>
    <default expression="" field="fid" applyOnUpdate="0"/>
    <default expression="" field="osm_id" applyOnUpdate="0"/>
    <default expression="" field="name" applyOnUpdate="0"/>
    <default expression="" field="amenity" applyOnUpdate="0"/>
    <default expression="" field="hstore_to_json" applyOnUpdate="0"/>
  </defaults>
  <constraints>
    <constraint exp_strength="0" constraints="3" notnull_strength="1" field="fid" unique_strength="1"/>
    <constraint exp_strength="0" constraints="0" notnull_strength="0" field="osm_id" unique_strength="0"/>
    <constraint exp_strength="0" constraints="0" notnull_strength="0" field="name" unique_strength="0"/>
    <constraint exp_strength="0" constraints="0" notnull_strength="0" field="amenity" unique_strength="0"/>
    <constraint exp_strength="0" constraints="0" notnull_strength="0" field="hstore_to_json" unique_strength="0"/>
  </constraints>
  <constraintExpressions>
    <constraint exp="" desc="" field="fid"/>
    <constraint exp="" desc="" field="osm_id"/>
    <constraint exp="" desc="" field="name"/>
    <constraint exp="" desc="" field="amenity"/>
    <constraint exp="" desc="" field="hstore_to_json"/>
  </constraintExpressions>
  <expressionfields/>
  <attributeactions>
    <defaultAction value="{00000000-0000-0000-0000-000000000000}" key="Canvas"/>
  </attributeactions>
  <attributetableconfig sortExpression="" sortOrder="0" actionWidgetStyle="dropDown">
    <columns>
      <column name="fid" width="-1" type="field" hidden="0"/>
      <column name="osm_id" width="-1" type="field" hidden="0"/>
      <column name="name" width="-1" type="field" hidden="0"/>
      <column name="amenity" width="-1" type="field" hidden="0"/>
      <column name="hstore_to_json" width="-1" type="field" hidden="0"/>
      <column width="-1" type="actions" hidden="1"/>
    </columns>
  </attributetableconfig>
  <conditionalstyles>
    <rowstyles/>
    <fieldstyles/>
  </conditionalstyles>
  <storedexpressions/>
  <editform tolerant="1"></editform>
  <editforminit/>
  <editforminitcodesource>0</editforminitcodesource>
  <editforminitfilepath></editforminitfilepath>
  <editforminitcode><![CDATA[# -*- coding: utf-8 -*-
"""
QGIS forms can have a Python function that is called when the form is
opened.

Use this function to add extra logic to your forms.

Enter the name of the function in the "Python Init function"
field.
An example follows:
"""
from qgis.PyQt.QtWidgets import QWidget

def my_form_open(dialog, layer, feature):
	geom = feature.geometry()
	control = dialog.findChild(QWidget, "MyLineEdit")
]]></editforminitcode>
  <featformsuppress>0</featformsuppress>
  <editorlayout>generatedlayout</editorlayout>
  <editable>
    <field editable="1" name="amenity"/>
    <field editable="1" name="fid"/>
    <field editable="1" name="hstore_to_json"/>
    <field editable="1" name="name"/>
    <field editable="1" name="osm_id"/>
  </editable>
  <labelOnTop>
    <field name="amenity" labelOnTop="0"/>
    <field name="fid" labelOnTop="0"/>
    <field name="hstore_to_json" labelOnTop="0"/>
    <field name="name" labelOnTop="0"/>
    <field name="osm_id" labelOnTop="0"/>
  </labelOnTop>
  <dataDefinedFieldProperties/>
  <widgets/>
  <previewExpression>fid</previewExpression>
  <mapTip></mapTip>
  <layerGeometryType>0</layerGeometryType>
</qgis>
