<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis version="3.14.1-Pi" simplifyDrawingTol="1" readOnly="0" styleCategories="AllStyleCategories" simplifyDrawingHints="0" simplifyMaxScale="1" simplifyLocal="1" minScale="100000000" hasScaleBasedVisibilityFlag="0" maxScale="0" simplifyAlgorithm="0" labelsEnabled="0">
  <flags>
    <Identifiable>1</Identifiable>
    <Removable>1</Removable>
    <Searchable>1</Searchable>
  </flags>
  <temporal durationUnit="min" mode="0" endExpression="" startExpression="" fixedDuration="0" accumulate="0" enabled="0" startField="" durationField="" endField="">
    <fixedRange>
      <start></start>
      <end></end>
    </fixedRange>
  </temporal>
  <renderer-v2 forceraster="0" toleranceUnit="MM" type="pointCluster" tolerance="20" toleranceUnitScale="3x:0,0,0,0,0,0" enableorderby="0">
    <renderer-v2 forceraster="0" type="singleSymbol" symbollevels="0" enableorderby="0">
      <symbols>
        <symbol alpha="1" clip_to_extent="1" force_rhr="0" type="marker" name="0">
          <layer class="SvgMarker" locked="0" enabled="1" pass="0">
            <prop k="angle" v="0"/>
            <prop k="color" v="231,113,72,255"/>
            <prop k="fixedAspectRatio" v="0"/>
            <prop k="horizontal_anchor_point" v="1"/>
            <prop k="name" v="base64:PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIGlkPSJteVN2ZyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+Cgk8aW1hZ2UgaGVpZ2h0PSIxNjAiIHdpZHRoPSIxNjAiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBS0FBQUFDZ0NBWUFBQUNMejJjdEFBQUFDWEJJV1hNQUFBN0VBQUFPeEFHVkt3NGJBQUFmRzBsRVFWUjRuTzJkWFpBYzEzWGZmNmVuWi9ZRGk4Vnl1VnlDRUFtQ0lDakxNTTFpVkk0ZVhFNkZlYkFsdVV5SWRzbDA2SkpKS25wSTh1REtTNnBjZmtnNXlrTlNlVXE1WENuYlNxd0ZSU1VWeDVXSUFDaFI1WklsRnFQWUtvZFNzU3dhZ2tDUWhQQkJyaGJBWXJIY3o1bWVlL0p3YjM5T3ord3NaMmFuWjNiK3FFSDMvdnYyMSszYjU5eC8zM3ZQRlZWbFgrSHNsNDhBMU5RN3FjaEpBSUdIQVZDZEJDWUI4SmgzZTB5Q1RBSVlaYzZsbjBSY09qVkdSRkRWRFpBTnkzRlRSRkIwQTVFMXQ4OU5iRlp2cUxJbGdrSDBod0NJbkM5UFRKNUhGWDc1NlZVUjhWVFZoRXViWkRnNXIzdFBkb1FSZGc5cFpRR1RKWGRnY1BiTDR3b1ZnRUM4UndFd3pJR3phTUxQQWFETWdZUldic1l1dEFMNEx0MlUyK2FEVkFCVW5kVkRmUkY3RHNDNGJRRlF0YnZLaHN2VktrSmdPVUxyV0FYTGdTNGhnTW9pc0dRMzgvY0lIc3FTaUN5aFVKNmN1SUFvcUFUeUswK2JvbG14VGppLzFiTWN1TUpuVVFGYmVCUStZU245T1hIdUZ1UVhIUWVTMlZNQnlaQWFwNHMyS1VTa3FvY0lndnFJaktNSzZMU0kySDBKbCtFQjFDNmpGMThBTmFvU2lBREN0eHg5SHZpaFBZMis0OUtCSytURGdwRUxIcUd2YU9tQ2k0N3EyWVdQQy9KeEFGUytBS0J3dndqM3B4S3FOckZzWGVBMFlkRWtZKzI2ektucUplQWlRTW56L3RoZHpVWC8xSE9YaXVaYTIrVmF1dUNpUTlJKzFGbHo1L1pHR0FnTWpBV3NubnRobmxCSTFIa0NBTkZIUkRnT29NcmpBSUpNSTB5bmRoNGVDN2dNTE5zLzVYVjNOZThBYjl2c01OOXkrNjJXbi9wbnEwV3pkbm5jQUZsQW5jY0pDUlg5WFFCQjVvQlpTQXFFNGJXQUFyT0l6S0lLcWlmY1RWOER2V0xGRGhkc29lVWFzTnJueTIwTEExUUE0MElsS2xscUh5UHh3Z241RnJ2QUtLUUxEczY5ZUF3NENxQnEvdERSaDkwdlJpOWRhN3ZjSHJyZ1hianFpNGhjQklWUzZmZmRWUytOL2Rxek40dm1na2VmWVVib0svcHZBVjk1eFZQd0JLaFZmM3JLWHBWOEZQZ1psK0pUQUdvL0xrK2w5czJyN3UwMVZ6d0RpQ3JMU05UMi9DM3M1ZjY5d0pzQWZuWHl1K0d0eU5OUHM2OUZpQ3Q4bm0xY2tGOTNYL3NmYzc4SWtsdTNLVWdKUkpEVWtuNXpzeUN6N3RwT3VBMnZLc3k0cTQ0S1lMOHhjc0VqOUJYOWM4RmZYemdPVUt2TGI2dktNODY0bld5YXZnaUNJNDhyb0FqWmtSTmVjNGJ6TDhxTS9VOEFUajJ6TkJJaEkrdzc3S2tGcko1OTRUREtQQUtpK2p1T2ZoeVJ4d0VVNW9TNGhwVzZzaUpVOS9LNFFUU0FvbGZVWHZzYmlId2Z3SU92dUR0YUtYL20rVDFyUmRsVEVhSXdMNktQS29JZy84TFJGZmVMbm1sMkdlM2Q5OUtXeHhWU2hMVG1sS01pZ2dxemhGM1dsRmRkbjBQWXcxYVVrUXNlb2Evb25RdCs1UlZmNCs5N2YyYlBKbzhCajhYdlphTzdIYm5nZnVrUzI3TWI1VlVSL2dyQS84eHovMzVnWFhCRElYS3FzWldBYk1iWi9YTk9VZ1RPclV0bU9YQ2MwcERwMmNJaUloNUFON211VzhEcW1RVTN6c0o3VklSSEhmMEZBSlREQ1BPRGFnRzk2Vm03Y3VBZ2N1Q2czYnl4WmwrWUQrNmdhNnZXd3BoNllTeGIrNXl0bVFPWGNVTUFqTERnTFB5RkN1VUxxTUJubmxrcnVnV2NCd3pvUHdiNXJPTk90bXZ0Q20wQkQ5a0M2TTBmd1p2L2lMM2VXNHVBWXQ2L2ltNnMyK1JhdDdzV3diSzF6VVViam9FY3N6ZEgxYVg1bXUzaXBVWkVOcnBwQVh0UkFBMFpjYVB1SnBOTGRzSEZCOG1jYWE4dFlKWUhWQlVSaVN5TEtrTlRMeVQrMjBNd3FEUVVvT0paUUpFdnVxZHpFampaSTRuVGUvaDIxS1UzZndUdlhtdnR2QWRPTkNUejdudlFKcDg5REI5N0hJRGdiNzhOQ0d4dndQYlczbHh2RHlES3AyeGgxT2txMVljQUt2QjczVHhIRHl5Z1JsYmp3N2pid3JuZ3RwRjgxY0l2Y1BhQXhYTzN1K09TNkxZdzZZb0lxWjVaT0JIVkc0U3dBK204SUhPN0ZSeDVIQ1RJSG5KUzhzRXYyL1VqOW5hOFE3T0lxL3VGeTF6VTYvWUhtT3Z2Z29CWnVRVXJ0d0RGM0xsZEhOZTZhMDZ2QVZkc2h2RFAzZE5aR2p2MStZNDd1SGJKQXNveDRKY0JCT2xJY1BUVkF2cGxaR3dDZ05KUjUyN0hKcER4aVp6RUdaUks5Z2Q0RDdtdWpPOWZ3YWhCRUdUMXRqMXRnU3hiKzV6Y0QzYW9xMFlkUmdSVlhTcUlDSW5OU2FlQ281OGlSQkpuMUJ6dXcwRHNnMnA0c1lwaDJUNEVKN0YvNm9ZSTZjZ0YxODk4NWJNQUJ2MHRoTTlDMm4xK0dIZmJEeGRjY3VKQzVvL2czV01GQjVVSzNZUjUveWVJQ1BYM3JxQ0xWKzNEREtyRktWaHRjZ0pXVmFsK1dkSC9JZ2pscDU1L296QXFXT2pNM2ZiREJTY0xmMmRDcERsRVFxc1JXL2lCYkVWSldJVXdNRUFud21UWEZyRDI4bGZqc1JuMStuOXk5S080Vm8vQ1cwRFAxdE1rMFpvUmZsNnhuQnZUN3VwejNZS3UzYkhMTzh2b25XVUF6TlZMOXNLQ0d0U0R3bG03Smx4Z240MStEK1Y3QUJWLzdBL2NiUWJ5NUc4SHZiYUFVeEFGYjN6S0xhUGpGTjRDaGdYdzRFejhmZSsrbzAxdnRsdVFxVU4yV1JtSHUrNEJRSmZlaTEreWVsQThhNWZQMldldFBLYkNjYkVORC8vUnZlVWJxbHJkQ3hIUzJOS1JYSmYwa2c2NWhwTjBnZXVScDIwRHlUUGI5bGQxZDFwQWE5ZVVjM2RpSE9XQnBDeGNjcjI3RnJBZS9BYndMOTJWak85Ni96N0QvL2d2QVNCVDA1RlYybE5VS3BIQThaK3dvMUROdXovRy9PUWk0cjRYRGdaa1dvUnBGR3IxN1Q5eTVGOEEvM3MzUittS0NNbDZ5aUs3NFA1WnZoWUlyVDdTNEFJTDZJSWJPWTFxN2IwVElkVXpwOE54dXI4ajhLdzcrenprdU9ETWtnNjUxSUU3NUx5UFBHVFBVeG1EeWxqekc5NUQ2TzFiNkIzYllxSmJXNFZ6dHp0L210SHpBQW92Z1BjVkJDcW5ubDNzcmd1V2FNamtjZUxZeW01VGVyM0lGbEN2djJ1WCtYZlpkd3lrQll6Q0gvTXc2RHlLSnlKTDNSVWhTUk9Wc3lsbEFTVzlwRU91NFNSRjRqSXZUTkdzMDE1eWdFSEZRekR0ZHR2YW9RQitNVmE3OHVCL2NDc3pyZmNwT0Nic0o4elNzWTlTZXRDMTJYYTUxYU5kQkQvOFcwUUVYVjVDVjI3MjVScTZDdFZmUWMxeDkzWitzcDFkUnFQaVJ1Z3JXbHJBMnN0SEV6SDVuT1ZUemZuMGtwRVJQVkFoU1hQZkNTZGwyOTJLa3QvUTJoSDJidDRORi9lSWpwZjJuRHR6M2tHWHBldXJjZk5jZVB1SnFzaWdjTmdJcmljQWdwZE9INnQ5YmNFTFhqcTlvamEwY0poZkpybHM3WUpWRHVPaVZJbWJ6RVV6RHlPRzVQK1pKeVErQkJjcGZUcmpwR3lWci9qbGhnS1lMV2p0Y09GNmR0a09wMVBUOXUvYlM1RjRzOXVLVmJkcm0wTm1SSml4bkI1enQyeEVaS1ZaSFhEa2drZm9LM0l0b0w3eVNzVytrZklFeXU4aVdzd1B1Q01VRnVyeFJiVk5qUXZFY1djYU1MS0FJL1FWdVJZd0NKYmNIR3M4Z2pBRHlacDlSaDAwY01VV0lhMitRTGN0UWpiWDBVMDc5NkRNekxwTEZjVHpkaVZDd3Q3U0lJVVJFbDNranJtSzk4TzFNd3ZIZzdPblBmL1U4eGZiRWlHSytRV3gzUTJQUitvMzlSRHlIUEpnaUpCV2RZbDJSWWh1Ym9EN2JpZlRoOEFWdm16Nm5VU0lJU3pjT2h3aUpNWEpVWHVyZWh6bGhNdjNpeU1STWtLaGtHc0J4Y2d6QUdvbi9oc2h4T1k2QUxwNGxmcmxId1BnMTl6c3FYZmZpemQzdU5tZSt4Zks0d3ErcS9wOE03dDVaQUZINkN0aUMvaU4weFVsbWdYOGZsZHRtbTZvMGU5akVXSnVMRnB1ZlRVZWhMNThBMUM4aVFOZzZ2Ync0clhYT3JLOVpkTUhRUkZFUTI4NE81ZWZIWFR6L1MvNSt2cWZHcjcvSmE5UmhDZ1ZFYlV0OWVJZGFlMTU5NmNJc1pHd2dQVlZ3Z2hZWnZtR3pmalplVERHNmxtL2xOcTNhVXZJMXFhOW5pQVlRaEVTRmNSWllETE9SSHdFNDE3Q2tRZ1pvYitJTEdDdHprbkMyY2RIaUdIcTlnZlVyMTZ5WE5LaUJsVVEwT1VibVBJbFVQQWUvdG4yamgxVTQzTU1LUlNwaUZCUmhlQnE1WmNjZlJrWGEyWmtBVWZvS3lJTHFNb3M4TE1BcmVPaERMWUkwUzNiZ3FGQnJlSE9ja1ZJVUlQcXR2dWo4WGhSeFZzTjFBTWcwOXJSUW9Sb3ZXNFBxcVk0b3FHSG5GRk91TDlXVmZVeXBMOER6Z01maTNLMUpRWlhoR2dZTUxJZWtFV2VDQ0VJckZoSVhFL3FlSzdpalNvWWt6ck9qaUtrSHRpL2pSbGFFWkxpaEVkY3hsMGV0WVNNVUFqNG5QMnpLUUNoOURPS1BOSG42K2s5d29yLzltYlVzc0hFZ2FiSlpYSUttYlJmcDhJbyticTlFVnRTdjJKZjZ1bTdrTU1QTkg0MmJZVmJpeWlDYm0vczhpWUdFd3BQdVpyVlZlRGJNQkloSS9RWmZoWHZZMjU5VHRBdzhFd0xETFlJQ2FHYkc1amxKU0Flckw1VFM0ajM0RWN0dDcySmJ0dDZZUmhSVldidXR0RlUwZFlpcEZZRjEzNXNQMFRMY0xlRUpEbGx6aFdQZS9UY3dpd3ZuOFluYkNZUjVrRGF0SWlESzBJaWJLNmp5MjRvWkJndFlZZVdrREQwcm03Rkx0aWJtTExIOWtwTng1aWtqbHVyMm5Pcm90dURGd1doTTA1bWJVN29IREFISXhjOFFwL2hvL0lQM1ByaFZ1Mmt3d1p6KzJiY3FmUkI1d1RHeGlPWDJnb3lQb21NVCs2WUxvV2dDZ2k2ZUJWejVSSTcxSE9HR2dxSHE0YkhVUjFad0JINkN4OFlqOWJiK29Zd0hDSWt5Wm1mdkFXQWQvZTljTGVOdXhSYXdzNEdwaHRFYmZoSi9jbmJJR0J1L2RRS0dFM0hpKzY3UU5oRERxaUFUaUY0dmlRTDRJNHRJQ0VHWDRRa09YUDE3WWozcG15TTZFamQ3aUJNV3JaNnVOWVJRYWxmZlF2Q2IzN2JXd1VVQ0h2SEFSVVZwZ1FadWVBUitndGZSY1BZTDFQN1NJT2s0VnBIekRzL3dyejdJeUNlTzRTNzVwQlo2NWE5NmJ1YUg2Tld0ZEh1MVU3ZGl0Z2UxSHByMGI3OW1UbEI5ak5VbVVMbFBtWDBHV2FFUHNOSFpjcXRWOXI3TkRCOElpU1BzeUZ6Z2VvV3VtcURPMm40aWNZclJkTTlSRzNMOWJyckRhUG9CNnNnb09zZm9LWnV1N2Z0VThIUlhJVFl1V1o4Q1NlZGdjcCtGU0Y1bkhHVEMzTG5kdVB0K2hVb3UvRmJHMnVGcStRWG5VUGlBamh5d1NQMEZiNUdBU2padnlMRVFRNU9JMU0yRW9uL2lYL1M4ZkhNMG5VN0c1SXE1cDBmZFh5OFlZRVZJWG9ZR1gyR0dhSFA4RW5XQWZkcFMwaUVXaFhkV0FOdzdiV2RRZThzbzZ1M0d5cmpSUkVEZlJRaFBtNldMVjhrS29CK3Zyakl3NUNLa0dvTjZxNEFocTBqT2VsU1hQSmx5YnhJdXBWbzlVaFV4b3NpQnZyWUVoSTFBWTljOEFoOWhZKzZHYkJoSExTTkNUT0cxd1VMZGJUbVFtNnMyRzkvTWp1SHpNNVo3c0xmV2U3Z2pJc0xDSHBqMFY2dVgwYmNweG10YnFNaVNHMGJEV3JXV0k1Y2NKS0xMS0NQczRKMnc4NHVXQkwvNTNHUjk1VDBzbE5PTTMvM25KTjRFYzhNSGw5WHlCbXl1WUV0ZklBaVhYc0hoNGxMd2xkMDFXMmFSbmUyZ09FTXQ4MDRSYnBlYjBqeVNmU1NrekhYU2VqQU5CS09oZ3UzVFI1RTVvL1k5UlhiWWlJVEI1REpLVlRCQzZxQXdnZDMwS0RhdExxNFh6bVVMWVFWc0dwa3pXMGJieXlmamRndkZqRHM4ZXhOVGVQTjNKMitycWxwdlBuN0FUQXVVS1VjbUVLbWJieG9hdHVBWUdvMWNKUFFRUEVzVWQ4NFlRdkNBcGhFRzU5aDlvMEZETGNwRVJtbEQyVnRLZy9jeTZlUXpQS2lXSjBpY2NrODg0RWxBRkhHc2JIY1JnQTQ1THBlbFVxWWpiWFdhY0YrUTF4ZlF3VktoNCtpS0d5c3c2M2VYdVlnUXBRMVlGR3duUkZjUUpQb3Y5WTdKLzdQNDRiR0JTYzJ4cjJka3hmWW1GY3ExbklxY1pmOXdyaTlBbkpnUDhPRXIzYzE2MWJ5c0Y5Y2NOVGJwVjVIMTIwV3RYTEJCQUZzYmFLQTU1VlFzUWNzaXRzckVnZFVGZFpBOGNFV1FJWHE2RE5NNHR4UkFReGdzNXErbmp3TEdOU2k2RmhhS2ptSE12b01rOHNKVldBTkJEKzFhU1JDRWxZdVl1UDdiR1VCazhkUmpXWVZMWXJWS1JKSFl0MVhrVVZzZ21OdGVPRDlnMUNFYkt6RDVzNGlSR3RWdEY2M0krRU96ZUtKb09NN0QzTGZqeERyZGQ4WHJBaEpiQm01NEt3STBaenJhaVpDckh1UnRJQ2hJRzZ2UUZ3U1Brb1luRzRrUXBLY1h3NXZEblVoZWx1NllMVWhkNVBSc1NqNU5tS1dxaDFiUXJGY1lSODVWd2UwRnZDTzIxQWRXY0RFdVN0MlpuVVZyTUJJcHMremdHb1FOMUZOOUFuR0wwY0QzRTExcTNDV3FJOFdzT3A1cmdDbU0zRmtBZE5XRG1zQjIyZ0pjVW5URmpCNWJOSVBveUNXcUc5Y0NCL2hEYmYrODIxNDRQMERGNVpYSGppQWYvUmhBS3FKRUI1WnlGMzNVSnFhSnBXOWZpVTZEbTVvNXdnQVhDdDVmQSt5Rm5Ea2dodTRkSXRJY3FWWkhpU3NYL2I2TTB2MktRZWdpaWVDOFZFdU8rNG1xQnRsVGROdVdVUHRnc3RsS0krbDcyMHJEc2Zic2pOQ3JRb2JhL2JhRXlKRXhpWnlDMTlSWE9IZWNycmtOdDBTWVEwd3ZsODk4QTVBcmJ4K0EvdUZHa1NhRnNCaHRvQ1V4NktJK0JHMk44RU5VbThwUXR4M1FMdlo1WVZmaG5FYk56cWdlSlpvcnprQk45c2p5L3pxODZzQXZxb214NFc0dHFUbWxjR2h0b0JvMXJDbDc3T0ZCVXluUzRvUW0vVWpDNWdQWDU1KzJvNEpPWFA2QXFpYjBWcWVicEordUZFcXBVSnVBSmpybDZtLysrTWRkOVhOTlhScjAyYjR0WGZpNGpsNXNDZVhPb2hRNVp1dU9FWmpYajBSOFVURUF6eGJUc1dhaHlZLzYzMmFjMW4zR1NicmhCT0pYV1l2T1h2dnVGOThRUTNwSWhlY2ZxK1Q3cWNoOHhQYncrVis0eHFkdEhYQkJxQjI1dlJOd0piTS9lcUNuV2hJNTRFMmRsQm8rUjJRT0hLV0NIZ2VhT1BENkxjcjdBZW5pSXRQSWpmRFBQT2Q5YU42ZG1FRnNNR1NrdzJnR1VqaS96d3UzREtJSWtUOE1wTFRnU0FXSDBtaU1ZK2lkOXQxeDFLdmhKUktxR29UaTdEUE9JOExiajBxZ0o2cUdsVTFLQ1o2cjFXYi91ekwzNXlMR2hBU3kwNDVEUzJJOXBacmhvWjBrUVZNN3hSbXR1MFZIWjdEK29jOEM3aWZ1UkRSaCtpeTU3MkRLNWsxSjRiM0hjWW53QTNCREZzd3ZJODhoQnkwRWJPQ0gzeTM2YTV5NEJBeWM0Lzk0L0Q5dGp1Vys5cXFyVXIza0VOdGovczFWYVh5MVBQZnkyNlBSSWpMSWdPWS9TdEMwdXRadEJRaHlkVkl2TVRMUEJlOEg3aFU1dVVnRWlHOC9KV29pd3lxNzdrRFRCTkh6N0tiR0dJUjRwWFFNTHpHOVhkRE11cWExZkk3WUtrY3RYcVk5Ni9ZWGFjT0lRY1BXVGZzbDIzZW1BQjFFMVJENDhNYk5nNTBCYmhDRTBRaUJOdEhxd3BRZmVuTDExem9pZnNSU1JWQVNmeWZ4NFZiQmxHRVVDcEZZMEhxYjUrMzEzRFhISjZMa2krcG04dmtnZThqcnRWREY2K2lnSGNZNU9BaGF3SExZL1lCMVVCTXRiOWlZQTg1aEdYQ3J5czVpRVJJNnBkTXNaOUVpSUs2ZjVFZndkYmgxTjFiTXhHaTBmOFNIVC9PUW8xbVRCSmlSWng5YU1QSTdRUS9seFg1cHR2NUNWR090SEdjb1lDTWowZXpvZ2VyTHViTDdTVzB2ck1vMDlzM0NINTYzVlpGQWl2alBLOEVCdzdhQitLV3VxRlJCOWY5QUxYVzc1Vm1oVEVTSWNsZkt2RStFeUhSYmJ0L1laMDJsUzVQaEJDKzlZbXh3SkpuQ2VKUE1sbXJNWXhjTW0veUVJdVFCS3BuWC9nL2J2V0l3bU1Bb2pxRHkrQ2hFeUZoKzY4WFR6aXRibFp6VVVOVUtRblQ1NGtRby9HY0lHNnJHT1BHaVFCaEMwdGliRWlVRG9hUTB5c3VoeTRDYjJxVFlLaEpFUkpCdi83MTF4Q2hXbHQ2VEZWWDNGcy9RM1R3eGpjL3UyV2dSRWhPQVJRM0FVM3FUVTdkWFBhZGpzZUVSRWxWTGFkcUZiS0F1Q0dleVhUSmh6Y3NuTUJsbDBNL0xwOTYvazJhSUZlRUlMR05rekN6aDFtRXVIOUp0Qllyb1FYTWVvTFlNY2ZHMHZrSElXb2h5YWFUSWVUYVJiNEkrZlNucXdMSXVkUGZWbGkyYnpNTHV6anVRTUdiY0YybWdocm01bUxyeEx2QnhocmNXa1FSdklrcEVKQzFPMW5uUFpRUXovczl0M3F0VmJwY0VaTHNvaFc3SDJGWVJVajhHdHVPcENMU2N0L1dJaVJyQlJ3cjhaL1pkSnF6NzZCekpKYXRrQ3RDUXRSZVhvak5nYkZ4Qk5YT3FEU1pURGZvSXNTYk9HQTV2NHpXQTNzZjRmVk1URWJSVXMxdDE0a2pUNFQ0RlpnbzJYellYTGNQd3dSMlVMdElOQU1USlgrUHhjRGVjYURMR3ZWMGtXdHUyeW90a0N0Q1FxaisyMFZjUC83YW1RZHRJRXNBa1ZRQmxJYi9HNjFacDV4bS91NG1Kd2VjQy9iTGlJdHdGVzJiT0lEY1pUc1p5RXFZdHpuV3IxeUJNU3Rpek9hNjNWbzNjWlQ4c1hGYm4vYkxmUmNJUGVSdUFoY0EvRjk3dHFYckRaSGZFaEtLa1JRU2IvMlFpWkRVWFdiUzJWdmJ1U1VraWRnMWFYUWVJZTRWRXo2ODdJTWNkQzdLdzl4Y3lVZStDSW53QjFFaDlFcW4vdzJBTVR5RE1seGpSc0tSY05WcU5JRGNlOEFPUnZmbTdzT2J1OWR1YmpYaDRPUVVYamd3M1Exa04zZVcwVHR1MnRkRE0zZ3E2TmoxbnR4Q1g2RVlWeHkvaGNkL2xoMTNpTkZTaEdRRVNZeGhFeUhSZlNWdjBVVzV5dHhiTXhFaTBmL3greThKVXlBcVVmTFlRalphbE1Ia3dobFJnRjNPdnRWU2hDUlJmL24wQmJkNkNRMjcxK2hSZ0VFWElWRWtMR05zUkZSQURqL2d1RHJtaHRWaVVmb2NFYUxibTA3QUNLWDVqemh1R3piWDdYckpzdzlKaGk5c3J5cHZxS2dCM2dJSkI1KzNoWllpSklPTEFOVXpwOTlHd2dJb1I0a3VMUGwvb3pYcmxOUE0zOTNrb2toWXBnNTFLeVM4KzQ0Q3RtK2ZMcjJYdnA0Y0VhSmJtMUJmUXdILzRDRkFrSTExdEZ5eHRyTGthanVlVnlUUjBCVk9oTmZkcGt2bEo1L2JWUUZzS1VMeWhVbml6UjhTRVJLS2pJWUxpVzZ6UFJHaTRMcGR4WThyUG8rbTA1SHpJQWVVNndRN2lKQkdsUEZmQWw0RHFFbjlieHc5aWFhL0RRNFN2QmszRlpkWFFseDdzSG5iQ2c2emRCMnoxSVp3Q0txd1pXUEkxTDlyeC9kN0Q1eWc5UFAvMEJWSUM1bVl3cnZiVGxLdnQ3clk2ckxIVUhRWldGYWdZcnpmZC9SV2kxMXkwYllJaWJwcVpTdFR1TGRnb0VXSWZiZFRiN1BFdit5K2VTSWszRVd6aEtzZjU4MUEwRkNYR2lDdVcyaGJoRVE0KzlVdHdBVzcwLzloRjN4QzRSY3NKOTVBaUJCUDBGQ3dlWGFwUVEwQ2E4WE1UNjNWMC9YVmhuM3pSQWdrSHRUV0JvaGdWbStEYTF1V2UrKzNoZENMdzM4MGMyY0Y1emJjaGg4QWYrM0kwUElGRFpteUEzWWpRa0pzaFNmY1Bydnczd0JFZFJ6azR3QWk5cWtXWG9TSUY3bmJxQnRXc0JtcjFodlhtKzZiSjBJZ1lRRmRPRjQrV01INFpVVEJDMVcxaXo4anhGTzlKaDh5QmVmRUZVQVIrVUdaMG91QXg2OS9Mb3d6dm12c1dvVGt0NVJJWEVGMVYxNThFYUtwYzRiSUNvNjhmVnVLRU9LSHBXQzdZQWtwRVJJZU04OENGcDNMWUxmR3F3RzdGaUZKVko2MEE0MXI1MDV2QWY4WEFETWczYmJHSnVKdVdBN20ycnZVMzJyYWQzTDN1SDJEK3UwYjlzRWRQd25pWHRYSkF3aEN2WHRuNmkxVUEwR3NlL1gwU1ZjWXIvSGs1OXBxNzIyRlhZdVEvREVraWJkYkdwZEZGQ0d1TktSZmEybHozeDFFU05acXBOeTR4Q256MGhXVGkrOHo2Nkk3eGU1RlNBNXE1MDR2Z2cxMnJxcXZ1ZXM5SnNqUndvcVFVbUxBZVRnZGEzVTdpbktLTnQ5M0p4R1NYSStXSDl5eHZERzI3Ym1KQzg3YnQvK2NYZ0QrRHN0ZmM5dGJkck5xRng5R2hPUmh5ZjNZUHJQd3F1T2VBSTRXVllTSTUwY3RJSkh3cUc0ajZncWdOTjkzUnhFQ0RZVkwxMndCWkd3Q21aeGlrQ0ptSVp6MzBQOEZVSHJ5OHgyNzNTUTZFaUZOaEluN3BtRlBVRlFSb29SaUkvNWx6OW1wQ0VsWmswVFNRWXVZRmFQeHBlc1Uwb3ZJVFNMaWJYOXQ0Yk1ndjJWOWpmeEc0Vnh3dVJ6RmdZbTRXaFd0cFFlTjUrNDdkUkNabkFaQWJ5L1JWc3lYTURaTXVZeTRTUHk2dWx4QWR4c3ZEZnJ2M04vZkdUdjEvS3YwQUYwUklUbXRKUzdDRmlDZHQ0NzBRb1NFTmlqNUwyOFFldDYrOXVMc0wreUlGQzhiSDZRbXRxY3NZVzY2NG5ESlcrMFZ1aUpDc25BVzhEekluMXNMYU51SlZUa2h5SW13OXROWEMyZ0N0SmJEdGJOdmRSdlYxWGdmeEE1Q3A0V0ZDZE1GaXUzVG9VMGZlRjg0MWNDOUpPY1IzaFJWalBBZGw2WnBkS3RPMFMwUmtvS3FHaEU1cjZwdmlvaFhQYnN3NytvOW4wYjF1T3ZvdWFzV0U4MzgzVEZuREdLcU82Zkw0MnBWcEpZZXVKNWNrc2M1OTZ5bWpnUzFyZ21FYm5HQ0JPNDIzL0RRUDBlRThxbm5YcVhINkxvSWNZWFBTeTdUOXR5dTlGdUVkSXZMczJLRHlLV1JZL1o3aEo2SmtGUUJkRnp0M01JeGtHT2dxSkd2dWVUalFHWFBYWENYdUtpZVNBSGM2QzQ1VkZjVlZpem5QZWtTTFZVKzgreWU5UlBybVFoSkx1T0NHSm5CTUJNOEVnOXliMFZJZDdnOEZ6d29IQWt1ODJqMkREMFRJVTBzNEFySVpaY0YvMVVBRlI0SEhyTW1SZVpHRnJEM25LTHZLV0tBMTBIL245aEVTMjdqR251SVhvcVFxQkFtdUJWVlhSWVJUOCs4K0tjQVZlci9GRGlDQ0FKejBHZ0pJYlk2cWZNVWdNdXpNQlNjRThRRnNlYXZ5bVBtdndQd3ljLzNaVUxqUFJFaHVjSWtnVENqUmlKa2J6alFyaHVkRDRzOUZTRzUzTGsvOFVGOFVJTDYrTDhHVVBRZklmd2lnS29OQTFJRWQ1dkhGZDRGcTRhVzdWVTgvUTRLNWVtSC9pUzZtU2VlMkhVdjVtNWlUMFZJVzhJazg3U0xKRGdHVVlRMHdHVzMyOWIzR1luMlZJUTBzWUFHSkhCWjhwcUlvS0x2QVQ4QVVPV1VPK3ljdWpwaWZKNlJCY3h3eGtYNGZ3OTR6NlZ5VS9EeUZuQXhMSGxTZ01JSGV5OUM4amhVTlhEY2E2cHE5QnRmZlVORXBsU1ZXcTErd2gzMnBFaTZBSWFXcUo5Y002dlRGMDR4N3JLdUFhOExVQjQzZitpU2IvSEpMM3pvc1J1OVF0OUVTQ3RPbkZtUjBOU29kVEQ5Rmh5RkZ5RUN5ZDdMK1Q2NFdPaS9DR21EQXdqT3ZuQU1PQXBnMEQ4Q0VEaXNLdlBwYys4dkY0eWRoK01TUUlYU3YzS2Jsam4xdVdoSzFDS2o3eUtrSFM1YlRRZ3RBTFFXQ1B0QmhLRGE4SUlNRXZvdlF0cTNnQ3ZodXNJZkE0anlDSERDY3Zvb2dNQ3NJalBwNnhsMEM2aUJPOTJ5SWl2MlB0VUdCQkl1U1RqUmVCUXdnTUxWOVpxaENDSmtSODd4S3lJU0RvVDVFa0QxcGRPUEtmbzRnRWdjbTBZZ1ZRQjNFaEtkY0huV2lTNXpBbFZYNzF4Q2VNZlY5RjUwYVMvNXA1NXJPaGxnMFZGSUVaTGxRa3VZUFE5QTJKczVoREo4SWlTTk1QcFcvQXc3TFFUOXhNQ0lrTGJ4bHk5V2NBUHU2MXYxVHdFWTFZOGk4Z2lBSXIvcVVrNmg2Ym1RKytXQ2NaR21zUHczc0lYcVI0SmVCTUhmUHZDYVMyNzR6ZC9zYTh0RnR6RlFJaVI3bm1aY0F4SStOS3pBaDNRUlJFajJtUkI5Skk0ZGN5OE1SUkV3TUNJRXJBdk9ucXVCKzhzWERYR1VwZ3N1MFJJaTV3RUV3a2pqZHhQV0ZaVlp1MDE5aEhDb25HMkRWaW9ndmsybWsrNEdLeHFHTmRFb0xrU0EyTG9heUliYnQ0cXJ2eUZzdUFJWGdGWmR0U0g4VkxJTTNITHJsN0FGY05sYVJqR0FFZnNTRmFMMW9wc1FlbENINkpFSU1Wa0wxd2xYUGZmaVBPaGhBSyt1eHdBTVpoSW5aa1NZQjFERFFVWEdIVGNIdGlCR25TU0lYb0F0a2JBdm5kekVkclpkRStRREFQWFVGalpsdzNNcXRVVHBBclpRclF6S2Q3dHVZL2dzWUp0YzdkeUxJT0s0bHU3TlNMTENaMWRpM3huR1dNdlpyOVZCRXhob0VkRXAvaitSbDlrT0hoSmRZd0FBQUFCSlJVNUVya0pnZ2c9PSI+PC9pbWFnZT4KPC9zdmc+Cg=="/>
            <prop k="offset" v="0,0"/>
            <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="offset_unit" v="MM"/>
            <prop k="outline_color" v="35,35,35,255"/>
            <prop k="outline_width" v="0"/>
            <prop k="outline_width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="outline_width_unit" v="MM"/>
            <prop k="scale_method" v="diameter"/>
            <prop k="size" v="40"/>
            <prop k="size_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="size_unit" v="Pixel"/>
            <prop k="vertical_anchor_point" v="1"/>
            <data_defined_properties>
              <Option type="Map">
                <Option type="QString" value="" name="name"/>
                <Option name="properties"/>
                <Option type="QString" value="collection" name="type"/>
              </Option>
            </data_defined_properties>
          </layer>
        </symbol>
      </symbols>
      <rotation/>
      <sizescale/>
    </renderer-v2>
    <symbol alpha="1" clip_to_extent="1" force_rhr="0" type="marker" name="centerSymbol">
      <layer class="SvgMarker" locked="0" enabled="1" pass="0">
        <prop k="angle" v="0"/>
        <prop k="color" v="245,75,80,255"/>
        <prop k="fixedAspectRatio" v="0"/>
        <prop k="horizontal_anchor_point" v="1"/>
        <prop k="name" v="base64:PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIGlkPSJteVN2ZyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+Cgk8aW1hZ2UgaGVpZ2h0PSIxNjAiIHdpZHRoPSIxNjAiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBS0FBQUFDZ0NBWUFBQUNMejJjdEFBQUFDWEJJV1hNQUFBN0VBQUFPeEFHVkt3NGJBQUFmRzBsRVFWUjRuTzJkWFpBYzEzWGZmNmVuWi9ZRGk4Vnl1VnlDRUFtQ0lDakxNTTFpVkk0ZVhFNkZlYkFsdVV5SWRzbDA2SkpKS25wSTh1REtTNnBjZmtnNXlrTlNlVXE1WENuYlNxd0ZSU1VWeDVXSUFDaFI1WklsRnFQWUtvZFNzU3dhZ2tDUWhQQkJyaGJBWXJIY3o1bWVlL0p3YjM5T3ord3NaMmFuWjNiK3FFSDMvdnYyMSszYjU5eC8zM3ZQRlZWbFgrSHNsNDhBMU5RN3FjaEpBSUdIQVZDZEJDWUI4SmgzZTB5Q1RBSVlaYzZsbjBSY09qVkdSRkRWRFpBTnkzRlRSRkIwQTVFMXQ4OU5iRlp2cUxJbGdrSDBod0NJbkM5UFRKNUhGWDc1NlZVUjhWVFZoRXViWkRnNXIzdFBkb1FSZGc5cFpRR1RKWGRnY1BiTDR3b1ZnRUM4UndFd3pJR3phTUxQQWFETWdZUldic1l1dEFMNEx0MlUyK2FEVkFCVW5kVkRmUkY3RHNDNGJRRlF0YnZLaHN2VktrSmdPVUxyV0FYTGdTNGhnTW9pc0dRMzgvY0lIc3FTaUN5aFVKNmN1SUFvcUFUeUswK2JvbG14VGppLzFiTWN1TUpuVVFGYmVCUStZU245T1hIdUZ1UVhIUWVTMlZNQnlaQWFwNHMyS1VTa3FvY0lndnFJaktNSzZMU0kySDBKbCtFQjFDNmpGMThBTmFvU2lBREN0eHg5SHZpaFBZMis0OUtCSytURGdwRUxIcUd2YU9tQ2k0N3EyWVdQQy9KeEFGUytBS0J3dndqM3B4S3FOckZzWGVBMFlkRWtZKzI2ektucUplQWlRTW56L3RoZHpVWC8xSE9YaXVaYTIrVmF1dUNpUTlJKzFGbHo1L1pHR0FnTWpBV3NubnRobmxCSTFIa0NBTkZIUkRnT29NcmpBSUpNSTB5bmRoNGVDN2dNTE5zLzVYVjNOZThBYjl2c01OOXkrNjJXbi9wbnEwV3pkbm5jQUZsQW5jY0pDUlg5WFFCQjVvQlpTQXFFNGJXQUFyT0l6S0lLcWlmY1RWOER2V0xGRGhkc29lVWFzTnJueTIwTEExUUE0MElsS2xscUh5UHh3Z241RnJ2QUtLUUxEczY5ZUF3NENxQnEvdERSaDkwdlJpOWRhN3ZjSHJyZ1hianFpNGhjQklWUzZmZmRWUytOL2Rxek40dm1na2VmWVVib0svcHZBVjk1eFZQd0JLaFZmM3JLWHBWOEZQZ1psK0pUQUdvL0xrK2w5czJyN3UwMVZ6d0RpQ3JMU05UMi9DM3M1ZjY5d0pzQWZuWHl1K0d0eU5OUHM2OUZpQ3Q4bm0xY2tGOTNYL3NmYzc4SWtsdTNLVWdKUkpEVWtuNXpzeUN6N3RwT3VBMnZLc3k0cTQ0S1lMOHhjc0VqOUJYOWM4RmZYemdPVUt2TGI2dktNODY0bld5YXZnaUNJNDhyb0FqWmtSTmVjNGJ6TDhxTS9VOEFUajJ6TkJJaEkrdzc3S2tGcko1OTRUREtQQUtpK2p1T2ZoeVJ4d0VVNW9TNGhwVzZzaUpVOS9LNFFUU0FvbGZVWHZzYmlId2Z3SU92dUR0YUtYL20rVDFyUmRsVEVhSXdMNktQS29JZy84TFJGZmVMbm1sMkdlM2Q5OUtXeHhWU2hMVG1sS01pZ2dxemhGM1dsRmRkbjBQWXcxYVVrUXNlb2Evb25RdCs1UlZmNCs5N2YyYlBKbzhCajhYdlphTzdIYm5nZnVrUzI3TWI1VlVSL2dyQS84eHovMzVnWFhCRElYS3FzWldBYk1iWi9YTk9VZ1RPclV0bU9YQ2MwcERwMmNJaUloNUFON211VzhEcW1RVTN6c0o3VklSSEhmMEZBSlREQ1BPRGFnRzk2Vm03Y3VBZ2N1Q2czYnl4WmwrWUQrNmdhNnZXd3BoNllTeGIrNXl0bVFPWGNVTUFqTERnTFB5RkN1VUxxTUJubmxrcnVnV2NCd3pvUHdiNXJPTk90bXZ0Q20wQkQ5a0M2TTBmd1p2L2lMM2VXNHVBWXQ2L2ltNnMyK1JhdDdzV3diSzF6VVViam9FY3N6ZEgxYVg1bXUzaXBVWkVOcnBwQVh0UkFBMFpjYVB1SnBOTGRzSEZCOG1jYWE4dFlKWUhWQlVSaVN5TEtrTlRMeVQrMjBNd3FEUVVvT0paUUpFdnVxZHpFampaSTRuVGUvaDIxS1UzZndUdlhtdnR2QWRPTkNUejdudlFKcDg5REI5N0hJRGdiNzhOQ0d4dndQYlczbHh2RHlES3AyeGgxT2txMVljQUt2QjczVHhIRHl5Z1JsYmp3N2pid3JuZ3RwRjgxY0l2Y1BhQXhYTzN1K09TNkxZdzZZb0lxWjVaT0JIVkc0U3dBK204SUhPN0ZSeDVIQ1RJSG5KUzhzRXYyL1VqOW5hOFE3T0lxL3VGeTF6VTYvWUhtT3Z2Z29CWnVRVXJ0d0RGM0xsZEhOZTZhMDZ2QVZkc2h2RFAzZE5aR2p2MStZNDd1SGJKQXNveDRKY0JCT2xJY1BUVkF2cGxaR3dDZ05KUjUyN0hKcER4aVp6RUdaUks5Z2Q0RDdtdWpPOWZ3YWhCRUdUMXRqMXRnU3hiKzV6Y0QzYW9xMFlkUmdSVlhTcUlDSW5OU2FlQ281OGlSQkpuMUJ6dXcwRHNnMnA0c1lwaDJUNEVKN0YvNm9ZSTZjZ0YxODk4NWJNQUJ2MHRoTTlDMm4xK0dIZmJEeGRjY3VKQzVvL2czV01GQjVVSzNZUjUveWVJQ1BYM3JxQ0xWKzNEREtyRktWaHRjZ0pXVmFsK1dkSC9JZ2pscDU1L296QXFXT2pNM2ZiREJTY0xmMmRDcERsRVFxc1JXL2lCYkVWSldJVXdNRUFud21UWEZyRDI4bGZqc1JuMStuOXk5S080Vm8vQ1cwRFAxdE1rMFpvUmZsNnhuQnZUN3VwejNZS3UzYkhMTzh2b25XVUF6TlZMOXNLQ0d0U0R3bG03Smx4Z240MStEK1Y3QUJWLzdBL2NiUWJ5NUc4SHZiYUFVeEFGYjN6S0xhUGpGTjRDaGdYdzRFejhmZSsrbzAxdnRsdVFxVU4yV1JtSHUrNEJRSmZlaTEreWVsQThhNWZQMldldFBLYkNjYkVORC8vUnZlVWJxbHJkQ3hIUzJOS1JYSmYwa2c2NWhwTjBnZXVScDIwRHlUUGI5bGQxZDFwQWE5ZVVjM2RpSE9XQnBDeGNjcjI3RnJBZS9BYndMOTJWak85Ni96N0QvL2d2QVNCVDA1RlYybE5VS3BIQThaK3dvMUROdXovRy9PUWk0cjRYRGdaa1dvUnBGR3IxN1Q5eTVGOEEvM3MzUittS0NNbDZ5aUs3NFA1WnZoWUlyVDdTNEFJTDZJSWJPWTFxN2IwVElkVXpwOE54dXI4ajhLdzcrenprdU9ETWtnNjUxSUU3NUx5UFBHVFBVeG1EeWxqekc5NUQ2TzFiNkIzYllxSmJXNFZ6dHp0L210SHpBQW92Z1BjVkJDcW5ubDNzcmd1V2FNamtjZUxZeW01VGVyM0lGbEN2djJ1WCtYZlpkd3lrQll6Q0gvTXc2RHlLSnlKTDNSVWhTUk9Wc3lsbEFTVzlwRU91NFNSRjRqSXZUTkdzMDE1eWdFSEZRekR0ZHR2YW9RQitNVmE3OHVCL2NDc3pyZmNwT0Nic0o4elNzWTlTZXRDMTJYYTUxYU5kQkQvOFcwUUVYVjVDVjI3MjVScTZDdFZmUWMxeDkzWitzcDFkUnFQaVJ1Z3JXbHJBMnN0SEV6SDVuT1ZUemZuMGtwRVJQVkFoU1hQZkNTZGwyOTJLa3QvUTJoSDJidDRORi9lSWpwZjJuRHR6M2tHWHBldXJjZk5jZVB1SnFzaWdjTmdJcmljQWdwZE9INnQ5YmNFTFhqcTlvamEwY0poZkpybHM3WUpWRHVPaVZJbWJ6RVV6RHlPRzVQK1pKeVErQkJjcGZUcmpwR3lWci9qbGhnS1lMV2p0Y09GNmR0a09wMVBUOXUvYlM1RjRzOXVLVmJkcm0wTm1SSml4bkI1enQyeEVaS1ZaSFhEa2drZm9LM0l0b0w3eVNzVytrZklFeXU4aVdzd1B1Q01VRnVyeFJiVk5qUXZFY1djYU1MS0FJL1FWdVJZd0NKYmNIR3M4Z2pBRHlacDlSaDAwY01VV0lhMitRTGN0UWpiWDBVMDc5NkRNekxwTEZjVHpkaVZDd3Q3U0lJVVJFbDNranJtSzk4TzFNd3ZIZzdPblBmL1U4eGZiRWlHSytRV3gzUTJQUitvMzlSRHlIUEpnaUpCV2RZbDJSWWh1Ym9EN2JpZlRoOEFWdm16Nm5VU0lJU3pjT2h3aUpNWEpVWHVyZWh6bGhNdjNpeU1STWtLaGtHc0J4Y2d6QUdvbi9oc2h4T1k2QUxwNGxmcmxId1BnMTl6c3FYZmZpemQzdU5tZSt4Zks0d3ErcS9wOE03dDVaQUZINkN0aUMvaU4weFVsbWdYOGZsZHRtbTZvMGU5akVXSnVMRnB1ZlRVZWhMNThBMUM4aVFOZzZ2Ync0clhYT3JLOVpkTUhRUkZFUTI4NE81ZWZIWFR6L1MvNSt2cWZHcjcvSmE5UmhDZ1ZFYlV0OWVJZGFlMTU5NmNJc1pHd2dQVlZ3Z2hZWnZtR3pmalplVERHNmxtL2xOcTNhVXZJMXFhOW5pQVlRaEVTRmNSWllETE9SSHdFNDE3Q2tRZ1pvYitJTEdDdHprbkMyY2RIaUdIcTlnZlVyMTZ5WE5LaUJsVVEwT1VibVBJbFVQQWUvdG4yamgxVTQzTU1LUlNwaUZCUmhlQnE1WmNjZlJrWGEyWmtBVWZvS3lJTHFNb3M4TE1BcmVPaERMWUkwUzNiZ3FGQnJlSE9ja1ZJVUlQcXR2dWo4WGhSeFZzTjFBTWcwOXJSUW9Sb3ZXNFBxcVk0b3FHSG5GRk91TDlXVmZVeXBMOER6Z01maTNLMUpRWlhoR2dZTUxJZWtFV2VDQ0VJckZoSVhFL3FlSzdpalNvWWt6ck9qaUtrSHRpL2pSbGFFWkxpaEVkY3hsMGV0WVNNVUFqNG5QMnpLUUNoOURPS1BOSG42K2s5d29yLzltYlVzc0hFZ2FiSlpYSUttYlJmcDhJbyticTlFVnRTdjJKZjZ1bTdrTU1QTkg0MmJZVmJpeWlDYm0vczhpWUdFd3BQdVpyVlZlRGJNQkloSS9RWmZoWHZZMjU5VHRBdzhFd0xETFlJQ2FHYkc1amxKU0Flckw1VFM0ajM0RWN0dDcySmJ0dDZZUmhSVldidXR0RlUwZFlpcEZZRjEzNXNQMFRMY0xlRUpEbGx6aFdQZS9UY3dpd3ZuOFluYkNZUjVrRGF0SWlESzBJaWJLNmp5MjRvWkJndFlZZVdrREQwcm03Rkx0aWJtTExIOWtwTng1aWtqbHVyMm5Pcm90dURGd1doTTA1bWJVN29IREFISXhjOFFwL2hvL0lQM1ByaFZ1Mmt3d1p6KzJiY3FmUkI1d1RHeGlPWDJnb3lQb21NVCs2WUxvV2dDZ2k2ZUJWejVSSTcxSE9HR2dxSHE0YkhVUjFad0JINkN4OFlqOWJiK29Zd0hDSWt5Wm1mdkFXQWQvZTljTGVOdXhSYXdzNEdwaHRFYmZoSi9jbmJJR0J1L2RRS0dFM0hpKzY3UU5oRERxaUFUaUY0dmlRTDRJNHRJQ0VHWDRRa09YUDE3WWozcG15TTZFamQ3aUJNV3JaNnVOWVJRYWxmZlF2Q2IzN2JXd1VVQ0h2SEFSVVZwZ1FadWVBUitndGZSY1BZTDFQN1NJT2s0VnBIekRzL3dyejdJeUNlTzRTNzVwQlo2NWE5NmJ1YUg2Tld0ZEh1MVU3ZGl0Z2UxSHByMGI3OW1UbEI5ak5VbVVMbFBtWDBHV2FFUHNOSFpjcXRWOXI3TkRCOElpU1BzeUZ6Z2VvV3VtcURPMm40aWNZclJkTTlSRzNMOWJyckRhUG9CNnNnb09zZm9LWnV1N2Z0VThIUlhJVFl1V1o4Q1NlZGdjcCtGU0Y1bkhHVEMzTG5kdVB0K2hVb3UvRmJHMnVGcStRWG5VUGlBamh5d1NQMEZiNUdBU2padnlMRVFRNU9JMU0yRW9uL2lYL1M4ZkhNMG5VN0c1SXE1cDBmZFh5OFlZRVZJWG9ZR1gyR0dhSFA4RW5XQWZkcFMwaUVXaFhkV0FOdzdiV2RRZThzbzZ1M0d5cmpSUkVEZlJRaFBtNldMVjhrS29CK3Zyakl3NUNLa0dvTjZxNEFocTBqT2VsU1hQSmx5YnhJdXBWbzlVaFV4b3NpQnZyWUVoSTFBWTljOEFoOWhZKzZHYkJoSExTTkNUT0cxd1VMZGJUbVFtNnMyRzkvTWp1SHpNNVo3c0xmV2U3Z2pJc0xDSHBqMFY2dVgwYmNweG10YnFNaVNHMGJEV3JXV0k1Y2NKS0xMS0NQczRKMnc4NHVXQkwvNTNHUjk1VDBzbE5PTTMvM25KTjRFYzhNSGw5WHlCbXl1WUV0ZklBaVhYc0hoNGxMd2xkMDFXMmFSbmUyZ09FTXQ4MDRSYnBlYjBqeVNmU1NrekhYU2VqQU5CS09oZ3UzVFI1RTVvL1k5UlhiWWlJVEI1REpLVlRCQzZxQXdnZDMwS0RhdExxNFh6bVVMWVFWc0dwa3pXMGJieXlmamRndkZqRHM4ZXhOVGVQTjNKMitycWxwdlBuN0FUQXVVS1VjbUVLbWJieG9hdHVBWUdvMWNKUFFRUEVzVWQ4NFlRdkNBcGhFRzU5aDlvMEZETGNwRVJtbEQyVnRLZy9jeTZlUXpQS2lXSjBpY2NrODg0RWxBRkhHc2JIY1JnQTQ1THBlbFVxWWpiWFdhY0YrUTF4ZlF3VktoNCtpS0d5c3c2M2VYdVlnUXBRMVlGR3duUkZjUUpQb3Y5WTdKLzdQNDRiR0JTYzJ4cjJka3hmWW1GY3ExbklxY1pmOXdyaTlBbkpnUDhPRXIzYzE2MWJ5c0Y5Y2NOVGJwVjVIMTIwV3RYTEJCQUZzYmFLQTU1VlFzUWNzaXRzckVnZFVGZFpBOGNFV1FJWHE2RE5NNHR4UkFReGdzNXErbmp3TEdOU2k2RmhhS2ptSE12b01rOHNKVldBTkJEKzFhU1JDRWxZdVl1UDdiR1VCazhkUmpXWVZMWXJWS1JKSFl0MVhrVVZzZ21OdGVPRDlnMUNFYkt6RDVzNGlSR3RWdEY2M0krRU96ZUtKb09NN0QzTGZqeERyZGQ4WHJBaEpiQm01NEt3STBaenJhaVpDckh1UnRJQ2hJRzZ2UUZ3U1Brb1luRzRrUXBLY1h3NXZEblVoZWx1NllMVWhkNVBSc1NqNU5tS1dxaDFiUXJGY1lSODVWd2UwRnZDTzIxQWRXY0RFdVN0MlpuVVZyTUJJcHMremdHb1FOMUZOOUFuR0wwY0QzRTExcTNDV3FJOFdzT3A1cmdDbU0zRmtBZE5XRG1zQjIyZ0pjVW5URmpCNWJOSVBveUNXcUc5Y0NCL2hEYmYrODIxNDRQMERGNVpYSGppQWYvUmhBS3FKRUI1WnlGMzNVSnFhSnBXOWZpVTZEbTVvNXdnQVhDdDVmQSt5Rm5Ea2dodTRkSXRJY3FWWkhpU3NYL2I2TTB2MktRZWdpaWVDOFZFdU8rNG1xQnRsVGROdVdVUHRnc3RsS0krbDcyMHJEc2Zic2pOQ3JRb2JhL2JhRXlKRXhpWnlDMTlSWE9IZWNycmtOdDBTWVEwd3ZsODk4QTVBcmJ4K0EvdUZHa1NhRnNCaHRvQ1V4NktJK0JHMk44RU5VbThwUXR4M1FMdlo1WVZmaG5FYk56cWdlSlpvcnprQk45c2p5L3pxODZzQXZxb214NFc0dHFUbWxjR2h0b0JvMXJDbDc3T0ZCVXluUzRvUW0vVWpDNWdQWDU1KzJvNEpPWFA2QXFpYjBWcWVicEordUZFcXBVSnVBSmpybDZtLysrTWRkOVhOTlhScjAyYjR0WGZpNGpsNXNDZVhPb2hRNVp1dU9FWmpYajBSOFVURUF6eGJUc1dhaHlZLzYzMmFjMW4zR1NicmhCT0pYV1l2T1h2dnVGOThRUTNwSWhlY2ZxK1Q3cWNoOHhQYncrVis0eHFkdEhYQkJxQjI1dlJOd0piTS9lcUNuV2hJNTRFMmRsQm8rUjJRT0hLV0NIZ2VhT1BENkxjcjdBZW5pSXRQSWpmRFBQT2Q5YU42ZG1FRnNNR1NrdzJnR1VqaS96d3UzREtJSWtUOE1wTFRnU0FXSDBtaU1ZK2lkOXQxeDFLdmhKUktxR29UaTdEUE9JOExiajBxZ0o2cUdsVTFLQ1o2cjFXYi91ekwzNXlMR2hBU3kwNDVEUzJJOXBacmhvWjBrUVZNN3hSbXR1MFZIWjdEK29jOEM3aWZ1UkRSaCtpeTU3MkRLNWsxSjRiM0hjWW53QTNCREZzd3ZJODhoQnkwRWJPQ0gzeTM2YTV5NEJBeWM0Lzk0L0Q5dGp1Vys5cXFyVXIza0VOdGovczFWYVh5MVBQZnkyNlBSSWpMSWdPWS9TdEMwdXRadEJRaHlkVkl2TVRMUEJlOEg3aFU1dVVnRWlHOC9KV29pd3lxNzdrRFRCTkh6N0tiR0dJUjRwWFFNTHpHOVhkRE11cWExZkk3WUtrY3RYcVk5Ni9ZWGFjT0lRY1BXVGZzbDIzZW1BQjFFMVJENDhNYk5nNTBCYmhDRTBRaUJOdEhxd3BRZmVuTDExem9pZnNSU1JWQVNmeWZ4NFZiQmxHRVVDcEZZMEhxYjUrMzEzRFhISjZMa2krcG04dmtnZThqcnRWREY2K2lnSGNZNU9BaGF3SExZL1lCMVVCTXRiOWlZQTg1aEdYQ3J5czVpRVJJNnBkTXNaOUVpSUs2ZjVFZndkYmgxTjFiTXhHaTBmOFNIVC9PUW8xbVRCSmlSWng5YU1QSTdRUS9seFg1cHR2NUNWR090SEdjb1lDTWowZXpvZ2VyTHViTDdTVzB2ck1vMDlzM0NINTYzVlpGQWl2alBLOEVCdzdhQitLV3VxRlJCOWY5QUxYVzc1Vm1oVEVTSWNsZkt2RStFeUhSYmJ0L1laMDJsUzVQaEJDKzlZbXh3SkpuQ2VKUE1sbXJNWXhjTW0veUVJdVFCS3BuWC9nL2J2V0l3bU1Bb2pxRHkrQ2hFeUZoKzY4WFR6aXRibFp6VVVOVUtRblQ1NGtRby9HY0lHNnJHT1BHaVFCaEMwdGliRWlVRG9hUTB5c3VoeTRDYjJxVFlLaEpFUkpCdi83MTF4Q2hXbHQ2VEZWWDNGcy9RM1R3eGpjL3UyV2dSRWhPQVJRM0FVM3FUVTdkWFBhZGpzZUVSRWxWTGFkcUZiS0F1Q0dleVhUSmh6Y3NuTUJsbDBNL0xwOTYvazJhSUZlRUlMR05rekN6aDFtRXVIOUp0Qllyb1FYTWVvTFlNY2ZHMHZrSElXb2h5YWFUSWVUYVJiNEkrZlNucXdMSXVkUGZWbGkyYnpNTHV6anVRTUdiY0YybWdocm01bUxyeEx2QnhocmNXa1FSdklrcEVKQzFPMW5uUFpRUXovczl0M3F0VmJwY0VaTHNvaFc3SDJGWVJVajhHdHVPcENMU2N0L1dJaVJyQlJ3cjhaL1pkSnF6NzZCekpKYXRrQ3RDUXRSZVhvak5nYkZ4Qk5YT3FEU1pURGZvSXNTYk9HQTV2NHpXQTNzZjRmVk1URWJSVXMxdDE0a2pUNFQ0RlpnbzJYellYTGNQd3dSMlVMdElOQU1USlgrUHhjRGVjYURMR3ZWMGtXdHUyeW90a0N0Q1FxaisyMFZjUC83YW1RZHRJRXNBa1ZRQmxJYi9HNjFacDV4bS91NG1Kd2VjQy9iTGlJdHdGVzJiT0lEY1pUc1p5RXFZdHpuV3IxeUJNU3Rpek9hNjNWbzNjWlQ4c1hGYm4vYkxmUmNJUGVSdUFoY0EvRjk3dHFYckRaSGZFaEtLa1JRU2IvMlFpWkRVWFdiUzJWdmJ1U1VraWRnMWFYUWVJZTRWRXo2ODdJTWNkQzdLdzl4Y3lVZStDSW53QjFFaDlFcW4vdzJBTVR5RE1seGpSc0tSY05WcU5JRGNlOEFPUnZmbTdzT2J1OWR1YmpYaDRPUVVYamd3M1Exa04zZVcwVHR1MnRkRE0zZ3E2TmoxbnR4Q1g2RVlWeHkvaGNkL2xoMTNpTkZTaEdRRVNZeGhFeUhSZlNWdjBVVzV5dHhiTXhFaTBmL3greThKVXlBcVVmTFlRalphbE1Ia3dobFJnRjNPdnRWU2hDUlJmL24wQmJkNkNRMjcxK2hSZ0VFWElWRWtMR05zUkZSQURqL2d1RHJtaHRWaVVmb2NFYUxibTA3QUNLWDVqemh1R3piWDdYckpzdzlKaGk5c3J5cHZxS2dCM2dJSkI1KzNoWllpSklPTEFOVXpwOTlHd2dJb1I0a3VMUGwvb3pYcmxOUE0zOTNrb2toWXBnNTFLeVM4KzQ0Q3RtK2ZMcjJYdnA0Y0VhSmJtMUJmUXdILzRDRkFrSTExdEZ5eHRyTGthanVlVnlUUjBCVk9oTmZkcGt2bEo1L2JWUUZzS1VMeWhVbml6UjhTRVJLS2pJWUxpVzZ6UFJHaTRMcGR4WThyUG8rbTA1SHpJQWVVNndRN2lKQkdsUEZmQWw0RHFFbjlieHc5aWFhL0RRNFN2QmszRlpkWFFseDdzSG5iQ2c2emRCMnoxSVp3Q0txd1pXUEkxTDlyeC9kN0Q1eWc5UFAvMEJWSUM1bVl3cnZiVGxLdnQ3clk2ckxIVUhRWldGYWdZcnpmZC9SV2kxMXkwYllJaWJwcVpTdFR1TGRnb0VXSWZiZFRiN1BFdit5K2VTSWszRVd6aEtzZjU4MUEwRkNYR2lDdVcyaGJoRVE0KzlVdHdBVzcwLzloRjN4QzRSY3NKOTVBaUJCUDBGQ3dlWGFwUVEwQ2E4WE1UNjNWMC9YVmhuM3pSQWdrSHRUV0JvaGdWbStEYTF1V2UrKzNoZENMdzM4MGMyY0Y1emJjaGg4QWYrM0kwUElGRFpteUEzWWpRa0pzaFNmY1Bydnczd0JFZFJ6azR3QWk5cWtXWG9TSUY3bmJxQnRXc0JtcjFodlhtKzZiSjBJZ1lRRmRPRjQrV01INFpVVEJDMVcxaXo4anhGTzlKaDh5QmVmRUZVQVIrVUdaMG91QXg2OS9Mb3d6dm12c1dvVGt0NVJJWEVGMVYxNThFYUtwYzRiSUNvNjhmVnVLRU9LSHBXQzdZQWtwRVJJZU04OENGcDNMWUxmR3F3RzdGaUZKVko2MEE0MXI1MDV2QWY4WEFETWczYmJHSnVKdVdBN20ycnZVMzJyYWQzTDN1SDJEK3UwYjlzRWRQd25pWHRYSkF3aEN2WHRuNmkxVUEwR3NlL1gwU1ZjWXIvSGs1OXBxNzIyRlhZdVEvREVraWJkYkdwZEZGQ0d1TktSZmEybHozeDFFU05acXBOeTR4Q256MGhXVGkrOHo2Nkk3eGU1RlNBNXE1MDR2Z2cxMnJxcXZ1ZXM5SnNqUndvcVFVbUxBZVRnZGEzVTdpbktLTnQ5M0p4R1NYSStXSDl5eHZERzI3Ym1KQzg3YnQvK2NYZ0QrRHN0ZmM5dGJkck5xRng5R2hPUmh5ZjNZUHJQd3F1T2VBSTRXVllTSTUwY3RJSkh3cUc0ajZncWdOTjkzUnhFQ0RZVkwxMndCWkd3Q21aeGlrQ0ptSVp6MzBQOEZVSHJ5OHgyNzNTUTZFaUZOaEluN3BtRlBVRlFSb29SaUkvNWx6OW1wQ0VsWmswVFNRWXVZRmFQeHBlc1Uwb3ZJVFNMaWJYOXQ0Yk1ndjJWOWpmeEc0Vnh3dVJ6RmdZbTRXaFd0cFFlTjUrNDdkUkNabkFaQWJ5L1JWc3lYTURaTXVZeTRTUHk2dWx4QWR4c3ZEZnJ2M04vZkdUdjEvS3YwQUYwUklUbXRKUzdDRmlDZHQ0NzBRb1NFTmlqNUwyOFFldDYrOXVMc0wreUlGQzhiSDZRbXRxY3NZVzY2NG5ESlcrMFZ1aUpDc25BVzhEekluMXNMYU51SlZUa2h5SW13OXROWEMyZ0N0SmJEdGJOdmRSdlYxWGdmeEE1Q3A0V0ZDZE1GaXUzVG9VMGZlRjg0MWNDOUpPY1IzaFJWalBBZGw2WnBkS3RPMFMwUmtvS3FHaEU1cjZwdmlvaFhQYnN3NytvOW4wYjF1T3ZvdWFzV0U4MzgzVEZuREdLcU82Zkw0MnBWcEpZZXVKNWNrc2M1OTZ5bWpnUzFyZ21FYm5HQ0JPNDIzL0RRUDBlRThxbm5YcVhINkxvSWNZWFBTeTdUOXR5dTlGdUVkSXZMczJLRHlLV1JZL1o3aEo2SmtGUUJkRnp0M01JeGtHT2dxSkd2dWVUalFHWFBYWENYdUtpZVNBSGM2QzQ1VkZjVlZpem5QZWtTTFZVKzgreWU5UlBybVFoSkx1T0NHSm5CTUJNOEVnOXliMFZJZDdnOEZ6d29IQWt1ODJqMkREMFRJVTBzNEFySVpaY0YvMVVBRlI0SEhyTW1SZVpHRnJEM25LTHZLV0tBMTBIL245aEVTMjdqR251SVhvcVFxQkFtdUJWVlhSWVJUOCs4K0tjQVZlci9GRGlDQ0FKejBHZ0pJYlk2cWZNVWdNdXpNQlNjRThRRnNlYXZ5bVBtdndQd3ljLzNaVUxqUFJFaHVjSWtnVENqUmlKa2J6alFyaHVkRDRzOUZTRzUzTGsvOFVGOFVJTDYrTDhHVVBRZklmd2lnS29OQTFJRWQ1dkhGZDRGcTRhVzdWVTgvUTRLNWVtSC9pUzZtU2VlMkhVdjVtNWlUMFZJVzhJazg3U0xKRGdHVVlRMHdHVzMyOWIzR1luMlZJUTBzWUFHSkhCWjhwcUlvS0x2QVQ4QVVPV1VPK3ljdWpwaWZKNlJCY3h3eGtYNGZ3OTR6NlZ5VS9EeUZuQXhMSGxTZ01JSGV5OUM4amhVTlhEY2E2cHE5QnRmZlVORXBsU1ZXcTErd2gzMnBFaTZBSWFXcUo5Y002dlRGMDR4N3JLdUFhOExVQjQzZitpU2IvSEpMM3pvc1J1OVF0OUVTQ3RPbkZtUjBOU29kVEQ5Rmh5RkZ5RUN5ZDdMK1Q2NFdPaS9DR21EQXdqT3ZuQU1PQXBnMEQ4Q0VEaXNLdlBwYys4dkY0eWRoK01TUUlYU3YzS2Jsam4xdVdoSzFDS2o3eUtrSFM1YlRRZ3RBTFFXQ1B0QmhLRGE4SUlNRXZvdlF0cTNnQ3ZodXNJZkE0anlDSERDY3Zvb2dNQ3NJalBwNnhsMEM2aUJPOTJ5SWl2MlB0VUdCQkl1U1RqUmVCUXdnTUxWOVpxaENDSmtSODd4S3lJU0RvVDVFa0QxcGRPUEtmbzRnRWdjbTBZZ1ZRQjNFaEtkY0huV2lTNXpBbFZYNzF4Q2VNZlY5RjUwYVMvNXA1NXJPaGxnMFZGSUVaTGxRa3VZUFE5QTJKczVoREo4SWlTTk1QcFcvQXc3TFFUOXhNQ0lrTGJ4bHk5V2NBUHU2MXYxVHdFWTFZOGk4Z2lBSXIvcVVrNmg2Ym1RKytXQ2NaR21zUHczc0lYcVI0SmVCTUhmUHZDYVMyNzR6ZC9zYTh0RnR6RlFJaVI3bm1aY0F4SStOS3pBaDNRUlJFajJtUkI5Skk0ZGN5OE1SUkV3TUNJRXJBdk9ucXVCKzhzWERYR1VwZ3N1MFJJaTV3RUV3a2pqZHhQV0ZaVlp1MDE5aEhDb25HMkRWaW9ndmsybWsrNEdLeHFHTmRFb0xrU0EyTG9heUliYnQ0cXJ2eUZzdUFJWGdGWmR0U0g4VkxJTTNITHJsN0FGY05sYVJqR0FFZnNTRmFMMW9wc1FlbENINkpFSU1Wa0wxd2xYUGZmaVBPaGhBSyt1eHdBTVpoSW5aa1NZQjFERFFVWEdIVGNIdGlCR25TU0lYb0F0a2JBdm5kekVkclpkRStRREFQWFVGalpsdzNNcXRVVHBBclpRclF6S2Q3dHVZL2dzWUp0YzdkeUxJT0s0bHU3TlNMTENaMWRpM3huR1dNdlpyOVZCRXhob0VkRXAvaitSbDlrT0hoSmRZd0FBQUFCSlJVNUVya0pnZ2c9PSI+PC9pbWFnZT4KPC9zdmc+Cg=="/>
        <prop k="offset" v="0,0"/>
        <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="offset_unit" v="MM"/>
        <prop k="outline_color" v="35,35,35,255"/>
        <prop k="outline_width" v="0"/>
        <prop k="outline_width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="outline_width_unit" v="MM"/>
        <prop k="scale_method" v="diameter"/>
        <prop k="size" v="40"/>
        <prop k="size_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="size_unit" v="Pixel"/>
        <prop k="vertical_anchor_point" v="1"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" value="" name="name"/>
            <Option name="properties"/>
            <Option type="QString" value="collection" name="type"/>
          </Option>
        </data_defined_properties>
      </layer>
      <layer class="SimpleMarker" locked="0" enabled="1" pass="0">
        <prop k="angle" v="0"/>
        <prop k="color" v="33,150,243,255"/>
        <prop k="horizontal_anchor_point" v="1"/>
        <prop k="joinstyle" v="bevel"/>
        <prop k="name" v="circle"/>
        <prop k="offset" v="0,0"/>
        <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="offset_unit" v="MM"/>
        <prop k="outline_color" v="255,255,255,255"/>
        <prop k="outline_style" v="solid"/>
        <prop k="outline_width" v="0"/>
        <prop k="outline_width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="outline_width_unit" v="MM"/>
        <prop k="scale_method" v="diameter"/>
        <prop k="size" v="25"/>
        <prop k="size_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="size_unit" v="Pixel"/>
        <prop k="vertical_anchor_point" v="1"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" value="" name="name"/>
            <Option name="properties"/>
            <Option type="QString" value="collection" name="type"/>
          </Option>
        </data_defined_properties>
      </layer>
      <layer class="FontMarker" locked="0" enabled="1" pass="0">
        <prop k="angle" v="0"/>
        <prop k="chr" v="A"/>
        <prop k="color" v="255,255,254,255"/>
        <prop k="font" v="Arial"/>
        <prop k="font_style" v=""/>
        <prop k="horizontal_anchor_point" v="1"/>
        <prop k="joinstyle" v="miter"/>
        <prop k="offset" v="0,-0.40000000000000002"/>
        <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="offset_unit" v="MM"/>
        <prop k="outline_color" v="255,255,255,255"/>
        <prop k="outline_width" v="0"/>
        <prop k="outline_width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="outline_width_unit" v="MM"/>
        <prop k="size" v="11.8"/>
        <prop k="size_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="size_unit" v="Pixel"/>
        <prop k="vertical_anchor_point" v="1"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" value="" name="name"/>
            <Option type="Map" name="properties">
              <Option type="Map" name="char">
                <Option type="bool" value="true" name="active"/>
                <Option type="QString" value="@cluster_size" name="expression"/>
                <Option type="int" value="3" name="type"/>
              </Option>
            </Option>
            <Option type="QString" value="collection" name="type"/>
          </Option>
        </data_defined_properties>
      </layer>
    </symbol>
  </renderer-v2>
  <customproperties>
    <property value="fid" key="dualview/previewExpressions"/>
    <property value="0" key="embeddedWidgets/count"/>
    <property key="variableNames"/>
    <property key="variableValues"/>
  </customproperties>
  <blendMode>0</blendMode>
  <featureBlendMode>0</featureBlendMode>
  <layerOpacity>1</layerOpacity>
  <SingleCategoryDiagramRenderer diagramType="Histogram" attributeLegend="1">
    <DiagramCategory penColor="#000000" lineSizeScale="3x:0,0,0,0,0,0" penWidth="0" sizeType="MM" barWidth="5" opacity="1" minimumSize="0" enabled="0" spacing="0" showAxis="0" lineSizeType="MM" direction="1" height="15" spacingUnitScale="3x:0,0,0,0,0,0" penAlpha="255" rotationOffset="270" spacingUnit="MM" backgroundAlpha="255" diagramOrientation="Up" scaleDependency="Area" maxScaleDenominator="1e+08" sizeScale="3x:0,0,0,0,0,0" labelPlacementMethod="XHeight" width="15" scaleBasedVisibility="0" backgroundColor="#ffffff" minScaleDenominator="0">
      <fontProperties description="MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0" style=""/>
      <attribute field="" color="#000000" label=""/>
      <axisSymbol>
        <symbol alpha="1" clip_to_extent="1" force_rhr="0" type="line" name="">
          <layer class="SimpleLine" locked="0" enabled="1" pass="0">
            <prop k="capstyle" v="square"/>
            <prop k="customdash" v="5;2"/>
            <prop k="customdash_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="customdash_unit" v="MM"/>
            <prop k="draw_inside_polygon" v="0"/>
            <prop k="joinstyle" v="bevel"/>
            <prop k="line_color" v="35,35,35,255"/>
            <prop k="line_style" v="solid"/>
            <prop k="line_width" v="0.26"/>
            <prop k="line_width_unit" v="MM"/>
            <prop k="offset" v="0"/>
            <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="offset_unit" v="MM"/>
            <prop k="ring_filter" v="0"/>
            <prop k="use_custom_dash" v="0"/>
            <prop k="width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <data_defined_properties>
              <Option type="Map">
                <Option type="QString" value="" name="name"/>
                <Option name="properties"/>
                <Option type="QString" value="collection" name="type"/>
              </Option>
            </data_defined_properties>
          </layer>
        </symbol>
      </axisSymbol>
    </DiagramCategory>
  </SingleCategoryDiagramRenderer>
  <DiagramLayerSettings priority="0" showAll="1" obstacle="0" placement="0" dist="0" linePlacementFlags="18" zIndex="0">
    <properties>
      <Option type="Map">
        <Option type="QString" value="" name="name"/>
        <Option name="properties"/>
        <Option type="QString" value="collection" name="type"/>
      </Option>
    </properties>
  </DiagramLayerSettings>
  <geometryOptions removeDuplicateNodes="0" geometryPrecision="0">
    <activeChecks/>
    <checkConfiguration/>
  </geometryOptions>
  <referencedLayers/>
  <referencingLayers/>
  <fieldConfiguration>
    <field name="fid">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="osm_id">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="name">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="amenity">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="hstore_to_json">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
  </fieldConfiguration>
  <aliases>
    <alias field="fid" index="0" name=""/>
    <alias field="osm_id" index="1" name=""/>
    <alias field="name" index="2" name=""/>
    <alias field="amenity" index="3" name=""/>
    <alias field="hstore_to_json" index="4" name=""/>
  </aliases>
  <excludeAttributesWMS/>
  <excludeAttributesWFS/>
  <defaults>
    <default field="fid" expression="" applyOnUpdate="0"/>
    <default field="osm_id" expression="" applyOnUpdate="0"/>
    <default field="name" expression="" applyOnUpdate="0"/>
    <default field="amenity" expression="" applyOnUpdate="0"/>
    <default field="hstore_to_json" expression="" applyOnUpdate="0"/>
  </defaults>
  <constraints>
    <constraint field="fid" notnull_strength="1" exp_strength="0" unique_strength="1" constraints="3"/>
    <constraint field="osm_id" notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0"/>
    <constraint field="name" notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0"/>
    <constraint field="amenity" notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0"/>
    <constraint field="hstore_to_json" notnull_strength="0" exp_strength="0" unique_strength="0" constraints="0"/>
  </constraints>
  <constraintExpressions>
    <constraint field="fid" exp="" desc=""/>
    <constraint field="osm_id" exp="" desc=""/>
    <constraint field="name" exp="" desc=""/>
    <constraint field="amenity" exp="" desc=""/>
    <constraint field="hstore_to_json" exp="" desc=""/>
  </constraintExpressions>
  <expressionfields/>
  <attributeactions>
    <defaultAction value="{00000000-0000-0000-0000-000000000000}" key="Canvas"/>
  </attributeactions>
  <attributetableconfig actionWidgetStyle="dropDown" sortExpression="" sortOrder="0">
    <columns>
      <column width="-1" type="field" hidden="0" name="fid"/>
      <column width="-1" type="field" hidden="0" name="osm_id"/>
      <column width="-1" type="field" hidden="0" name="name"/>
      <column width="-1" type="field" hidden="0" name="amenity"/>
      <column width="-1" type="field" hidden="0" name="hstore_to_json"/>
      <column width="-1" type="actions" hidden="1"/>
    </columns>
  </attributetableconfig>
  <conditionalstyles>
    <rowstyles/>
    <fieldstyles/>
  </conditionalstyles>
  <storedexpressions/>
  <editform tolerant="1"></editform>
  <editforminit/>
  <editforminitcodesource>0</editforminitcodesource>
  <editforminitfilepath></editforminitfilepath>
  <editforminitcode><![CDATA[# -*- coding: utf-8 -*-
"""
QGIS forms can have a Python function that is called when the form is
opened.

Use this function to add extra logic to your forms.

Enter the name of the function in the "Python Init function"
field.
An example follows:
"""
from qgis.PyQt.QtWidgets import QWidget

def my_form_open(dialog, layer, feature):
	geom = feature.geometry()
	control = dialog.findChild(QWidget, "MyLineEdit")
]]></editforminitcode>
  <featformsuppress>0</featformsuppress>
  <editorlayout>generatedlayout</editorlayout>
  <editable>
    <field editable="1" name="amenity"/>
    <field editable="1" name="fid"/>
    <field editable="1" name="hstore_to_json"/>
    <field editable="1" name="name"/>
    <field editable="1" name="osm_id"/>
  </editable>
  <labelOnTop>
    <field labelOnTop="0" name="amenity"/>
    <field labelOnTop="0" name="fid"/>
    <field labelOnTop="0" name="hstore_to_json"/>
    <field labelOnTop="0" name="name"/>
    <field labelOnTop="0" name="osm_id"/>
  </labelOnTop>
  <dataDefinedFieldProperties/>
  <widgets/>
  <previewExpression>fid</previewExpression>
  <mapTip></mapTip>
  <layerGeometryType>0</layerGeometryType>
</qgis>
