<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis hasScaleBasedVisibilityFlag="0" simplifyDrawingTol="1" version="3.14.1-Pi" simplifyLocal="1" simplifyDrawingHints="0" labelsEnabled="0" simplifyMaxScale="1" maxScale="0" styleCategories="AllStyleCategories" readOnly="0" minScale="100000000" simplifyAlgorithm="0">
  <flags>
    <Identifiable>1</Identifiable>
    <Removable>1</Removable>
    <Searchable>1</Searchable>
  </flags>
  <temporal startExpression="" fixedDuration="0" startField="" durationField="" accumulate="0" enabled="0" mode="0" endField="" endExpression="" durationUnit="min">
    <fixedRange>
      <start></start>
      <end></end>
    </fixedRange>
  </temporal>
  <renderer-v2 forceraster="0" enableorderby="0" tolerance="20" toleranceUnitScale="3x:0,0,0,0,0,0" type="pointCluster" toleranceUnit="MM">
    <renderer-v2 forceraster="0" enableorderby="0" symbollevels="0" type="singleSymbol">
      <symbols>
        <symbol clip_to_extent="1" force_rhr="0" alpha="1" type="marker" name="0">
          <layer pass="0" enabled="1" locked="0" class="SvgMarker">
            <prop v="0" k="angle"/>
            <prop v="231,113,72,255" k="color"/>
            <prop v="0" k="fixedAspectRatio"/>
            <prop v="1" k="horizontal_anchor_point"/>
            <prop v="base64:PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIGlkPSJteVN2ZyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+Cgk8aW1hZ2UgaGVpZ2h0PSIxNjAiIHdpZHRoPSIxNjAiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBS0FBQUFDZ0NBWUFBQUNMejJjdEFBQUFDWEJJV1hNQUFBN0VBQUFPeEFHVkt3NGJBQUFmRTBsRVFWUjRuTzJkZjR3YzUzbmZQOC9zN1BMSVcxTGtpU0lwbXBCb2lwSmNXcUpVSTdXQk5FMVVGRzJkb2dtU3dGWk1PYzQvS2REMkQ2UC9GSEJ0UzVVb3lnMENCQ2ppb0VpdHREVmlXWlJjbzAzYm9MRVQyTEdpRnJHVHlvSnN5VFJGVTdURU1DSjVKby9IdTczai9kaWRwMys4N3p2enp1enMzdDdkN3UzczNYeUo1VHYzblhmbWZXZm1uZWQ1disrdkVWVmxLMkgreFpNSEFhSklqb0Vjcy9ROUFLanVBTmtCUU1BK3UyK0gvWUd5MTFEcWN4RWlxREtQeUR3S29OZEVRR0VlcElFWURoUlU1a0VXZ0FqUjF4RVFPRk92MU02Z3dLT2ZtaEdSUUZVakZ3SnNWaTdvMTRNdFVXSXRrRzRXMEMrNW80TDVGMCtPQVRVQTFlQUJnQWoyZ3JGb0F1OEhuRFZ6Vm02M0RXdEFpSWxZdDF6b3pvY2FxNmNRaXVNZ3NuZXdDYkprRHRWNXl5MGgwalNiT20vUHNRU1dFNTIwZWJvQ1ROcHovd0FJVUNZRENTWUJ4c1B3TEFvSVRYbjAzMFJGczJMcjRjSnVEM1BVQ3A5RkRWemgwUSthUU42UHhPNzJwd0VVUlVSU0I2cXV3RWxNZ3VWVU5SQVJWRFVVWVV4VlVkaGxPY1NlQTBCRWJMcVdVOE9oR2lIYXRBbDh3NloxQm5qZEpNSUZjeUlBbHRaN2c0cUUwZ1dYR0NxNnV1Q2lZL2JGWno0QWZBQUExZDh3SVlkRTVKQWZiMFhMdGc3T2Jmc2hNQmdPenFPY1E2RFM0dmVzVlR3My9va256aGZOdGZiS2RYWEJJNGF0WWMybFF6aWlHQmtMMkhqaDFENnNhSWpnRVFDQmUwR09BS0Q2c0kyNlMwUjIrY2R1SWdzNGhma2h5aXNBaWw0QTNnSUlnK0FiOXJpWkhTY2VueW1hdGN2alJzY0NLdnNRanRudFR3SWc3QldZTU50SmdkaTBVSjBRa1FrcmRJNGFBY01sNEtMWnoxa3hidmtTTURQTXJQYUswWEZia3RrZWNkY3pFSWdSNktOMGJ3cnBnaHN2bkRvTTNHWC8vQjBiSGdBNTRNY2JwR3Z0bGR0UUY5dzdkdzdrSElCVWdrL2JiRS91L05obnJ4WE5CWStPQlN5eEtURjhDL2kxendlS0JJSXlPMzN6RjIxajYzMGkzSTlwcS8wd2dBaDFSZXIrb2JaWmwyRnlndk41ZnNoUU9WV2RBcm1HYVd6L2h0M3hBK0FOVU9yaCsvNXZmQzJQUHNvd0xlRFFSWWhDSUJEWTIvZkw5cmtlQnpsdU8rcE5QRlV5bnREdmtCZ2E1N2I5RUliTEFSTWlURmp1cU0zMlM0cnVGbk5INHdJNGJKUXV1TVJRTVRRWHZIajY1QkdBWmVReEZUbGhIZHF4VHZHTElEanl1SUtLa0s2Y0NDOWJ5L2xWb2ZKZkFjWlBmR2F5RkNFbHRodzIxQUxPbmY3Y0FlTGVqTlluYkJZZUZ1RmhBRVgyNWxXcm9SaUNJNDhyb2dqcGdidW9DZ0t2QWQ4MWRQQWxHM2w2NThjM3JoZGxZMFdJNmMxNEFBVUMrUmVXcllIVUlCRWNlZDJjUlJBY2VWd1JSVWdQM0YzV0hVK0k4RUZWUmVDbHVJeHVZQzlLNllKTERCV0RjOEZmKzN6b3RlLzlaL3QySFJmaytHb2RpT0dINzI3enVCRjF3VG1jdU1ISEx3SGZCS1YrNG9sL043SXVXQkY3YVpKY1oycFBObFkzRHNqOFZSeXVXOFZodERqcmltMzlRdG9LaTRnRU5sN2Z1TDVid01hWGYzTWZBZ1N0QjBBZkFGRDREYnY3Z0NEN1NndFlQRTVWWEwzMmJWUXZJSUpHK2tWRUFUa2JVRG1MS09NblB0c290Z1VVOWdFUnFqK0g4QkZEeVRIL1lrc0xXRHpPRTFxSEVUbHN0NWRzbkQ4RXZZUktKQ0x6L2JTQS9TK0FTb1NreFkwcGVwSUtXUVZuK09GYnV6eHVzMWpBenB3Q0VvQkVpTFlWb09KWndLQjEwbDdNTWVEWWdDUk9pUTJBQkh3WUFsQjJRZlJlV3lZLzFjODBCaU5DWXRHeEZuZGJ1dURpY1ltSzdMY3c2WXNJbVh2KzFGRlhiMUE3Z0ZSaG53aDcrK0VFREQ5OGQ1dkhiWDRYTE9BUCt4Zjk1M2JINU03SC91MjZCN2oyeHdLYXd2Y1BiWDZQcmMvYWxSYXdjSnh3Q0hCVFhlTUJJNm82V1F3UjR2Vk5yVmR3bENKa0ZEaTdwdzhpWkYwdXVQSGlNeDhCUVBsVk1FMHVnM2djaGg5K1ljdmp0bDRCbEFVQWxQK0N5dStMQ09PUGZlYTF3cWhnWndkTEY3elpPY3o0UW5LczJpQkZ5TnhYVHRWUnMvaVBxdng3U3o5Z2Y2VUZMSnpGNmkrblNGTUFsTzhBM3dGUWFUMXBJemQzUGZaVWM5QVdzSTdZWmMyVVg3SmNmSjdTQWhiQk9nMk9rMlQ1dXVNS1J3U05nTit5WlhSZVZaZFdZd0hYTmh4TENkRDhvVnhxYytlSDYrWFVudG4vdXloY1lpbjhjQ3R3QUVTMmNBYXVqTHJDbGRkamtzZXQyZ0pxaTE4Qi9xVkpqVEdYclhZclVXSnpRM2NKc2dzVTBjcnYya0x3VmVDL3IrWXNxeStBdEJlMmRtTmR1dUF0eDVsZ2NDS2tjZnJVY2J2NUNlRFhUYUt5RDlLRnNoUWh4UklORzhLcG5MRTcvZ0NDTDRuQStJblBYT20zQ0hFdDRFZGN3WE1vTFdCZXVJVTRpY3ZHUFFMN1FBTVJtUnljQ01sQTI3WkxFYkkxT1NKVkFwQStpWkNUSitNQ3F2ZFdmdE51N202M0NDVktBS3IvQ0ZwSGJLM3VIL2R5U0RrcnJzUlEwVldFekQzLzlFSGdBRUFrd1RjTnEyTmdtbC9pa3dpWnhYSDZMMFBNbklWMFhvdkFxVXBodE1Dd09WR2RCcVlVSUpCL0lHYlJxZW1kSDN0OGlnNVlRWVRJQVlUaktJaVlqN2xrcFFFdUwrSnRlL0VTdGJoMkRrQWtSNDBXZ0RNRlVTQVZza1U1ZG9Qc3RyWDR3NWFOUkdTNmt3b3VYWENKb1NMWEF1clhQbDhUaEVqa0VaUlBJbWtCWHFMRWlsQTlhWWVKZmhINFVxZG9wUVVzTVZUa2lwQzVGMDc5REVDa2ZCemtZNGJWM1pBV0hQRkpTaEZTS0RGUUNFNzBvdldhWHhMa0Q0QmcvTVRqNThnZzN3VXJQeVhtdmg1QjNKY2t6ZWw4d1JISDk3aFNoQlJCREJTQ3U4dVdtU01reXdTZkswVklpVUloM3dJS0oyeTVQclNSNG1QOHcvOE1FR1JzSE5sZVh6RitpZDRSM1dyQXdoeW9Ndjhudjc5eENTc1BxeEphaC9IMTdPN1NBcFlZS21JTE9QZlZrelZWOXhYdzRKQ3R6TzNLaXBSZVJjaWFKbUdPV2FzWDFzaENDN0FnZVI3bnR2M1EzSWRpY1JMVzR2NnJSRGg1SVF5R1F5Y1FNWFhBWjU4TjlRdGZpSGoyMlhoNGx1K0NheEovcGw0T3h2WHVMb0lqajF1UENBbTZ1TjFzSVNnSzU3YXpZZUc0YWcycU5jdHZuSEJTa1FsZ0J3bENUTzhJcFFncE1YVEVGbEJid1RIYzE4Y0xqbWhwRVFCZGFNQkNJN1hQV2VDTjRsSk5YMng4MHh0amRZTHRkVlNWb0pZYUkxSUlDR29Yb1ZjYXV5Wi94dEp2WTllYUtTMWdpYUVpcVFOR1RJRCtMZkQ3SDlveFVCSFNCWDdGdi9uajF3eDNhODVZd1MwTTJWNUhySGlyM3ZkM2VoSW1HeXBDUEU0MGJwQ2VVZFczSVMxQzlvRzh6Mlc0RXdiZEU5SUpmcDZhUC82K1NldFdnMmhoTGgyUHJUVXBLVzR6VmFWMi93Y051NEl3R1ZidmphamNhM2U4WGZhRWxDZ0VRdjdYYnhuN0xkeXY4SWpaTERaYU42NEN2dlhKaDdNSUJDRlN5WGI2OUNZNXROV0VxQW5BMHB0LzFWc0dkOXlHaUJEczNrOWx6d0hXWXRsY3VxclFQUGVYSFpQU2hRYTZNT2NkVzF5MFZIL0pYdVZmQTM4R3BRZ3BNV1NFYzNOTDc3UGJlMFZOblZDN3ZFMUZFQ0dWM2ZzTmw5Y000dzJWcWh5NHg1QkJnSjJXbXNTTGE1OHJjQnBCWkQ0aVZMMWwwb3JtWjlENUdmK0NRVXdhaWhJZU1yYzBxTzhoMkRrUjMwK0phNCt5TXFjUlp0MGZaZm5OditwWXlRL0dFaEhTYTYvTTBFU0lzTmZRZXNmTTZhY21abDg0U2FpSk10bnJubEkzRjF3RUVWS1pPQUJBYStwS3V3anhoa3FGQisvcGVzNVZ3N3JpMXJWTFJOZi9CdkNjZGxCQktsVlFwWHJYTVhORHhzYTc5dTcwaW02aVFjYnFWQ1lPcEY3UW9vb1FZTUpXblBaaWZxVUxMakZjaElMOGJRQzEweTlIQWRzKzlBc0FSRXNMc0d4V2pHMWVNb050bTVmZm9uWDVyWUdrR3g2NlB4VnVOSUk3anhMZWVRK2doSGZjM1ZjcnU1RVE1UUFFRDZNZDF2Z3JVV0tqRUdveVNDZnNaYUdzSW9pUU9OMUtCYlhabDdGeEFJTHRPOUVkdDYxNGJNL2MwZ0pxcmF6UHNieVlISU5BRUlBRWdCcFJJQ0JCQ0s3NXA3cHQ3VU9xcXZZYWc0cEpFMGtHN05xaGE2czUzN0JFaU9NRWFwaVZkb01RY1FWUXdsN2EvNG9nUW1LdVVqVVZmMER0QTRsMjdDS283MTc1MkI0NVhWNUE1MjZtdUtneDdYRnFMdDZLRUVVSjlod3cxMVFkSTZpTnBRWUtyR2xJbFMyOHJqQUwyalppZkRYbkcvNDhGbW9DZFpEU0JaY1lMa0pVbmZpb3Q1bTJEVWJ6MHBzQUJMdHVKOWkxZDFYSHRockdJbVhkWmVjRG10QnFBYkQwNCs4QkVOMjRRbVI3V1ZwejA0QjVjWjMzY0c1M1RYM0JmdS9JeEFGUUpYenZRNG1GNnpLVUtxanZRUUJwdGREcHE2Z3F6Y2wzZWttMUl6ZFVxTlNCTzZGc2hpa3haSVNLRzRaUHJVMWQ1R0NRSXFUNXpnOE11MjBIYk51UnFoV3UxSFBibXI1aVR4bkVnaVNPNTRtTDFqWFRnQncxcHREWkcyYmJXYnZxR09HaCt3QUliWDFMRitiUnhYa0FtbS9iVVRpUzlLeFU5dDl0amgyckU0elZ6WlZWS21SN09Gdyt0ZFZFRnhkQVlQbWM2VnNPYnJ1RDRMWjlnQkxjL3A0MjBTQ1ZDaUJFUy9OZzg5cTg4RDNXaW1HTEVOQ2FJbldBRUVrS1lONWl0RzJaWjNBaVpQbmltWTd1b3RlaFVwWGJEeExzUFpTTzUyVzRaWHN3V2xmZnBqbjVqamxtM0lpVzhOQjljUnRmc01mVVRLS1phMFF6MXdGWWZ2dDFlNzRBdFFXMGN1Y1JCQ0hZWXdjZUtKRGpUcVBHTkNMUXZQb09yY2wzUU5VV2FLRnk1ejJFeldVVXBXTHpuaElOUVFnaWFHT2FhUFk2b0VUVFY3eTd0RG9uN0l6RXNFU0lpaGdWVE9tQ1N3d1pJU3FlQ0JscVh2cURTaFdwcGkyUWI4VVdYLzFURTIzbjdZVDdEd093L1VQLzFNUmJYb3g3Vm01OTh6bkROYWFKNXRQTk1PSGQ3NmQ2NUNGem5uM0dCVWR6MDdSdVhFV0JwZGRmYnJORHRTUEhBYUd5NTBCODdFSnRPeUttVDN2eDlUOEh4VGJYR0xFUzdER0RMb0k5KzBIRTlQek1YdS9QZlJvaVJMV083WGtyTFdDSm9TTEVFeUc5ZkROazhEMGgrYjBqdmE1Y0pSSkFwWktPdDd4a2xxWUFwTHJOa052SENjWnRqNGx0ekdidVptd3BvOGEwUFhZaHprZXcwelFOQmZVOWlEMVdXMDBFaUc1Y3BYbjVMVkJGNTZiam5NZmgwcUs1cXRheXpic1MxTTA1Wkc0bWJtVE9pNmNpY1JWS1llTkZROTlGQ0NHMkI4NFhJZUd3UlVnbkRxRFhsYXNJZ3FSQU9iU1d6Ym9vRUxlM0JXTjF4SXFQK09Fdkx5WUYwTHJkVkp2ZmJiWUE3cHdnY01jdUxSajNlT09xVWZFS05CZmlLM0doTHQweU55bHEyYndMd1k3ZElCQnR1NFpVUWxQWWN1S0o5MEZ3ODM1dmRNOUZ2MFdJSzREbFlJUVNRMFlJdUM5Z2p5bmF2aWhMQm9WM3dXUGpjZVhkSWRpOUg3RURGSmJPbXZrVnk1ZmVSQzcrd0owSmdNcnQ3NkgyNE0vR3h3QzJ4OFFNUkEzdmVjaW1tNlM1OE9xZm9oZ1hyTXVMb0ZBOThoQUtoSGNlb1hyblBhZ0loS1kvTjdweGhlYUY3NE1vdDc3OVI4YWtCWlhZQ3B2UjFKb2E1UnpzUGdBQ3djMXJ0S0FZYm5SOWd4R3NCUlJDVkkwVkZLRVhGMnlqOXNCSkpsd25KOWs0SGJoY1JwUDhTWHRNNlppZURiUEplaGVyWGhSM254Tk96SDMxWEtoN0F1N0JwQjIxZjBZdnJXejFadmhsYUgyY3ZScEJDQlZtQUVSMWwwTGZMT0JhR2tnN2MrNUtNZ25uY2VtakRDb2g3aWxXMzJ1c21OODAwN1FEV0lPRmVkU0tGVGY4SGduaTRWQXQyM0N0U3d0bVNCYkc4Z2tRTFRTc1FDQVdJYTJwZDIxK0ZLeTQwTVlOb3RrYlpnQ05GVEtWblVuZnQ0emxETE1LS3FZZ1N4Q240UzRmVGNKUjRVUlpBSmtHQ0FYc0haZXhYc2NpakpvRmxFbzFGaWF1RGE1NStYeGMwWGNqcVBWV0E3MWxKaHU1TmtLcVlTeGNYQUgwaDJORjAxZlRyNHdRNzJzQnVuakxGRHc3eUNGYU1BdEZLaERhTnNUSy9yc0o3endLNUEremtyQnFubDhRRk1lS3JZUERWUHRNQVV3dVZYdnBDaDVKQzVnYWFPcGxQcnVscWYwNThmS085ZDd3NUUxUDNHamUxVVh1dURoV0VqTnZabHRxUFVJdjhhSlp0cDR0WUh3N2xWRFFTWHRyeGhRbUdISElXSjF3OS82Tyt3TTdvNjY2WnorMVkzOFhTTnI4b3RsclJEUFhBRml5bmYzR0t0cVpkMDJyMTFMaXA5MEN1OVc3Z3FBU0Y3anFrUWRSSkI1cUpoQVAwY3FPWUc3TGMyMDdvS1pQZUJOQW9TRWlWMFFnUkNSeU96YURDSkdjekt5OHlLUi92S1JTMWxRU3ZoOUp0cnU0bW5qYm4zSHNERUxRNHpSS2RiYXlRRzUwWFM3WUUyUWg2dXFBTEhXYmtKN2NtR0s3WUEwQ1UybjN1WlhtZjFpUkVkUW5VTHNkMmxDYlM5QmNNdkhzQUZaL0FudDZ5SlV0TEJXN0puZFlNMHZqb29uSTJMYkRERUR0NEc3TlBjenM4NFRKWm5EQktFdGl0VWNJRWhmQXpTQkNURmRjbU9GV3NJQnV2a1p0REhhYVdrZ2xNNlJya0ZoeFRvZ1ZKaExXQ21QRjFpbENsckFGME9zSjBiakMyKzJYRjgvbkVxdmxoK3ZsYkkzZC83c0RsMmZGOCtwVy9lTGN0aDhPakhOWGw3bjhVZVA4cHhzQ1ppaXh5T0dlWkhCUkVkb2hXRzJyWUpVb0drUzBnWEJaSVA2QWlLbDE5ZWlEQyttQ3BlMElMMi9kWGZCNnVBMWRKZC9XUEl2Z1J0ZnBndU02YzZpcTgzYlAwaWkzQThielFBYjRqUkUzWXk2NjFZaVhCbmF6OE1RS0RnWEMvWGRiLzFKRHFyWFZUVUx2d2xHcFdBR0RHYlpsYjFHQnhFVnZIQ3loMG5BdTJBMzNYUnBsQ3hoczMybW9uQUxZTDJzWFRkc3BtMU5YNHUxNFFwTmJyUjZvM0hZN09KMWNyZlhOQWxKSmVtVjBlYkZ3bHExbkRvbEZTT3lDVFFWeFpSTllWQXZZTGVmOXNvQnhLdUtuNS9McWI5bThTM0lPNklNRjlOUDBMRXRoTEZ2dkZqQkdHS2k4Wm5jODJNdUk2SzJHNlByZnhEUHBsdXg4a3R6dkJUZHV4dVZ1K2EvZkJERkxCRmZ2L3hDQ1FtYTltclZBcW1NRTQ3dk5zMnpNclB0OHc0S2dseVNNdmdPK0JTVGZCZVdlb0lBdXVGdk8xK09Dd1IrbTV2a1JiN3VUcTNHaElqMzNlblRqa2h4MVQ3Zm9IQUJLZ0JDRllMN1hvSEFONDV0Qk93OU1MYW9MemhNaGJoSzZoTlg0TzJsdUtIMnZMdGlNbTNJOUs1NGZrV1M3emRWVUtpWm1FSnBGaTRTVVMyMXp0MUdFYUdUYXlPYmNYSlFsY0hPRjk5MU52RGlSbTlNeWdpNVlSQ2Z0azcyTzBBQ2ljRHlNTGdETU5vT2ZnQzdabTlKMVhHQWhMYURyTGFnbVdYZkw2S2ErUDJ3TFlNOVdNYWlZQXV6blp5VUxhTHZpcEZKQnd0QzhuZDBzb0VZUXRSQ0ZscHVUY3FzQmkzT2d5ZEF3c1NKRU82Vkw0YmtyMXJoTWpYLzB5Um1BVUZQelFzekFoRzUxd2FKYXdDUlB2anpvZkIwOVc4QzJ0dnRNWHZJc29IK1VuZFZHTndzSXlTSkk5dExkUGRXVTlVenV6Q2hhUVBQU3BPOXZLSTgrdVFBZ3A1ODVpLzJpdGNLampCaUNtbkZOdWpBWEw3bVJKeHBjajBsd3gzc0liMzhQQUxVSGY2N2plV1gzZmtLN1RNZVl0WjdSdFV0RVA3bGt0cHVtT1lUcU5xaHRSNEJ0RC82c3VkL1ZNYk5NaC8vR1JpMHpxRUZnOGJ0L2dtTGFGNlBwcXgzZndjb2RkNWtYbzdsQVpYeDNtNUljRllqSzE2MDNPTys0UUVRQ01TdnR4SmJRTEdLWS80UHVYTHY3N0Fjbm50dnJ3SWt6Ry82Wjh1TDVsS1RxRGl2MmVuZzVjOGY2ZTEyNWlhMFVpWldMWGEvOVR6eHJKclJuTVJWYUt4bGJFYzJQVjNqT1ZVVzhGekpVKytYcXh1bFQxMURPSjdjdEgwVjF3YkZRQ0lLVUUyNkxaMmU0UmJNM1VEdThpbTNmQmFEaUZoaUNaSzZ3NTViZFpQUUtrb2laMXJMSmE4V3VrS3JZcFVFMGRRNmlGZ0swcGk3VHVuNFprZno1SkM2N0tSZnJYSEJZZzIzajVoNlBvZ3RHZm1qRGErNEpoZGI2TWZ2ODA5TWkvTWpjNlhaTDRLT1FJc1RPK1JBSlVsYXA3Vmc3RHlScTNFQWFabm0ycHAxZ3hIc2ZvbkxiSFdiYkxZZnJYVmc4R1gwOHZRVHdTaENSMk8yMnJsK202UmJFekpsUGdyY2RoNjZlV0swaFFSQkh5c2JMTzdaSW5FUnkxaHFydUFBR3FocXBhaVFRamZKd3JPU2ZmNmJlampXMWV6dDEwMjQ3OUcwNGxpMXBPUjBhN2RuSjdsTzdOb05MdDBPOG9uUE9VL3IzSUI2N0ZGU0RDMkJLWm5NNVl0VGcxdk5ieTVDeTZLYnQ0NTE4QjdGaUpyVFROL3VGNW9Ydm9VRHI4bmxhdnVCWUJhUTJaais2Mk4xREZRdmFRS1VoQ3RzLy90bnZaUGY2SWdUTS9KbG9GRVZJeklwNForcnRXUGN6WmRmUFI5b0Y1M0Y1dzdIeU9PZG1YVjVYVTNtUFJVaWNOKzM1MkdGejJTRmtXY1FpNU5aWFB4ZVBVRkQwWFh2SGRxR2tKcW9XVllURWV6d2JIOWg1dDcwaUdMK3Q3ZUpXYWkvc2VWNkhGVWxCZlEvc3UzdFZkOENkUjhLcW1WTmlMN2c0NHFJTGgwNkRYT3gwejBQUCtpM1pIek9ubjc1a1g5ZERJdEwySGFoQ2lwQ2NqSVNyTElCeE41ZWZ4Qm9zWU40K3Q4NnoxUGRRY1lXb1I2UkVpT3ZSc1JhbUNPS2lPeWRUUU56dWwwVXNRdnlmSDJGMFJFaGlMWkl6SmZ1eXgrWnhrczJHUFY4V2F4RWh6alM0NHJtcU82QmUzdUx6SlpmZkQ0RXdNRzRGNUU2Z0VKV3YyODFIRkQzWXczbUdqb1Z2LzAvQWZNcTFrcDJZbnZIbW5iaW91WWpZRWM1THIvODVBR1p4eUl4YjlqaTNlS1NyRGNSdmZ6Zk9wWS9OZys5emM3aldUeTRpYWdhLzZ0ek5uaDVzVVNDcTU0R3ZkZXJlalVXSS8vT2pqb3dJOFNyL2NRK0g2NjNRd1hGNVg3MGFGQmMvRTlLWDc5K2F3bkV1engzYWxzT3N5d1Zvbkg3bS93QW9IRVE1YmxqZDdaNXRJVVdJVzYzcTVuWFVMbzJ4VWVqMzFYYmsvQThuSmw2OU9JTEQ1MFNkOERnSHZLRnVHY0FNZkJFU1EvLzM1MTlHWVBiR3plTUswd0tJU056OFgwUVI0ajZqRlMwdklwbVY1RE1HcEs5YzFvTU90QUQ2bkxVd3hSSWNxZkJ0VUJCNXMzN2lpVGZvZ0h3Ukl1a0xCd292UW9iR2VYOW02QzNQNFJla0RzaWZ4ZjN6bjF3U0lEaDk2cytBS1lBSXZ0ajlWQ1ZLSktnSW4xSVVFYm5VTFY2dUNQSEVTQUNtRUJkZGhBeU44LzdNMEZ1YVN5M1cxQVc1SXNSaDd2bW5yN2cwRk93Nmd0UVZVaTJwUlJBaFErTzB3NGpvTGNpSjZoUndUUUFSdVdRTFlkZnBlN2tpeEVHZmV1b0tkdTJZeHIzaUNpQWkwdGFVUDNRUk1pek92dlZGcVBnUG04TU1aamtMc1AzRUUxMWRyME91Q01uckVmRnFscVVJeWRTKysxMTVIMW5PUGJWVmpFanF2cFRVazAvR2hWQmZlT1lKdTNrQzFaR2JNMUppY0JEUlNJMHIrQWJ3SHpvMU91ZWhxd2p4Zi9FUlNpbENmTTc3TTBOdkdjNWZmcGhWZmdDenF3dk91T096d0ZtRTg2aGVSUFZpNllKTEYydzRmUTE0RmZnUlJxekdRKzVYUWxjUmtzRTVnTm5UcDk1Q3pQZ3VnYnZjemxLRUpLSGJ1MVU0UVY2eGU4N1hUendlaTlWZTBMTUY3RFpVaTlJQ0ZzUVNEWWxyZTI2OVk5WHIyVlpicmY4QnZBeXdYQW0rYmVrZFpOb0dTMnh5Q0ZQQUZBSzZISDdhc2d1clBVM1BJaVFXSTE0aFQ1cGlLRVZJTzcyNXVUNmhhMDlJSGhhL2ZISUIyejhzeUl1Vy9pQ3FQNFVoQTFzN0lBbGhmUndVb3Rjamo5dGlQU0VpZGtsbjVWWGdMK3dkY1phdnlTcXhHaEhpc09BU25QdnlNODhEUk9nWXdnZnMvbVRtZENwY0p5ZlpPQVhockVVb2doallJRzdlOFBwcU5kTG5nR0RicjM5Nm5qVmkxU0xFL3dtSy8xRnBnMnlGVlB2QVpXckJSZUtHVmZFZkZwZCszcXMxWG0yUTFYU2JkTUxjNlZNUEF3OERxUERGUWJqZ1hyK1l2dEZjdkVSdlB5KzNZSndZMTlvRXFFVHk5KzNNMTB2YlAvN1pudnA3dTJIVklpUjMySlltOXFIZGZVb2ZPRW5YZ292RWVYOW02TTNEZWNoWjRHcGRXTFVJeWNQYzZWTlhnTmNBSXRXWFRhYmxNTUpkL2JLQWhSQWNlZHpXRUNGbkJmMCtDQ0pjc29Xd0w2dWtyMFdFNUdIUy9waDkvdFJMbG5zRXVDdjlEa2ttWEFVbjJUZ0Y0YXlWS0loQUdBZ0huQUg1YndEOWNMcysxaVZDT3ZTVTJGSFV6bW9renBrMWM1bWFjWkU0Nzg4TXZYbTRBYUl2SXFUdHBDTEI3T21uUHdMOHFxVitaYjB1dUFpQ0k0L2I1Q0xrYWJ2NXJaMlBQZjRTQTBCZlJFaTdLTW5XSzdNdVZWYkpTYnBtWENUTyt6TkRqenlYZlJxRFFGOUVTQmJXQXA0QnZtSXAxMDk4Vk5HanhCYWsxMWNUQ2lFNDhyaE5Ja0pFVERPTG9HZUFOd3d0MzdLN082NXV0VjcwUzRTa29LcVJpSnhSMVRkRUpKZzUvZlErVStqNGVaUWpkdUxTNm5wTUpCdW5JSnkxRkVVU0RXdmtYRGZhYXdINkZRUjJuSGppSlFhTXZvc1FXL2lDVkdqZU1QdW11WWVwT1dFbkxsTXpMaExYcmZJK1NweVBRZnJjYkZLREVpRitBWFRjN0FzbkR3c2NWa0FqK1VNYmZVeEVhc2xkeUhmQlJSQWNlZHlJaTVBWllCb2drT0FYN0o3SjhST2Z1Y0lHWVdBaXhBL3poWWxKUDlrVTJsMnZKRC9KL0YwVXp2c3pReGVmUzNtZDRXQmdJcVNEQlp3RzNnWkErVThtTWc4cmV0eFdoUGQyc29DRkVCeDUzR2lLa0hmVnJBZitDdkQvTE9tRzBqZllRQXhTaE1TRjBPT21WWFZLUklLWjUwNTlBUURSandsNjBGUVNaYTg1UTlZUzRyMitGSXV6MXFRZ1FxSTNUcm1vUUFEZnJGZWowd0I4OUlrcGhvQU5FU0Y1WERvYkFsM25rMlJxMEVYaTFsUHhIeGFIQnBsWGFtallVQkdTeS8zUlV5RjJia3BqTnZqWEFLaitQWkNmeHZqbEhZWWF2dURJNHdvdlFrU2RaWHNKNVZzQzFBOUcvekcrbUVlZVhQVW81bjVpUTBWSUw4SWsrVmFIQ3pNMTZhSngzcDhadWhpY0I1RTJIelAwTHhKdHFBanBZQUVqa2tiUWwrM25zdDdGekRrQTRSZE53RjdNTDBFcFFsS2NXU0lEQk40RmVWZFVVVkc3NEx6OFNKVnozcXM5OU1JSEd5OUM4amhVdFdtNWwxVTF1dlhsazY4aDFGRm9JVWROWEk2SlNMb0E1cjdtRzh4WmExTUljUUdSSFRGNkNYZ0ZFWGFHMGUrWTJMckFSNTljODl5TlFXRm9JcVFiaDNNVmtzM3VCb3FMVVJRaDBIRTErcUppK0NLa0J3NmdjZnB6aDNGTGdVanJkMjFLQjRCOWZ0cGJUb1NZcnhDWkx4RzE5Ri9aQ0ZNN2YrMkpudGRuR1NhR0xrSjY0ZHFyQ2FiR3JkNTJ6NkpoczRtUTFPZGxKUk1XSDhNWEliMWJ3T2trQmYwOUFFSHVCWTRhU2g4d0hCTUk2UzlLajdnSUVkU0p0Q2tWbVFaRmtGZU1SWlR6WUQ4MGprNVpDMWk0dWw0bkZFR0VyTWhaZmxva1htLzRXWURHNlZQSFZjMTBVRkF6NXREMHFLUUxZR3cyQnNCNUltQU5vcUUzVHMxSEpESGRaUmRzbk9kczJ1ZkhUenplOFdPQVJVY2hSVWlXYzVZd200NXBlbkJsem01c1JoR1NncHA2cC9jTTEvRGNDNE9SRVNFOTQ3bmZydUY2VmlvTEh3WlE5RDZFZXdFRS9vbmhxQXZwYnlFUFRZUmdWNW95Zi80eEVJRCtVTkJ6QU9PaHZteGpSM3gwdUQwWC9jWklpWkJzT3AyNFhpRHgvd1VRSVpsblFrNGo4UURzUkNFd01pSUVqQXZPcHRYR1BmZmJmcy9LV1J0T0FtZnM5Zzl0ZUR2MkE0d0tFNVlMRmFuWkU3dDVMRFZGN0RxS3JwN3BjVTRzUUZPSjYycnoxbjB1dFhIUVZER2NxTHFta2lsRTNBZnV6bU1Lb0xPS0VSRFo1cjFDOUY3MEU4SUE2aEFERWlGUjFzS3RoMnU4K1BRK2hRTjIvMkhEeWc3ekF5SjE3WXM3VldVTVFBSjFQVEU3VUhHRjBSV0tCWkt4ZE5lQUFLVUJ6SG9jd0R6Q1BBSzFadXNzcGxCTmIvdTFKMGVpM2E3ZkdHMFJzazVPSUpLT1ZzV0pEaUp2TzltMU1uTFBxelpoN3h3akxTTFdpLzhQVnlPTGFNVmxLZ2dBQUFBQVNVVk9SSzVDWUlJPSI+PC9pbWFnZT4KPC9zdmc+Cg==" k="name"/>
            <prop v="0,0" k="offset"/>
            <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
            <prop v="MM" k="offset_unit"/>
            <prop v="35,35,35,255" k="outline_color"/>
            <prop v="0" k="outline_width"/>
            <prop v="3x:0,0,0,0,0,0" k="outline_width_map_unit_scale"/>
            <prop v="MM" k="outline_width_unit"/>
            <prop v="diameter" k="scale_method"/>
            <prop v="40" k="size"/>
            <prop v="3x:0,0,0,0,0,0" k="size_map_unit_scale"/>
            <prop v="Pixel" k="size_unit"/>
            <prop v="1" k="vertical_anchor_point"/>
            <data_defined_properties>
              <Option type="Map">
                <Option type="QString" value="" name="name"/>
                <Option name="properties"/>
                <Option type="QString" value="collection" name="type"/>
              </Option>
            </data_defined_properties>
          </layer>
        </symbol>
      </symbols>
      <rotation/>
      <sizescale/>
    </renderer-v2>
    <symbol clip_to_extent="1" force_rhr="0" alpha="1" type="marker" name="centerSymbol">
      <layer pass="0" enabled="1" locked="0" class="SvgMarker">
        <prop v="0" k="angle"/>
        <prop v="245,75,80,255" k="color"/>
        <prop v="0" k="fixedAspectRatio"/>
        <prop v="1" k="horizontal_anchor_point"/>
        <prop v="base64:PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIGlkPSJteVN2ZyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+Cgk8aW1hZ2UgaGVpZ2h0PSIxNjAiIHdpZHRoPSIxNjAiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBS0FBQUFDZ0NBWUFBQUNMejJjdEFBQUFDWEJJV1hNQUFBN0VBQUFPeEFHVkt3NGJBQUFmRTBsRVFWUjRuTzJkZjR3YzUzbmZQOC9zN1BMSVcxTGtpU0lwbXBCb2lwSmNXcUpVSTdXQk5FMVVGRzJkb2dtU3dGWk1PYzQvS2REMkQ2UC9GSEJ0UzVVb3lnMENCQ2ppb0VpdHREVmlXWlJjbzAzYm9MRVQyTEdpRnJHVHlvSnN5VFJGVTdURU1DSjVKby9IdTczai9kaWRwMys4N3p2enp1enMzdDdkN3UzczNYeUo1VHYzblhmbWZXZm1uZWQ1disrdkVWVmxLMkgreFpNSEFhSklqb0Vjcy9ROUFLanVBTmtCUU1BK3UyK0gvWUd5MTFEcWN4RWlxREtQeUR3S29OZEVRR0VlcElFWURoUlU1a0VXZ0FqUjF4RVFPRk92MU02Z3dLT2ZtaEdSUUZVakZ3SnNWaTdvMTRNdFVXSXRrRzRXMEMrNW80TDVGMCtPQVRVQTFlQUJnQWoyZ3JGb0F1OEhuRFZ6Vm02M0RXdEFpSWxZdDF6b3pvY2FxNmNRaXVNZ3NuZXdDYkprRHRWNXl5MGgwalNiT20vUHNRU1dFNTIwZWJvQ1ROcHovd0FJVUNZRENTWUJ4c1B3TEFvSVRYbjAzMFJGczJMcjRjSnVEM1BVQ3A5RkRWemgwUSthUU42UHhPNzJwd0VVUlVSU0I2cXV3RWxNZ3VWVU5SQVJWRFVVWVV4VlVkaGxPY1NlQTBCRWJMcVdVOE9oR2lIYXRBbDh3NloxQm5qZEpNSUZjeUlBbHRaN2c0cUUwZ1dYR0NxNnV1Q2lZL2JGWno0QWZBQUExZDh3SVlkRTVKQWZiMFhMdGc3T2Jmc2hNQmdPenFPY1E2RFM0dmVzVlR3My9va256aGZOdGZiS2RYWEJJNGF0WWMybFF6aWlHQmtMMkhqaDFENnNhSWpnRVFDQmUwR09BS0Q2c0kyNlMwUjIrY2R1SWdzNGhma2h5aXNBaWw0QTNnSUlnK0FiOXJpWkhTY2VueW1hdGN2alJzY0NLdnNRanRudFR3SWc3QldZTU50SmdkaTBVSjBRa1FrcmRJNGFBY01sNEtMWnoxa3hidmtTTURQTXJQYUswWEZia3RrZWNkY3pFSWdSNktOMGJ3cnBnaHN2bkRvTTNHWC8vQjBiSGdBNTRNY2JwR3Z0bGR0UUY5dzdkdzdrSElCVWdrL2JiRS91L05obnJ4WE5CWStPQlN5eEtURjhDL2kxendlS0JJSXlPMzN6RjIxajYzMGkzSTlwcS8wd2dBaDFSZXIrb2JaWmwyRnlndk41ZnNoUU9WV2RBcm1HYVd6L2h0M3hBK0FOVU9yaCsvNXZmQzJQUHNvd0xlRFFSWWhDSUJEWTIvZkw5cmtlQnpsdU8rcE5QRlV5bnREdmtCZ2E1N2I5RUliTEFSTWlURmp1cU0zMlM0cnVGbk5INHdJNGJKUXV1TVJRTVRRWHZIajY1QkdBWmVReEZUbGhIZHF4VHZHTElEanl1SUtLa0s2Y0NDOWJ5L2xWb2ZKZkFjWlBmR2F5RkNFbHRodzIxQUxPbmY3Y0FlTGVqTlluYkJZZUZ1RmhBRVgyNWxXcm9SaUNJNDhyb2dqcGdidW9DZ0t2QWQ4MWRQQWxHM2w2NThjM3JoZGxZMFdJNmMxNEFBVUMrUmVXcllIVUlCRWNlZDJjUlJBY2VWd1JSVWdQM0YzV0hVK0k4RUZWUmVDbHVJeHVZQzlLNllKTERCV0RjOEZmKzN6b3RlLzlaL3QySFJmaytHb2RpT0dINzI3enVCRjF3VG1jdU1ISEx3SGZCS1YrNG9sL043SXVXQkY3YVpKY1oycFBObFkzRHNqOFZSeXVXOFZodERqcmltMzlRdG9LaTRnRU5sN2Z1TDVid01hWGYzTWZBZ1N0QjBBZkFGRDREYnY3Z0NEN1NndFlQRTVWWEwzMmJWUXZJSUpHK2tWRUFUa2JVRG1MS09NblB0c290Z1VVOWdFUnFqK0g4QkZEeVRIL1lrc0xXRHpPRTFxSEVUbHN0NWRzbkQ4RXZZUktKQ0x6L2JTQS9TK0FTb1NreFkwcGVwSUtXUVZuK09GYnV6eHVzMWpBenB3Q0VvQkVpTFlWb09KWndLQjEwbDdNTWVEWWdDUk9pUTJBQkh3WUFsQjJRZlJlV3lZLzFjODBCaU5DWXRHeEZuZGJ1dURpY1ltSzdMY3c2WXNJbVh2KzFGRlhiMUE3Z0ZSaG53aDcrK0VFREQ5OGQ1dkhiWDRYTE9BUCt4Zjk1M2JINU03SC91MjZCN2oyeHdLYXd2Y1BiWDZQcmMvYWxSYXdjSnh3Q0hCVFhlTUJJNm82V1F3UjR2Vk5yVmR3bENKa0ZEaTdwdzhpWkYwdXVQSGlNeDhCUVBsVk1FMHVnM2djaGg5K1ljdmp0bDRCbEFVQWxQK0N5dStMQ09PUGZlYTF3cWhnWndkTEY3elpPY3o0UW5LczJpQkZ5TnhYVHRWUnMvaVBxdng3U3o5Z2Y2VUZMSnpGNmkrblNGTUFsTzhBM3dGUWFUMXBJemQzUGZaVWM5QVdzSTdZWmMyVVg3SmNmSjdTQWhiQk9nMk9rMlQ1dXVNS1J3U05nTit5WlhSZVZaZFdZd0hYTmh4TENkRDhvVnhxYytlSDYrWFVudG4vdXloY1lpbjhjQ3R3QUVTMmNBYXVqTHJDbGRkamtzZXQyZ0pxaTE4Qi9xVkpqVEdYclhZclVXSnpRM2NKc2dzVTBjcnYya0x3VmVDL3IrWXNxeStBdEJlMmRtTmR1dUF0eDVsZ2NDS2tjZnJVY2J2NUNlRFhUYUt5RDlLRnNoUWh4UklORzhLcG5MRTcvZ0NDTDRuQStJblBYT20zQ0hFdDRFZGN3WE1vTFdCZXVJVTRpY3ZHUFFMN1FBTVJtUnljQ01sQTI3WkxFYkkxT1NKVkFwQStpWkNUSitNQ3F2ZFdmdE51N202M0NDVktBS3IvQ0ZwSGJLM3VIL2R5U0RrcnJzUlEwVldFekQzLzlFSGdBRUFrd1RjTnEyTmdtbC9pa3dpWnhYSDZMMFBNbklWMFhvdkFxVXBodE1Dd09WR2RCcVlVSUpCL0lHYlJxZW1kSDN0OGlnNVlRWVRJQVlUaktJaVlqN2xrcFFFdUwrSnRlL0VTdGJoMkRrQWtSNDBXZ0RNRlVTQVZza1U1ZG9Qc3RyWDR3NWFOUkdTNmt3b3VYWENKb1NMWEF1clhQbDhUaEVqa0VaUlBJbWtCWHFMRWlsQTlhWWVKZmhINFVxZG9wUVVzTVZUa2lwQzVGMDc5REVDa2ZCemtZNGJWM1pBV0hQRkpTaEZTS0RGUUNFNzBvdldhWHhMa0Q0QmcvTVRqNThnZzN3VXJQeVhtdmg1QjNKY2t6ZWw4d1JISDk3aFNoQlJCREJTQ3U4dVdtU01reXdTZkswVklpVUloM3dJS0oyeTVQclNSNG1QOHcvOE1FR1JzSE5sZVh6RitpZDRSM1dyQXdoeW9Ndjhudjc5eENTc1BxeEphaC9IMTdPN1NBcFlZS21JTE9QZlZrelZWOXhYdzRKQ3R6TzNLaXBSZVJjaWFKbUdPV2FzWDFzaENDN0FnZVI3bnR2M1EzSWRpY1JMVzR2NnJSRGg1SVF5R1F5Y1FNWFhBWjU4TjlRdGZpSGoyMlhoNGx1K0NheEovcGw0T3h2WHVMb0lqajF1UENBbTZ1TjFzSVNnSzU3YXpZZUc0YWcycU5jdHZuSEJTa1FsZ0J3bENUTzhJcFFncE1YVEVGbEJid1RIYzE4Y0xqbWhwRVFCZGFNQkNJN1hQV2VDTjRsSk5YMng4MHh0amRZTHRkVlNWb0pZYUkxSUlDR29Yb1ZjYXV5Wi94dEp2WTllYUtTMWdpYUVpcVFOR1RJRCtMZkQ3SDlveFVCSFNCWDdGdi9uajF3eDNhODVZd1MwTTJWNUhySGlyM3ZkM2VoSW1HeXBDUEU0MGJwQ2VVZFczSVMxQzlvRzh6Mlc0RXdiZEU5SUpmcDZhUC82K1NldFdnMmhoTGgyUHJUVXBLVzR6VmFWMi93Y051NEl3R1ZidmphamNhM2U4WGZhRWxDZ0VRdjdYYnhuN0xkeXY4SWpaTERaYU42NEN2dlhKaDdNSUJDRlN5WGI2OUNZNXROV0VxQW5BMHB0LzFWc0dkOXlHaUJEczNrOWx6d0hXWXRsY3VxclFQUGVYSFpQU2hRYTZNT2NkVzF5MFZIL0pYdVZmQTM4R3BRZ3BNV1NFYzNOTDc3UGJlMFZOblZDN3ZFMUZFQ0dWM2ZzTmw5Y000dzJWcWh5NHg1QkJnSjJXbXNTTGE1OHJjQnBCWkQ0aVZMMWwwb3JtWjlENUdmK0NRVXdhaWhJZU1yYzBxTzhoMkRrUjMwK0phNCt5TXFjUlp0MGZaZm5OditwWXlRL0dFaEhTYTYvTTBFU0lzTmZRZXNmTTZhY21abDg0U2FpSk10bnJubEkzRjF3RUVWS1pPQUJBYStwS3V3anhoa3FGQisvcGVzNVZ3N3JpMXJWTFJOZi9CdkNjZGxCQktsVlFwWHJYTVhORHhzYTc5dTcwaW02aVFjYnFWQ1lPcEY3UW9vb1FZTUpXblBaaWZxVUxMakZjaElMOGJRQzEweTlIQWRzKzlBc0FSRXNMc0d4V2pHMWVNb050bTVmZm9uWDVyWUdrR3g2NlB4VnVOSUk3anhMZWVRK2doSGZjM1ZjcnU1RVE1UUFFRDZNZDF2Z3JVV0tqRUdveVNDZnNaYUdzSW9pUU9OMUtCYlhabDdGeEFJTHRPOUVkdDYxNGJNL2MwZ0pxcmF6UHNieVlISU5BRUlBRWdCcFJJQ0JCQ0s3NXA3cHQ3VU9xcXZZYWc0cEpFMGtHN05xaGE2czUzN0JFaU9NRWFwaVZkb01RY1FWUXdsN2EvNG9nUW1LdVVqVVZmMER0QTRsMjdDS283MTc1MkI0NVhWNUE1MjZtdUtneDdYRnFMdDZLRUVVSjlod3cxMVFkSTZpTnBRWUtyR2xJbFMyOHJqQUwyalppZkRYbkcvNDhGbW9DZFpEU0JaY1lMa0pVbmZpb3Q1bTJEVWJ6MHBzQUJMdHVKOWkxZDFYSHRockdJbVhkWmVjRG10QnFBYkQwNCs4QkVOMjRRbVI3V1ZwejA0QjVjWjMzY0c1M1RYM0JmdS9JeEFGUUpYenZRNG1GNnpLVUtxanZRUUJwdGREcHE2Z3F6Y2wzZWttMUl6ZFVxTlNCTzZGc2hpa3haSVNLRzRaUHJVMWQ1R0NRSXFUNXpnOE11MjBIYk51UnFoV3UxSFBibXI1aVR4bkVnaVNPNTRtTDFqWFRnQncxcHREWkcyYmJXYnZxR09HaCt3QUliWDFMRitiUnhYa0FtbS9iVVRpUzlLeFU5dDl0amgyckU0elZ6WlZWS21SN09Gdyt0ZFZFRnhkQVlQbWM2VnNPYnJ1RDRMWjlnQkxjL3A0MjBTQ1ZDaUJFUy9OZzg5cTg4RDNXaW1HTEVOQ2FJbldBRUVrS1lONWl0RzJaWjNBaVpQbmltWTd1b3RlaFVwWGJEeExzUFpTTzUyVzRaWHN3V2xmZnBqbjVqamxtM0lpVzhOQjljUnRmc01mVVRLS1phMFF6MXdGWWZ2dDFlNzRBdFFXMGN1Y1JCQ0hZWXdjZUtKRGpUcVBHTkNMUXZQb09yY2wzUU5VV2FLRnk1ejJFeldVVXBXTHpuaElOUVFnaWFHT2FhUFk2b0VUVFY3eTd0RG9uN0l6RXNFU0lpaGdWVE9tQ1N3d1pJU3FlQ0JscVh2cURTaFdwcGkyUWI4VVdYLzFURTIzbjdZVDdEd093L1VQLzFNUmJYb3g3Vm01OTh6bkROYWFKNXRQTk1PSGQ3NmQ2NUNGem5uM0dCVWR6MDdSdVhFV0JwZGRmYnJORHRTUEhBYUd5NTBCODdFSnRPeUttVDN2eDlUOEh4VGJYR0xFUzdER0RMb0k5KzBIRTlQek1YdS9QZlJvaVJMV083WGtyTFdDSm9TTEVFeUc5ZkROazhEMGgrYjBqdmE1Y0pSSkFwWktPdDd4a2xxWUFwTHJOa052SENjWnRqNGx0ekdidVptd3BvOGEwUFhZaHprZXcwelFOQmZVOWlEMVdXMDBFaUc1Y3BYbjVMVkJGNTZiam5NZmgwcUs1cXRheXpic1MxTTA1Wkc0bWJtVE9pNmNpY1JWS1llTkZROTlGQ0NHMkI4NFhJZUd3UlVnbkRxRFhsYXNJZ3FSQU9iU1d6Ym9vRUxlM0JXTjF4SXFQK09Fdkx5WUYwTHJkVkp2ZmJiWUE3cHdnY01jdUxSajNlT09xVWZFS05CZmlLM0doTHQweU55bHEyYndMd1k3ZElCQnR1NFpVUWxQWWN1S0o5MEZ3ODM1dmRNOUZ2MFdJSzREbFlJUVNRMFlJdUM5Z2p5bmF2aWhMQm9WM3dXUGpjZVhkSWRpOUg3RURGSmJPbXZrVnk1ZmVSQzcrd0owSmdNcnQ3NkgyNE0vR3h3QzJ4OFFNUkEzdmVjaW1tNlM1OE9xZm9oZ1hyTXVMb0ZBOThoQUtoSGNlb1hyblBhZ0loS1kvTjdweGhlYUY3NE1vdDc3OVI4YWtCWlhZQ3B2UjFKb2E1UnpzUGdBQ3djMXJ0S0FZYm5SOWd4R3NCUlJDVkkwVkZLRVhGMnlqOXNCSkpsd25KOWs0SGJoY1JwUDhTWHRNNlppZURiUEplaGVyWGhSM254Tk96SDMxWEtoN0F1N0JwQjIxZjBZdnJXejFadmhsYUgyY3ZScEJDQlZtQUVSMWwwTGZMT0JhR2tnN2MrNUtNZ25uY2VtakRDb2g3aWxXMzJ1c21OODAwN1FEV0lPRmVkU0tGVGY4SGduaTRWQXQyM0N0U3d0bVNCYkc4Z2tRTFRTc1FDQVdJYTJwZDIxK0ZLeTQwTVlOb3RrYlpnQ05GVEtWblVuZnQ0emxETE1LS3FZZ1N4Q240UzRmVGNKUjRVUlpBSmtHQ0FYc0haZXhYc2NpakpvRmxFbzFGaWF1RGE1NStYeGMwWGNqcVBWV0E3MWxKaHU1TmtLcVlTeGNYQUgwaDJORjAxZlRyNHdRNzJzQnVuakxGRHc3eUNGYU1BdEZLaERhTnNUSy9yc0o3endLNUEremtyQnFubDhRRk1lS3JZUERWUHRNQVV3dVZYdnBDaDVKQzVnYWFPcGxQcnVscWYwNThmS085ZDd3NUUxUDNHamUxVVh1dURoV0VqTnZabHRxUFVJdjhhSlp0cDR0WUh3N2xWRFFTWHRyeGhRbUdISElXSjF3OS82Tyt3TTdvNjY2WnorMVkzOFhTTnI4b3RsclJEUFhBRml5bmYzR0t0cVpkMDJyMTFMaXA5MEN1OVc3Z3FBU0Y3anFrUWRSSkI1cUpoQVAwY3FPWUc3TGMyMDdvS1pQZUJOQW9TRWlWMFFnUkNSeU96YURDSkdjekt5OHlLUi92S1JTMWxRU3ZoOUp0cnU0bW5qYm4zSHNERUxRNHpSS2RiYXlRRzUwWFM3WUUyUWg2dXFBTEhXYmtKN2NtR0s3WUEwQ1UybjN1WlhtZjFpUkVkUW5VTHNkMmxDYlM5QmNNdkhzQUZaL0FudDZ5SlV0TEJXN0puZFlNMHZqb29uSTJMYkRERUR0NEc3TlBjenM4NFRKWm5EQktFdGl0VWNJRWhmQXpTQkNURmRjbU9GV3NJQnV2a1p0REhhYVdrZ2xNNlJya0ZoeFRvZ1ZKaExXQ21QRjFpbENsckFGME9zSjBiakMyKzJYRjgvbkVxdmxoK3ZsYkkzZC83c0RsMmZGOCtwVy9lTGN0aDhPakhOWGw3bjhVZVA4cHhzQ1ppaXh5T0dlWkhCUkVkb2hXRzJyWUpVb0drUzBnWEJaSVA2QWlLbDE5ZWlEQyttQ3BlMElMMi9kWGZCNnVBMWRKZC9XUEl2Z1J0ZnBndU02YzZpcTgzYlAwaWkzQThielFBYjRqUkUzWXk2NjFZaVhCbmF6OE1RS0RnWEMvWGRiLzFKRHFyWFZUVUx2d2xHcFdBR0RHYlpsYjFHQnhFVnZIQ3loMG5BdTJBMzNYUnBsQ3hoczMybW9uQUxZTDJzWFRkc3BtMU5YNHUxNFFwTmJyUjZvM0hZN09KMWNyZlhOQWxKSmVtVjBlYkZ3bHExbkRvbEZTT3lDVFFWeFpSTllWQXZZTGVmOXNvQnhLdUtuNS9McWI5bThTM0lPNklNRjlOUDBMRXRoTEZ2dkZqQkdHS2k4Wm5jODJNdUk2SzJHNlByZnhEUHBsdXg4a3R6dkJUZHV4dVZ1K2EvZkJERkxCRmZ2L3hDQ1FtYTltclZBcW1NRTQ3dk5zMnpNclB0OHc0S2dseVNNdmdPK0JTVGZCZVdlb0lBdXVGdk8xK09Dd1IrbTV2a1JiN3VUcTNHaElqMzNlblRqa2h4MVQ3Zm9IQUJLZ0JDRllMN1hvSEFONDV0Qk93OU1MYW9MemhNaGJoSzZoTlg0TzJsdUtIMnZMdGlNbTNJOUs1NGZrV1M3emRWVUtpWm1FSnBGaTRTVVMyMXp0MUdFYUdUYXlPYmNYSlFsY0hPRjk5MU52RGlSbTlNeWdpNVlSQ2Z0azcyTzBBQ2ljRHlNTGdETU5vT2ZnQzdabTlKMVhHQWhMYURyTGFnbVdYZkw2S2ErUDJ3TFlNOVdNYWlZQXV6blp5VUxhTHZpcEZKQnd0QzhuZDBzb0VZUXRSQ0ZscHVUY3FzQmkzT2d5ZEF3c1NKRU82Vkw0YmtyMXJoTWpYLzB5Um1BVUZQelFzekFoRzUxd2FKYXdDUlB2anpvZkIwOVc4QzJ0dnRNWHZJc29IK1VuZFZHTndzSXlTSkk5dExkUGRXVTlVenV6Q2hhUVBQU3BPOXZLSTgrdVFBZ3A1ODVpLzJpdGNLampCaUNtbkZOdWpBWEw3bVJKeHBjajBsd3gzc0liMzhQQUxVSGY2N2plV1gzZmtLN1RNZVl0WjdSdFV0RVA3bGt0cHVtT1lUcU5xaHRSNEJ0RC82c3VkL1ZNYk5NaC8vR1JpMHpxRUZnOGJ0L2dtTGFGNlBwcXgzZndjb2RkNWtYbzdsQVpYeDNtNUljRllqSzE2MDNPTys0UUVRQ01TdnR4SmJRTEdLWS80UHVYTHY3N0Fjbm50dnJ3SWt6Ry82Wjh1TDVsS1RxRGl2MmVuZzVjOGY2ZTEyNWlhMFVpWldMWGEvOVR6eHJKclJuTVJWYUt4bGJFYzJQVjNqT1ZVVzhGekpVKytYcXh1bFQxMURPSjdjdEgwVjF3YkZRQ0lLVUUyNkxaMmU0UmJNM1VEdThpbTNmQmFEaUZoaUNaSzZ3NTViZFpQUUtrb2laMXJMSmE4V3VrS3JZcFVFMGRRNmlGZ0swcGk3VHVuNFprZno1SkM2N0tSZnJYSEJZZzIzajVoNlBvZ3RHZm1qRGErNEpoZGI2TWZ2ODA5TWkvTWpjNlhaTDRLT1FJc1RPK1JBSlVsYXA3Vmc3RHlScTNFQWFabm0ycHAxZ3hIc2ZvbkxiSFdiYkxZZnJYVmc4R1gwOHZRVHdTaENSMk8yMnJsK202UmJFekpsUGdyY2RoNjZlV0swaFFSQkh5c2JMTzdaSW5FUnkxaHFydUFBR3FocXBhaVFRamZKd3JPU2ZmNmJlampXMWV6dDEwMjQ3OUcwNGxpMXBPUjBhN2RuSjdsTzdOb05MdDBPOG9uUE9VL3IzSUI2N0ZGU0RDMkJLWm5NNVl0VGcxdk5ieTVDeTZLYnQ0NTE4QjdGaUpyVFROL3VGNW9Ydm9VRHI4bmxhdnVCWUJhUTJaais2Mk4xREZRdmFRS1VoQ3RzLy90bnZaUGY2SWdUTS9KbG9GRVZJeklwNForcnRXUGN6WmRmUFI5b0Y1M0Y1dzdIeU9PZG1YVjVYVTNtUFJVaWNOKzM1MkdGejJTRmtXY1FpNU5aWFB4ZVBVRkQwWFh2SGRxR2tKcW9XVllURWV6d2JIOWg1dDcwaUdMK3Q3ZUpXYWkvc2VWNkhGVWxCZlEvc3UzdFZkOENkUjhLcW1WTmlMN2c0NHFJTGgwNkRYT3gwejBQUCtpM1pIek9ubjc1a1g5ZERJdEwySGFoQ2lwQ2NqSVNyTElCeE41ZWZ4Qm9zWU40K3Q4NnoxUGRRY1lXb1I2UkVpT3ZSc1JhbUNPS2lPeWRUUU56dWwwVXNRdnlmSDJGMFJFaGlMWkl6SmZ1eXgrWnhrczJHUFY4V2F4RWh6alM0NHJtcU82QmUzdUx6SlpmZkQ0RXdNRzRGNUU2Z0VKV3YyODFIRkQzWXczbUdqb1Z2LzAvQWZNcTFrcDJZbnZIbW5iaW91WWpZRWM1THIvODVBR1p4eUl4YjlqaTNlS1NyRGNSdmZ6Zk9wWS9OZys5emM3aldUeTRpYWdhLzZ0ek5uaDVzVVNDcTU0R3ZkZXJlalVXSS8vT2pqb3dJOFNyL2NRK0g2NjNRd1hGNVg3MGFGQmMvRTlLWDc5K2F3bkV1engzYWxzT3N5d1Zvbkg3bS93QW9IRVE1YmxqZDdaNXRJVVdJVzYzcTVuWFVMbzJ4VWVqMzFYYmsvQThuSmw2OU9JTEQ1MFNkOERnSHZLRnVHY0FNZkJFU1EvLzM1MTlHWVBiR3plTUswd0tJU056OFgwUVI0ajZqRlMwdklwbVY1RE1HcEs5YzFvTU90QUQ2bkxVd3hSSWNxZkJ0VUJCNXMzN2lpVGZvZ0h3Ukl1a0xCd292UW9iR2VYOW02QzNQNFJla0RzaWZ4ZjN6bjF3U0lEaDk2cytBS1lBSXZ0ajlWQ1ZLSktnSW4xSVVFYm5VTFY2dUNQSEVTQUNtRUJkZGhBeU44LzdNMEZ1YVN5M1cxQVc1SXNSaDd2bW5yN2cwRk93Nmd0UVZVaTJwUlJBaFErTzB3NGpvTGNpSjZoUndUUUFSdVdRTFlkZnBlN2tpeEVHZmV1b0tkdTJZeHIzaUNpQWkwdGFVUDNRUk1pek92dlZGcVBnUG04TU1aamtMc1AzRUUxMWRyME91Q01uckVmRnFscVVJeWRTKysxMTVIMW5PUGJWVmpFanF2cFRVazAvR2hWQmZlT1lKdTNrQzFaR2JNMUppY0JEUlNJMHIrQWJ3SHpvMU91ZWhxd2p4Zi9FUlNpbENmTTc3TTBOdkdjNWZmcGhWZmdDenF3dk91T096d0ZtRTg2aGVSUFZpNllKTEYydzRmUTE0RmZnUlJxekdRKzVYUWxjUmtzRTVnTm5UcDk1Q3pQZ3VnYnZjemxLRUpLSGJ1MVU0UVY2eGU4N1hUendlaTlWZTBMTUY3RFpVaTlJQ0ZzUVNEWWxyZTI2OVk5WHIyVlpicmY4QnZBeXdYQW0rYmVrZFpOb0dTMnh5Q0ZQQUZBSzZISDdhc2d1clBVM1BJaVFXSTE0aFQ1cGlLRVZJTzcyNXVUNmhhMDlJSGhhL2ZISUIyejhzeUl1Vy9pQ3FQNFVoQTFzN0lBbGhmUndVb3Rjamo5dGlQU0VpZGtsbjVWWGdMK3dkY1phdnlTcXhHaEhpc09BU25QdnlNODhEUk9nWXdnZnMvbVRtZENwY0p5ZlpPQVhockVVb2doallJRzdlOFBwcU5kTG5nR0RicjM5Nm5qVmkxU0xFL3dtSy8xRnBnMnlGVlB2QVpXckJSZUtHVmZFZkZwZCszcXMxWG0yUTFYU2JkTUxjNlZNUEF3OERxUERGUWJqZ1hyK1l2dEZjdkVSdlB5KzNZSndZMTlvRXFFVHk5KzNNMTB2YlAvN1pudnA3dTJIVklpUjMySlltOXFIZGZVb2ZPRW5YZ292RWVYOW02TTNEZWNoWjRHcGRXTFVJeWNQYzZWTlhnTmNBSXRXWFRhYmxNTUpkL2JLQWhSQWNlZHpXRUNGbkJmMCtDQ0pjc29Xd0w2dWtyMFdFNUdIUy9waDkvdFJMbG5zRXVDdjlEa2ttWEFVbjJUZ0Y0YXlWS0loQUdBZ0huQUg1YndEOWNMcysxaVZDT3ZTVTJGSFV6bW9renBrMWM1bWFjWkU0Nzg4TXZYbTRBYUl2SXFUdHBDTEI3T21uUHdMOHFxVitaYjB1dUFpQ0k0L2I1Q0xrYWJ2NXJaMlBQZjRTQTBCZlJFaTdLTW5XSzdNdVZWYkpTYnBtWENUTyt6TkRqenlYZlJxRFFGOUVTQmJXQXA0QnZtSXAxMDk4Vk5HanhCYWsxMWNUQ2lFNDhyaE5Ja0pFVERPTG9HZUFOd3d0MzdLN082NXV0VjcwUzRTa29LcVJpSnhSMVRkRUpKZzUvZlErVStqNGVaUWpkdUxTNm5wTUpCdW5JSnkxRkVVU0RXdmtYRGZhYXdINkZRUjJuSGppSlFhTXZvc1FXL2lDVkdqZU1QdW11WWVwT1dFbkxsTXpMaExYcmZJK1NweVBRZnJjYkZLREVpRitBWFRjN0FzbkR3c2NWa0FqK1VNYmZVeEVhc2xkeUhmQlJSQWNlZHlJaTVBWllCb2drT0FYN0o3SjhST2Z1Y0lHWVdBaXhBL3poWWxKUDlrVTJsMnZKRC9KL0YwVXp2c3pReGVmUzNtZDRXQmdJcVNEQlp3RzNnWkErVThtTWc4cmV0eFdoUGQyc29DRkVCeDUzR2lLa0hmVnJBZitDdkQvTE9tRzBqZllRQXhTaE1TRjBPT21WWFZLUklLWjUwNTlBUURSandsNjBGUVNaYTg1UTlZUzRyMitGSXV6MXFRZ1FxSTNUcm1vUUFEZnJGZWowd0I4OUlrcGhvQU5FU0Y1WERvYkFsM25rMlJxMEVYaTFsUHhIeGFIQnBsWGFtallVQkdTeS8zUlV5RjJia3BqTnZqWEFLaitQWkNmeHZqbEhZWWF2dURJNHdvdlFrU2RaWHNKNVZzQzFBOUcvekcrbUVlZVhQVW81bjVpUTBWSUw4SWsrVmFIQ3pNMTZhSngzcDhadWhpY0I1RTJIelAwTHhKdHFBanBZQUVqa2tiUWwrM25zdDdGekRrQTRSZE53RjdNTDBFcFFsS2NXU0lEQk40RmVWZFVVVkc3NEx6OFNKVnozcXM5OU1JSEd5OUM4amhVdFdtNWwxVTF1dlhsazY4aDFGRm9JVWROWEk2SlNMb0E1cjdtRzh4WmExTUljUUdSSFRGNkNYZ0ZFWGFHMGUrWTJMckFSNTljODl5TlFXRm9JcVFiaDNNVmtzM3VCb3FMVVJRaDBIRTErcUppK0NLa0J3NmdjZnB6aDNGTGdVanJkMjFLQjRCOWZ0cGJUb1NZcnhDWkx4RzE5Ri9aQ0ZNN2YrMkpudGRuR1NhR0xrSjY0ZHFyQ2FiR3JkNTJ6NkpoczRtUTFPZGxKUk1XSDhNWEliMWJ3T2trQmYwOUFFSHVCWTRhU2g4d0hCTUk2UzlLajdnSUVkU0p0Q2tWbVFaRmtGZU1SWlR6WUQ4MGprNVpDMWk0dWw0bkZFR0VyTWhaZmxva1htLzRXWURHNlZQSFZjMTBVRkF6NXREMHFLUUxZR3cyQnNCNUltQU5vcUUzVHMxSEpESGRaUmRzbk9kczJ1ZkhUenplOFdPQVJVY2hSVWlXYzVZd200NXBlbkJsem01c1JoR1NncHA2cC9jTTEvRGNDNE9SRVNFOTQ3bmZydUY2VmlvTEh3WlE5RDZFZXdFRS9vbmhxQXZwYnlFUFRZUmdWNW95Zi80eEVJRCtVTkJ6QU9PaHZteGpSM3gwdUQwWC9jWklpWkJzT3AyNFhpRHgvd1VRSVpsblFrNGo4UURzUkNFd01pSUVqQXZPcHRYR1BmZmJmcy9LV1J0T0FtZnM5Zzl0ZUR2MkE0d0tFNVlMRmFuWkU3dDVMRFZGN0RxS3JwN3BjVTRzUUZPSjYycnoxbjB1dFhIUVZER2NxTHFta2lsRTNBZnV6bU1Lb0xPS0VSRFo1cjFDOUY3MEU4SUE2aEFERWlGUjFzS3RoMnU4K1BRK2hRTjIvMkhEeWc3ekF5SjE3WXM3VldVTVFBSjFQVEU3VUhHRjBSV0tCWkt4ZE5lQUFLVUJ6SG9jd0R6Q1BBSzFadXNzcGxCTmIvdTFKMGVpM2E3ZkdHMFJzazVPSUpLT1ZzV0pEaUp2TzltMU1uTFBxelpoN3h3akxTTFdpLzhQVnlPTGFNVmxLZ2dBQUFBQVNVVk9SSzVDWUlJPSI+PC9pbWFnZT4KPC9zdmc+Cg==" k="name"/>
        <prop v="0,0" k="offset"/>
        <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
        <prop v="MM" k="offset_unit"/>
        <prop v="35,35,35,255" k="outline_color"/>
        <prop v="0" k="outline_width"/>
        <prop v="3x:0,0,0,0,0,0" k="outline_width_map_unit_scale"/>
        <prop v="MM" k="outline_width_unit"/>
        <prop v="diameter" k="scale_method"/>
        <prop v="40" k="size"/>
        <prop v="3x:0,0,0,0,0,0" k="size_map_unit_scale"/>
        <prop v="Pixel" k="size_unit"/>
        <prop v="1" k="vertical_anchor_point"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" value="" name="name"/>
            <Option name="properties"/>
            <Option type="QString" value="collection" name="type"/>
          </Option>
        </data_defined_properties>
      </layer>
      <layer pass="0" enabled="1" locked="0" class="SimpleMarker">
        <prop v="0" k="angle"/>
        <prop v="33,150,243,255" k="color"/>
        <prop v="1" k="horizontal_anchor_point"/>
        <prop v="bevel" k="joinstyle"/>
        <prop v="circle" k="name"/>
        <prop v="0,0" k="offset"/>
        <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
        <prop v="MM" k="offset_unit"/>
        <prop v="255,255,255,255" k="outline_color"/>
        <prop v="solid" k="outline_style"/>
        <prop v="0" k="outline_width"/>
        <prop v="3x:0,0,0,0,0,0" k="outline_width_map_unit_scale"/>
        <prop v="MM" k="outline_width_unit"/>
        <prop v="diameter" k="scale_method"/>
        <prop v="25" k="size"/>
        <prop v="3x:0,0,0,0,0,0" k="size_map_unit_scale"/>
        <prop v="Pixel" k="size_unit"/>
        <prop v="1" k="vertical_anchor_point"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" value="" name="name"/>
            <Option name="properties"/>
            <Option type="QString" value="collection" name="type"/>
          </Option>
        </data_defined_properties>
      </layer>
      <layer pass="0" enabled="1" locked="0" class="FontMarker">
        <prop v="0" k="angle"/>
        <prop v="A" k="chr"/>
        <prop v="255,255,254,255" k="color"/>
        <prop v="Arial" k="font"/>
        <prop v="" k="font_style"/>
        <prop v="1" k="horizontal_anchor_point"/>
        <prop v="miter" k="joinstyle"/>
        <prop v="0,-0.40000000000000002" k="offset"/>
        <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
        <prop v="MM" k="offset_unit"/>
        <prop v="255,255,255,255" k="outline_color"/>
        <prop v="0" k="outline_width"/>
        <prop v="3x:0,0,0,0,0,0" k="outline_width_map_unit_scale"/>
        <prop v="MM" k="outline_width_unit"/>
        <prop v="11.8" k="size"/>
        <prop v="3x:0,0,0,0,0,0" k="size_map_unit_scale"/>
        <prop v="Pixel" k="size_unit"/>
        <prop v="1" k="vertical_anchor_point"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" value="" name="name"/>
            <Option type="Map" name="properties">
              <Option type="Map" name="char">
                <Option type="bool" value="true" name="active"/>
                <Option type="QString" value="@cluster_size" name="expression"/>
                <Option type="int" value="3" name="type"/>
              </Option>
            </Option>
            <Option type="QString" value="collection" name="type"/>
          </Option>
        </data_defined_properties>
      </layer>
    </symbol>
  </renderer-v2>
  <customproperties>
    <property key="dualview/previewExpressions" value="fid"/>
    <property key="embeddedWidgets/count" value="0"/>
    <property key="variableNames"/>
    <property key="variableValues"/>
  </customproperties>
  <blendMode>0</blendMode>
  <featureBlendMode>0</featureBlendMode>
  <layerOpacity>1</layerOpacity>
  <SingleCategoryDiagramRenderer diagramType="Histogram" attributeLegend="1">
    <DiagramCategory spacing="0" penColor="#000000" barWidth="5" lineSizeScale="3x:0,0,0,0,0,0" height="15" lineSizeType="MM" penAlpha="255" backgroundColor="#ffffff" scaleBasedVisibility="0" scaleDependency="Area" diagramOrientation="Up" rotationOffset="270" maxScaleDenominator="1e+08" minimumSize="0" penWidth="0" sizeScale="3x:0,0,0,0,0,0" sizeType="MM" spacingUnitScale="3x:0,0,0,0,0,0" enabled="0" minScaleDenominator="0" direction="1" labelPlacementMethod="XHeight" width="15" spacingUnit="MM" opacity="1" showAxis="0" backgroundAlpha="255">
      <fontProperties description="MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0" style=""/>
      <attribute color="#000000" label="" field=""/>
      <axisSymbol>
        <symbol clip_to_extent="1" force_rhr="0" alpha="1" type="line" name="">
          <layer pass="0" enabled="1" locked="0" class="SimpleLine">
            <prop v="square" k="capstyle"/>
            <prop v="5;2" k="customdash"/>
            <prop v="3x:0,0,0,0,0,0" k="customdash_map_unit_scale"/>
            <prop v="MM" k="customdash_unit"/>
            <prop v="0" k="draw_inside_polygon"/>
            <prop v="bevel" k="joinstyle"/>
            <prop v="35,35,35,255" k="line_color"/>
            <prop v="solid" k="line_style"/>
            <prop v="0.26" k="line_width"/>
            <prop v="MM" k="line_width_unit"/>
            <prop v="0" k="offset"/>
            <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
            <prop v="MM" k="offset_unit"/>
            <prop v="0" k="ring_filter"/>
            <prop v="0" k="use_custom_dash"/>
            <prop v="3x:0,0,0,0,0,0" k="width_map_unit_scale"/>
            <data_defined_properties>
              <Option type="Map">
                <Option type="QString" value="" name="name"/>
                <Option name="properties"/>
                <Option type="QString" value="collection" name="type"/>
              </Option>
            </data_defined_properties>
          </layer>
        </symbol>
      </axisSymbol>
    </DiagramCategory>
  </SingleCategoryDiagramRenderer>
  <DiagramLayerSettings obstacle="0" dist="0" showAll="1" zIndex="0" linePlacementFlags="18" placement="0" priority="0">
    <properties>
      <Option type="Map">
        <Option type="QString" value="" name="name"/>
        <Option name="properties"/>
        <Option type="QString" value="collection" name="type"/>
      </Option>
    </properties>
  </DiagramLayerSettings>
  <geometryOptions removeDuplicateNodes="0" geometryPrecision="0">
    <activeChecks/>
    <checkConfiguration/>
  </geometryOptions>
  <referencedLayers/>
  <referencingLayers/>
  <fieldConfiguration>
    <field name="fid">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="osm_id">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="name">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="amenity">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="hstore_to_json">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
  </fieldConfiguration>
  <aliases>
    <alias index="0" field="fid" name=""/>
    <alias index="1" field="osm_id" name=""/>
    <alias index="2" field="name" name=""/>
    <alias index="3" field="amenity" name=""/>
    <alias index="4" field="hstore_to_json" name=""/>
  </aliases>
  <excludeAttributesWMS/>
  <excludeAttributesWFS/>
  <defaults>
    <default applyOnUpdate="0" expression="" field="fid"/>
    <default applyOnUpdate="0" expression="" field="osm_id"/>
    <default applyOnUpdate="0" expression="" field="name"/>
    <default applyOnUpdate="0" expression="" field="amenity"/>
    <default applyOnUpdate="0" expression="" field="hstore_to_json"/>
  </defaults>
  <constraints>
    <constraint notnull_strength="1" unique_strength="1" constraints="3" exp_strength="0" field="fid"/>
    <constraint notnull_strength="0" unique_strength="0" constraints="0" exp_strength="0" field="osm_id"/>
    <constraint notnull_strength="0" unique_strength="0" constraints="0" exp_strength="0" field="name"/>
    <constraint notnull_strength="0" unique_strength="0" constraints="0" exp_strength="0" field="amenity"/>
    <constraint notnull_strength="0" unique_strength="0" constraints="0" exp_strength="0" field="hstore_to_json"/>
  </constraints>
  <constraintExpressions>
    <constraint exp="" field="fid" desc=""/>
    <constraint exp="" field="osm_id" desc=""/>
    <constraint exp="" field="name" desc=""/>
    <constraint exp="" field="amenity" desc=""/>
    <constraint exp="" field="hstore_to_json" desc=""/>
  </constraintExpressions>
  <expressionfields/>
  <attributeactions>
    <defaultAction key="Canvas" value="{00000000-0000-0000-0000-000000000000}"/>
  </attributeactions>
  <attributetableconfig sortExpression="" actionWidgetStyle="dropDown" sortOrder="0">
    <columns>
      <column hidden="0" width="-1" type="field" name="fid"/>
      <column hidden="0" width="-1" type="field" name="osm_id"/>
      <column hidden="0" width="-1" type="field" name="name"/>
      <column hidden="0" width="-1" type="field" name="amenity"/>
      <column hidden="0" width="-1" type="field" name="hstore_to_json"/>
      <column hidden="1" width="-1" type="actions"/>
    </columns>
  </attributetableconfig>
  <conditionalstyles>
    <rowstyles/>
    <fieldstyles/>
  </conditionalstyles>
  <storedexpressions/>
  <editform tolerant="1"></editform>
  <editforminit/>
  <editforminitcodesource>0</editforminitcodesource>
  <editforminitfilepath></editforminitfilepath>
  <editforminitcode><![CDATA[# -*- coding: utf-8 -*-
"""
QGIS forms can have a Python function that is called when the form is
opened.

Use this function to add extra logic to your forms.

Enter the name of the function in the "Python Init function"
field.
An example follows:
"""
from qgis.PyQt.QtWidgets import QWidget

def my_form_open(dialog, layer, feature):
	geom = feature.geometry()
	control = dialog.findChild(QWidget, "MyLineEdit")
]]></editforminitcode>
  <featformsuppress>0</featformsuppress>
  <editorlayout>generatedlayout</editorlayout>
  <editable>
    <field name="amenity" editable="1"/>
    <field name="fid" editable="1"/>
    <field name="hstore_to_json" editable="1"/>
    <field name="name" editable="1"/>
    <field name="osm_id" editable="1"/>
  </editable>
  <labelOnTop>
    <field labelOnTop="0" name="amenity"/>
    <field labelOnTop="0" name="fid"/>
    <field labelOnTop="0" name="hstore_to_json"/>
    <field labelOnTop="0" name="name"/>
    <field labelOnTop="0" name="osm_id"/>
  </labelOnTop>
  <dataDefinedFieldProperties/>
  <widgets/>
  <previewExpression>fid</previewExpression>
  <mapTip></mapTip>
  <layerGeometryType>0</layerGeometryType>
</qgis>
