<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis simplifyMaxScale="1" simplifyDrawingTol="1" simplifyLocal="1" minScale="100000000" labelsEnabled="0" version="3.14.1-Pi" simplifyAlgorithm="0" hasScaleBasedVisibilityFlag="0" simplifyDrawingHints="0" maxScale="0" styleCategories="AllStyleCategories" readOnly="0">
  <flags>
    <Identifiable>1</Identifiable>
    <Removable>1</Removable>
    <Searchable>1</Searchable>
  </flags>
  <temporal startField="" startExpression="" accumulate="0" endField="" endExpression="" fixedDuration="0" durationUnit="min" durationField="" mode="0" enabled="0">
    <fixedRange>
      <start></start>
      <end></end>
    </fixedRange>
  </temporal>
  <renderer-v2 toleranceUnitScale="3x:0,0,0,0,0,0" toleranceUnit="MM" type="pointCluster" tolerance="20" enableorderby="0" forceraster="0">
    <renderer-v2 type="singleSymbol" enableorderby="0" forceraster="0" symbollevels="0">
      <symbols>
        <symbol type="marker" clip_to_extent="1" alpha="1" name="0" force_rhr="0">
          <layer class="SvgMarker" pass="0" locked="0" enabled="1">
            <prop k="angle" v="0"/>
            <prop k="color" v="231,113,72,255"/>
            <prop k="fixedAspectRatio" v="0"/>
            <prop k="horizontal_anchor_point" v="1"/>
            <prop k="name" v="base64:PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIGlkPSJteVN2ZyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+Cgk8aW1hZ2UgaGVpZ2h0PSIxNjAiIHdpZHRoPSIxNjAiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBS0FBQUFDZ0NBWUFBQUNMejJjdEFBQUFDWEJJV1hNQUFBN0VBQUFPeEFHVkt3NGJBQUFmdkVsRVFWUjRuTzJkVzJ3Y1dYcmZmMTkxczNrUnlkVlFYSzV1TTh1WjFXaldXb2tpTmZJQ0hqdklPSXRkYVl6cytvSzFuYldUSnlPdzgyRGtKWUJoSUVHd2VVZ1F3RUZnR0lIanpXVUFHekhzT0k0VGJ6eWsxbnVSSjluMXdpdU5OQ05aSTJtMXM5b1pEYVhsVUJTSDVEU2J6ZTc2OG5CT1hicTd1cnVhZlN0UzlRZklxdjdYcWFwVHAwNTkzL21mcTZncWp4WCs4c3hoZ0dLWkV3b25BRnpLSHdOQVpVU1FFUnR5Q2tCaEJQTUhNR20zSXlJMm5Lc3VJcWhxWGtUeXFxQ09MZ3NDcW5tUURSRUFYVllVa0R4b0FjUVYxV3YyZWplR0JySTNVT0RUbDlaRXhGRlYxOXNDN0ZYTzZkQnJUWkZpUjVCR0ZqQ2NjM2NOL3ZMTWtFSU9vRmpTa3dBS2s0aXhhTUFuN0hZU3hGbzUzWS9aeVFsazdmRlJlMjRXZXowQ1M1Z1ZrWnc5eDFWQW9BUVVBVlRJRzJPblJVRks1aFROMitzVk1XRkJXUkp6OEFHd1pLLzl0d2lPbW1OTG9BeGxzemNSUUNuSlp5NjdTYk5pN1hCZVlrZGkxMlUrZ3h3Mjg0Qiswbktmd0xwYmtCY0FWRUhzMnhmTWpwb2ZsUWlGOHltdE9PeUlnQ3BaRVlaVUFXWGNjSUx4eFBZdUVselB2NFlBcXE2cWxrUUVoSzhDaUhBRHVHWWo5RmJvOXNVVzB5UFJTRjF3aXI2aW9RdE9PZ3J6YzJlQU13Q0kvQXFBcWg0VmthUGhjS3FLVkpteFRuSGVmbmhyb3RONUR2UU9jQnRBSFAxZEc1M2JRK2RldjVNMDF4cVhhK2lDZHhtc05hLzJvZDNtcE02Mkc5emV3NjZ4Z0pzWFpxZEFqWkFveTRzQWlEd3I4QXlBd3F6aEdCZGtQSHp1SHJLQUs4Q0tqY1lsRXdIZUFyNEhvQm0rcWlpQ3JJMmN1N3FXTkdzWHhlMG1DemdGWW9TRXlLOERDRXdpTW1IM0FWdTRyekVhZThNQ3FzcUVDQk0yVHg2ejlZdjNnTGR0Z0p0aUZNNDlZQzBpNG9uRExoTWhSbUtpV2lsRmE4TDBrdE9JYmUrNGl0aUpvRkd5UGNGSXBBc3V6SitaQnA0Q1VQUzNMWDFRUkE2R3czWFR0Y2JsZXVtQ1crQnVBN2RSeUdUTHYybnJlcFlHejExYlRwb0wzbVVXTU1WZVEvOHQ0UHl6anFLT0lHekt2czhKZ2lySEJYa09RTkh6TnVRb0lxUGhVMFVWcmJKT3ZlYkVxOUVPYjZHdm5LcXVBTXNBZ3FuWUJ2NFd1SzdBOE1iVi8rYy95eThFRFE2UHBRaXhtYyt4NnUxbk1TNWxCcGdCZ2xZSzFhaEdpcjV6M241NFM1ODVZRUpFSmxRVlJZN1pGTHlvc044ZTl6Tmd2NUc2NEJSOVJkOWM4TmJYWmt6OTNiYnpTOEFYekxkcnExa2lrQVRCRWNVbFZJUTA1QVJlTmE2YlB4bktsZjg3QUorNnRwU0trQlNQSFhwcUFRdnpjd2RScG95eDAzOWtvekNMYmNWUVpES3FYR01qMm5mQkVjVWxVWVRFNE40MjZjMVY0REtBWk9UMzdlT3REcCs3MHJOV2xONktFR1VLT0dseW1QeWFaWE5nK3RZMWFsTklndUNJNHBJb1FtSndUNWtXRXlhQVQ2b3FvbHdNUFZuUFdsRlNGNXlpcitpZUM1NS9OaHVxMy9zdnRqcGxCbVNtMVMvWVJyVHY3amFLMjZVdU9JSVRGMERSaXdKZlUyRDRwU3YvZXRlNllGdXY1MitEQXlGVjZlMDM0MnlDVmJ2Q1JIQmluekcwQlhZZnAwRitCR01BcWpPTGlEZ0FuZVE2YmdHTDgyZW1BRnpjazhCSis1Sit4UjQrQ0RLVldzRGtjU2JOQmRDNytFTUE1R1d6MVp0RHVlMmJBSHpxK2tiU0xlQVU0SUw4WFJVK2IxL1RpZkREcGhZd2VaeDRIREt0NkxRWlZ1cVBQL2t6a0h1Z3JvamtPMmtCdTVFQlhheTQ4VjZTRWIxU3NhVUZEcEpoN2FJNHFmNWdRcFcvdTUvem45c0JZOEdxTTFEaUxHQlo5SXQyOTRRZ0o3b2tjVkwwQkhyZWVDMFozeXJtbmdZWWhOL281QjI2SWtMOGIyY243aloxd2NualFpblFhV0hTRVJHeU5UOTNER1Fhd0JXL0ErbVVJSk9kcUVpRlpMamJLRzZ2aUpBbTNEMFEwM29pN3EvYWw3TTA4dExyYlhkdzdaQUZsR25nMHdEU3J1QklMV0FTdWFPS0hyVlM1WVJuSGxSMUtTRWlKQ2l3dGlzNFVoR1NjTTVQQy9HdG1RMjNJd3ZZbGdzdXpwLzVQSUFMdjRqd2VhaDBuenR4dDZrTFRqb25CWE5BLzZ1VDVUOEpNUERwSzFjVG80SUYybk8zcVF0T05oZXlDcjR0YkVPWXRHd0J0eStjR2NWTy9sTjIrZmVHMVpPSWVETlJwUllROWpEbnovYjFiWVJ2QXd3Tlp2NmxmV0VsK1h1WFM5MjJnS1BnVDNYMk16YVcvblZTQzVnd2k5VjVMbXVyWm1aQW53RnhFZjZ0U1F2eXFscnNoUWd4Ri9OL0JuVkZxUWhKbUdqb0ZtZjJYQVZRSEFRWERTeWNEZGQ1QzFoMitUbmduNWlMTVdUdVgyTWpVdXgxcUk0ak1pNnFGQXJ1NzFqMlQ0RC8yY3BsV3M2QTFUWGpRTVd2MUFVbnptWDJVcGgwcng1d2MvN01qRTN4cHduS2dEWkNRU2JjS3k1NDROaXYyZ2NLMTMxUnkzVkpoT2oyT2xwYUI4Qzk5K2ZKYzhFVm5CR2dvSmVMQ3ljUGJzMmZKSGYrMm9PT3VtQVZNOFd0bU9uUUtqTGdYclNBV1M4RDlnbnU1aUs2ZVI4Qml1OStPVG5XTHBvN29TaWlmQXlUTnh3UldZcGpBV09QQ1JFMWYxSFE2bjNQZXRsdHU1d3A2R3JGNzI1emZZY1N5RHExeFo3UU5wR2MrRjN4M0todVcxRmNFd3NvZmdZVlp2K04zZDFmYWZQMkpvcC84NDhCY0NaZndQbndqNXY5c2VOZHYyL3AzVDlIRU1xcmI2Q3IxK2phbUoydVFEN2prbnZHL2pnWDU0eDBWRnlLdnFLaEJTeGNPSDBRTUhQeUNkNWFHa05hNWFTRXdHMEptTEtVTFZoTHFHQXRBeDlDY2s4WWQvN0VLUUw1WXJmNWQ0M3J6UytpaGZ2QnVmYktVbU1OdXNkcGZ0RnNpNnRRM3FvSXBhSHlxYmNmM3BySDNTRzN2V0hTc3JpS2JqMzA0MlZTS05qaXAxcVNPQ2FBWXdvVUZ1YW04L096VG1GaGJsWE5iRjFlZXJuaGJlTjFRbHc1S01LTXlVdXlIOEF1ZlZFWmppb1ZES2d0MFBzVnRtQXkzNzVwQUxKSFBsdHpQM2ZGVEh2c0FscTRYNkZTZTYyQ3RYRGZjTnVyNEZabXdMQTQ4dmFydHp2bXR0ZU1JaTZ1UXZGaG9EenRoK3B0RThtcDdrZGt2ekUrVE5zbmRFVmt0WjRLVGwxd2lyNGkwZ0xxL0xHY0lBajdYZ1IrUGFMQ29pVmtwbDQwMjBQbnlCeXFYeloxSnM0QzRLNWV3MzMvR2dJVTMveXR0dTdkZFpRMkFDZy92SVM3Y2drRjNJZmZNZGJNeVNHWlFWQWwrL1EvTk9IM2ZSUm4zOVA5aTIrdm9IelI3cjBNL0g2OVlLa0ZUTkZYUkZyQW9vNSswcXFKWjRIOXhyMTd2cjYybnF5WkNIRStkQW9FWkhDS09KQ2hLUnhPbVgwTnJ0eExFUkordG1xRVJVanAvZ0lDdUd1M2NOZHVBK0NNR2d1bmhTVjAwNGlaOHVJQ0t1QThjZGFXbDRCOUg2MFZJZDROaFE0TGhGNXpPbTJmNUdPRmhabG50aTZjZGdiUHZYNDduZ2dSenRxVWVBYU0rUEFiS2lKZVNqTVI0anh4eWtScitDT1J0NnU1L2RCSGtDRVROdHpycEI4OVg2SnE0Y0lDd2wxY3FGRHVxSktaL0RFUXdkMTZpTHRwdUhKKzBTYWk0QXlaWlllZDBlbUs2L250cXZhTERsNXRBZ1ZIYys0cDg3ejZES3JIYkFhNm5ZcVFGSWxDcEFWMGtTL1kzYU1kYWZNWVBtSys1dXhvczVDN0FycjFFQzJhT2pwMzVUSVZIUXFhbmZ2b0RVcGJ5NkJLem9xelBRMlZXU1didFlaeW9mcHdhZ0ZUOUJXQkJYemxaRTY5bGNGbHdGdnVkTnlVeVlPUzBFNUVpSDd3ZlhOdzVFbGtZS3hwcFB5dVNKcE1FWUtXUXEwanB1RHRqQnhHaGc4YmFzQ3VsWmdackNtb28yWC8zTWhXbEQwalFydzhvUk9DSEFPRnkyZXpldWw1bDh0bm5Wb1JvdVJFekdBakVRNVhwcmlFZ3JVdVF2amdydWtta1IyRGtTZHBpdEk2Yk40SE5KRWlSTjF5cUhYRUZMeGw2TENweDFTRmdWSHpFcHhjclpEUUVyakZDaVc5UjBXSTJUZUxTWTc0T1VRMWk0aHJQN2hVaEtUb0wzd0xXTWprVG9qWTFjZWpQdnMyVUh6enR4QzhyazB2SUVEbW83OVVFODYwQlF1bCt3dTQ5eGRJNmxnVForUXdqSGp1ZGhRUTNQZXY0VDY2VEdSUDV4QmsrQWpPL2xPZFR1TGtRaldIU0E1VkN1K1ZmOEt5ZDdFejlhY1dNRVZmRWE2R21WRFZId0h2SS9aOGVhWHMySWtJd1hLYWZ4djNQZk5UaTJ1VlZrSVYxL1pBMGZVNzRHNmJheVZRaElUTGI1bUQ1MUFSZE8wVzd2cHRFNzVjckNtVXk4Z2hBSnp4NHpnVHoxZGNaeStMa0FwTzlaaDl1alZWdlFzVklrU25FUGs0aEwyR1ZHMTNLRUlzNStidklmbDdLRkJlL2xaa0ZxL2hFaWhDd2kwaG1jTm1NYzhTaW54dzE1eFIzcW9wbE12UUlSREJHVDlPNXNCWkUrNXhFQ0hoTkRCTnV3QjMwNWFRRklsQWxtOSszRFpQREQySDhpSlFVM0J1QmQ2NENXZmZ0Ti9XNmE1Y05nZUhEK040ZFdVTml1SHUxa093dllHZDhlT1dXNFl0MDdHMnZIVFJSSFA0c0JFRTRMdTFwc01vWTNKZW5KMmhRNDJmMTNZaHkwMmNoVS84YzN2dUpYdlFkTWRTQldmOHVZYlhxYjN1OHpnSGJMV09aeTFEeFJVZ01aelhHdVMzaDllQksrN1BXUFArRHZCMVNFVklpajRqVzlnWStyalpsVWxzbWRCMHZXcEJoR1JISURNTVFNWjJ0WmZCQThpZzZmVlJYcndBQXM3NGp3U1dxaEVlWGNIZFhBUU5MSXlVOGxEYUJNQmRmY1BHZnRqL0tyMXdIYk9BdGh1VjM2cFJFYXp4bUJBWk9td1NTaklnR1pObWNjZU9lRkh5ckx0Q0VpMmdsdkpRTnUrRDlkdUFRQ2JYVUlTSU1ta095WWUzTHB5YUtINWxocXk2amxFbW9wTmloMkVHcnlXZUNDRXpBb01IQU1nZS9aemhuQnc0ZytabEZoOGlLSko3SXNnb0RhQ2JpK0NhSlNxaXdwZSsvM0p3RDVzUjRseTNGVGpXQmN0QWJRZUtwbU5DUmc3WG5GTXZmQTFuRTlnWk9kenhaK29rZE9zaEZCK2FqMlpnekdRMFo3Q1pjSnF3Sm13U21JVFVCYWZvTTdJT3pBR295c0ZhMDlic2JHTWRNa2YrUHRtbmZ0NXl0WjBOTXJZQUx0WktOb09XaStqMmV0M2pBMmYrSFFEbHQvOEhwWGYrMU95LysyVnpqN0hqTFJmNFU3UU9kL21iSnMxRElpUjJselRrWUxtY25RVk5MV0NLL2lLcm1EbitRTE9xTmRYSm9hMUIrSmN6WmkzYjhPR2F6cVlWaFZUSjJZSmpKbDZzSkdQS2QrQ1hCUlVIYnpJdnNWWldoby80MVQ3bGxlK1lPRzJ2bWQ0MEZaR2hZZTI1VjlZS2l3dXZ3QjNXQmY2cFRVUUlSSWlMdUZ6NEZVQmx1UHdpV2xoc1VHdmZKUzQ3WnJyUktUQjh5TWJWeHMrSWl0WmFSMVJ6bUpsMm5TemlaVURKMWhjZjBTTEVjM1V5ZkFTcFZvdmxQQlJYekhOa0J1MEo4U2JqRWlkamhqT0MzKzFKcktBQi9Idko4R0ZrM0loNFhmcUdDYjY5N2crVkRDTGRXUEg2U2pzY3hoY0dFZkZySmtMcUhJdkZlUWtzdGZmU3dxSnhkejFXdkRKOENJYVBBT3JYdTNyUkVvVmd6c2k0clNQa1JIVVVrZFFGcCtndnNxcnF6ZjB5S2tSODdnMlErY2hQbWxPSGc5WUNyMEhlM2ZnKytzRmRFKzdBV2ZOaEQ5ZXZuZ2hEaG9NcWlQSVBMd0xocnl4VTE3aHZtbXpHdU9xdEgveWg0ZktMbEpmK3F2SjZUZHA5K3owWFlGeTREeTlSK3Q2WGVtNEJuU2VDVnBuT1ZBM0pLQ0tISUsyR1NkRm5aTEZyZnFEa0Fxa1JzeVhFYXlmTmp2bUZaZDM0UG9vWnFLM3J0MEFoOC9Rdm01eWUyeDh2VnJrRGlCVVhmanV5dTRWcnk0TytCUndZUSszb0FiOGJWWFlFc2EweTRna1p2eWdjUmkyWGRCSEN3SmpwVmROckRCN3dSV1lRVnh1L25ZZ1FOS2MyM3dVWkVIS0JsNG9wUWlKcS9EMjNxK3UzY0ZmZlFCR3krNTQyNThRY2xpbURrNllSSDBXdGE5WHR0UnB4SVFOai9pQW52OXRYWnRodkFoVHZmakdiNHBJdVFpUTdhb283dlJZaGd4UDJZdytQWTdHSGR5SkNoQnd3cW1rOVlJcCtJeXZJUVFCRk96cHFYTWFlSTdQdmFSUndobHR6R3pJd1p0c1hJVHY5eXdDVTdsK2dmUDlDMDNPZEQvKzRQL2Rna3R0U2Q0TE0wWjhtYy9Tbit4Mk5Ea0JHZ1lOQ1dnMlRvcy9Jb3VxTkJjNTViait1Q0trdVNGdlNsQnRHbnZRbkdHb0wrejVxN2pHd3YyYThSc1hZV2s4MHJOM0NycWFIODlCMERGV2hab2IvTUpkOTl0ZHFyaGRYaExocnR3eTN0V3g3aDVnd05jV3BUTTUwU1JxYU11bFMwYW9RVDRSNHdxN1h2YkhJQlYzclpPeDQyeUlFMVN5MkJTNnIzbUIweUxZcVFxSUswbjdyd3I0bk8rSUN2Y2tjM1lFUDFkYmxoVnNKdkgwN09BaWc3SVZyVmc5b00rQk9SSWk3Zmd0QlFxcS96dHZNam9PQTg2RlRPRS9NVU5tcUVFK0U2UG90dndOQTVEMjZ4TW5ZY3pqano2RW9XYS8xcXcwUm9rYjhEa0ZhRDVpaXo4aUtlQ3RnTTZScTU0YnBnQXZ1Tkl6TGJPNkNZZWRETU9PNllOZE94d3RRdXZNbDM1MkgzWG85enYzaFJaOGIvSWsvTWltY080QU1IbWp1Z2pjWEthOWNibnFQVG5NWlFBZkdBTzFJUFNCQ0ZzUzRZRUpXTUk0THJtRHJ1T0NhZDkwQjJIbEdLcmtJbHhsK1dBOXh1V2dYSFBLSFFXU0MrNG45S0VOYkwwZ3pMaWpPQkprczhMMjFjUkxQbWJWd2owNXc0UWV2cVFkRWNGdE5BejlUbXJiZ05YdGtISldPV0VEcGhnVkVxYzdaVVJiTDJmY1U0azJBWkR2QTJsWE5LczZONHFJdG9KZGNBZHpDRDNFZm1YRXBZWXZScW9WeDM3OWx5b1ZqeDVIQlNadUdOczBqTENCRGgreVltc0RhMTc2anpuTXlkaHdaUG9RcXRSWVFiVGtOVUMwSXJIckN3MnRlR0FyZXgrNjFnREx5SkprUHYyRDJXMXhhSzdZRkxDemh2bjhOYU04Q0dnRURtanRRZTY4SUMraU1ISVk0ZzdvNkRCazJVODlKS0Q1dFdVQ2hBS3g2YWdTdytWM0R2M2FuQmZSaTc4WFZQeGFqS1M2dUJRd3NWWHNXTUVoTHJicHVIUXZZalM4N0J2eWlxVWFVQVhka0FmMHJrMFZaQWhBWVVyUFVVbHR3Vnk2QlNFVVhyZjdEQWFwZlhoUVhFMXFFYmM5eDdQeGpjOWR2bWtKNlRFc3RFMmZKSHZqUjlqczh0TW0xQzBFMkVCNWcxQWl1ZjZCRExoamQ4YXR0Rk9sWUxqZ2N2OENQS1RVWkpZS0w2NExEY2ZGOXhBNWNzRU9WTzJzbVFpcmkxRzh1U0l0V1hYQTRPYlBnbHdHTEhXMEpvYk9JNjRJMS93N2w5NzVsT050S1Vma0UxSEM1cXRtcUtxNFg1WUpEY1JGa3h5N1lxOEFOa3E2eEMzWWZYc0o5ZEJsdnNVanhwWlIwbFdQb2tEOUlYaWFlYjlzRkMxb0VOaFRJb3JKaER4VDNnZ1YwOCs4ZytYY3F3a1hZdjBydTFCZnJYaTlKRnRCOWRKblNuZC9yc1FhMjgrN1lWcTNzQVcvOFRKQVdMVnRBS0dJTlh6WlVVcWZWVVhGSnRJQlNGZDlXdUtSYlFMVjJxZGNWMFJWUDNnRVJFczVaV1VVZjJLdFAweUxjOS83S0pJNlRRLzNleC9IZ3JRd2VOdm5aSTUrTGQxODdPNWFXdDlDcXBWUlQ3QWJJaGlQY2g2cUZhbHAyd1JWY2F5NDQzRVRqYlp1RmoycmlxN2d2UkY0ckxwZDBGN3hYV2tMQzZaWUY4cFpyV1lTVUZtMEhVY21BWXdlZHgzVEJ1cjBHZm1FM0tQVFdEUjl5ZSs3N053M25GdjF4dzg3Qno1aW81UFlqQTVWalQ4SXVvQ0dYY0Jjc1k4ZHhqbnpXajAvZ082U3JuTE52Mmw5b3ZETXVXSXVpdGd3b0l1L2JkQzBHU1J6UEFyb1BhbnNvT3hQUHg3S0FsRFlxZXY0MHE3c09XeDJ2dXhYbExUOERlajJuWmQ4MFlsZXJiQlZKdDRETytIT3hGdnJwT0xLanlNQTRrV05DZG1JQmxhTDRJc1Npc253Znp3SkdjbkZGaUdkdFF0dUd3Y01pSkxTUktpNzZWcld0TTAyNUJGckFrUHJEa2xSOHhkM2lQTHVvMGlFTEdDQXJVcjVxZHAxVGdRcmVPZHoxVzREZ1RQNVkyOWVxQjIvYTNuRE9OL2NGTm00MStVTGljVjUzS3pud293M24rK3NwaGsxOTNPNXRDZkcvb0hzNUxYMGIyaFFoMFp4bkw1cjVWTEVmVzdCdEdEems5aXI4ZGVQSTdKenpYRTFFd0xRbHBFMFhES2ppaU9CbWNjeDZEWlJaVnE4Y3FKcmJxUXNXdDJqOWZJbUdhTU1GdTNhc1J6ZmhyWFR1Wm02ZzN1S0NtKzhhYmkzb2V0K1dDOTVhTnRkN2RNVWNWM0RYYmdKaXFwZzJGM3Z1YmVOeTdxTXJmdnpqdW1BVmxteXFQUlRUQzh2TkRoNXgzd0lvdkoxNXp6YVJnSGo5QW5kZ0FkMml6U3h1Uktqd0NUdTNnTzRqTTF1QzkzbUUwWEhPTFNLRkg1cDlyd3ZXNXFJZmwzWXNvRzQ5UkFEMzBWVTBmeSs0dHQxNjkwc2lkR3ZackpzTUVOc0N5Z01GUkZqaHBldHJZT1lIREkwTEVSZThndThPTFNERXNtaHRpUkQvWHJXeDZUUm5vbXEvMi9EOU8yQUJvVExUUjFWRjlicmROM2I3Y0RqdThTMWd6UWVlbFJQWHpaaVFINXk1U2JDaTlTL1VwTVRqaXEySDRMbEtuMnhzcldOamV3TUVkSHNEOTRNZlZMMjQrNlpzNVlraXU1OGtyczczV2hlT3NtQ3o3UjJmRXhGSFJCd3F4b1lJSXRWYld3c2Uyby9pRVB1bE5LM1lzMUkrdEcwWTNIUEJvVDhWK3M2RlhZenZXbE11a292eXFGbTFLMWR2enM4dEM5d0J6N3RJNUFsUm1UN01tWGNqZThZRk4rUGFkc0dQRWFmd3BrMjNaUzh0czliNnNUbC9laFhrdTBFQ203M0tiZFN2V3E0VkM3aWphaGovUHVHNDlvZHJSNFE4YnB5cWU5Tit1bjRHZEZUVlZWVVhGYitJbzZxb1ZtL05INkg5S0E2MUkrRmpXY0RLYmNQZ25nVU0vWW5TZDg1KzJSWGJsS3ZERVh5d0h2eUs2S0ZCZlF1Yk16ZlRIazRwT2dRMTlYMGJyaWdqNTEvL2R2Vngzd1c3WHp1TldLRlg2dzVURjF5UFMxMXdFdzV2UC9yOStpS0VyOC82M2FSVnNTdjFNUTZNQnBlcHZHZ1VKNUNLRUVnNXZJeW9xOERiMUlGdkFUSE5jRVdBL0N1ejl5eDNWSVRSMUFLbUZuQ25ITENDclYySmdpOUNLdjdDaWEya0lpUVZJVHZtUWk4d0VwRkxGem5DZ3YyeVgxUnZHdnBXb2NWZ1V2R1lrNU9uMkh0UTVBN0tmTDNqZmt0SStBOENsN3JqbGhDa2JxNzNMcHkyaE94OWpuQm1pa0FnUWtJb3pNLytYM3ZtWVVSbkFGVFo3MTJyT2wrRk9mTnVCQzNsY1l1bXZ0R0pzb0NwQ05uam5IckM0emJJZGVwTWhob1dJVDcwTHo3MktpSVUyRGVEeXFvS2lJZy8waWNxUTRjNVJkRnkzdTl1aEIzUVVubENLa0wyTWlmS1hkdUw1dGJRUzY5ZHB3NGlSVWpnUnMyVkJWb1hJWGlac281bFMwWEludWJNKzI5c1ZLQ09DT0dsN3hZRllHSHU2NkFyTml1OTNQUnFPNEFaV2xsc1dGeE1zZnVnSXI5aHZjTzlSdUVpWGJDSHpmblRqclYvaElQRmNjRm0yK0FyOE1TSERkaTAyakIxd2J1Szg5T0Z4b2dVSVI0S0YyWWYrSmR3elR5Q21EVytSc0xod2pjU01PVzVVaDYybHV0R3dOMTgxNFF1NWFHY3IrdUIzYnp0b3I2OVh1T21VeEdTTEE3VkZSV1dqVUdSZXpZVHJ0RUFEUzJnS2crQUJ3Q0YrYmtsYkxLTHlFaDEyQm9MV041RXQ1YnJpNHZOKzZDZ3BYVW9yZGVQWWVHK3VXWnBQYldBeWVlV2dac0F3K2RmYStoNlBUUzBnQkJrem1DY2FJMGhpcmFBZGx2WEJLdm5kN1hpK2hFQi9ldW1GakRaWEpCTThVdjAwU0xFUjVBNU16TDNMd0JjK0FJeHhveTQ3MzBUZC9sYm9FcnBuZjl0TW1ONUM5R2l5V3liOTRQY2JMZUZpejlsTXErM05KU0MrK2c3OW9MYnNSOHFSYStocmhoVCtGWEgwZi9ReXBtUkxTSDFXa2M4eEIwVDRtMjlhU1U4RDlvd1hNV052SC9Xa3FZdElZbmtxQ3lpdExUNlZoTVhIS0E0UDNmVDd0NVJyNVpiZWNxN2ZZMExEclZ3bUFITUFsb0N0U3U0UmJTRTZMWXRDN3BsMDQ2c2dHdUhLcnZsMUFVbmxGTzRLcVl2NlhmQkY2dXgwRkNFVk9FMndPYjg3UGZFNjk4bDhwUjNNUHdOZUxNbytiTXBGVmNJankzMXFsUnF3cFUyekg1cEEzY3JxTkEyMTZUR1FxWWlKQm1jZ0oycVF1N2t6bDFwS1FOR2Q4ZHE4QmMrdVZsM0xMOWJWcHRjVWxvOTBwYVFhSzRkTkJFaHRSQngvaGZ3S29DcS9qV0F3Z2hWZFlNcDlqcDBSWlFWZ0tHQndtOWFzdERnaEVpMDRvTE5IZWJucUNwMEFwWHVzY2ExdHNrWnZ2L3VOb3A3WEYxd3B4QmJoSGpZdXZCOEFkUE5HbHo5SXh1alQ2cHkxa2JPaWVwbTFRNW5yaXZRWjhFUnhUMXVJa1FoYncrOUptQVhaUEV0WDVNcDBXclJzZ1cwTnlzQWZQREt6SDhERUp3aEVUbGpqenVwQmR6RG5IcHppc3RyNHNnZkFBNmZldE9iWjd4bHRDeEN3bjllb2JRQ3FRalowMXpWNjI3VmVOVkFPckVBWFdGaGJoYVlCVUI1dWJxRnc5eXBEYzRjb09ieEU4SHRmUmVNVWhMclhwWHlUNnBKZ1h2REw3MGVxNzIzRVhiaWdtdXdPVCtMLzBMRVNVWElYdVA4cHd3OUw1MUJ5eUlrQ29XRnVRY2dWd0ZVOVZXVGIzUmFrS2RTRWJJSE9MZ0orb1o1WG1KMXM0cUxqbGhBVFBQTEVzRG0vT3hGeTcybzZGT3BCZHo5SE1JTkIvMVRGSElkY0x0aGRNUUNobEZZbUhNQTF4VGpXcmQycVFWTUlBZkJsOVpoZEVTRTFGeFV4TW0vTXZkNTRCY0JCUDI1VklUc1FrNzBYOWw4OTQyaDgxY3UwZ1YweWdWWFFGWGR6Zmt6QVJIVjhZRFVCZThhanU2aDR5NFlmQXQ0QS9oakFKUVIrOEtPQ1hMTTlJaEpYWENTT0lXU2ZTODNFSzdiL1BjTis0SFZuZDJxWFhUTkFvcklEVlc5TGlMTzVsL01UcG12U2w1UzVSblRJVFYraTRuaCsyL3Rvcmk5WWdGRktkbGZWNEUvRmxFR3oxMjlTSmZSTlF0b002R2pxdTVXeUIzN2VTcGs1VklMbUF6T2Z6N3ZRQS9RTlJFU3pvQWVsNStmbXhhWU51VmIvc3dHSDBMSXBTS2tMOXlhd3FvQWpteC8xajdRVXU3OHRRZjBDTjEwd1g0bTlMakNnckdFZ1JGVVI4UzZzZFFGOTBGY21OaDNVMlEwUTA5Y3NNZmw1K2RXQmU3YXgvN1BObi9OZ3N5QWdqS1p1dUR1Y3dxTGFzWndYQkxVRGp2MHgzSnMwRVAwMUFLS3lLcXFyb2lJVTVpZitUMFVWSngvSUhBWUJJVEoxQUwyZ0ZOZjFYNXR5Tm4rUXdET1hWK2hEK2lwQmF3UUpndW5mVi9zbDZicUNCTklocldMNG5hcEJYUUlMMzNYUi9SVWhFUnlYMzQraXgyYlVzaTQvOHhjUWY4T3lBdldWZHV4SnJVWklSbGNzak9naWhyTHBseDBWTDZoQWtQRFYvNmoveWd2Tmx2WXVidm90UXV1NGZnL1o2dk94WGU5QXVDTGsvNjcyeWh1TjdoZ0grR01hbjcyM1FyMnpRWDczSmVmZHduR0VyeHFWTEV1QXE4Qm9QSTVlMndTZExMaVBxa0xydVRFejFDTGlyZldpeTdZZUg0WDVYWW9vL1k5ODBFQ0xLQ0lvS29seTcycXF1N21LNmV2SW95YXp6Unp6RjcxQkNJVkdUQzFnSldjK0V0c3lEM0VEQllmbHRKdjI4QUZ6bDNmOGRpTmJxSC9GakNxdXVhVkdiOHV1Z0xhTzhzV2wwdVdCUlJFdGRiMUpoajlGeUV4T0lETnI1eVpGc3hjTk9yeU80YlZnNkpNVmQyZHgwcUVtRldJN3BpWWxQK3BqZFRLNFBuWC9TVlJrNHdrdU9DbUhNRG1oYm1JTzFuL0U3NDNqNWtMam96aDdrRWlYWEFkQzdnYVN1VGZOUnQ5RmpCbFJPV2tQVFlCN0NlRVBlQ0NTL2JRaWdxcktJam9KWE4vN21CbXBRSnZ3Z0JJWEZtdkhuYU5CVlRWVlJIeEJzSjhDV0J6NGZRTTZLdzU3b3lBTllpaE5VMWc5MXRBVVlvMnl5OEJiNWxIZFAvQVJ1Zk80TG5YNnk0R21IVHNHZ3NJSm5PR2Z4Y3V6T0w1WUMrTEtDQTlGQ3U5RWlIKzA5VXFqSTRia0Y1aTE0aVEyUGpLNlJ5MlphWG95bmtBVitVNDhDeUFJajlsUTQ0S1dyV0dXTDlFaUs1ZzNhZkNLNWhNOWFhVE1YTXlEaDdkZnRYZXpPWEU5YjYyWEhRYXU4a0Z1OVZ4amVRdXpOU0pWVVF4dlFNVFhuYkNCVmNoc3AxV284UHVldXhxRnh6SmZlVjB1R1hGbTFaNENmU0dqZDJiOXN3RDRKVVZkUUpBbEN5UXMrZDQ4eDNtVlB4NUZMMXlaZzRrYS9ZOVYwd0pURmtOTzRHUFFGSHRJdUFpa2cvQ2FWRk1UdlNxU2xhQWgzYi9EaVlEZWxiUkJWeWIrUkxSZXRGSkNGMG9RL1RWQXNia2lndHpVOEJCYzl5ZEJuQ1ZFZkRYUUprQ1VCaERHQUlRbUxUY2lLZ05KLzRIVU1EMnBSTjFsd0ZIWVVPUmRRQVJ4OHRzZVVIeklDQnlFNU9wVmdmUFhkNFY5WGFkeHQ2emdERzU3UXRud0xjb1FYbk9EeDhFcmJtV2hJTDZydEVmUnVBZFZMZSswNnpnZDdXSWFCZi9INlhWWTFYZkxiMDZBQUFBQUVsRlRrU3VRbUNDIj48L2ltYWdlPgo8L3N2Zz4K"/>
            <prop k="offset" v="0,0"/>
            <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="offset_unit" v="MM"/>
            <prop k="outline_color" v="35,35,35,255"/>
            <prop k="outline_width" v="0"/>
            <prop k="outline_width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="outline_width_unit" v="MM"/>
            <prop k="scale_method" v="diameter"/>
            <prop k="size" v="40"/>
            <prop k="size_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="size_unit" v="Pixel"/>
            <prop k="vertical_anchor_point" v="1"/>
            <data_defined_properties>
              <Option type="Map">
                <Option type="QString" value="" name="name"/>
                <Option name="properties"/>
                <Option type="QString" value="collection" name="type"/>
              </Option>
            </data_defined_properties>
          </layer>
        </symbol>
      </symbols>
      <rotation/>
      <sizescale/>
    </renderer-v2>
    <symbol type="marker" clip_to_extent="1" alpha="1" name="centerSymbol" force_rhr="0">
      <layer class="SvgMarker" pass="0" locked="0" enabled="1">
        <prop k="angle" v="0"/>
        <prop k="color" v="245,75,80,255"/>
        <prop k="fixedAspectRatio" v="0"/>
        <prop k="horizontal_anchor_point" v="1"/>
        <prop k="name" v="base64:PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIGlkPSJteVN2ZyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+Cgk8aW1hZ2UgaGVpZ2h0PSIxNjAiIHdpZHRoPSIxNjAiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBS0FBQUFDZ0NBWUFBQUNMejJjdEFBQUFDWEJJV1hNQUFBN0VBQUFPeEFHVkt3NGJBQUFmdkVsRVFWUjRuTzJkVzJ3Y1dYcmZmMTkxczNrUnlkVlFYSzV1TTh1WjFXaldXb2tpTmZJQ0hqdklPSXRkYVl6cytvSzFuYldUSnlPdzgyRGtKWUJoSUVHd2VVZ1F3RUZnR0lIanpXVUFHekhzT0k0VGJ6eWsxbnVSSjluMXdpdU5OQ05aSTJtMXM5b1pEYVhsVUJTSDVEU2J6ZTc2OG5CT1hicTd1cnVhZlN0UzlRZklxdjdYcWFwVHAwNTkzL21mcTZncWp4WCs4c3hoZ0dLWkV3b25BRnpLSHdOQVpVU1FFUnR5Q2tCaEJQTUhNR20zSXlJMm5Lc3VJcWhxWGtUeXFxQ09MZ3NDcW5tUURSRUFYVllVa0R4b0FjUVYxV3YyZWplR0JySTNVT0RUbDlaRXhGRlYxOXNDN0ZYTzZkQnJUWkZpUjVCR0ZqQ2NjM2NOL3ZMTWtFSU9vRmpTa3dBS2s0aXhhTUFuN0hZU3hGbzUzWS9aeVFsazdmRlJlMjRXZXowQ1M1Z1ZrWnc5eDFWQW9BUVVBVlRJRzJPblJVRks1aFROMitzVk1XRkJXUkp6OEFHd1pLLzl0d2lPbW1OTG9BeGxzemNSUUNuSlp5NjdTYk5pN1hCZVlrZGkxMlUrZ3h3Mjg0Qiswbktmd0xwYmtCY0FWRUhzMnhmTWpwb2ZsUWlGOHltdE9PeUlnQ3BaRVlaVUFXWGNjSUx4eFBZdUVselB2NFlBcXE2cWxrUUVoSzhDaUhBRHVHWWo5RmJvOXNVVzB5UFJTRjF3aXI2aW9RdE9PZ3J6YzJlQU13Q0kvQXFBcWg0VmthUGhjS3FLVkpteFRuSGVmbmhyb3RONUR2UU9jQnRBSFAxZEc1M2JRK2RldjVNMDF4cVhhK2lDZHhtc05hLzJvZDNtcE02Mkc5emV3NjZ4Z0pzWFpxZEFqWkFveTRzQWlEd3I4QXlBd3F6aEdCZGtQSHp1SHJLQUs4Q0tqY1lsRXdIZUFyNEhvQm0rcWlpQ3JJMmN1N3FXTkdzWHhlMG1DemdGWW9TRXlLOERDRXdpTW1IM0FWdTRyekVhZThNQ3FzcUVDQk0yVHg2ejlZdjNnTGR0Z0p0aUZNNDlZQzBpNG9uRExoTWhSbUtpV2lsRmE4TDBrdE9JYmUrNGl0aUpvRkd5UGNGSXBBc3V6SitaQnA0Q1VQUzNMWDFRUkE2R3czWFR0Y2JsZXVtQ1crQnVBN2RSeUdUTHYybnJlcFlHejExYlRwb0wzbVVXTU1WZVEvOHQ0UHl6anFLT0lHekt2czhKZ2lySEJYa09RTkh6TnVRb0lxUGhVMFVWcmJKT3ZlYkVxOUVPYjZHdm5LcXVBTXNBZ3FuWUJ2NFd1SzdBOE1iVi8rYy95eThFRFE2UHBRaXhtYyt4NnUxbk1TNWxCcGdCZ2xZSzFhaEdpcjV6M241NFM1ODVZRUpFSmxRVlJZN1pGTHlvc044ZTl6Tmd2NUc2NEJSOVJkOWM4TmJYWmt6OTNiYnpTOEFYekxkcnExa2lrQVRCRWNVbFZJUTA1QVJlTmE2YlB4bktsZjg3QUorNnRwU0trQlNQSFhwcUFRdnpjd2RScG95eDAzOWtvekNMYmNWUVpES3FYR01qMm5mQkVjVWxVWVRFNE40MjZjMVY0REtBWk9UMzdlT3REcCs3MHJOV2xONktFR1VLT0dseW1QeWFaWE5nK3RZMWFsTklndUNJNHBJb1FtSndUNWtXRXlhQVQ2b3FvbHdNUFZuUFdsRlNGNXlpcitpZUM1NS9OaHVxMy9zdnRqcGxCbVNtMVMvWVJyVHY3amFLMjZVdU9JSVRGMERSaXdKZlUyRDRwU3YvZXRlNllGdXY1MitEQXlGVjZlMDM0MnlDVmJ2Q1JIQmluekcwQlhZZnAwRitCR01BcWpPTGlEZ0FuZVE2YmdHTDgyZW1BRnpjazhCSis1Sit4UjQrQ0RLVldzRGtjU2JOQmRDNytFTUE1R1d6MVp0RHVlMmJBSHpxK2tiU0xlQVU0SUw4WFJVK2IxL1RpZkREcGhZd2VaeDRIREt0NkxRWlZ1cVBQL2t6a0h1Z3JvamtPMmtCdTVFQlhheTQ4VjZTRWIxU3NhVUZEcEpoN2FJNHFmNWdRcFcvdTUvem45c0JZOEdxTTFEaUxHQlo5SXQyOTRRZ0o3b2tjVkwwQkhyZWVDMFozeXJtbmdZWWhOL281QjI2SWtMOGIyY243aloxd2NualFpblFhV0hTRVJHeU5UOTNER1Fhd0JXL0ErbVVJSk9kcUVpRlpMamJLRzZ2aUpBbTNEMFEwM29pN3EvYWw3TTA4dExyYlhkdzdaQUZsR25nMHdEU3J1QklMV0FTdWFPS0hyVlM1WVJuSGxSMUtTRWlKQ2l3dGlzNFVoR1NjTTVQQy9HdG1RMjNJd3ZZbGdzdXpwLzVQSUFMdjRqd2VhaDBuenR4dDZrTFRqb25CWE5BLzZ1VDVUOEpNUERwSzFjVG80SUYybk8zcVF0T05oZXlDcjR0YkVPWXRHd0J0eStjR2NWTy9sTjIrZmVHMVpPSWVETlJwUllROWpEbnovYjFiWVJ2QXd3Tlp2NmxmV0VsK1h1WFM5MjJnS1BnVDNYMk16YVcvblZTQzVnd2k5VjVMbXVyWm1aQW53RnhFZjZ0U1F2eXFscnNoUWd4Ri9OL0JuVkZxUWhKbUdqb0ZtZjJYQVZRSEFRWERTeWNEZGQ1QzFoMitUbmduNWlMTVdUdVgyTWpVdXgxcUk0ak1pNnFGQXJ1NzFqMlQ0RC8yY3BsV3M2QTFUWGpRTVd2MUFVbnptWDJVcGgwcng1d2MvN01qRTN4cHduS2dEWkNRU2JjS3k1NDROaXYyZ2NLMTMxUnkzVkpoT2oyT2xwYUI4Qzk5K2ZKYzhFVm5CR2dvSmVMQ3ljUGJzMmZKSGYrMm9PT3VtQVZNOFd0bU9uUUtqTGdYclNBV1M4RDlnbnU1aUs2ZVI4Qml1OStPVG5XTHBvN29TaWlmQXlUTnh3UldZcGpBV09QQ1JFMWYxSFE2bjNQZXRsdHU1d3A2R3JGNzI1emZZY1N5RHExeFo3UU5wR2MrRjN4M0todVcxRmNFd3NvZmdZVlp2K04zZDFmYWZQMkpvcC84NDhCY0NaZndQbndqNXY5c2VOZHYyL3AzVDlIRU1xcmI2Q3IxK2phbUoydVFEN2prbnZHL2pnWDU0eDBWRnlLdnFLaEJTeGNPSDBRTUhQeUNkNWFHa05hNWFTRXdHMEptTEtVTFZoTHFHQXRBeDlDY2s4WWQvN0VLUUw1WXJmNWQ0M3J6UytpaGZ2QnVmYktVbU1OdXNkcGZ0RnNpNnRRM3FvSXBhSHlxYmNmM3BySDNTRzN2V0hTc3JpS2JqMzA0MlZTS05qaXAxcVNPQ2FBWXdvVUZ1YW04L096VG1GaGJsWE5iRjFlZXJuaGJlTjFRbHc1S01LTXlVdXlIOEF1ZlZFWmppb1ZES2d0MFBzVnRtQXkzNzVwQUxKSFBsdHpQM2ZGVEh2c0FscTRYNkZTZTYyQ3RYRGZjTnVyNEZabXdMQTQ4dmFydHp2bXR0ZU1JaTZ1UXZGaG9EenRoK3B0RThtcDdrZGt2ekUrVE5zbmRFVmt0WjRLVGwxd2lyNGkwZ0xxL0xHY0lBajdYZ1IrUGFMQ29pVmtwbDQwMjBQbnlCeXFYeloxSnM0QzRLNWV3MzMvR2dJVTMveXR0dTdkZFpRMkFDZy92SVM3Y2drRjNJZmZNZGJNeVNHWlFWQWwrL1EvTk9IM2ZSUm4zOVA5aTIrdm9IelI3cjBNL0g2OVlLa0ZUTkZYUkZyQW9vNSswcXFKWjRIOXhyMTd2cjYybnF5WkNIRStkQW9FWkhDS09KQ2hLUnhPbVgwTnJ0eExFUkordG1xRVJVanAvZ0lDdUd1M2NOZHVBK0NNR2d1bmhTVjAwNGlaOHVJQ0t1QThjZGFXbDRCOUg2MFZJZDROaFE0TGhGNXpPbTJmNUdPRmhabG50aTZjZGdiUHZYNDduZ2dSenRxVWVBYU0rUEFiS2lKZVNqTVI0anh4eWtScitDT1J0NnU1L2RCSGtDRVROdHpycEI4OVg2SnE0Y0lDd2wxY3FGRHVxSktaL0RFUXdkMTZpTHRwdUhKKzBTYWk0QXlaWlllZDBlbUs2L250cXZhTERsNXRBZ1ZIYys0cDg3ejZES3JIYkFhNm5ZcVFGSWxDcEFWMGtTL1kzYU1kYWZNWVBtSys1dXhvczVDN0FycjFFQzJhT2pwMzVUSVZIUXFhbmZ2b0RVcGJ5NkJLem9xelBRMlZXU1didFlaeW9mcHdhZ0ZUOUJXQkJYemxaRTY5bGNGbHdGdnVkTnlVeVlPUzBFNUVpSDd3ZlhOdzVFbGtZS3hwcFB5dVNKcE1FWUtXUXEwanB1RHRqQnhHaGc4YmFzQ3VsWmdackNtb28yWC8zTWhXbEQwalFydzhvUk9DSEFPRnkyZXpldWw1bDh0bm5Wb1JvdVJFekdBakVRNVhwcmlFZ3JVdVF2amdydWtta1IyRGtTZHBpdEk2Yk40SE5KRWlSTjF5cUhYRUZMeGw2TENweDFTRmdWSHpFcHhjclpEUUVyakZDaVc5UjBXSTJUZUxTWTc0T1VRMWk0aHJQN2hVaEtUb0wzd0xXTWprVG9qWTFjZWpQdnMyVUh6enR4QzhyazB2SUVEbW83OVVFODYwQlF1bCt3dTQ5eGRJNmxnVForUXdqSGp1ZGhRUTNQZXY0VDY2VEdSUDV4QmsrQWpPL2xPZFR1TGtRaldIU0E1VkN1K1ZmOEt5ZDdFejlhY1dNRVZmRWE2R21WRFZId0h2SS9aOGVhWHMySWtJd1hLYWZ4djNQZk5UaTJ1VlZrSVYxL1pBMGZVNzRHNmJheVZRaElUTGI1bUQ1MUFSZE8wVzd2cHRFNzVjckNtVXk4Z2hBSnp4NHpnVHoxZGNaeStMa0FwTzlaaDl1alZWdlFzVklrU25FUGs0aEwyR1ZHMTNLRUlzNStidklmbDdLRkJlL2xaa0ZxL2hFaWhDd2kwaG1jTm1NYzhTaW54dzE1eFIzcW9wbE12UUlSREJHVDlPNXNCWkUrNXhFQ0hoTkRCTnV3QjMwNWFRRklsQWxtOSszRFpQREQySDhpSlFVM0J1QmQ2NENXZmZ0Ti9XNmE1Y05nZUhEK040ZFdVTml1SHUxa093dllHZDhlT1dXNFl0MDdHMnZIVFJSSFA0c0JFRTRMdTFwc01vWTNKZW5KMmhRNDJmMTNZaHkwMmNoVS84YzN2dUpYdlFkTWRTQldmOHVZYlhxYjN1OHpnSGJMV09aeTFEeFJVZ01aelhHdVMzaDllQksrN1BXUFArRHZCMVNFVklpajRqVzlnWStyalpsVWxzbWRCMHZXcEJoR1JISURNTVFNWjJ0WmZCQThpZzZmVlJYcndBQXM3NGp3U1dxaEVlWGNIZFhBUU5MSXlVOGxEYUJNQmRmY1BHZnRqL0tyMXdIYk9BdGh1VjM2cFJFYXp4bUJBWk9td1NTaklnR1pObWNjZU9lRkh5ckx0Q0VpMmdsdkpRTnUrRDlkdUFRQ2JYVUlTSU1ta095WWUzTHB5YUtINWxocXk2amxFbW9wTmloMkVHcnlXZUNDRXpBb01IQU1nZS9aemhuQnc0ZytabEZoOGlLSko3SXNnb0RhQ2JpK0NhSlNxaXdwZSsvM0p3RDVzUjRseTNGVGpXQmN0QWJRZUtwbU5DUmc3WG5GTXZmQTFuRTlnWk9kenhaK29rZE9zaEZCK2FqMlpnekdRMFo3Q1pjSnF3Sm13U21JVFVCYWZvTTdJT3pBR295c0ZhMDlic2JHTWRNa2YrUHRtbmZ0NXl0WjBOTXJZQUx0WktOb09XaStqMmV0M2pBMmYrSFFEbHQvOEhwWGYrMU95LysyVnpqN0hqTFJmNFU3UU9kL21iSnMxRElpUjJselRrWUxtY25RVk5MV0NLL2lLcm1EbitRTE9xTmRYSm9hMUIrSmN6WmkzYjhPR2F6cVlWaFZUSjJZSmpKbDZzSkdQS2QrQ1hCUlVIYnpJdnNWWldoby80MVQ3bGxlK1lPRzJ2bWQ0MEZaR2hZZTI1VjlZS2l3dXZ3QjNXQmY2cFRVUUlSSWlMdUZ6NEZVQmx1UHdpV2xoc1VHdmZKUzQ3WnJyUktUQjh5TWJWeHMrSWl0WmFSMVJ6bUpsMm5TemlaVURKMWhjZjBTTEVjM1V5ZkFTcFZvdmxQQlJYekhOa0J1MEo4U2JqRWlkamhqT0MzKzFKcktBQi9Idko4R0ZrM0loNFhmcUdDYjY5N2crVkRDTGRXUEg2U2pzY3hoY0dFZkZySmtMcUhJdkZlUWtzdGZmU3dxSnhkejFXdkRKOENJYVBBT3JYdTNyUkVvVmd6c2k0clNQa1JIVVVrZFFGcCtndnNxcnF6ZjB5S2tSODdnMlErY2hQbWxPSGc5WUNyMEhlM2ZnKytzRmRFKzdBV2ZOaEQ5ZXZuZ2hEaG9NcWlQSVBMd0xocnl4VTE3aHZtbXpHdU9xdEgveWg0ZktMbEpmK3F2SjZUZHA5K3owWFlGeTREeTlSK3Q2WGVtNEJuU2VDVnBuT1ZBM0pLQ0tISUsyR1NkRm5aTEZyZnFEa0Fxa1JzeVhFYXlmTmp2bUZaZDM0UG9vWnFLM3J0MEFoOC9Rdm01eWUyeDh2VnJrRGlCVVhmanV5dTRWcnk0TytCUndZUSszb0FiOGJWWFlFc2EweTRna1p2eWdjUmkyWGRCSEN3SmpwVmROckRCN3dSV1lRVnh1L25ZZ1FOS2MyM3dVWkVIS0JsNG9wUWlKcS9EMjNxK3UzY0ZmZlFCR3krNTQyNThRY2xpbURrNllSSDBXdGE5WHR0UnB4SVFOai9pQW52OXRYWnRodkFoVHZmakdiNHBJdVFpUTdhb283dlJZaGd4UDJZdytQWTdHSGR5SkNoQnd3cW1rOVlJcCtJeXZJUVFCRk96cHFYTWFlSTdQdmFSUndobHR6R3pJd1p0c1hJVHY5eXdDVTdsK2dmUDlDMDNPZEQvKzRQL2Rna3R0U2Q0TE0wWjhtYy9Tbit4Mk5Ea0JHZ1lOQ1dnMlRvcy9Jb3VxTkJjNTViait1Q0trdVNGdlNsQnRHbnZRbkdHb0wrejVxN2pHd3YyYThSc1hZV2s4MHJOM0NycWFIODlCMERGV2hab2IvTUpkOTl0ZHFyaGRYaExocnR3eTN0V3g3aDVnd05jV3BUTTUwU1JxYU11bFMwYW9RVDRSNHdxN1h2YkhJQlYzclpPeDQyeUlFMVN5MkJTNnIzbUIweUxZcVFxSUswbjdyd3I0bk8rSUN2Y2tjM1lFUDFkYmxoVnNKdkgwN09BaWc3SVZyVmc5b00rQk9SSWk3Zmd0QlFxcS96dHZNam9PQTg2RlRPRS9NVU5tcUVFK0U2UG90dndOQTVEMjZ4TW5ZY3pqano2RW9XYS8xcXcwUm9rYjhEa0ZhRDVpaXo4aUtlQ3RnTTZScTU0YnBnQXZ1Tkl6TGJPNkNZZWRETU9PNllOZE94d3RRdXZNbDM1MkgzWG85enYzaFJaOGIvSWsvTWltY080QU1IbWp1Z2pjWEthOWNibnFQVG5NWlFBZkdBTzFJUFNCQ0ZzUzRZRUpXTUk0THJtRHJ1T0NhZDkwQjJIbEdLcmtJbHhsK1dBOXh1V2dYSFBLSFFXU0MrNG45S0VOYkwwZ3pMaWpPQkprczhMMjFjUkxQbWJWd2owNXc0UWV2cVFkRWNGdE5BejlUbXJiZ05YdGtISldPV0VEcGhnVkVxYzdaVVJiTDJmY1U0azJBWkR2QTJsWE5LczZONHFJdG9KZGNBZHpDRDNFZm1YRXBZWXZScW9WeDM3OWx5b1ZqeDVIQlNadUdOczBqTENCRGgreVltc0RhMTc2anpuTXlkaHdaUG9RcXRSWVFiVGtOVUMwSXJIckN3MnRlR0FyZXgrNjFnREx5SkprUHYyRDJXMXhhSzdZRkxDemh2bjhOYU04Q0dnRURtanRRZTY4SUMraU1ISVk0ZzdvNkRCazJVODlKS0Q1dFdVQ2hBS3g2YWdTdytWM0R2M2FuQmZSaTc4WFZQeGFqS1M2dUJRd3NWWHNXTUVoTHJicHVIUXZZalM4N0J2eWlxVWFVQVhka0FmMHJrMFZaQWhBWVVyUFVVbHR3Vnk2QlNFVVhyZjdEQWFwZlhoUVhFMXFFYmM5eDdQeGpjOWR2bWtKNlRFc3RFMmZKSHZqUjlqczh0TW0xQzBFMkVCNWcxQWl1ZjZCRExoamQ4YXR0Rk9sWUxqZ2N2OENQS1RVWkpZS0w2NExEY2ZGOXhBNWNzRU9WTzJzbVFpcmkxRzh1U0l0V1hYQTRPYlBnbHdHTEhXMEpvYk9JNjRJMS93N2w5NzVsT050S1Vma0UxSEM1cXRtcUtxNFg1WUpEY1JGa3h5N1lxOEFOa3E2eEMzWWZYc0o5ZEJsdnNVanhwWlIwbFdQb2tEOUlYaWFlYjlzRkMxb0VOaFRJb3JKaER4VDNnZ1YwOCs4ZytYY3F3a1hZdjBydTFCZnJYaTlKRnRCOWRKblNuZC9yc1FhMjgrN1lWcTNzQVcvOFRKQVdMVnRBS0dJTlh6WlVVcWZWVVhGSnRJQlNGZDlXdUtSYlFMVjJxZGNWMFJWUDNnRVJFczVaV1VVZjJLdFAweUxjOS83S0pJNlRRLzNleC9IZ3JRd2VOdm5aSTUrTGQxODdPNWFXdDlDcXBWUlQ3QWJJaGlQY2g2cUZhbHAyd1JWY2F5NDQzRVRqYlp1RmoycmlxN2d2UkY0ckxwZDBGN3hYV2tMQzZaWUY4cFpyV1lTVUZtMEhVY21BWXdlZHgzVEJ1cjBHZm1FM0tQVFdEUjl5ZSs3N053M25GdjF4dzg3Qno1aW81UFlqQTVWalQ4SXVvQ0dYY0Jjc1k4ZHhqbnpXajAvZ082U3JuTE52Mmw5b3ZETXVXSXVpdGd3b0l1L2JkQzBHU1J6UEFyb1BhbnNvT3hQUHg3S0FsRFlxZXY0MHE3c09XeDJ2dXhYbExUOERlajJuWmQ4MFlsZXJiQlZKdDRETytIT3hGdnJwT0xLanlNQTRrV05DZG1JQmxhTDRJc1Npc253Znp3SkdjbkZGaUdkdFF0dUd3Y01pSkxTUktpNzZWcld0TTAyNUJGckFrUHJEa2xSOHhkM2lQTHVvMGlFTEdDQXJVcjVxZHAxVGdRcmVPZHoxVzREZ1RQNVkyOWVxQjIvYTNuRE9OL2NGTm00MStVTGljVjUzS3pud293M24rK3NwaGsxOTNPNXRDZkcvb0hzNUxYMGIyaFFoMFp4bkw1cjVWTEVmVzdCdEdEems5aXI4ZGVQSTdKenpYRTFFd0xRbHBFMFhES2ppaU9CbWNjeDZEWlJaVnE4Y3FKcmJxUXNXdDJqOWZJbUdhTU1GdTNhc1J6ZmhyWFR1Wm02ZzN1S0NtKzhhYmkzb2V0K1dDOTVhTnRkN2RNVWNWM0RYYmdKaXFwZzJGM3Z1YmVOeTdxTXJmdnpqdW1BVmxteXFQUlRUQzh2TkRoNXgzd0lvdkoxNXp6YVJnSGo5QW5kZ0FkMml6U3h1Uktqd0NUdTNnTzRqTTF1QzkzbUUwWEhPTFNLRkg1cDlyd3ZXNXFJZmwzWXNvRzQ5UkFEMzBWVTBmeSs0dHQxNjkwc2lkR3ZackpzTUVOc0N5Z01GUkZqaHBldHJZT1lIREkwTEVSZThndThPTFNERXNtaHRpUkQvWHJXeDZUUm5vbXEvMi9EOU8yQUJvVExUUjFWRjlicmROM2I3Y0RqdThTMWd6UWVlbFJQWHpaaVFINXk1U2JDaTlTL1VwTVRqaXEySDRMbEtuMnhzcldOamV3TUVkSHNEOTRNZlZMMjQrNlpzNVlraXU1OGtyczczV2hlT3NtQ3o3UjJmRXhGSFJCd3F4b1lJSXRWYld3c2Uyby9pRVB1bE5LM1lzMUkrdEcwWTNIUEJvVDhWK3M2RlhZenZXbE11a292eXFGbTFLMWR2enM4dEM5d0J6N3RJNUFsUm1UN01tWGNqZThZRk4rUGFkc0dQRWFmd3BrMjNaUzh0czliNnNUbC9laFhrdTBFQ203M0tiZFN2V3E0VkM3aWphaGovUHVHNDlvZHJSNFE4YnB5cWU5Tit1bjRHZEZUVlZWVVhGYitJbzZxb1ZtL05INkg5S0E2MUkrRmpXY0RLYmNQZ25nVU0vWW5TZDg1KzJSWGJsS3ZERVh5d0h2eUs2S0ZCZlF1Yk16ZlRIazRwT2dRMTlYMGJyaWdqNTEvL2R2Vngzd1c3WHp1TldLRlg2dzVURjF5UFMxMXdFdzV2UC9yOStpS0VyOC82M2FSVnNTdjFNUTZNQnBlcHZHZ1VKNUNLRUVnNXZJeW9xOERiMUlGdkFUSE5jRVdBL0N1ejl5eDNWSVRSMUFLbUZuQ25ITENDclYySmdpOUNLdjdDaWEya0lpUVZJVHZtUWk4d0VwRkxGem5DZ3YyeVgxUnZHdnBXb2NWZ1V2R1lrNU9uMkh0UTVBN0tmTDNqZmt0SStBOENsN3JqbGhDa2JxNzNMcHkyaE94OWpuQm1pa0FnUWtJb3pNLytYM3ZtWVVSbkFGVFo3MTJyT2wrRk9mTnVCQzNsY1l1bXZ0R0pzb0NwQ05uam5IckM0emJJZGVwTWhob1dJVDcwTHo3MktpSVUyRGVEeXFvS2lJZy8waWNxUTRjNVJkRnkzdTl1aEIzUVVubENLa0wyTWlmS1hkdUw1dGJRUzY5ZHB3NGlSVWpnUnMyVkJWb1hJWGlac281bFMwWEludWJNKzI5c1ZLQ09DT0dsN3hZRllHSHU2NkFyTml1OTNQUnFPNEFaV2xsc1dGeE1zZnVnSXI5aHZjTzlSdUVpWGJDSHpmblRqclYvaElQRmNjRm0yK0FyOE1TSERkaTAyakIxd2J1Szg5T0Z4b2dVSVI0S0YyWWYrSmR3elR5Q21EVytSc0xod2pjU01PVzVVaDYybHV0R3dOMTgxNFF1NWFHY3IrdUIzYnp0b3I2OVh1T21VeEdTTEE3VkZSV1dqVUdSZXpZVHJ0RUFEUzJnS2crQUJ3Q0YrYmtsYkxLTHlFaDEyQm9MV041RXQ1YnJpNHZOKzZDZ3BYVW9yZGVQWWVHK3VXWnBQYldBeWVlV2dac0F3K2RmYStoNlBUUzBnQkJrem1DY2FJMGhpcmFBZGx2WEJLdm5kN1hpK2hFQi9ldW1GakRaWEpCTThVdjAwU0xFUjVBNU16TDNMd0JjK0FJeHhveTQ3MzBUZC9sYm9FcnBuZjl0TW1ONUM5R2l5V3liOTRQY2JMZUZpejlsTXErM05KU0MrK2c3OW9MYnNSOHFSYStocmhoVCtGWEgwZi9ReXBtUkxTSDFXa2M4eEIwVDRtMjlhU1U4RDlvd1hNV052SC9Xa3FZdElZbmtxQ3lpdExUNlZoTVhIS0E0UDNmVDd0NVJyNVpiZWNxN2ZZMExEclZ3bUFITUFsb0N0U3U0UmJTRTZMWXRDN3BsMDQ2c2dHdUhLcnZsMUFVbmxGTzRLcVl2NlhmQkY2dXgwRkNFVk9FMndPYjg3UGZFNjk4bDhwUjNNUHdOZUxNbytiTXBGVmNJankzMXFsUnF3cFUyekg1cEEzY3JxTkEyMTZUR1FxWWlKQm1jZ0oycVF1N2t6bDFwS1FOR2Q4ZHE4QmMrdVZsM0xMOWJWcHRjVWxvOTBwYVFhSzRkTkJFaHRSQngvaGZ3S29DcS9qV0F3Z2hWZFlNcDlqcDBSWlFWZ0tHQndtOWFzdERnaEVpMDRvTE5IZWJucUNwMEFwWHVzY2ExdHNrWnZ2L3VOb3A3WEYxd3B4QmJoSGpZdXZCOEFkUE5HbHo5SXh1alQ2cHkxa2JPaWVwbTFRNW5yaXZRWjhFUnhUMXVJa1FoYncrOUptQVhaUEV0WDVNcDBXclJzZ1cwTnlzQWZQREt6SDhERUp3aEVUbGpqenVwQmR6RG5IcHppc3RyNHNnZkFBNmZldE9iWjd4bHRDeEN3bjllb2JRQ3FRalowMXpWNjI3VmVOVkFPckVBWFdGaGJoYVlCVUI1dWJxRnc5eXBEYzRjb09ieEU4SHRmUmVNVWhMclhwWHlUNnBKZ1h2REw3MGVxNzIzRVhiaWdtdXdPVCtMLzBMRVNVWElYdVA4cHd3OUw1MUJ5eUlrQ29XRnVRY2dWd0ZVOVZXVGIzUmFrS2RTRWJJSE9MZ0orb1o1WG1KMXM0cUxqbGhBVFBQTEVzRG0vT3hGeTcybzZGT3BCZHo5SE1JTkIvMVRGSElkY0x0aGRNUUNobEZZbUhNQTF4VGpXcmQycVFWTUlBZkJsOVpoZEVTRTFGeFV4TW0vTXZkNTRCY0JCUDI1VklUc1FrNzBYOWw4OTQyaDgxY3UwZ1YweWdWWFFGWGR6Zmt6QVJIVjhZRFVCZThhanU2aDR5NFlmQXQ0QS9oakFKUVIrOEtPQ1hMTTlJaEpYWENTT0lXU2ZTODNFSzdiL1BjTis0SFZuZDJxWFhUTkFvcklEVlc5TGlMTzVsL01UcG12U2w1UzVSblRJVFYraTRuaCsyL3Rvcmk5WWdGRktkbGZWNEUvRmxFR3oxMjlTSmZSTlF0b002R2pxdTVXeUIzN2VTcGs1VklMbUF6T2Z6N3ZRQS9RTlJFU3pvQWVsNStmbXhhWU51VmIvc3dHSDBMSXBTS2tMOXlhd3FvQWpteC8xajdRVXU3OHRRZjBDTjEwd1g0bTlMakNnckdFZ1JGVVI4UzZzZFFGOTBGY21OaDNVMlEwUTA5Y3NNZmw1K2RXQmU3YXgvN1BObi9OZ3N5QWdqS1p1dUR1Y3dxTGFzWndYQkxVRGp2MHgzSnMwRVAwMUFLS3lLcXFyb2lJVTVpZitUMFVWSngvSUhBWUJJVEoxQUwyZ0ZOZjFYNXR5Tm4rUXdET1hWK2hEK2lwQmF3UUpndW5mVi9zbDZicUNCTklocldMNG5hcEJYUUlMMzNYUi9SVWhFUnlYMzQraXgyYlVzaTQvOHhjUWY4T3lBdldWZHV4SnJVWklSbGNzak9naWhyTHBseDBWTDZoQWtQRFYvNmoveWd2Tmx2WXVidm90UXV1NGZnL1o2dk94WGU5QXVDTGsvNjcyeWh1TjdoZ0grR01hbjcyM1FyMnpRWDczSmVmZHduR0VyeHFWTEV1QXE4Qm9QSTVlMndTZExMaVBxa0xydVRFejFDTGlyZldpeTdZZUg0WDVYWW9vL1k5ODBFQ0xLQ0lvS29seTcycXF1N21LNmV2SW95YXp6Unp6RjcxQkNJVkdUQzFnSldjK0V0c3lEM0VEQllmbHRKdjI4QUZ6bDNmOGRpTmJxSC9GakNxdXVhVkdiOHV1Z0xhTzhzV2wwdVdCUlJFdGRiMUpoajlGeUV4T0lETnI1eVpGc3hjTk9yeU80YlZnNkpNVmQyZHgwcUVtRldJN3BpWWxQK3BqZFRLNFBuWC9TVlJrNHdrdU9DbUhNRG1oYm1JTzFuL0U3NDNqNWtMam96aDdrRWlYWEFkQzdnYVN1VGZOUnQ5RmpCbFJPV2tQVFlCN0NlRVBlQ0NTL2JRaWdxcktJam9KWE4vN21CbXBRSnZ3Z0JJWEZtdkhuYU5CVlRWVlJIeEJzSjhDV0J6NGZRTTZLdzU3b3lBTllpaE5VMWc5MXRBVVlvMnl5OEJiNWxIZFAvQVJ1Zk80TG5YNnk0R21IVHNHZ3NJSm5PR2Z4Y3V6T0w1WUMrTEtDQTlGQ3U5RWlIKzA5VXFqSTRia0Y1aTE0aVEyUGpLNlJ5MlphWG95bmtBVitVNDhDeUFJajlsUTQ0S1dyV0dXTDlFaUs1ZzNhZkNLNWhNOWFhVE1YTXlEaDdkZnRYZXpPWEU5YjYyWEhRYXU4a0Z1OVZ4amVRdXpOU0pWVVF4dlFNVFhuYkNCVmNoc3AxV284UHVldXhxRnh6SmZlVjB1R1hGbTFaNENmU0dqZDJiOXN3RDRKVVZkUUpBbEN5UXMrZDQ4eDNtVlB4NUZMMXlaZzRrYS9ZOVYwd0pURmtOTzRHUFFGSHRJdUFpa2cvQ2FWRk1UdlNxU2xhQWgzYi9EaVlEZWxiUkJWeWIrUkxSZXRGSkNGMG9RL1RWQXNia2lndHpVOEJCYzl5ZEJuQ1ZFZkRYUUprQ1VCaERHQUlRbUxUY2lLZ05KLzRIVU1EMnBSTjFsd0ZIWVVPUmRRQVJ4OHRzZVVIeklDQnlFNU9wVmdmUFhkNFY5WGFkeHQ2emdERzU3UXRud0xjb1FYbk9EeDhFcmJtV2hJTDZydEVmUnVBZFZMZSswNnpnZDdXSWFCZi9INlhWWTFYZkxiMDZBQUFBQUVsRlRrU3VRbUNDIj48L2ltYWdlPgo8L3N2Zz4K"/>
        <prop k="offset" v="0,0"/>
        <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="offset_unit" v="MM"/>
        <prop k="outline_color" v="35,35,35,255"/>
        <prop k="outline_width" v="0"/>
        <prop k="outline_width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="outline_width_unit" v="MM"/>
        <prop k="scale_method" v="diameter"/>
        <prop k="size" v="40"/>
        <prop k="size_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="size_unit" v="Pixel"/>
        <prop k="vertical_anchor_point" v="1"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" value="" name="name"/>
            <Option name="properties"/>
            <Option type="QString" value="collection" name="type"/>
          </Option>
        </data_defined_properties>
      </layer>
      <layer class="SimpleMarker" pass="0" locked="0" enabled="1">
        <prop k="angle" v="0"/>
        <prop k="color" v="33,150,243,255"/>
        <prop k="horizontal_anchor_point" v="1"/>
        <prop k="joinstyle" v="bevel"/>
        <prop k="name" v="circle"/>
        <prop k="offset" v="0,0"/>
        <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="offset_unit" v="MM"/>
        <prop k="outline_color" v="255,255,255,255"/>
        <prop k="outline_style" v="solid"/>
        <prop k="outline_width" v="0"/>
        <prop k="outline_width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="outline_width_unit" v="MM"/>
        <prop k="scale_method" v="diameter"/>
        <prop k="size" v="25"/>
        <prop k="size_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="size_unit" v="Pixel"/>
        <prop k="vertical_anchor_point" v="1"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" value="" name="name"/>
            <Option name="properties"/>
            <Option type="QString" value="collection" name="type"/>
          </Option>
        </data_defined_properties>
      </layer>
      <layer class="FontMarker" pass="0" locked="0" enabled="1">
        <prop k="angle" v="0"/>
        <prop k="chr" v="A"/>
        <prop k="color" v="255,255,254,255"/>
        <prop k="font" v="Arial"/>
        <prop k="font_style" v=""/>
        <prop k="horizontal_anchor_point" v="1"/>
        <prop k="joinstyle" v="miter"/>
        <prop k="offset" v="0,-0.40000000000000002"/>
        <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="offset_unit" v="MM"/>
        <prop k="outline_color" v="255,255,255,255"/>
        <prop k="outline_width" v="0"/>
        <prop k="outline_width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="outline_width_unit" v="MM"/>
        <prop k="size" v="11.8"/>
        <prop k="size_map_unit_scale" v="3x:0,0,0,0,0,0"/>
        <prop k="size_unit" v="Pixel"/>
        <prop k="vertical_anchor_point" v="1"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" value="" name="name"/>
            <Option type="Map" name="properties">
              <Option type="Map" name="char">
                <Option type="bool" value="true" name="active"/>
                <Option type="QString" value="@cluster_size" name="expression"/>
                <Option type="int" value="3" name="type"/>
              </Option>
            </Option>
            <Option type="QString" value="collection" name="type"/>
          </Option>
        </data_defined_properties>
      </layer>
    </symbol>
  </renderer-v2>
  <customproperties>
    <property value="fid" key="dualview/previewExpressions"/>
    <property value="0" key="embeddedWidgets/count"/>
    <property key="variableNames"/>
    <property key="variableValues"/>
  </customproperties>
  <blendMode>0</blendMode>
  <featureBlendMode>0</featureBlendMode>
  <layerOpacity>1</layerOpacity>
  <SingleCategoryDiagramRenderer diagramType="Histogram" attributeLegend="1">
    <DiagramCategory spacing="0" backgroundColor="#ffffff" sizeType="MM" penAlpha="255" backgroundAlpha="255" sizeScale="3x:0,0,0,0,0,0" rotationOffset="270" maxScaleDenominator="1e+08" direction="1" scaleDependency="Area" spacingUnit="MM" spacingUnitScale="3x:0,0,0,0,0,0" penWidth="0" enabled="0" penColor="#000000" showAxis="0" minScaleDenominator="0" scaleBasedVisibility="0" width="15" lineSizeScale="3x:0,0,0,0,0,0" lineSizeType="MM" height="15" labelPlacementMethod="XHeight" diagramOrientation="Up" minimumSize="0" barWidth="5" opacity="1">
      <fontProperties style="" description="MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0"/>
      <attribute color="#000000" field="" label=""/>
      <axisSymbol>
        <symbol type="line" clip_to_extent="1" alpha="1" name="" force_rhr="0">
          <layer class="SimpleLine" pass="0" locked="0" enabled="1">
            <prop k="capstyle" v="square"/>
            <prop k="customdash" v="5;2"/>
            <prop k="customdash_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="customdash_unit" v="MM"/>
            <prop k="draw_inside_polygon" v="0"/>
            <prop k="joinstyle" v="bevel"/>
            <prop k="line_color" v="35,35,35,255"/>
            <prop k="line_style" v="solid"/>
            <prop k="line_width" v="0.26"/>
            <prop k="line_width_unit" v="MM"/>
            <prop k="offset" v="0"/>
            <prop k="offset_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <prop k="offset_unit" v="MM"/>
            <prop k="ring_filter" v="0"/>
            <prop k="use_custom_dash" v="0"/>
            <prop k="width_map_unit_scale" v="3x:0,0,0,0,0,0"/>
            <data_defined_properties>
              <Option type="Map">
                <Option type="QString" value="" name="name"/>
                <Option name="properties"/>
                <Option type="QString" value="collection" name="type"/>
              </Option>
            </data_defined_properties>
          </layer>
        </symbol>
      </axisSymbol>
    </DiagramCategory>
  </SingleCategoryDiagramRenderer>
  <DiagramLayerSettings placement="0" linePlacementFlags="18" dist="0" showAll="1" priority="0" zIndex="0" obstacle="0">
    <properties>
      <Option type="Map">
        <Option type="QString" value="" name="name"/>
        <Option name="properties"/>
        <Option type="QString" value="collection" name="type"/>
      </Option>
    </properties>
  </DiagramLayerSettings>
  <geometryOptions removeDuplicateNodes="0" geometryPrecision="0">
    <activeChecks/>
    <checkConfiguration/>
  </geometryOptions>
  <referencedLayers/>
  <referencingLayers/>
  <fieldConfiguration>
    <field name="fid">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="osm_id">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="name">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="amenity">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="hstore_to_json">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
  </fieldConfiguration>
  <aliases>
    <alias field="fid" index="0" name=""/>
    <alias field="osm_id" index="1" name=""/>
    <alias field="name" index="2" name=""/>
    <alias field="amenity" index="3" name=""/>
    <alias field="hstore_to_json" index="4" name=""/>
  </aliases>
  <excludeAttributesWMS/>
  <excludeAttributesWFS/>
  <defaults>
    <default applyOnUpdate="0" field="fid" expression=""/>
    <default applyOnUpdate="0" field="osm_id" expression=""/>
    <default applyOnUpdate="0" field="name" expression=""/>
    <default applyOnUpdate="0" field="amenity" expression=""/>
    <default applyOnUpdate="0" field="hstore_to_json" expression=""/>
  </defaults>
  <constraints>
    <constraint constraints="3" field="fid" notnull_strength="1" exp_strength="0" unique_strength="1"/>
    <constraint constraints="0" field="osm_id" notnull_strength="0" exp_strength="0" unique_strength="0"/>
    <constraint constraints="0" field="name" notnull_strength="0" exp_strength="0" unique_strength="0"/>
    <constraint constraints="0" field="amenity" notnull_strength="0" exp_strength="0" unique_strength="0"/>
    <constraint constraints="0" field="hstore_to_json" notnull_strength="0" exp_strength="0" unique_strength="0"/>
  </constraints>
  <constraintExpressions>
    <constraint field="fid" exp="" desc=""/>
    <constraint field="osm_id" exp="" desc=""/>
    <constraint field="name" exp="" desc=""/>
    <constraint field="amenity" exp="" desc=""/>
    <constraint field="hstore_to_json" exp="" desc=""/>
  </constraintExpressions>
  <expressionfields/>
  <attributeactions>
    <defaultAction value="{00000000-0000-0000-0000-000000000000}" key="Canvas"/>
  </attributeactions>
  <attributetableconfig actionWidgetStyle="dropDown" sortExpression="" sortOrder="0">
    <columns>
      <column width="-1" type="field" hidden="0" name="fid"/>
      <column width="-1" type="field" hidden="0" name="osm_id"/>
      <column width="-1" type="field" hidden="0" name="name"/>
      <column width="-1" type="field" hidden="0" name="amenity"/>
      <column width="-1" type="field" hidden="0" name="hstore_to_json"/>
      <column width="-1" type="actions" hidden="1"/>
    </columns>
  </attributetableconfig>
  <conditionalstyles>
    <rowstyles/>
    <fieldstyles/>
  </conditionalstyles>
  <storedexpressions/>
  <editform tolerant="1"></editform>
  <editforminit/>
  <editforminitcodesource>0</editforminitcodesource>
  <editforminitfilepath></editforminitfilepath>
  <editforminitcode><![CDATA[# -*- coding: utf-8 -*-
"""
QGIS forms can have a Python function that is called when the form is
opened.

Use this function to add extra logic to your forms.

Enter the name of the function in the "Python Init function"
field.
An example follows:
"""
from qgis.PyQt.QtWidgets import QWidget

def my_form_open(dialog, layer, feature):
	geom = feature.geometry()
	control = dialog.findChild(QWidget, "MyLineEdit")
]]></editforminitcode>
  <featformsuppress>0</featformsuppress>
  <editorlayout>generatedlayout</editorlayout>
  <editable>
    <field editable="1" name="amenity"/>
    <field editable="1" name="fid"/>
    <field editable="1" name="hstore_to_json"/>
    <field editable="1" name="name"/>
    <field editable="1" name="osm_id"/>
  </editable>
  <labelOnTop>
    <field name="amenity" labelOnTop="0"/>
    <field name="fid" labelOnTop="0"/>
    <field name="hstore_to_json" labelOnTop="0"/>
    <field name="name" labelOnTop="0"/>
    <field name="osm_id" labelOnTop="0"/>
  </labelOnTop>
  <dataDefinedFieldProperties/>
  <widgets/>
  <previewExpression>fid</previewExpression>
  <mapTip></mapTip>
  <layerGeometryType>0</layerGeometryType>
</qgis>
