<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis hasScaleBasedVisibilityFlag="0" minScale="100000000" simplifyMaxScale="1" simplifyDrawingHints="0" simplifyDrawingTol="1" maxScale="0" simplifyLocal="1" version="3.14.1-Pi" readOnly="0" simplifyAlgorithm="0" labelsEnabled="0" styleCategories="AllStyleCategories">
  <flags>
    <Identifiable>1</Identifiable>
    <Removable>1</Removable>
    <Searchable>1</Searchable>
  </flags>
  <temporal endExpression="" accumulate="0" endField="" durationUnit="min" durationField="" startExpression="" enabled="0" mode="0" startField="" fixedDuration="0">
    <fixedRange>
      <start></start>
      <end></end>
    </fixedRange>
  </temporal>
  <renderer-v2 type="pointCluster" tolerance="20" forceraster="0" toleranceUnitScale="3x:0,0,0,0,0,0" enableorderby="0" toleranceUnit="MM">
    <renderer-v2 type="singleSymbol" forceraster="0" enableorderby="0" symbollevels="0">
      <symbols>
        <symbol type="marker" alpha="1" name="0" force_rhr="0" clip_to_extent="1">
          <layer class="SvgMarker" enabled="1" pass="0" locked="0">
            <prop v="0" k="angle"/>
            <prop v="231,113,72,255" k="color"/>
            <prop v="0" k="fixedAspectRatio"/>
            <prop v="1" k="horizontal_anchor_point"/>
            <prop v="base64:PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIGlkPSJteVN2ZyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+Cgk8aW1hZ2UgaGVpZ2h0PSIxNjAiIHdpZHRoPSIxNjAiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBS0FBQUFDZ0NBWUFBQUNMejJjdEFBQUFDWEJJV1hNQUFBN0VBQUFPeEFHVkt3NGJBQUFmbEVsRVFWUjRuTzJkYjNCYzEzbmVmKy9kaXdVRVFpQUVnaUFGMFJSRmk1UkZVNHlpT1BxUWNhYnFUTnE2K1RlT3grUFVTZnFoelllMkh6ejkwbzRrMGg1S2tRQktxV2M2VVNaeG9qYnhURFBwTk1tazZVeGlKek5SYkVYVnRJcEZ1eHBKcGlXS29rU0toQWtRQUVFWUJJSGR1L2Z0aDNQTzNidDNMeGE3d0M3MkxubWZtY1ZkUFBmY2M4NjllKzc3bnVmOEZWWGxkc0xjODg5UEFHZ1lIQUdPV1ByakFLb01nZ3hhYnR3Y2RGQUV5OG1ZQ2FlRFlEaFZRaEZRZEVXUUZVWHh4SnV6MTY2QUxvT2dLbk1LQ0t3b3JBcUVBbS9adE03NGhjSVpnTHNlZjN4SlJEeFZEZDBSNEZibHZIYjhxRGx5YkJiU3lBTEdTMjZ2WU83NTV3Y1FLUUpRS1I4RkNKVXgwSEVBRWUrVEpxU09FVms1UmdCVUtZTDRsaHV5NFh3UmlnQnFyUjZLRDRZRDNQTUpnSkpKUTFaTU1DMko0VkUxbkEwVDJMaG54Y1I3QlpnRkVPVDdnS2ZvcklqaENwNy9qZzBYN0hyaWlUQnJWbXdybkh2WXFlaTF3Z2VBU0JIVklRQlZIaldrZmhMRXVkdWZNaFFnVW5zcENyV1VDV2RKaVpQdVdsVVBFVkQxRVJsQUZWU0hFVUZjR3FvMmJ2TTlPaEtkRDFVSmJKUXYyYlRPWUYyMHdQbFkrcVhOUHBvc0luZkJPYnFLaGk0NDY3aDY2dGxIQkI0QkNQRiszZEw3QlBiRnc2a3FrckIyN2VMYzkvZ1I2QWdIZWc0NEN5QjRYN1BaT2J2NytQRnpXWE90elhJTlhYRFdJV0JkSkNCVmE1NThwYVNEbkt4ejdBUjNLNkpuTE9EVnFhbHhuR2dRZlF3QTVSRENRUUJWSGpZaFpWaUU0ZmkxdDVBRlhBQVc3SDJldHRrNUQ3d1BvS0crWk91WVMzdSsvT1dsckZtN05LNlhMT0E0VWJ1ZGZNa2NHRk1ZdGQvTlFSVk4ySTFieGdJcW80aU1HZ0dqOTFzaGRBbjBvZzM1amcxNUNWaWlCOUJMQlRBR2pmNUtvckRaeHQ1dDQ5ejMrSkh0NUZJc2RDOGhreTU0N3RTcEE4QitBQ1g4TFV2dkJka2JEOWRKMTlvc3Q1MHV1QVh1cklnUks3N0tremJiczZNblRzeGx6UVhuelRBNXVvcnVXOEFYWHZCVXhCTlZacGVYZjlHeWgwVjR3UGdhL1F3QXdoRElVUHpTM0FLdUkxWlVGeERtVkVHUWwyeTJ2dys4cmNENG9VT3Z1bnVSTDN5QlRsaTJacm11MXdFVlBBSFB2Z2EvWkIvb01lQ1lxV2pGZitodTViSzNvREFxeUNnb0t0eHZtNnRlUm5YRXZqaXZObzVoKzVDNzRCeGRSZGRjOE94enp4MEVRQ3UvQW53UlFLcjl0WFhJZ3J0TjQ3TG9namZpQkhuRi91cC9Cdndwd1BqeDQ3TzVDTWx4MjJGYkxlRGNjNU43c2IwWlljaS90UFREaU9uRkVEdmdNdzFac0hacFhFOWFRSkdMcUtMd0J2QmRBRkgrbTcyOXhmRnQ3RVhaVmhHaU1DNXcxRGFvL2x2TEZRVXBibkJwampaQ1ZmZUxDS0k2aXZDb0tpaThIR3ZrM3JaZWxOd0Y1K2dxT3VlQ1gzakJqN1h2L1lFaDlaaHRZbWtaV1hDM2FWd3Z1dUEwVGtUTTRHUGxaZUR2RkJnL2ZueXFaMTJ3aXVtbDFab2ZUeHIrZU90eDdvRWxrUVhPZlU4ZWU1TFRhaSszVUY5WVJNUXp3ZHJIdGQwQ0xwdzZOUTVRSVR5cWNOVGNHTDl1dTg3M2lzaDRvK3ZYUXhhc1hScDNxMWhBQkFSQmxROUJ6OXRCSGw4SFVEUEs1aDFVR1Q5eFlqbnJGbkFjQ0JYK0Vlam5RUkNSSTgxYXU5d0NkcHZqQU1nQkFEU2FmL0lYcUY1Q0pCU1JsWFphd0U2SWtKQkkzTFRub2RpTTF5V1VCYzU5ang5dkZTNEdENUVRRTY2bUFLbHF1Qld1N1Jhd1F2ZzBnTUFSR3ZSczVNZytGUDJNaUNES01IQWZ4aWc4M3M0ME9pSkNvb0dUbTNDM3VRdk9IbGN6NkxiTndxUXRJbVIyYXVwK1VUMEFnSWNiUURwT2c1Nk5WcEVGd1pIRzNUSWlwQUdIY2dtNGFHLy8zOWpqN0hnYkJyaTJ4UUlLSEVEa245aC90eVE0Y2d1WVBRNWhIMjZxcTBicjZhQ3FzMXUxZ0cwUklXYmNxTnAycEE0OEFMSWhPTks0TEltR2JSWW1rVFhiaWdqWmtndStldXJVNTgwMy9XWGc4NXVPcUFsa3dkMm1jYmVEQzY3aFJGYk5qZk9Ib3ZwZkVHSDM4ZU52ZE5VRko1Rzc0UFJ6dHdKWFk2N3MvM1ZXclpNaVpQYjVaNFp3SzBlRmhmOXM2YVBpZWowNmhIWlpyT0tod3dCVTV1ZW9MQ3hzT2I3YjBBSUc5c1pmRTNoTkZlNElncFAyMFFURFR6MFZkTm9DRGxGZDF1eXo5bGdUVDVZdFlQOERwZ0N1bmFXdUFPWVdzQ25PQjFBNEJub1EwL0h3dkEyNm9xcWxWaXpnWmtXSVI0T2hYTzErQURiamRlbHNobFA3Z1RiRmx5R0JzSjJjL1pWQyt5MHFDOUtpQ0duZEFvYmU1MUQrblVtTWdaYXY3d0xFNzBQNnpLMFdobmNhcnI4bnNwNVpLQXlMeURBb3EwWC90eTM5WjhEL2JDV2VUYmhnMXk3ZUlFVEdYSEE4dTVHRlRibUgzQVZ2bG9zOFFzc2lwT2tDT0RjMVpRZVN5bjFVNjRDcDZKUUwzaXduZlgxNGc0UFJlUUJkeHdXM21zWnRKMExTT09Hb0FLcDhkMlpxYXUvTTVDVGp4NDlmU2JwYmUrMm1YZkFSQUVFT0lvMExZTllzb0Zjc1VoZ2Fxam1mVzhDMmN0RnVBd0xqcUhvaU10dEpFZElRbmJLQVNUVE5KYzZyNnJvV3NGV3UyMklnU3h4bUhLaUhTSnRFeU5OUFJ3VzAwdWVmQWhBWVNiTWVPWElJL0ZQQkxCZ0svTE5tcnNsbnhlWG9LaHBhd0t1K3Z4ZllDOGJ5V1hvZ3pTM0YwZTVLcnoxUjd3NmI1YWh2OVJPMkVGK2NjMVdGNVBGMjVNeHF0ZmNyY1BXNVp3OWNQZldNZC9XNVp4ZFZOV3J4ZDJMRUhUY1NJWHNST1lZcEVDTWJoSzFCdSt1QlcxSEJRTW9xcCswYmpJQUl4SThtODdjZHAraUlpSXlnYW9ib21lY2Vpc2ppZWlvNGQ4RTV1b3BVQzZndnZGQVVFVlI0REEyL3BDSjVaVEZIUzFEMW5yYWRGbCtIYU4yWk91VGxLa2RYa1ZvQUYyNzg2Tkg1NWFWSEJRNGhNaUl3RXJXZk5mR0I5cll4dVhwV1hUck5jaEFiaEdEZ1JNaFcwMGdWSVRrSGNBRGtBT2pIWjA4OWMvRHFjODhlaGlaRlNJaCtTc3hVK1lNZ0k1dHA5Y3RGeU8zTktleTN6K2dneXYzMkJ6aWJpNUFjbVVLNkNNSDdvaW9ndWkvdGZJNGN6VUxoWVVGOFcvLzVtK1Q1M0FMbTZDb2lDM2oxUHoxZDFHZ1g4TDU5b0tBeUxLbmQ5bzJSOTRTUWN3N0tLTUw5QUx6NG9xKy8vL3NoTDc3b3BZbVFva1RiMURNUnJlK1hPbkJwWStRaUpPY1FRVVJHZ2NIWTQvTXh2U1BrSWlSSDF4RlpRQzM1UjFCOUJFQUszY3RRcDFFWU1WM2Eza0ErSjJRN29LcEZFU21xS25NTHM1KzI5SWZZdFdaeUM1aWpxNGpYQVVjUmVSQnNIUWZxOXFkdEZsa1RJVjUvUHpKc05sR1gvbjVERnZ4Y2hHd3pwNkVWSTdDa3FoOUNyQUNLV2J2NUUrYWYyc0xYNnlKRUJnWW83S3gxdmVMN3VRalpkazRPMlVmNFlkNFRraU1UOE9lZWYzNElRTkVIZ01lQVRUYTg1TWpSR0tyaFoyM1Y2aVBnVzVDTGtCeGRoaytsOGduN2ZReTM4TXd0SmtMVTNsTVN1UWpaZG03TWZKWGRjMU5Uby9PblR1R0RVU2FDakJFYitIeExpWkJFWE1sMHRwSkdMa0phNGtaakJYRU0xZHdGNStndS9CQitIRURzOU1zY09Ub09aYStpRCtjV01FZlg0WU5aNDA5Ulg2enJUdGIvY2hHU2k1QzJjbWhSWVVnRXp5ZGFaRktxdlNMa0lxUlpMaGNobStDRW9xQkRrRS8zemRGbCtLZzY4VEZVYXlaN0g4Vjc3d1hBMzcrZnZvL3Ryem5YZi9ndzNrNnpYRy81dmJNQUJIUDFLK2ZuNkFCVWhoUzVHL0tla0J4ZGhrOTFHSDdSK2VsZUZpR0YwVkVLZDVtUkwvMkhId0RBMjdrVGIyaW9KcHlXU3VqeXNybnh3MmJyQnUrdXV3aXV6Z0pRZXY5OGMrbm1JcVIxRGkxaXk1MlB5RkNWdEpWL2VsZUVGTzRhb1hqdzR3QVVqM3pTQlV3OEFOQnlHVjFaTWVGKzRpY0E4SVozNHQxNUp3RGw4eDgwbFc0dVFqWW5Rb0FoTkhmQk9icU1oQWpwYWw2MmhNRlAvelFBaFYyaitHTzdBRmo0M2Q4Qm9QL0JCK2wvMEt5ajdZUkorZkpsVmw3L0RnQnJaOTgxNFk0OFNQOFJHKzVmL1dzQVNoK2NwL3lCc1lhbEN4ZGF5cE8vWnc5OWUvYWlxZ3djTzRhSXFRNjR3YkVPbGV1TGhOZXZvd3JMTC8wdElrSmxlUm05Y2FPMWg5QXJVQm5DOXJ6bEZqQkhWOUhUSWtSOEgvRk4rN2svTVFGQVpmRWFxMisrWmU2amJQZlZDeXBvRU5UbDA4VVhycG9kU0VzZlhTSmNYUU9nYitJZUFMekJRZm9mZkJDQXdyalpuU0pjV1NHOGFlcVBCQlZ6OUR6ekFRcWp1MHhWNTQ0N3pQNGtDc0hzakhtV2x5K2o3aHJmTjA2bjJJZjBGUkdVZ1llT0lVQjUrakxCOURRS1ZLNWZqNTVCemJGSE9ZMzF3TVZFQ0QzWEV5SytIODN4Nk50bmxyRUpwcWRaZmNzVVFDcXVBSmFoVWxrM2o3cG1DbDM1bzQ4SUxsMEN3UFA3QU51R2FOMTJueTJvcHIxdzNrU3l1bW9lYnFFQXZnK3FGQTgvWUY2Z0tGMWw1VHV2SXlLVXIxeWhNanVMcXBxOGkrRGZQVUhmUGZlZ3FndysrcWpwdWZGOWRHWEZGTURGeGV3SmlhMXdFUFhBNVM0NFIxZmhDNWpYR2gxQXpkb3d2ZUtDKys2NWgrSjlabHVLbFgvNEJ3REtIMTBrdkhtekpseDQ0d2JsSzFjQTB3UGkwS2g5NzhaM1RIeTgvcDNvN1IydzE4cU9JV1RIamlpL0tNWVZXOWU2L00xdklFQ3dhTVdGaTU2WVJ4RWhYRnREY0VMbnZOdjgyZHpieEFSMy90TG5FQkhtdi9hN0pvSnlZS3g2QnR6b1ZqZ1JqYmxnT3lSTFJhcGhTVCsyZ25hNzRPUk5KTG5vbXBUcjByalUrRGRJSS82QVVxK05wWmQyYklWeitYTXZoTVlDYkNhK0xIRngrSW91QVlneURObTJnQ1FzbHRmZlQ4Rk9PRis5OENFQTRmS05Pc3VtUVlDdUdVUHZLdlM2dXBwcUFaTnB4TGxnYnM1UVMwdEkwU3drRmowalY5VUJ3dXZYRWFyaUpzMENyc2VWTGw0d0w4d2RkK0R2MlFQRUJOYTFhNFRYcnJVVVh5WTVaUlZZQlBCRldiWm5Cb2haa2JSaks5Z09DeWo5QTlGYUw1VlowNFVXcnE3V1gxZXBSRUlqZEFWd0xTVmNTaHB4YnJNREZWcXhFc0hGaTRCcFF3d3JGWVNxSWljSUNLOWR5NFFWMjZJRnJCWkFkMFlCeVhnelRMMTFvc3JGempVYWZGbzlsOTdIMjhnQ3BuSWlxYytxRFZiQ0htUDNsVGhtenJJMXlVWDNvK0NyeUt5OXF3SFFVWG9JM280aC9MMm1JeWRJdHBYRlVKNlppVVJJTURNRGtQbGVodUNqaTZ5VTFrQmg2R2QreGhURUlJZ3NaRTlEWkJtNElxTDRBcUVob3o4OTQ0TFQwbHMzWENMT01DMytEYTV0eEhYQVRVVms1QkdzSGNtQ0c5M1N2VldiQXZCQmx3RlVLVW5pZk9aZGNQeWVrbzJmdFJtS3VJb2Rna1dwMU5BRis3dE1mN0lVaTVIZzZCakNFTUlRQmNyVDAwYkFMQy9qK201TTRUTzlNb1ZkdTBBaFdKalBuR3R0d1FXWHNOckRCL05Gb05ScklpUXR2WFhEV1M3dWVodFpRSDlzREFCdng0NjZzWVR0aGdZQjJLN0NZSG9hTUcyWG9jMnJXeTdaR3h5TVhnelhFNU1seTlhQ2RTOUJ0UUFDUFNwQ1ltaldBamJOeGM5dElFSzJqcXE4U0h2MmRiK0JybisrRjdnNGZGU3UyQk1IV2k5cTNVVmxmcDdWZDgxUUt0ZG1wamR1Vk4zc0ZqRDA4NzhBVURQZ3dTRTVJTFdkTDl6TnQ5NDJpYmhlRDJEdDdEc29nZ1lCL3Y1N3pYazdqNlUzb2Nzb1A0VGtSalU5NklLVFlkc2xMaHIyZERUSWF6dnVWeUY2Nk1aNlZCZk1TMXFTTExuV0ZseHdCQi9Vaml1aTVPNnVWMXh3ZUdPWllNWTByL1FkTkgzQzh0RkhsSklXY0JNdWVPMzgrd0Q0WTd2eGQrK3VDZFp1Q3hqTXoxT1pOM1U2TFFmbW9kdlJPMHExOGR6YnNZT0NuY25YeXk1WUVuWEE2L1pNeVpYVFhyR0E0WTBiVVEvSUhULzVrd0RvOGpKaWgxUTF1bllqcm56ZVRFcVNnbDlYQU50dEFTdno4NVNjUzYzVWpsc1VVZ3FnYW05YlFKR1NaOW9DWXowaENrS1BpUkFsNG1vMXc5WkZTRnB2U2p6K2RsckErUDJrUHZ2NFA3YlR1WmN0WUxVZDBMamdOK3lEZUtqSE5BakJ3anpCdkJrZ1VIekFESlhxaTAxQ1gvckdYMjA2N3RVMzN3U3NsVjFjQkdEdzBVZTNrdDA2M0R4OUdvRFMrZmNwbnorLzd1T3ZMSm5CRGJKL1AvN2V2UTFmamw2QWlsNEsvZkpyYU13Q21sTFpXeTY0bHJNV0tVWTEyemJZS3RkdUZ4eWRTL2t1MUQ5L0VXbjRHL1VFcDNnSW9TOTJ2d1pGNWpDVlExUzEyQk11T0M0YTdNdzJmKy9kOU8yOUc2ak80VWh0bW1uV0xWZEN0RndHWVBXdE4rdnV0ZTlqKzBITUtCeTE4MGxjYjRaYS9hcEE4WjRKNHoyTFJhU3Z6N2hSTjArbFlucEQxM05kd2VLaXFRdTY0VjJhM2w2WWRtMldPRUZuN2FsNWhHV1UwQjhyaGVjQnJ2WjVWN0VGVUVTS0xvTDRzUlZzdHdVc25YMFBNQU1VdkVObU80bytOMUJoWmlicVZXZzJ2Z2dhUm9wMHpjMDFpY0ViM29rSUJJdlhJN0Z3OC9UcmRRVkVyRWlTSFR2d2R0aWVGVmNBTmRZZDc3SVJPMFpEeUd3QjcyRUxlTVgrdTdEN1A1NWNBdkExUGk5RXpNQUUxV3d1VXQ2VXhZSW94elZEbVRZcFREUjJiVnBLSW9xcXMzTXhQbkZzQkUwYzE3TW1VZmlldFlEMThPWGtTV1BYVDAyK0ErcDJ0UDVDU3RpZXdPcWJiN0YyNWd3QUk3LzJxd0NVM3Y4QXNiUG5TaDkrdU9tNGgzNzI1d0FJbDY0VFhqZkNaT2t2djJIS2JSQ2cxbElPcGxpN202ZGZSNmlkSjdMRFRxYS9iYUR5TjdZZ25uT1VKeUtlaUhqRUxLR0lnRWpOc1pWUEZJYzlicFZ6THFjdXJSVE9rdGFWMm85RTMxcU9MelVOSllyYmVXeWxzYWRvMW1XbWhVdGFqdlZjY05hNU5JL3FxOTI1ZW5acWNzNlZURk41N2swWExKVktSRGxoSW9VKytteTlzSFRwc2ptcEZkUlcvaHZGRjNmQnBmZE43MGhsNlRxaGJacnh4L2VZQXQ3ZkgxbFpNKzlFMFlWclpxZ1ZJTVYrRVBEM2ZTenF0WW1uRVQ4bW43MW5OMWdVMyt5ajI3TXVXUFVIbHA5ejkrNWI2OGZNNU9RaThCNVFiY2FnOXRnS3RyOFp4a0kxNmsxd3dxVC93U1BSVW0wcnI3NXFnZ1VnWWNxcmxXeHlpZVdqL0lIcEhhbGN2eDVOYm5MdXRyQnJseG1yaDNManBiOHo0UllYbzNBRER4MER3TC9IVEVJSFplM2Q5NkkwNHNja0Y5OWdFZGEzZ0duWFpvbno0QjFiR0tNQzZLbHFxS3FoUU9qY2lLcUNhczJ4bFE4dURudmNLdWZlK0xxME5zRVJmYlp3cmNsY3JiVlUrMGVyY2lSNVRJWWpKVnphdGZFa28rZlM3TFVaNHVJVzBTRWFEZU9wbnNlV3pNcG1URjRHNGVaL3lNQkExSlkzOENsanNjb2ZYYVRjNm1wWCswMFBTM0hvVGp3N01YM3RyYmRBWU8zc1dZS1pHWlRxQ2x4My9QZ2pGTys3RDBRbzJia2NheCtjNThiZnYyek8yN3hzaE9LOTk1cGZyVkpoN1d4dkRjT3lzeTZYQVVaUG5IZ3RlVDR1UXNDTVpncDdXWVIwa3F1S216aVhlT0FrcUVTOU1xMU92VkhsUGEwT3RCMmlvUjFjTXI5SlJDSmtmbkl5R2lLak1HMGVtZ3dMT3RSTElpU05DMWZYcU5obWs2SWQwQm4wRHpUVk5oZ1hJZGpWdG9JZi9wQ1NXeDNMempjdTdCckZ0ejB2VG95RU4xZFlPL045UUNpN09SeGhTSEZpb3FZUXBvbVFhTFV0QmYvdUNSRFExVFdDNmN0UjJHNElpVlk1MEVWZzNhbDhrUWpCOUlLVUFLNU1UbDZ5Vm1nZnlOQm1QSExYUkVnYXQ3YUtMaTBCUkJQWnZZSCsrdmhUcm5VV0VJaDZSSUlyUDZSc1hhcHp0MzE3OXRPM2Y3L1JRSGJ3UVBuQ2hjajFobXRyeGoxUE9CRlNMZXRwbFhjOEwxcStyVzlpd3JqeDgrZWpPU09wbGpLREhMQ0FWTnY5a29oRVNQd2pFbnMvYnhVUjRqNVJPdElXVVpNVUN5SktkUUpsOUFpakh5Yk5tNlJWM3RIWUQ1bXd6RmtURjQyNGpacFEvRlJXeGZXSVBBWk1OSTdpOXNNZER6MFU5V0tFUzRzb1FuRGhBc3R2dm1uRWNjbTRaWDlpZ29GanB2bWxNRzdtckFUVGx5bGZ2SWhDM2Q0bFVHMXlHWGpvSVFhT1BnUWlCTE5YVUlUeTVjdVVMbHhJTGNTWmhjbzVnYit1cXlwWlJDSWsvcWtKZXF1SUVQZUowdEZOeDZkSXBFZmk4elhzNHpMUG5jWXZmeVBYVmJVZXh2TFZwWkZ5VFZhNWFxYlRuMFlrUXVLWW5acjYzK2FiVHFoeXpOSWp5WERySVdzaVJJckZhRDIvY05Xc0hhaEIwTElJY2ZPRHd4OHRzVFpybW5qQ0c4dW1nSVNobVptbjRJM3NqTkl3NGtjSTVzeWNqM0J0RmNvQktsRFlPWXdpK0JNVFNMK3hmQVc3d0xvM3VJUEF6aE1wdld1YVhxSjVJeTY3WkV0d0pJU1JFeDVuZ2JkUlRWME1OUzVDSXVnTEw3d0NNUHVqcFdPS0xob3I0RFZkQUNGYklrVDZpaFRzb0FDM1NwWUdsWlpGU01FV3dOTHNURFJuSkUxY0ZBOGZBb3hvY09IY0N2dXlZMGNVajdkekJCRWppUHhkWTFFYm9nS1ZtWm1vSGJPVW1JS1pCWEhSQlBlaHFjakt1Mk5QSG4rYmRaQXFRaUJlc28xQnZWVkVTTTIzVGNabkw0NnNaWjI0VU11NG9EWFBNL2FEaVVZR1Z3R3g4U2RmaTI0TGljMXc5ZzdaQ09raTVFdGZLZ2tnVTFQZkFoWk1wUHIxRFdQTEtQdzk0d3djUFFyQXlxdW1kbEdaYjMydHY5WHZtamtjaFowN0kzRlJQUHdBaUZLK1BHMmFTQlFXL3ZBUHpHdmIzNDgzTUlBcURQLzh6NkVJZW5NMXNzSm1BSkpTbVY4dzdYc0t5OTh5L2NocUo2YjNsT0NJb1lBOGJxdFNLVk1VcTBnVklURXhZcGJ2SmFWeTNrTWl4TjVBNHJPSitIRHZ0TWJpU2NnTnFYL3ZhOFJLN0tTcjY4YXZkYy9iZmMrQ2tOZ01sMXFQVDBHcUNIRzRPam5wbHUxQVlkYkdQb1F5MkNqU3JJaVE0ajFtNndhempLL2gzREs3NGMyYkxZdVF2b1AzR2E1VWp1Wm4zUHplL3pQY3padUVidSs1UTNienc5akNSdUg4bkxHQXBSSzZacVpnRjY3dk5QVzlhd3RHY0NpcEU5T2g4NktoTFp6cUFuWThnWWgzeWY2T1N6UkFxZ2h4MEtlZXVvSWR4ejliOU4yRUVrU2tZUUcwWVdxT1crVXNrWmJRdXB3VEJkN3duUkVYWDJhM1ZSSGlOa0VzWDc0YzlVaTQ2WnZPM1FMYzhXbXoyWXkzY3lmZXlBZ0MzSGpwYndHcnZ1MWNFRGRVcTNMdFdxUnc2N0tUOGoyckhLYnd2UU13K3VTVERWMnZRNm9JaVlzUmg2Ukk2QWtSUXJ4Q2JQN2JTbnlwQWlieFFGVXhZaUwyQTZuV0NwTDF2bVZOU0xUS1JmZlRRc1ZWTnZMUkR2T25UbjBXSUVTL3FLb041NHgwMHdVWGhxcDdlSXo4NnE4QnhrcTVLWld1YWFQWitBYU9mSktpM2FwcjRBRXpxRFZlZDR2bnRkVjdLNzFuQnFTdW5UbkQyZy9PWk1PTmJvWlREVzNqL3U4VnZQQjNBRVlmLzhvWm1rQkRFUkwvUkZjb21SWWhOWUtKYWlWNTB3SW1rYmQ0L3BKNWJmWGVrdGd1Z2RCMnJ2WmVXdHA5cTZFSWlXUCsxS2wzekRjOXB4cTFjdGQzWnRJZEN5aHViN2ZkdTZOOTQ5WnNJM0F3T3hOTlRJL2kzQ0ErdDZPU3YyK2ZIV3BmUmJzc29GbHVWL0gzN1l2cWhXdnZuYzJPWld1V1UzMERKRVI0RHlkV20wUkRFWkxBV1lEWnlXZmZGOWZOSXBKYUFNMnAramU5a3lKRSt1eXVtYnQzUi9NL2JwNStIWUJnZGpaYW1yY216Z2J4dVRqOFBYdWlaWEdUK1V2TGF5djNGc1ZicWVBVml5alZYbzltSy81WjRGVGt0UDN2M09qalgybXBBRFlVSWVuQ0pGWjV6cEFJd1gzTWhaQ1NuODNFbDFaSGpuUHR1bCtGR3ZHU0pYR3hFVmZQTm8vMG5wQkc4UHovQmJ3Q1FGajV2NVlkdEordVllUlh6Q1QwOHZRMEs5Ynl1U2FTVkV1M0FRWis3TWNBVWd0Z3UrR1BqVkc0Nnk1alZiNzVqWTZuMXc2SWFmTmJFR0JBdkNjdHU5cHFQRTJMa0VpTXhIK1EyQ3ZSYlJGQzlHa2NydW40M0lOT0V3dHRFaUUxOFZDdFY1RTRacEZyRjVvV0lRNVhuM3R1RmRzL0RQd1BlM3hVMFU4Qm9IamRFQ0Z1RW5wbGZpRmFNN0Jad1pIRzNmemU5d3hWcU82RTNpbG9xWVNXekt5OWVPVys2K0lpamROb1NlZnZDZndmRzg1WnZ2cHQ2VGRBS3lMRVlkVWxPUC9zczM4TVVJRUJrRWRzamozWWZoSGkydFFxeThzdEM0NDBidlVOMDhVbUJUOFNPSjJDV2RyTi9JWnBWb2NNY1FwUkFjUXIvSkdBZCtjVFQ2eXdTYlFzUWhLZnVqcFN0MFNJKzBpVDRacm1wRnJUV085RDR0Z3FWMzEyMlJJWFRlUjV5NjZoNlo2UVJyZzZOZlV3OERDQW9sL3ZoZ3Z1R21mcmpwbHdqeDNqTkFBSkFQeFEvN0VOYzJuMHhJbW0rbnNib1dVUnNwNHdjVzlIdDBSSTE3allEK1dPdHhvWC81WXNvRnRGeXlJa0RWZW5wcTRJdkFHZ3FxL1lEQjhRWVg5dUFYdWZ3NHh3ZVJNMWxzK0dhVGpNcWxsc1JvU2tZZFordURJNStiTE45R1BBL3UwU0lkM21raGJrVnVLQU15Qi9qc0RvOGVOYmRydHhiRldFMUU5cWp5cW1HNHVMWnJrdEM0bE9jc1R2TmhzQ29VT0NveU5vaXdpcGkxVEVtNTE4OXZQQUx3TW9mQzUzd1QzSUtiOWhUMzE3L1BqeGwra0EyaUpDa3A5a3ZUSVhJYjNKYlFmYUlrS1NzQmJ3RFBBbkFOZzVKQXIzSTl3UENwcGJ3R3h4YWlhaktHY0UzRHplYjl2anVxdGJiUlh0RWlFMVVETkM5b3lxdm0wSzQrUzR2ZGwvanVwQlJLREZIaE5MMUNlV0VhN1pDbjFXT2JYdGZNQWJBbitDS3J0UG5IaVpEcVB0SXNRV1BpOStWRlZjVzZINzRYSVJraTJ1QnFycEwxMEgwREVSRWkrQWpyczZPWGtBT0FDZzZGL1k0QU9JRkhNWDNBVk9kUWxZdE13djJGT3o0OGVQdXgyTk9vNk9pWkQ0TWZwT2JZV1gySUkxdVFqWmZnNUlNWC9iaTQ2SmtIVXM0Q0x3SVFDcS85VUdmMWhWajluWGN5eTNnTnZBcVU1ajFnTS9EV28zdGhNM2xENnhxMk5uSWJSaFJFTVNTUXVZeGwxOTVwbjdBZFNUZjRISUYrMFQra1M3ODVLakhxcjZtdjN5eHdOQjViOERESjg4MmZwaU9XM0Fkb21RT3E0bUY3R0tQWWxqcGdUSExTSkM2SURSMlN5MlZZU2tjazg5NVdQbnBzd1YvZjhBRUNvL0RmeVVkUnVETnRMdXU5czBMdXN1Mk16ZEFIaFprRytqeXU0ZytMM29YazZlYkhrVWN6dXh2U0lraFl0bkptNEZnYnJLZnRjRlJ3K0trSnJuRzJ0ZXNVKzU3ZlgvVnJHdEltUWRDeGhpNXhJSXZJSUlxa3dEWmxLRzZpL2FhTWNVeGhJSjVSWXdmdFJvY2RGcFFhWVZCWFZiOE1wN0luTFc1VnN5VVBpZ3N6MGhEVVZJakVOVkE4dTlvcXJod20vKzVodkFFRUFsS0J1eEFrZEVaS3d1c2J3bkpINE1iUXZDSmVDMElQUUh3Vy9aSUt2REowOXVldTVHcDlBMUVkS0lnMXBYN05CMXdaRnhFUUpFYmFpOWd1NkxrQ1k0QU51THNoOUFQWDRiUUdDdkt1T0p4RzhyRnd4NkRyY0RlUkQrZSt0UkZuWi81U3ZSbHFoWlJ0ZEZTRE5jc3BwUVUrRyt6VVdJYXIzMTZ5VXIySDBSMHJ3RlhIVGZGYjRHSUhBSTFOUVJWWTdhMDZPZ3RWdEs5TG9GVkhWTkpRdUlMS0lnb3FkdDRITmlOeHBYMVFWckFUTlgxMXNQV1JBaEczS1dYNVRxZXNNdkFzeE9QWE1NT3gwVXFzc0dpMGo5bmlZOUxFSVVTclpBemdMbmpRblVQN0xueisxKzRzdnJiZ2FZZFdSU2hDUTVad21UNmF4M1U3ZWFDSUZhQzVtb3QyZW1WMk16NkJrUjBpeG12dnJWSXJablJjcmx6d0NnZXRpNGEwRDBaMjNRSVZYVDFCUExlRmRjc08ydHNEMFc4azNBVS9nQmRrM0c4WEw1RlJzODdIYlBSYnZSVXlJa21jNTZYRVBFekV4V1JFanlOeUdsa2JqOVppSWI2QmtSQXNZRko5Tktjak5mL1dyVXM0TGRNZ0JUZHpLTFpncy9BRkRZRllrVlpkU2N3a2NvMm12TVBCYWxDT0xIT2RDaWlMR3lybmRMbFVDZ2hJQ3FPQkZRRWxkL0UxMng1aThBS2RudnJxbGtBWEQ3Tkp6REZFQm5GVU1nZEEzTjZVKzhkeUYwYVRoV0sxeWNUMHRuTTl6TWM3OHhyckFYUUFMdkFJQ0lEb3E0Q1ZReWJxN2xUaFN6QVVqVUUxTU5oeXNVeWlwaXh0S0ZLbk5pbnV1eXdJL010YUV0YkxJaWVDc0FLdktPdlg1eDl4TlA5RVM3WGJ2Ujh5SmtLNXdZeTVKcVZXS2VPa1FrUlFtYkVKRnJqSjIyZGJ4bXJWVlBpNGl0NHY4RHlQK29PeDZwQWVNQUFBQUFTVVZPUks1Q1lJST0iPjwvaW1hZ2U+Cjwvc3ZnPgo=" k="name"/>
            <prop v="0,0" k="offset"/>
            <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
            <prop v="MM" k="offset_unit"/>
            <prop v="35,35,35,255" k="outline_color"/>
            <prop v="0" k="outline_width"/>
            <prop v="3x:0,0,0,0,0,0" k="outline_width_map_unit_scale"/>
            <prop v="MM" k="outline_width_unit"/>
            <prop v="diameter" k="scale_method"/>
            <prop v="40" k="size"/>
            <prop v="3x:0,0,0,0,0,0" k="size_map_unit_scale"/>
            <prop v="Pixel" k="size_unit"/>
            <prop v="1" k="vertical_anchor_point"/>
            <data_defined_properties>
              <Option type="Map">
                <Option type="QString" value="" name="name"/>
                <Option name="properties"/>
                <Option type="QString" value="collection" name="type"/>
              </Option>
            </data_defined_properties>
          </layer>
        </symbol>
      </symbols>
      <rotation/>
      <sizescale/>
    </renderer-v2>
    <symbol type="marker" alpha="1" name="centerSymbol" force_rhr="0" clip_to_extent="1">
      <layer class="SvgMarker" enabled="1" pass="0" locked="0">
        <prop v="0" k="angle"/>
        <prop v="245,75,80,255" k="color"/>
        <prop v="0" k="fixedAspectRatio"/>
        <prop v="1" k="horizontal_anchor_point"/>
        <prop v="base64:PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIGlkPSJteVN2ZyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+Cgk8aW1hZ2UgaGVpZ2h0PSIxNjAiIHdpZHRoPSIxNjAiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBS0FBQUFDZ0NBWUFBQUNMejJjdEFBQUFDWEJJV1hNQUFBN0VBQUFPeEFHVkt3NGJBQUFmbEVsRVFWUjRuTzJkYjNCYzEzbmVmKy9kaXdVRVFpQUVnaUFGMFJSRmk1UkZVNHlpT1BxUWNhYnFUTnE2K1RlT3grUFVTZnFoelllMkh6ejkwbzRrMGg1S2tRQktxV2M2VVNaeG9qYnhURFBwTk1tazZVeGlKek5SYkVYVnRJcEZ1eHBKcGlXS29rU0toQWtRQUVFWUJJSGR1L2Z0aDNQTzNidDNMeGE3d0M3MkxubWZtY1ZkUFBmY2M4NjllKzc3bnVmOEZWWGxkc0xjODg5UEFHZ1lIQUdPV1ByakFLb01nZ3hhYnR3Y2RGQUV5OG1ZQ2FlRFlEaFZRaEZRZEVXUUZVWHh4SnV6MTY2QUxvT2dLbk1LQ0t3b3JBcUVBbS9adE03NGhjSVpnTHNlZjN4SlJEeFZEZDBSNEZibHZIYjhxRGx5YkJiU3lBTEdTMjZ2WU83NTV3Y1FLUUpRS1I4RkNKVXgwSEVBRWUrVEpxU09FVms1UmdCVUtZTDRsaHV5NFh3UmlnQnFyUjZLRDRZRDNQTUpnSkpKUTFaTU1DMko0VkUxbkEwVDJMaG54Y1I3QlpnRkVPVDdnS2ZvcklqaENwNy9qZzBYN0hyaWlUQnJWbXdybkh2WXFlaTF3Z2VBU0JIVklRQlZIaldrZmhMRXVkdWZNaFFnVW5zcENyV1VDV2RKaVpQdVdsVVBFVkQxRVJsQUZWU0hFVUZjR3FvMmJ2TTlPaEtkRDFVSmJKUXYyYlRPWUYyMHdQbFkrcVhOUHBvc0luZkJPYnFLaGk0NDY3aDY2dGxIQkI0QkNQRiszZEw3QlBiRnc2a3FrckIyN2VMYzkvZ1I2QWdIZWc0NEN5QjRYN1BaT2J2NytQRnpXWE90elhJTlhYRFdJV0JkSkNCVmE1NThwYVNEbkt4ejdBUjNLNkpuTE9EVnFhbHhuR2dRZlF3QTVSRENRUUJWSGpZaFpWaUU0ZmkxdDVBRlhBQVc3SDJldHRrNUQ3d1BvS0crWk91WVMzdSsvT1dsckZtN05LNlhMT0E0VWJ1ZGZNa2NHRk1ZdGQvTlFSVk4ySTFieGdJcW80aU1HZ0dqOTFzaGRBbjBvZzM1amcxNUNWaWlCOUJMQlRBR2pmNUtvckRaeHQ1dDQ5ejMrSkh0NUZJc2RDOGhreTU0N3RTcEE4QitBQ1g4TFV2dkJka2JEOWRKMTlvc3Q1MHV1QVh1cklnUks3N0tremJiczZNblRzeGx6UVhuelRBNXVvcnVXOEFYWHZCVXhCTlZacGVYZjlHeWgwVjR3UGdhL1F3QXdoRElVUHpTM0FLdUkxWlVGeERtVkVHUWwyeTJ2dys4cmNENG9VT3Z1bnVSTDN5QlRsaTJacm11MXdFVlBBSFB2Z2EvWkIvb01lQ1lxV2pGZitodTViSzNvREFxeUNnb0t0eHZtNnRlUm5YRXZqaXZObzVoKzVDNzRCeGRSZGRjOE94enp4MEVRQ3UvQW53UlFLcjl0WFhJZ3J0TjQ3TG9namZpQkhuRi91cC9Cdndwd1BqeDQ3TzVDTWx4MjJGYkxlRGNjNU43c2IwWlljaS90UFREaU9uRkVEdmdNdzFac0hacFhFOWFRSkdMcUtMd0J2QmRBRkgrbTcyOXhmRnQ3RVhaVmhHaU1DNXcxRGFvL2x2TEZRVXBibkJwampaQ1ZmZUxDS0k2aXZDb0tpaThIR3ZrM3JaZWxOd0Y1K2dxT3VlQ1gzakJqN1h2L1lFaDlaaHRZbWtaV1hDM2FWd3Z1dUEwVGtUTTRHUGxaZUR2RkJnL2ZueXFaMTJ3aXVtbDFab2ZUeHIrZU90eDdvRWxrUVhPZlU4ZWU1TFRhaSszVUY5WVJNUXp3ZHJIdGQwQ0xwdzZOUTVRSVR5cWNOVGNHTDl1dTg3M2lzaDRvK3ZYUXhhc1hScDNxMWhBQkFSQmxROUJ6OXRCSGw4SFVEUEs1aDFVR1Q5eFlqbnJGbkFjQ0JYK0Vlam5RUkNSSTgxYXU5d0NkcHZqQU1nQkFEU2FmL0lYcUY1Q0pCU1JsWFphd0U2SWtKQkkzTFRub2RpTTF5V1VCYzU5ang5dkZTNEdENUVRRTY2bUFLbHF1Qld1N1Jhd1F2ZzBnTUFSR3ZSczVNZytGUDJNaUNES01IQWZ4aWc4M3M0ME9pSkNvb0dUbTNDM3VRdk9IbGN6NkxiTndxUXRJbVIyYXVwK1VUMEFnSWNiUURwT2c1Nk5WcEVGd1pIRzNUSWlwQUdIY2dtNGFHLy8zOWpqN0hnYkJyaTJ4UUlLSEVEa245aC90eVE0Y2d1WVBRNWhIMjZxcTBicjZhQ3FzMXUxZ0cwUklXYmNxTnAycEE0OEFMSWhPTks0TEltR2JSWW1rVFhiaWdqWmtndStldXJVNTgwMy9XWGc4NXVPcUFsa3dkMm1jYmVEQzY3aFJGYk5qZk9Ib3ZwZkVHSDM4ZU52ZE5VRko1Rzc0UFJ6dHdKWFk2N3MvM1ZXclpNaVpQYjVaNFp3SzBlRmhmOXM2YVBpZWowNmhIWlpyT0tod3dCVTV1ZW9MQ3hzT2I3YjBBSUc5c1pmRTNoTkZlNElncFAyMFFURFR6MFZkTm9DRGxGZDF1eXo5bGdUVDVZdFlQOERwZ0N1bmFXdUFPWVdzQ25PQjFBNEJub1EwL0h3dkEyNm9xcWxWaXpnWmtXSVI0T2hYTzErQURiamRlbHNobFA3Z1RiRmx5R0JzSjJjL1pWQyt5MHFDOUtpQ0duZEFvYmU1MUQrblVtTWdaYXY3d0xFNzBQNnpLMFdobmNhcnI4bnNwNVpLQXlMeURBb3EwWC90eTM5WjhEL2JDV2VUYmhnMXk3ZUlFVEdYSEE4dTVHRlRibUgzQVZ2bG9zOFFzc2lwT2tDT0RjMVpRZVN5bjFVNjRDcDZKUUwzaXduZlgxNGc0UFJlUUJkeHdXM21zWnRKMExTT09Hb0FLcDhkMlpxYXUvTTVDVGp4NDlmU2JwYmUrMm1YZkFSQUVFT0lvMExZTllzb0Zjc1VoZ2Fxam1mVzhDMmN0RnVBd0xqcUhvaU10dEpFZElRbmJLQVNUVE5KYzZyNnJvV3NGV3UyMklnU3h4bUhLaUhTSnRFeU5OUFJ3VzAwdWVmQWhBWVNiTWVPWElJL0ZQQkxCZ0svTE5tcnNsbnhlWG9LaHBhd0t1K3Z4ZllDOGJ5V1hvZ3pTM0YwZTVLcnoxUjd3NmI1YWh2OVJPMkVGK2NjMVdGNVBGMjVNeHF0ZmNyY1BXNVp3OWNQZldNZC9XNVp4ZFZOV3J4ZDJMRUhUY1NJWHNST1lZcEVDTWJoSzFCdSt1QlcxSEJRTW9xcCswYmpJQUl4SThtODdjZHAraUlpSXlnYW9ib21lY2Vpc2ppZWlvNGQ4RTV1b3BVQzZndnZGQVVFVlI0REEyL3BDSjVaVEZIUzFEMW5yYWRGbCtIYU4yWk91VGxLa2RYa1ZvQUYyNzg2Tkg1NWFWSEJRNGhNaUl3RXJXZk5mR0I5cll4dVhwV1hUck5jaEFiaEdEZ1JNaFcwMGdWSVRrSGNBRGtBT2pIWjA4OWMvRHFjODhlaGlaRlNJaCtTc3hVK1lNZ0k1dHA5Y3RGeU8zTktleTN6K2dneXYzMkJ6aWJpNUFjbVVLNkNNSDdvaW9ndWkvdGZJNGN6VUxoWVVGOFcvLzVtK1Q1M0FMbTZDb2lDM2oxUHoxZDFHZ1g4TDU5b0tBeUxLbmQ5bzJSOTRTUWN3N0tLTUw5QUx6NG9xKy8vL3NoTDc3b3BZbVFva1RiMURNUnJlK1hPbkJwWStRaUpPY1FRVVJHZ2NIWTQvTXh2U1BrSWlSSDF4RlpRQzM1UjFCOUJFQUszY3RRcDFFWU1WM2Eza0ErSjJRN29LcEZFU21xS25NTHM1KzI5SWZZdFdaeUM1aWpxNGpYQVVjUmVSQnNIUWZxOXFkdEZsa1RJVjUvUHpKc05sR1gvbjVERnZ4Y2hHd3pwNkVWSTdDa3FoOUNyQUNLV2J2NUUrYWYyc0xYNnlKRUJnWW83S3gxdmVMN3VRalpkazRPMlVmNFlkNFRraU1UOE9lZWYzNElRTkVIZ01lQVRUYTg1TWpSR0tyaFoyM1Y2aVBnVzVDTGtCeGRoaytsOGduN2ZReTM4TXd0SmtMVTNsTVN1UWpaZG03TWZKWGRjMU5Uby9PblR1R0RVU2FDakJFYitIeExpWkJFWE1sMHRwSkdMa0phNGtaakJYRU0xZHdGNStndS9CQitIRURzOU1zY09Ub09aYStpRCtjV01FZlg0WU5aNDA5Ulg2enJUdGIvY2hHU2k1QzJjbWhSWVVnRXp5ZGFaRktxdlNMa0lxUlpMaGNobStDRW9xQkRrRS8zemRGbCtLZzY4VEZVYXlaN0g4Vjc3d1hBMzcrZnZvL3Ryem5YZi9ndzNrNnpYRy81dmJNQUJIUDFLK2ZuNkFCVWhoUzVHL0tla0J4ZGhrOTFHSDdSK2VsZUZpR0YwVkVLZDVtUkwvMkhId0RBMjdrVGIyaW9KcHlXU3VqeXNybnh3MmJyQnUrdXV3aXV6Z0pRZXY5OGMrbm1JcVIxRGkxaXk1MlB5RkNWdEpWL2VsZUVGTzRhb1hqdzR3QVVqM3pTQlV3OEFOQnlHVjFaTWVGKzRpY0E4SVozNHQxNUp3RGw4eDgwbFc0dVFqWW5Rb0FoTkhmQk9icU1oQWpwYWw2MmhNRlAvelFBaFYyaitHTzdBRmo0M2Q4Qm9QL0JCK2wvMEt5ajdZUkorZkpsVmw3L0RnQnJaOTgxNFk0OFNQOFJHKzVmL1dzQVNoK2NwL3lCc1lhbEN4ZGF5cE8vWnc5OWUvYWlxZ3djTzRhSXFRNjR3YkVPbGV1TGhOZXZvd3JMTC8wdElrSmxlUm05Y2FPMWg5QXJVQm5DOXJ6bEZqQkhWOUhUSWtSOEgvRk4rN2svTVFGQVpmRWFxMisrWmU2amJQZlZDeXBvRU5UbDA4VVhycG9kU0VzZlhTSmNYUU9nYitJZUFMekJRZm9mZkJDQXdyalpuU0pjV1NHOGFlcVBCQlZ6OUR6ekFRcWp1MHhWNTQ0N3pQNGtDc0hzakhtV2x5K2o3aHJmTjA2bjJJZjBGUkdVZ1llT0lVQjUrakxCOURRS1ZLNWZqNTVCemJGSE9ZMzF3TVZFQ0QzWEV5SytIODN4Nk50bmxyRUpwcWRaZmNzVVFDcXVBSmFoVWxrM2o3cG1DbDM1bzQ4SUxsMEN3UFA3QU51R2FOMTJueTJvcHIxdzNrU3l1bW9lYnFFQXZnK3FGQTgvWUY2Z0tGMWw1VHV2SXlLVXIxeWhNanVMcXBxOGkrRGZQVUhmUGZlZ3FndysrcWpwdWZGOWRHWEZGTURGeGV3SmlhMXdFUFhBNVM0NFIxZmhDNWpYR2gxQXpkb3d2ZUtDKys2NWgrSjlabHVLbFgvNEJ3REtIMTBrdkhtekpseDQ0d2JsSzFjQTB3UGkwS2g5NzhaM1RIeTgvcDNvN1IydzE4cU9JV1RIamlpL0tNWVZXOWU2L00xdklFQ3dhTVdGaTU2WVJ4RWhYRnREY0VMbnZOdjgyZHpieEFSMy90TG5FQkhtdi9hN0pvSnlZS3g2QnR6b1ZqZ1JqYmxnT3lSTFJhcGhTVCsyZ25hNzRPUk5KTG5vbXBUcjByalUrRGRJSS82QVVxK05wWmQyYklWeitYTXZoTVlDYkNhK0xIRngrSW91QVlneURObTJnQ1FzbHRmZlQ4Rk9PRis5OENFQTRmS05Pc3VtUVlDdUdVUHZLdlM2dXBwcUFaTnB4TGxnYnM1UVMwdEkwU3drRmowalY5VUJ3dXZYRWFyaUpzMENyc2VWTGw0d0w4d2RkK0R2MlFQRUJOYTFhNFRYcnJVVVh5WTVaUlZZQlBCRldiWm5Cb2haa2JSaks5Z09DeWo5QTlGYUw1VlowNFVXcnE3V1gxZXBSRUlqZEFWd0xTVmNTaHB4YnJNREZWcXhFc0hGaTRCcFF3d3JGWVNxSWljSUNLOWR5NFFWMjZJRnJCWkFkMFlCeVhnelRMMTFvc3JGempVYWZGbzlsOTdIMjhnQ3BuSWlxYytxRFZiQ0htUDNsVGhtenJJMXlVWDNvK0NyeUt5OXF3SFFVWG9JM280aC9MMm1JeWRJdHBYRlVKNlppVVJJTURNRGtQbGVodUNqaTZ5VTFrQmg2R2QreGhURUlJZ3NaRTlEWkJtNElxTDRBcUVob3o4OTQ0TFQwbHMzWENMT01DMytEYTV0eEhYQVRVVms1QkdzSGNtQ0c5M1N2VldiQXZCQmx3RlVLVW5pZk9aZGNQeWVrbzJmdFJtS3VJb2Rna1dwMU5BRis3dE1mN0lVaTVIZzZCakNFTUlRQmNyVDAwYkFMQy9qK201TTRUTzlNb1ZkdTBBaFdKalBuR3R0d1FXWHNOckRCL05Gb05ScklpUXR2WFhEV1M3dWVodFpRSDlzREFCdng0NjZzWVR0aGdZQjJLN0NZSG9hTUcyWG9jMnJXeTdaR3h5TVhnelhFNU1seTlhQ2RTOUJ0UUFDUFNwQ1ltaldBamJOeGM5dElFSzJqcXE4U0h2MmRiK0JybisrRjdnNGZGU3UyQk1IV2k5cTNVVmxmcDdWZDgxUUt0ZG1wamR1Vk4zc0ZqRDA4NzhBVURQZ3dTRTVJTFdkTDl6TnQ5NDJpYmhlRDJEdDdEc29nZ1lCL3Y1N3pYazdqNlUzb2Nzb1A0VGtSalU5NklLVFlkc2xMaHIyZERUSWF6dnVWeUY2Nk1aNlZCZk1TMXFTTExuV0ZseHdCQi9Vaml1aTVPNnVWMXh3ZUdPWllNWTByL1FkTkgzQzh0RkhsSklXY0JNdWVPMzgrd0Q0WTd2eGQrK3VDZFp1Q3hqTXoxT1pOM1U2TFFmbW9kdlJPMHExOGR6YnNZT0NuY25YeXk1WUVuWEE2L1pNeVpYVFhyR0E0WTBiVVEvSUhULzVrd0RvOGpKaWgxUTF1bllqcm56ZVRFcVNnbDlYQU50dEFTdno4NVNjUzYzVWpsc1VVZ3FnYW05YlFKR1NaOW9DWXowaENrS1BpUkFsNG1vMXc5WkZTRnB2U2p6K2RsckErUDJrUHZ2NFA3YlR1WmN0WUxVZDBMamdOK3lEZUtqSE5BakJ3anpCdkJrZ1VIekFESlhxaTAxQ1gvckdYMjA2N3RVMzN3U3NsVjFjQkdEdzBVZTNrdDA2M0R4OUdvRFMrZmNwbnorLzd1T3ZMSm5CRGJKL1AvN2V2UTFmamw2QWlsNEsvZkpyYU13Q21sTFpXeTY0bHJNV0tVWTEyemJZS3RkdUZ4eWRTL2t1MUQ5L0VXbjRHL1VFcDNnSW9TOTJ2d1pGNWpDVlExUzEyQk11T0M0YTdNdzJmKy9kOU8yOUc2ak80VWh0bW1uV0xWZEN0RndHWVBXdE4rdnV0ZTlqKzBITUtCeTE4MGxjYjRaYS9hcEE4WjRKNHoyTFJhU3Z6N2hSTjArbFlucEQxM05kd2VLaXFRdTY0VjJhM2w2WWRtMldPRUZuN2FsNWhHV1UwQjhyaGVjQnJ2WjVWN0VGVUVTS0xvTDRzUlZzdHdVc25YMFBNQU1VdkVObU80bytOMUJoWmlicVZXZzJ2Z2dhUm9wMHpjMDFpY0ViM29rSUJJdlhJN0Z3OC9UcmRRVkVyRWlTSFR2d2R0aWVGVmNBTmRZZDc3SVJPMFpEeUd3QjcyRUxlTVgrdTdEN1A1NWNBdkExUGk5RXpNQUUxV3d1VXQ2VXhZSW94elZEbVRZcFREUjJiVnBLSW9xcXMzTXhQbkZzQkUwYzE3TW1VZmlldFlEMThPWGtTV1BYVDAyK0ErcDJ0UDVDU3RpZXdPcWJiN0YyNWd3QUk3LzJxd0NVM3Y4QXNiUG5TaDkrdU9tNGgzNzI1d0FJbDY0VFhqZkNaT2t2djJIS2JSQ2cxbElPcGxpN202ZGZSNmlkSjdMRFRxYS9iYUR5TjdZZ25uT1VKeUtlaUhqRUxLR0lnRWpOc1pWUEZJYzlicFZ6THFjdXJSVE9rdGFWMm85RTMxcU9MelVOSllyYmVXeWxzYWRvMW1XbWhVdGFqdlZjY05hNU5JL3FxOTI1ZW5acWNzNlZURk41N2swWExKVktSRGxoSW9VKytteTlzSFRwc2ptcEZkUlcvaHZGRjNmQnBmZE43MGhsNlRxaGJacnh4L2VZQXQ3ZkgxbFpNKzlFMFlWclpxZ1ZJTVYrRVBEM2ZTenF0WW1uRVQ4bW43MW5OMWdVMyt5ajI3TXVXUFVIbHA5ejkrNWI2OGZNNU9RaThCNVFiY2FnOXRnS3RyOFp4a0kxNmsxd3dxVC93U1BSVW0wcnI3NXFnZ1VnWWNxcmxXeHlpZVdqL0lIcEhhbGN2eDVOYm5MdXRyQnJseG1yaDNManBiOHo0UllYbzNBRER4MER3TC9IVEVJSFplM2Q5NkkwNHNja0Y5OWdFZGEzZ0duWFpvbno0QjFiR0tNQzZLbHFxS3FoUU9qY2lLcUNhczJ4bFE4dURudmNLdWZlK0xxME5zRVJmYlp3cmNsY3JiVlUrMGVyY2lSNVRJWWpKVnphdGZFa28rZlM3TFVaNHVJVzBTRWFEZU9wbnNlV3pNcG1URjRHNGVaL3lNQkExSlkzOENsanNjb2ZYYVRjNm1wWCswMFBTM0hvVGp3N01YM3RyYmRBWU8zc1dZS1pHWlRxQ2x4My9QZ2pGTys3RDBRbzJia2NheCtjNThiZnYyek8yN3hzaE9LOTk1cGZyVkpoN1d4dkRjT3lzeTZYQVVaUG5IZ3RlVDR1UXNDTVpncDdXWVIwa3F1S216aVhlT0FrcUVTOU1xMU92VkhsUGEwT3RCMmlvUjFjTXI5SlJDSmtmbkl5R2lLak1HMGVtZ3dMT3RSTElpU05DMWZYcU5obWs2SWQwQm4wRHpUVk5oZ1hJZGpWdG9JZi9wQ1NXeDNMempjdTdCckZ0ejB2VG95RU4xZFlPL045UUNpN09SeGhTSEZpb3FZUXBvbVFhTFV0QmYvdUNSRFExVFdDNmN0UjJHNElpVlk1MEVWZzNhbDhrUWpCOUlLVUFLNU1UbDZ5Vm1nZnlOQm1QSExYUkVnYXQ3YUtMaTBCUkJQWnZZSCsrdmhUcm5VV0VJaDZSSUlyUDZSc1hhcHp0MzE3OXRPM2Y3L1JRSGJ3UVBuQ2hjajFobXRyeGoxUE9CRlNMZXRwbFhjOEwxcStyVzlpd3JqeDgrZWpPU09wbGpLREhMQ0FWTnY5a29oRVNQd2pFbnMvYnhVUjRqNVJPdElXVVpNVUN5SktkUUpsOUFpakh5Yk5tNlJWM3RIWUQ1bXd6RmtURjQyNGpacFEvRlJXeGZXSVBBWk1OSTdpOXNNZER6MFU5V0tFUzRzb1FuRGhBc3R2dm1uRWNjbTRaWDlpZ29GanB2bWxNRzdtckFUVGx5bGZ2SWhDM2Q0bFVHMXlHWGpvSVFhT1BnUWlCTE5YVUlUeTVjdVVMbHhJTGNTWmhjbzVnYit1cXlwWlJDSWsvcWtKZXF1SUVQZUowdEZOeDZkSXBFZmk4elhzNHpMUG5jWXZmeVBYVmJVZXh2TFZwWkZ5VFZhNWFxYlRuMFlrUXVLWW5acjYzK2FiVHFoeXpOSWp5WERySVdzaVJJckZhRDIvY05Xc0hhaEIwTElJY2ZPRHd4OHRzVFpybW5qQ0c4dW1nSVNobVptbjRJM3NqTkl3NGtjSTVzeWNqM0J0RmNvQktsRFlPWXdpK0JNVFNMK3hmQVc3d0xvM3VJUEF6aE1wdld1YVhxSjVJeTY3WkV0d0pJU1JFeDVuZ2JkUlRWME1OUzVDSXVnTEw3d0NNUHVqcFdPS0xob3I0RFZkQUNGYklrVDZpaFRzb0FDM1NwWUdsWlpGU01FV3dOTHNURFJuSkUxY0ZBOGZBb3hvY09IY0N2dXlZMGNVajdkekJCRWppUHhkWTFFYm9nS1ZtWm1vSGJPVW1JS1pCWEhSQlBlaHFjakt1Mk5QSG4rYmRaQXFRaUJlc28xQnZWVkVTTTIzVGNabkw0NnNaWjI0VU11NG9EWFBNL2FEaVVZR1Z3R3g4U2RmaTI0TGljMXc5ZzdaQ09raTVFdGZLZ2tnVTFQZkFoWk1wUHIxRFdQTEtQdzk0d3djUFFyQXlxdW1kbEdaYjMydHY5WHZtamtjaFowN0kzRlJQUHdBaUZLK1BHMmFTQlFXL3ZBUHpHdmIzNDgzTUlBcURQLzh6NkVJZW5NMXNzSm1BSkpTbVY4dzdYc0t5OTh5L2NocUo2YjNsT0NJb1lBOGJxdFNLVk1VcTBnVklURXhZcGJ2SmFWeTNrTWl4TjVBNHJPSitIRHZ0TWJpU2NnTnFYL3ZhOFJLN0tTcjY4YXZkYy9iZmMrQ2tOZ01sMXFQVDBHcUNIRzRPam5wbHUxQVlkYkdQb1F5MkNqU3JJaVE0ajFtNndhempLL2gzREs3NGMyYkxZdVF2b1AzR2E1VWp1Wm4zUHplL3pQY3padUVidSs1UTNienc5akNSdUg4bkxHQXBSSzZacVpnRjY3dk5QVzlhd3RHY0NpcEU5T2g4NktoTFp6cUFuWThnWWgzeWY2T1N6UkFxZ2h4MEtlZXVvSWR4ejliOU4yRUVrU2tZUUcwWVdxT1crVXNrWmJRdXB3VEJkN3duUkVYWDJhM1ZSSGlOa0VzWDc0YzlVaTQ2WnZPM1FMYzhXbXoyWXkzY3lmZXlBZ0MzSGpwYndHcnZ1MWNFRGRVcTNMdFdxUnc2N0tUOGoyckhLYnd2UU13K3VTVERWMnZRNm9JaVlzUmg2Ukk2QWtSUXJ4Q2JQN2JTbnlwQWlieFFGVXhZaUwyQTZuV0NwTDF2bVZOU0xUS1JmZlRRc1ZWTnZMUkR2T25UbjBXSUVTL3FLb041NHgwMHdVWGhxcDdlSXo4NnE4QnhrcTVLWld1YWFQWitBYU9mSktpM2FwcjRBRXpxRFZlZDR2bnRkVjdLNzFuQnFTdW5UbkQyZy9PWk1PTmJvWlREVzNqL3U4VnZQQjNBRVlmLzhvWm1rQkRFUkwvUkZjb21SWWhOWUtKYWlWNTB3SW1rYmQ0L3BKNWJmWGVrdGd1Z2RCMnJ2WmVXdHA5cTZFSWlXUCsxS2wzekRjOXB4cTFjdGQzWnRJZEN5aHViN2ZkdTZOOTQ5WnNJM0F3T3hOTlRJL2kzQ0ErdDZPU3YyK2ZIV3BmUmJzc29GbHVWL0gzN1l2cWhXdnZuYzJPWld1V1UzMERKRVI0RHlkV20wUkRFWkxBV1lEWnlXZmZGOWZOSXBKYUFNMnAramU5a3lKRSt1eXVtYnQzUi9NL2JwNStIWUJnZGpaYW1yY216Z2J4dVRqOFBYdWlaWEdUK1V2TGF5djNGc1ZicWVBVml5alZYbzltSy81WjRGVGt0UDN2M09qalgybXBBRFlVSWVuQ0pGWjV6cEFJd1gzTWhaQ1NuODNFbDFaSGpuUHR1bCtGR3ZHU0pYR3hFVmZQTm8vMG5wQkc4UHovQmJ3Q1FGajV2NVlkdEordVllUlh6Q1QwOHZRMEs5Ynl1U2FTVkV1M0FRWis3TWNBVWd0Z3UrR1BqVkc0Nnk1alZiNzVqWTZuMXc2SWFmTmJFR0JBdkNjdHU5cHFQRTJMa0VpTXhIK1EyQ3ZSYlJGQzlHa2NydW40M0lOT0V3dHRFaUUxOFZDdFY1RTRacEZyRjVvV0lRNVhuM3R1RmRzL0RQd1BlM3hVMFU4Qm9IamRFQ0Z1RW5wbGZpRmFNN0Jad1pIRzNmemU5d3hWcU82RTNpbG9xWVNXekt5OWVPVys2K0lpamROb1NlZnZDZndmRzg1WnZ2cHQ2VGRBS3lMRVlkVWxPUC9zczM4TVVJRUJrRWRzamozWWZoSGkydFFxeThzdEM0NDBidlVOMDhVbUJUOFNPSjJDV2RyTi9JWnBWb2NNY1FwUkFjUXIvSkdBZCtjVFQ2eXdTYlFzUWhLZnVqcFN0MFNJKzBpVDRacm1wRnJUV085RDR0Z3FWMzEyMlJJWFRlUjV5NjZoNlo2UVJyZzZOZlV3OERDQW9sL3ZoZ3Z1R21mcmpwbHdqeDNqTkFBSkFQeFEvN0VOYzJuMHhJbW0rbnNib1dVUnNwNHdjVzlIdDBSSTE3allEK1dPdHhvWC81WXNvRnRGeXlJa0RWZW5wcTRJdkFHZ3FxL1lEQjhRWVg5dUFYdWZ3NHh3ZVJNMWxzK0dhVGpNcWxsc1JvU2tZZFordURJNStiTE45R1BBL3UwU0lkM21raGJrVnVLQU15Qi9qc0RvOGVOYmRydHhiRldFMUU5cWp5cW1HNHVMWnJrdEM0bE9jc1R2TmhzQ29VT0NveU5vaXdpcGkxVEVtNTE4OXZQQUx3TW9mQzUzd1QzSUtiOWhUMzE3L1BqeGwra0EyaUpDa3A5a3ZUSVhJYjNKYlFmYUlrS1NzQmJ3RFBBbkFOZzVKQXIzSTl3UENwcGJ3R3h4YWlhaktHY0UzRHplYjl2anVxdGJiUlh0RWlFMVVETkM5b3lxdm0wSzQrUzR2ZGwvanVwQlJLREZIaE5MMUNlV0VhN1pDbjFXT2JYdGZNQWJBbitDS3J0UG5IaVpEcVB0SXNRV1BpOStWRlZjVzZINzRYSVJraTJ1QnFycEwxMEgwREVSRWkrQWpyczZPWGtBT0FDZzZGL1k0QU9JRkhNWDNBVk9kUWxZdE13djJGT3o0OGVQdXgyTk9vNk9pWkQ0TWZwT2JZV1gySUkxdVFqWmZnNUlNWC9iaTQ2SmtIVXM0Q0x3SVFDcS85VUdmMWhWajluWGN5eTNnTnZBcVU1ajFnTS9EV28zdGhNM2xENnhxMk5uSWJSaFJFTVNTUXVZeGwxOTVwbjdBZFNUZjRISUYrMFQra1M3ODVLakhxcjZtdjN5eHdOQjViOERESjg4MmZwaU9XM0Fkb21RT3E0bUY3R0tQWWxqcGdUSExTSkM2SURSMlN5MlZZU2tjazg5NVdQbnBzd1YvZjhBRUNvL0RmeVVkUnVETnRMdXU5czBMdXN1Mk16ZEFIaFprRytqeXU0ZytMM29YazZlYkhrVWN6dXh2U0lraFl0bkptNEZnYnJLZnRjRlJ3K0trSnJuRzJ0ZXNVKzU3ZlgvVnJHdEltUWRDeGhpNXhJSXZJSUlxa3dEWmxLRzZpL2FhTWNVeGhJSjVSWXdmdFJvY2RGcFFhWVZCWFZiOE1wN0luTFc1VnN5VVBpZ3N6MGhEVVZJakVOVkE4dTlvcXJod20vKzVodkFFRUFsS0J1eEFrZEVaS3d1c2J3bkpINE1iUXZDSmVDMElQUUh3Vy9aSUt2REowOXVldTVHcDlBMUVkS0lnMXBYN05CMXdaRnhFUUpFYmFpOWd1NkxrQ1k0QU51THNoOUFQWDRiUUdDdkt1T0p4RzhyRnd4NkRyY0RlUkQrZSt0UkZuWi81U3ZSbHFoWlJ0ZEZTRE5jc3BwUVUrRyt6VVdJYXIzMTZ5VXIySDBSMHJ3RlhIVGZGYjRHSUhBSTFOUVJWWTdhMDZPZ3RWdEs5TG9GVkhWTkpRdUlMS0lnb3FkdDRITmlOeHBYMVFWckFUTlgxMXNQV1JBaEczS1dYNVRxZXNNdkFzeE9QWE1NT3gwVXFzc0dpMGo5bmlZOUxFSVVTclpBemdMbmpRblVQN0xueisxKzRzdnJiZ2FZZFdSU2hDUTVad21UNmF4M1U3ZWFDSUZhQzVtb3QyZW1WMk16NkJrUjBpeG12dnJWSXJablJjcmx6d0NnZXRpNGEwRDBaMjNRSVZYVDFCUExlRmRjc08ydHNEMFc4azNBVS9nQmRrM0c4WEw1RlJzODdIYlBSYnZSVXlJa21jNTZYRVBFekV4V1JFanlOeUdsa2JqOVppSWI2QmtSQXNZRko5Tktjak5mL1dyVXM0TGRNZ0JUZHpLTFpncy9BRkRZRllrVlpkU2N3a2NvMm12TVBCYWxDT0xIT2RDaWlMR3lybmRMbFVDZ2hJQ3FPQkZRRWxkL0UxMng1aThBS2RudnJxbGtBWEQ3Tkp6REZFQm5GVU1nZEEzTjZVKzhkeUYwYVRoV0sxeWNUMHRuTTl6TWM3OHhyckFYUUFMdkFJQ0lEb3E0Q1ZReWJxN2xUaFN6QVVqVUUxTU5oeXNVeWlwaXh0S0ZLbk5pbnV1eXdJL010YUV0YkxJaWVDc0FLdktPdlg1eDl4TlA5RVM3WGJ2Ujh5SmtLNXdZeTVKcVZXS2VPa1FrUlFtYkVKRnJqSjIyZGJ4bXJWVlBpNGl0NHY4RHlQK29PeDZwQWVNQUFBQUFTVVZPUks1Q1lJST0iPjwvaW1hZ2U+Cjwvc3ZnPgo=" k="name"/>
        <prop v="0,0" k="offset"/>
        <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
        <prop v="MM" k="offset_unit"/>
        <prop v="35,35,35,255" k="outline_color"/>
        <prop v="0" k="outline_width"/>
        <prop v="3x:0,0,0,0,0,0" k="outline_width_map_unit_scale"/>
        <prop v="MM" k="outline_width_unit"/>
        <prop v="diameter" k="scale_method"/>
        <prop v="40" k="size"/>
        <prop v="3x:0,0,0,0,0,0" k="size_map_unit_scale"/>
        <prop v="Pixel" k="size_unit"/>
        <prop v="1" k="vertical_anchor_point"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" value="" name="name"/>
            <Option name="properties"/>
            <Option type="QString" value="collection" name="type"/>
          </Option>
        </data_defined_properties>
      </layer>
      <layer class="SimpleMarker" enabled="1" pass="0" locked="0">
        <prop v="0" k="angle"/>
        <prop v="33,150,243,255" k="color"/>
        <prop v="1" k="horizontal_anchor_point"/>
        <prop v="bevel" k="joinstyle"/>
        <prop v="circle" k="name"/>
        <prop v="0,0" k="offset"/>
        <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
        <prop v="MM" k="offset_unit"/>
        <prop v="255,255,255,255" k="outline_color"/>
        <prop v="solid" k="outline_style"/>
        <prop v="0" k="outline_width"/>
        <prop v="3x:0,0,0,0,0,0" k="outline_width_map_unit_scale"/>
        <prop v="MM" k="outline_width_unit"/>
        <prop v="diameter" k="scale_method"/>
        <prop v="25" k="size"/>
        <prop v="3x:0,0,0,0,0,0" k="size_map_unit_scale"/>
        <prop v="Pixel" k="size_unit"/>
        <prop v="1" k="vertical_anchor_point"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" value="" name="name"/>
            <Option name="properties"/>
            <Option type="QString" value="collection" name="type"/>
          </Option>
        </data_defined_properties>
      </layer>
      <layer class="FontMarker" enabled="1" pass="0" locked="0">
        <prop v="0" k="angle"/>
        <prop v="A" k="chr"/>
        <prop v="255,255,254,255" k="color"/>
        <prop v="Arial" k="font"/>
        <prop v="" k="font_style"/>
        <prop v="1" k="horizontal_anchor_point"/>
        <prop v="miter" k="joinstyle"/>
        <prop v="0,-0.40000000000000002" k="offset"/>
        <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
        <prop v="MM" k="offset_unit"/>
        <prop v="255,255,255,255" k="outline_color"/>
        <prop v="0" k="outline_width"/>
        <prop v="3x:0,0,0,0,0,0" k="outline_width_map_unit_scale"/>
        <prop v="MM" k="outline_width_unit"/>
        <prop v="11.8" k="size"/>
        <prop v="3x:0,0,0,0,0,0" k="size_map_unit_scale"/>
        <prop v="Pixel" k="size_unit"/>
        <prop v="1" k="vertical_anchor_point"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" value="" name="name"/>
            <Option type="Map" name="properties">
              <Option type="Map" name="char">
                <Option type="bool" value="true" name="active"/>
                <Option type="QString" value="@cluster_size" name="expression"/>
                <Option type="int" value="3" name="type"/>
              </Option>
            </Option>
            <Option type="QString" value="collection" name="type"/>
          </Option>
        </data_defined_properties>
      </layer>
    </symbol>
  </renderer-v2>
  <customproperties>
    <property value="fid" key="dualview/previewExpressions"/>
    <property value="0" key="embeddedWidgets/count"/>
    <property key="variableNames"/>
    <property key="variableValues"/>
  </customproperties>
  <blendMode>0</blendMode>
  <featureBlendMode>0</featureBlendMode>
  <layerOpacity>1</layerOpacity>
  <SingleCategoryDiagramRenderer diagramType="Histogram" attributeLegend="1">
    <DiagramCategory backgroundAlpha="255" lineSizeScale="3x:0,0,0,0,0,0" minimumSize="0" penAlpha="255" spacing="0" sizeType="MM" opacity="1" width="15" rotationOffset="270" scaleBasedVisibility="0" direction="1" lineSizeType="MM" maxScaleDenominator="1e+08" enabled="0" showAxis="0" penWidth="0" sizeScale="3x:0,0,0,0,0,0" penColor="#000000" labelPlacementMethod="XHeight" diagramOrientation="Up" minScaleDenominator="0" height="15" spacingUnitScale="3x:0,0,0,0,0,0" barWidth="5" spacingUnit="MM" backgroundColor="#ffffff" scaleDependency="Area">
      <fontProperties description="MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0" style=""/>
      <attribute color="#000000" field="" label=""/>
      <axisSymbol>
        <symbol type="line" alpha="1" name="" force_rhr="0" clip_to_extent="1">
          <layer class="SimpleLine" enabled="1" pass="0" locked="0">
            <prop v="square" k="capstyle"/>
            <prop v="5;2" k="customdash"/>
            <prop v="3x:0,0,0,0,0,0" k="customdash_map_unit_scale"/>
            <prop v="MM" k="customdash_unit"/>
            <prop v="0" k="draw_inside_polygon"/>
            <prop v="bevel" k="joinstyle"/>
            <prop v="35,35,35,255" k="line_color"/>
            <prop v="solid" k="line_style"/>
            <prop v="0.26" k="line_width"/>
            <prop v="MM" k="line_width_unit"/>
            <prop v="0" k="offset"/>
            <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
            <prop v="MM" k="offset_unit"/>
            <prop v="0" k="ring_filter"/>
            <prop v="0" k="use_custom_dash"/>
            <prop v="3x:0,0,0,0,0,0" k="width_map_unit_scale"/>
            <data_defined_properties>
              <Option type="Map">
                <Option type="QString" value="" name="name"/>
                <Option name="properties"/>
                <Option type="QString" value="collection" name="type"/>
              </Option>
            </data_defined_properties>
          </layer>
        </symbol>
      </axisSymbol>
    </DiagramCategory>
  </SingleCategoryDiagramRenderer>
  <DiagramLayerSettings showAll="1" zIndex="0" linePlacementFlags="18" dist="0" obstacle="0" placement="0" priority="0">
    <properties>
      <Option type="Map">
        <Option type="QString" value="" name="name"/>
        <Option name="properties"/>
        <Option type="QString" value="collection" name="type"/>
      </Option>
    </properties>
  </DiagramLayerSettings>
  <geometryOptions geometryPrecision="0" removeDuplicateNodes="0">
    <activeChecks/>
    <checkConfiguration/>
  </geometryOptions>
  <referencedLayers/>
  <referencingLayers/>
  <fieldConfiguration>
    <field name="fid">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="osm_id">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="name">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="amenity">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="hstore_to_json">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
  </fieldConfiguration>
  <aliases>
    <alias field="fid" name="" index="0"/>
    <alias field="osm_id" name="" index="1"/>
    <alias field="name" name="" index="2"/>
    <alias field="amenity" name="" index="3"/>
    <alias field="hstore_to_json" name="" index="4"/>
  </aliases>
  <excludeAttributesWMS/>
  <excludeAttributesWFS/>
  <defaults>
    <default expression="" applyOnUpdate="0" field="fid"/>
    <default expression="" applyOnUpdate="0" field="osm_id"/>
    <default expression="" applyOnUpdate="0" field="name"/>
    <default expression="" applyOnUpdate="0" field="amenity"/>
    <default expression="" applyOnUpdate="0" field="hstore_to_json"/>
  </defaults>
  <constraints>
    <constraint exp_strength="0" field="fid" constraints="3" unique_strength="1" notnull_strength="1"/>
    <constraint exp_strength="0" field="osm_id" constraints="0" unique_strength="0" notnull_strength="0"/>
    <constraint exp_strength="0" field="name" constraints="0" unique_strength="0" notnull_strength="0"/>
    <constraint exp_strength="0" field="amenity" constraints="0" unique_strength="0" notnull_strength="0"/>
    <constraint exp_strength="0" field="hstore_to_json" constraints="0" unique_strength="0" notnull_strength="0"/>
  </constraints>
  <constraintExpressions>
    <constraint field="fid" exp="" desc=""/>
    <constraint field="osm_id" exp="" desc=""/>
    <constraint field="name" exp="" desc=""/>
    <constraint field="amenity" exp="" desc=""/>
    <constraint field="hstore_to_json" exp="" desc=""/>
  </constraintExpressions>
  <expressionfields/>
  <attributeactions>
    <defaultAction value="{00000000-0000-0000-0000-000000000000}" key="Canvas"/>
  </attributeactions>
  <attributetableconfig sortOrder="0" sortExpression="" actionWidgetStyle="dropDown">
    <columns>
      <column type="field" name="fid" hidden="0" width="-1"/>
      <column type="field" name="osm_id" hidden="0" width="-1"/>
      <column type="field" name="name" hidden="0" width="-1"/>
      <column type="field" name="amenity" hidden="0" width="-1"/>
      <column type="field" name="hstore_to_json" hidden="0" width="-1"/>
      <column type="actions" hidden="1" width="-1"/>
    </columns>
  </attributetableconfig>
  <conditionalstyles>
    <rowstyles/>
    <fieldstyles/>
  </conditionalstyles>
  <storedexpressions/>
  <editform tolerant="1"></editform>
  <editforminit/>
  <editforminitcodesource>0</editforminitcodesource>
  <editforminitfilepath></editforminitfilepath>
  <editforminitcode><![CDATA[# -*- coding: utf-8 -*-
"""
QGIS forms can have a Python function that is called when the form is
opened.

Use this function to add extra logic to your forms.

Enter the name of the function in the "Python Init function"
field.
An example follows:
"""
from qgis.PyQt.QtWidgets import QWidget

def my_form_open(dialog, layer, feature):
	geom = feature.geometry()
	control = dialog.findChild(QWidget, "MyLineEdit")
]]></editforminitcode>
  <featformsuppress>0</featformsuppress>
  <editorlayout>generatedlayout</editorlayout>
  <editable>
    <field name="amenity" editable="1"/>
    <field name="fid" editable="1"/>
    <field name="hstore_to_json" editable="1"/>
    <field name="name" editable="1"/>
    <field name="osm_id" editable="1"/>
  </editable>
  <labelOnTop>
    <field name="amenity" labelOnTop="0"/>
    <field name="fid" labelOnTop="0"/>
    <field name="hstore_to_json" labelOnTop="0"/>
    <field name="name" labelOnTop="0"/>
    <field name="osm_id" labelOnTop="0"/>
  </labelOnTop>
  <dataDefinedFieldProperties/>
  <widgets/>
  <previewExpression>fid</previewExpression>
  <mapTip></mapTip>
  <layerGeometryType>0</layerGeometryType>
</qgis>
