<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis labelsEnabled="0" simplifyMaxScale="1" minScale="100000000" readOnly="0" hasScaleBasedVisibilityFlag="0" styleCategories="AllStyleCategories" simplifyLocal="1" simplifyDrawingHints="0" simplifyAlgorithm="0" simplifyDrawingTol="1" maxScale="0" version="3.14.1-Pi">
  <flags>
    <Identifiable>1</Identifiable>
    <Removable>1</Removable>
    <Searchable>1</Searchable>
  </flags>
  <temporal mode="0" enabled="0" durationField="" durationUnit="min" endField="" fixedDuration="0" startField="" accumulate="0" startExpression="" endExpression="">
    <fixedRange>
      <start></start>
      <end></end>
    </fixedRange>
  </temporal>
  <renderer-v2 toleranceUnitScale="3x:0,0,0,0,0,0" tolerance="20" enableorderby="0" forceraster="0" type="pointCluster" toleranceUnit="MM">
    <renderer-v2 enableorderby="0" symbollevels="0" type="singleSymbol" forceraster="0">
      <symbols>
        <symbol force_rhr="0" type="marker" name="0" clip_to_extent="1" alpha="1">
          <layer enabled="1" class="SvgMarker" locked="0" pass="0">
            <prop v="0" k="angle"/>
            <prop v="231,113,72,255" k="color"/>
            <prop v="0" k="fixedAspectRatio"/>
            <prop v="1" k="horizontal_anchor_point"/>
            <prop v="base64:PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIGlkPSJteVN2ZyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+Cgk8aW1hZ2UgaGVpZ2h0PSIxNjAiIHdpZHRoPSIxNjAiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBS0FBQUFDZ0NBWUFBQUNMejJjdEFBQUFDWEJJV1hNQUFBN0VBQUFPeEFHVkt3NGJBQUFmK1VsRVFWUjRuTzJkYlhCYzEzbmZmOC9GWWdHQ0s1Q0VJQktpUllnbUtlc2xpc1RLa2p4anExT0NyRVVyWTlHSzR6aDFPa2svNUVQZkp0TnBwek9aZkdnelRqdnRkUG9oazhsNDBwbSt1SEVuZFZMSEx5UVZ5WFlaa2FQWXFrYVdGY3BtS0ZvQ0tacWlKQkFDUVpBQ1FYQUI3Tk1QenpuM1pmZnU0bTJCdmJ1OGY4N3lYdnp2T2ZlZWUvYnM4NXovZVJWVjVaYkNrU2UyQTZDRkJ5QjR3TEc3amRNK2tENEFBdG5xcnZXNUQ2Z09BaWphaHhnbkdsUVFVTlVaUVdaQVFabEFBSmhCbUxiYnlBUUtvRE1vc3dnVmhKOENxSEJhTm5TZFJvRlAvOTlySWhLb2FzVWZBVHFWQzVyeXBlYklzVUpJSXdzWUw3bHRneU5QOUNvVUFVUjZIZ1Nnd2lDb1dUVFJYd0JRbFVFQmIrVTJBeWdVQlFvV1RrckdhVUdRSWhhcHo0VXJpTmd6UUN4L2xIbWdiSnpPdUhCbEVlWmR1QmwzanpJWXB6QXVBaWhqSU9NdTd0OGlCS282THNJNEN2UVZ6bURoNXVYSlk1V3NXYkhWY0lWRzMyWGJGVDVERVNpNTg4Y0JGUDBGUWJ5Ny9XUVlVaVFaVXpXRkE2UXF2RWFrcWdZaVlnVlZwTmY5b1B0RkpBeG5uR0xoc0dQNHd4ZUFDc284QWdqSDNLTk9BejkxanprWFMxRjVPWm1SZGVRdU9FZEwwZEFGWng1SERqd0NQQUtBOGx0MjRDNFI3b29IVXpYcnN4YWNQNDhmZ2JYaVJnWGVCQ0RRUDNiSmVWTU9uUmpObW10ZEt0ZlFCYmNaQW9pOFpZNzJRUHRZd0tQN3QrSkZ3d0w3QUZTNFIwUjJBYWl5MXdKcXY0ajB4Nk4yaWdWRWRSS1l0SG9rcjdya25BUE9XbUxrbUl0M1RaNTU0VnJXckYwYTEwNFdjQ3RnUWtMNGJUc3dDQXhBbFQ3b1VDZ01pTWdBcXFpeXgzNEVlaEc0NEFKNHRYd1J1TmJDcEM0WjdTbENURlNpdWNNbDhYc1RrcXE5RFpCTkYzeDAvMDVnR0FDVlAzVHNrUHVFV0V2WHVsUnVuVVhJVXJrM1JjVEVTbGZsZDEyeXgrV3pKeWF5NW9MYjB3TG02QmkwM2dJKy8xU2dTQ0FvbEc4ZUFrRkZQeVp3cjB2aVoxeklFbEVEc3lHMTRYaWRPWDhlUDBLcnVVbEVKaHgzektYNmIwRlBBVkMrNHdmK1ZlU0wzNkNWRnJEbElrUWhFQWhjRDhFdkF3anlFUEJRSWx5YUs2UzJ1clBlbkQrUEgyazlOeUF3WU5ka2owdnBDWVhOTHQxaEFXdzFjaGVjbzZWb25Rdit5MC92QW1CaDRkZFJ2bVFtSmV5dnJVRVdCRWNhbDFFUjBwQVQ0VVZuT3I4QndmOEI0TkN4OFZ5RTVMamxzTDRXOE1qSUVNcFdHOEFwditIc3lsN0U5MkxJWU4yNFdSQWNhVncyUlVoalRxemhXcFdUQ0QrMk41R3Z1YmVia3MrdFh5L0tlb3VRclFnUEFnajhFOGNWOGVQdEdpQUxnaU9OeTZnSWFjd3B3eUtDaUE0QWo0T0N5b2xZcEhYclJjbGRjSTZXWXUxYzhQTlBGV0x0ZS84ZEJJU2E1cFVsSXd2dU5vMXJSeGVjeXZtUjNYb0MwYjhDNEhQSC8wUGJ1bUJGbkVVWE93dDlWb012cng3bk02d2FXZURFK2EzRWtmYmoxQ3Y2K0tzbEM0dUlCQURONUpwdkFRLy9mVGZQb3ZLZ3IrK0IvSlo3NXlFa25JZXhQR1RCMnFWeEhXSUJyWTRvZ0o1WE9DY0F3bGRSQWVFTXlCa1UrTnl4NmF4YndLMUFCZmg3d0JjYzk4Q1NyVjF1QVZ2Q2llZVFuWUx1QkFHbDdDNThHOVdMSUJVUm1XbW1CVndMRVZJaFRkejRGMDhyVkl0eEVQMXlzOFpaL1NsNTdCUk9GS2VLQThUcWlOVUZTRlVycStHYWJ3RkZ2K3hPSHNBUElNM1JubEErNHlyeS9WRDVLR1lPZjZlWmoxZ1RFUko2ejVXNDI5d0ZaNDRMaFNTMWRiaHNpSkREQi9ZQU95MkYrQUdrVzdFaDg4MUJGZ1JIR3RjaElxUXhSelRzUDlCLzdISmhYQTRkWC9VQTEyWlp3SjNBcDkzNTZnUkhiZ0d6eU4wRmVwZHp3V0cxU2xYSHN5aENvc1N2UkhEa0lpVGJYQXpORUNHcmM4R0hSMXd6aS93YUlsOW9ISGlWeUlLN1RlTnVDUmVjNEdidHRmVi9DUHhYQUo0NWZyTFZMamlKM0FWM0x1Y0taanhYVmlOTWxtOEJuOTBmenMzUUJmMERTNHc4aU1pRHk3dlJNcEVGYTVmRzNYb1cwSzMyeGN1b3ZneEFnZDl6M0x3OGZXSityUzFnQ2JkQ2dTRFBPQzU1bjl3Q2RqSlhBRVdWaHhEWkpWQUIvVTh1OEl5cWx0ZERoQVQyVVV0WU5Yemkwd3JRU2poTGVlMXpzc0JsU1NDc0kyZmZUcmg4WDFpTzFyNG5aRUUrRC94VDk3VGVaY2ZQMFNub0Z3bjZVWVVGK1NQSGZRUDQxbkp1c2dJWDdINE5EWVBrTHZpVzRpS1BzSVlpNVBDSUcwZ3F2d0h5bTNhNndxRlZLMEVXQkVjYWQrdUprRFR1TklEQ253akIxeERnMExHeHBvb1FGV3NCRjlnRml4UzgzQUxlYXR3RHpqUHVCcmFpQkNJeTNsUVJJbXFmcFFXVzVIRzFuS1c4OWpsWjRESW9FRm9vVENvb0FVS3pSSWhFQlZSRy9xTTcyOXc0VG81YkZxcFBvcnJML1hWd0tWSHlXWEU1V29yR0l1VFprZTM0TmZrcVlqT2xsRjZGUlBPTHF3MkU1MDJ2OUlKTlRhaEthaFk0bXpJaCtGRno2bkxpbHVSVXA4UXZJYXg2QUROd1V6eHpmSkk2V0dTZkVCa1M1Q0gzc00zdVNhbU5NRFZjayt1QmtxSkdzOERadVN1UThjSjZLM0t3R1pITllvWmpwN3RTRVpHcGVpbzRkOEU1V29wVUM2alBQMVVVQkZIMm9mcmJhUzBST1hJMFJDQmZkbWRmQmI1V045ajZwQ1pIam5TazF3SG55NCs3czNzUXQ1R2Yrc3BtSkRnODFrK0VKSi9jTXE2N2hIVGJhc0U2OElDOS83VzNrUS9Qbzc3NjZ1TzY0eTNJN1hTWGR1dmhmYnM0TWhKdzZQaWJ2aTdvajZrRlVOQkg3VmF5QzlmdWw5QUlxWEdxaVE0V0lkMGw2TFBHQWRtK0QwUXMzSWZuc3lFR3NzRU51OTZTWGFyc2NWbjRaaTVDY21RSzZTNjR3cGV3RnA2N0pGY2dqZEY5bTVuL3JwNlYzeU1vUWxmUnFoeWYrSDFBNE4wWDROMFR4czFmYjFKaVd3QmxyeUFGVjBmN2J2WGwzQUxtYUNraUMvamNTRkg5VHVQSVhXNjlwUDdxbnBKY2hOaTdoajBoMkhYMStiQ1N5dnVXZTVHQkJ5MFBOd3doSXVnZEgwZTZiek51OU90WkVoZkw0MnpMQ05zcTRzZVBGdlRWajFmNDhhTkJyUWhSaWlKdUl4aGh1eDkwblNJdmNoRVMvaGY5NE1MY1drbmxmZlBINEtPSDdGbGUzQlJLc1BsZUJJVzN2cDRsY2JFOERoa0Erc0xNVXkwZ1VoRVJjaEdTbytVSUxhQXVCQStBUGdJZ3RmWXN4MXBpOGczZ20xYmwrTVYvYnR6VWFSaC9OVkVOYVU5b0VaRWlxdkRPYlU4NDhqeHVyWm5jQXVab0tVSUxLS29Ed1AxQU9NUW1EYmVjQ0luMWV0QXpZTnlHUWFUM0RuZDlvNzEvYVFkeSs4T1dkemV2R0RjM2pjeE5XOTVVeXZVcjZyTWZJRmRPVzdqM2Y0QWc2T1JQSXk0V0p6UGlZZ1djcU4rM2ptdXFlaDZTN1lCYmdmc0FGbXY3dTZWRVNLelhnLzdkeHZVT1FPK0F1NzRSRUtTMEl5eGtUTDFsd21SbURCYktkbDh0MTYrbzMvZ0FaaWNzM1BzdkdYZDFGSzZkalg0UVdSTVhLK0ZFN25IdEJ1ZnpucEFjbVVDQkkwODQvMUs4RjJSZlMxUFRLaFEyMm5ITC9URGdsci9iNGFZMEZFcFFkRm5rZXlRV2JrS2xiT2NUcjl1eGZ6ZmM2ZXJZODlPQVFOQnR2UndBNy8rMVdkZkowM0RsakJtQ3l5ZHIwL0xPZDVQVmtEamlQU2FEZSszNjlBV1lmbWUxT2JBdVVDclAyQ2pxeWp2QUM1Q0xrQnd0UmdFSzk3bnpRVnlkc05FOGtZNFJJVDJia09JbSsyUDdpSEY5MnhCZjM1dTFhUXhhZmhzcHU2M1Q3bkxoNW1lUXNsbER2VHFLS0doeEM3TEo1ZDNFNjVZblhSdVFRcSs5UnVsdVJOUzQwdDBtVnJxNnJkZGorbDFrNXIzRksvU2xqeUMzN2JTOEh2cVV4UjEveFlTT0F1WEp6QWlPVkU1bDBCV1FPL1RvdmdHZUhhR0EzMUZiR01SWnhNWGFBVHRDaEJRM1FXbUgvYkhyODhaMTlaaUxBeGo3b1hHVHArSEtHOFlObTF1V3lnTE1mV2puVTJldGtyM0paYU1JZkhEU1JFajNSdWd1MmZOMzIvcWRVcnJiamdCejA0UkR1V2JlVzd4Q3YzRTdiSHZjNHQ2MTMranlORnc5YXowbU55ZXpJempTdVFFclhUcUlXejg4ZDhFNVdvb0NHdndkZHo1MFMzU0FlSEV4OUNtNDgxUEphM1BUVUhZekNILzZGVHZ1ZkJvZSsvTHludUY3TXk1OEQ5NzVudFZQK29iTUNwZDJRR25Zcmp1cnlQWVJzMTZxOE1OL1plRVd5cUJ6eWZ0ZStwR0pIbFdZR28xRXpiV3o3ZFpqTWtTRnZXaHVBWE8wR0FYUVhnQ0ZRb01Pa0JCdEtVTGlnbVByWThadEdFVG1wbzN6OHp0bXhwQ3JaNDNiWUdKRWkvMVdONHpmajZpZUhGYXlVVHY2dVRNaWFPOFdwSCszVmNESGYrVENCVWhwT0JsT3VwQXU2eTdsemlmczFhK09JdGZPSlN2MHVvQlV5cGJYVTI5RXZTaGtVSEEwNExCTnlrc0lRUUczeW9GQW9hYmRxUTdhVG9URUJjYzJtMjhsQ3pkZGV4MWhBWlNaUzNEWnRldHRkTU9paXBzallaSjRWMWVBZkNYYnNmRmVKT2taZ00xNzdNcVovd2tJNHR4dklselFCVjA5bHZZN1AybkNaS0VNMTg1VlZlZ1hvRkt4Y0pPbkl3RWowbXB4c1N3T3BLaWlKVUZ5RjV5anRTZ2didTBYdC9KOVIySEROanZ1T0FoM2Y5Yk96LzZGSFNkZWo2emQ3US9iY1dZTWJseXk4d2YvbVIwck4yR2l1c2NpeFFmY25EUXhBRkNlanVvbGZVTjJuTGxrbHZuY042MkpSNEdyMW1kTTkwYWJXNExDSi8vQTRnWkZ1TTJhYk14NmRoQ1VraWgzUWk1Q2NyUVlCZFR0K1FIRldubFJpN1lTSWM2eTZjYnRrWkR3WE84Z3N1Vis0MmF2R0RkL0EzRTlJSHo0YytNK3ZCRFp1NG8xaXlpUkRkUWJZL2IrSDd5RzNMaGtTZlpEdEtRTGtTNnJnUGNNMkNzRlJXVEJDWWxodHh0cXNSL3AyUnoxamlEb2hpRkUzZXBUWFVVTFYxbEFxR1JDU0t4T2hHZ1JLSUZTd0xsZWdXTEhpWkE3OWhxMzhTT1JrQmgwM0pZSGJGQUJ3TnZmTnU3bTVTaWM2K0NYMlVtNGFRWFVEMGFvWFIzTERiMmFlTTMrM3JRYkVDVG90c0tqUU84VzQxQTNiRXRoeDVNV3Q4ZUdkOFhmUlBxR2pGTkF1cDNRS0lOV01pRWtWaVZDQkZjQWN4ZWNvOFVvZ0hTV0NPa3VoYzBxWWE5SEdycUtOYzByOU4wWmNZLy91L3B4Wjhic0EzRG1hL2FyM25FdzdDdE94Y1RyRnU3U0t6RCtJK00yMzdPMDlBMS9ockRYWStxTituSGFCVW9KdFo2MzNBTG1hQ25DT2lCUVhNcWVJWmtYSWQwbHhQVmkrRUdqU3BjMTlzYkRxVWFOd2RmTm1tblFoZlRjWGorYzUyQnBQU0V1cnFwQ3o1WXduK1RtcEwxYTdIb1lMaTN1YmNNVzkvcTdtUkVTcTV5c1hoQ3hEcEFDRWhiQXdsS25ZMlphaEhTWHdsNE1yMXB0cmY5a0FVd1VxaHRXQUdYREVHeThvMzQ0endGTDZnbVJHTmN6NE1KaGs1YmlRa1lXaVZzYXRyaHVXRmdXaE1UcUpxdmpldUEwZDhFNVdvc0NhanRnQTcxcTdUTU5rWGtYM0RlRURMcWVqYlBmTkc2aGJIMi9BUGYvSStPQ0l1TG5hN2hiYUhFajByY3RlYjltdWVEdWpYYnUyL1FFbUw5dTUwRTNFaFF0M09XZklDaDY1UTAzTFZQZ3NTOWIzSW1UMlhHanErTUtBcjBnRkVodXRjbFNzTGdMOXU0bDdpSlh3L21DbmZMTUdxNjJIaHYrS0dJcGxab0FNVGNSdjFUUEJjY3kxSTZMdUZIU3d5ZTQySHRMR0NybXFsUGpTaHR5NEgvR0JVWGRoQWY2VVRKdUFaUFBUZVc2ZWhBL3k2M2ZOdTNSRDg4ajE5NDN6dlVGYTgrQU5RQkRPTHhlaFNpdXYxODlDNml4YzVaZ0FUMFhDOCtsVit4OG9leUdXYWtiWG8vMW9telk1dVpTYUcxY2ZQSE0wRDRoUytXVVdSR1pBbE1qYmt5U21jU2xJTk1XTU9pRzRtMzJoeHVNSURPWG90NE0xd1lucFdHNHpZMU1udk05SEVSeC9mM1cwZ0w2dE14T3drMmJVT1RiRjJYd1lSamNtN0RlSFdNQmhWbGdTb0ZDdEF4SDB1TFVRK1l0SUxHeGNTNVZpa2FjcG5CaHVKVDdyYVVGOUsrWmtvY2hwOXA1RmpCOFQrc0xIbmM1MlFzTTBFbm91OU9PdTM0bG1uOHg5WllkcjUyRnE2TjJYblpPNE9kSGJiZ1VSSlBWZTI4UDE0UUowVlcwU2VkZ2JZZ0NuUHNXdlBQOVpMaUZjalNCL2Rvb3lhTGxPV3hTKzdiSDdNY3hmTkNDZEJWdDJkLzJtdXV4SklneURZeUJVQkNrWW16NDMrSTNXSlJyc1FpcDVsTGFHT091TFJwWWtNTFZmYTdFZzhYY1kxVzQ4SmgwUlZVdUtVcW5TME9xU3crUEdYQ2pxK0RpS0tCaEhiRGNhRldzNklidDVJSWRGM2VqZm9XclRYdHNrU0d3MldhQWJyZ0QyZUFhb2d1MnFLZDI5VVROTmY1K2M5T0lxemVHU2UwZFJQby9hdmtRdUtZV1hVQjAzcHp6MXNlTW16eUZUSjR5bDdUenMrYVNlcllndlFQMnVsMUY0eVNvZGVsaFhtZkJqYTdLQlpjRkszY0ZpQXBneHpURE5MS0FmbFdyM3BoYjdmMHo0d1llRElkd2VSY3NjVGZxN3pmOVRqUmN5MXV2RFhmQXdQMzI2RUtwOWpYNmQ1dGxlK3ZyTUhuS0xNTE9ROUY3VkwxS3lIV2dCUlNSc3NLMEVGOGhGVHBRaERndVRVakVPUzhvNHZjTHhZb3IxSWxuYU5nQUhpYlY1MFA4TldKSEJCS0xtUk1URjR2MUJYc3VIcGRXVzdHVmN5NDdBSnNKTjJhRTd1eUkrdTdNV0RUWHcvZUlMQlZ6MDJHL2NEaVVLNlcvbWI0N3dTMnhFYzREMlhJL0REMngrSStyZWdqWVVuQmozSDRaYzIyOFgwZ1MwOEQ3a0ZpZ1Vtcnl1UjZ5N1lKVDBwYldscGNRSnU2UThnTmMwM2JBcXV0MTQ3b2UvVTV4d2ZHV2dJSXFNeGFnUTBSSWZGNkg1M1RCNXRSQ3VGNWZVcGhzTVM3b2lpYXJoM0diMUE1WWRzdjJMcFNSb0R1czh0UjN3WlptQlppNVpPNTdicnBUWEhBWjFFU0l3RldYcjUwaFFoWnUyQlRKT0tjTDRkQXNYd0NUd3VSMnh4VnEzRnpUTEtEcmlaR0ZjcWlTRzFwQWwyYUJxSGZFcjhpVkFTdTJ5bWFZTW9HR0toandsV0lXUmVZdElOU09rQUZxaEVSQ2hNUUZCL1hESlo1QklzNlNla0o4bW4xK05iS0ExT2FydXE4eEMxWnN0VDBoUGtjTFNPV2t1L0NMSFNGQ3BpL0FoeGZzM0MrOWNYWFVWcE1DbUoreFkvOXVOM3NOOEVPd3B0K0JTYmZjN2IyLzJkeDArVjRYZ0UxN2t0Zm1yMXRhVmVEVVZ3Q0YyL2RHVFVJWHZtZEhQdytscmFHQVhpVGdaYWphTGJNalhIQ0NjK1pmSlhFdmNIK0dqWGlTRXRkZmFwSUw5cHpHNHNXZml5Q2llSnNxVmZkUGUxYml1VzNCeFR5QkVvaFFLYUNWOHhhMGF3SW9BMmlEZ2FtWmQ4Rng3Z05iVWtPN3VoRzN4UUx2SGpldVBJWDRKVGY4Y3J3M0p4RTNTZDB2UHE3ZEc2TjlRdnd6Ym55QXpGNjI4d1czLzBmNUtqSXpsblNaNFRBcndDL2xlLzFkWkhiU3VMTi9ZUzZwRWd2WE4yVGhDcVVvWDJmYzVQZjJGeUhqcm1oZUZodUZWU2xRdm53T2dPNnRIeUJXQUVXa1lXTlYyMWhBMXg0b3R6OE1XOXpxOTI2d1FidzNJeHkyRmUvMThISDd0a1g3aFBobnpGNk9SSVVMTCtXcmNPTlNWUDhVTVVYdENnMXUyYmZFMEt0ejMwcmtuUURzL2hVN0w1WWl6cTFYMHdFV2NNeForRWwrNllWcllNMHdRZXpsS2hCVnBOUFFWaFl3YmVoVlhIQ0U5NCtIcXhZcktjOUFvcDZRMlB0YlQ0ZDMrMnB4cS9JbUlTNDA1WFZEUVJLUEcxbVJERml4RlhQeENvZEhRYjU0eXVhRUhONS9CdFR2YVAxRk9nRithRlZsRGphNm9WbWYrUGQyblB2UWVqNEFMdi9FanBPbjRjcHBPNy93dkF0M1BRcm5VZnVMczZGVm8zK1d2RkN3UmNwUllIYk1PTCtmaUFMRFQxclFEZHNzZmZFZjRma2o4TE0vV1hVV1pBb3F2bnlGaWl3UWtVQkVBcXJtaHRUN3NBaVhkSi91dUZwT3hFeTR5TXE0bERxRHFHQ2xwOHJOSTRsUGFOSHJQS1BhN1FoeHp1Y25kVGovbXBMSTkrVDlhbDFiOGhudHc2V2g0SGV1NXZEK0NWeko3QmdYN0xscmJ5TVhYN0EvN3JPVlVqWG9zazJoSWR3RFRsV2pvVmRqUHpCdThPRndDNGJ3ZnZIaFdINm0ycWJkeUtZOXRTTEVyNFQxODZQR2xYWWdXeCsxVjl1d3pkeHR3YTJtcFFwalB6U1hOZld6YUFKNzU3aGd2NjdJaE0vTGdyTis2Skg5VThCYlVQc0ZWaU90TENlNWpJZ1F6MTE3RzI1OFlIOTg3TmVOQzdxaHNNRzRvdHZqbzZzWXpRbngrNFRjdmpjVUJ1SDlZZ3RaaXUrbEdIb0NoZzhtSHUzRGlhcXRsZzgyRjJYcjQ4YTVaMFZXVVdEc0pUdS9PaHJ1dWhuWjVscHIwbFpjVURuajZzQmhBUXhVdGFLcUZaU0s0djVwL1ErTGNQYVRsZVJ4dFp4YXV1Si9MNDhEczlIUkorMDM1a1dBTzNIaGFrTjZBWUZHbGo5OGlzK0hNSno5OWhOeVJ4V1Z5TlBFajk3b3grOGJ2WUcyTlFlMXhpdHFpQTQ0SjhpRUJhNDRNdDF2WnhLUC9JNGRQemdaYlFJNDQ1YmJuWitPaE1RUC9xVWRQN0lmUGpKaTU3NlpwYlFqbWlsMzFwcEl1SEVwdEY0TlY5dEt3OFRKYUo2STN6dWtmN2Radm5nMVoreUhadmtVdVBoZG9rcE5HK1YvSGRqOEQ1MFdCWjQ1L25MMTlWQ0V1T3lvQUpWSVlFUVY0OHlMRVAvQ29RK3VGeTVXcmErSkcvdkMvUzFTVEdYaUVTRW40VDNTaFVRc2JyMXdVdXZHc2lZa2xzc2xNNjBXa1FoNTlrQVpQenhmZWM5TXB2U0RKcm9CL0crekhoZCtzZXNoUXJiY2kyeSsxLzd3UXFLck45d0t3VGZENlB3TlpQNkdjVzZrakU2Y2pJWmV1WFg5dEhzVDBsTzFnZUhDamJDZUY4YWR2OUY0TU1LVk4xenk1Nk45UXZwMzIvWHVVclNMdXQ4ZC9jcHA1T3BvNkt5eUlocWF3UUZUd0FYcUlCUWhXRGRjR2FEeW5aR0xMdkpkaU5Rc1hKbFdtSlBjT29tUXpmZkN6cWZ0RDcrYmVXazQ2czF3M1c3Q0pDeTRKWEI4RDhibDE2Tk5DTjBld1ZJQ2ZBRjBPMlBLK0Nzdy9tb3k3a0k1VEV1YUJmU0xTRXBRalBZSjhac1p6azI3TldFMGRNK2hXSW5kTVJPaW9RbWNaVDZ4a1JoSmhDSWsvb2wvejVrV0lTbnUwY0tSVUFvSmNSRVhKbzN1NTBWR3BFY1NsOExyOGVmRzhpdkJFUk1hL29wV0NST3lKeHFhd1MyR1Fpb3JZWXYxUGxTM0wrbE9yY0RsaytBR0JmQUp0NlR1OUR2UlBBMjM4R1ROcG45Z1ZsS2RwWHpsMzlxeGJ5amNvb3U3bmVBb0RjTkRmczhRSHplMlk3cGZsdGNQZHZDY1loYno1aVFnOERmLzJZemIxVkdYdm5pbHBUTUVSeDJNS3ZwOHZiY0xSVWo4RXcrUWJSRkNMSjVMYnpMeHRlRVd2Vi95SnBGYmxOaEJRazRTNFZ4K0tZbm5DaG9tTWU2eVd5MFExa3VFK0o5WUdpSVJFc2VSQTM4Tm9PaDJnWWNBVk5sYzcyWnhMdnl5MTBPRTNMeUsrUHF0RzdTcDE5OUZycjlyM0lKYm9sY1g2cXd0V0hXL3VlbEljTHp2ZWtLS201R2VmdU9LYmxLN2YwK3dmVUlVRzZKMTVRMXpQVE5XbjlNRkV6K0sySEFzc0NGZlJPNHFhNktoaWR3RmwwZHZLcHlTT3V1UkY2b3RIb0QrNVZNdklpQnpzdytoT3VVczNHWi9QYzJjSnJsMUVpRnoxMkRPclM3bmV4cmNjQ2U3MVZ3c2JqSnk2djNtcjRkN2dWUVBnUUlpb1JORUs5aUhGczBONVJJSXF3RFYxakhKeGQ5Tk9wRFQ4NjVBL2t3T0hUOUZIYVNLRUNSVzczWmZYQ1pGU0lJakVnVXI3akZaaEhNUHNXZkVua2Z5Mk9xS2Z4WTRTQmJPZWtnWElVODlWeGFBb3dkZVVIUlNyREI4ZGRHN3RSSys5Nk5SaFdPMThIc0oxOVk1aUJ6eldqMjh6UkJVWE5jVUZ4c0ZTM1hCSG5wa2Z4Q2ExWG9WL1ZSdW5WeHdCcmhxbDVvOVY5ZzZMbDVYcm9kMEVlTHg3RWcwRGFzU2pMdXprcUo5OFdDMUJrSFdSNFJrZ0xOcGxwbXArTGVVQTUwRUpsekJ1K2dLbjE4Q09oV05MYUF5QmxnaFBMemZGMEJFcEs4NmJHNEJzMkYxV3NsaHc2ek9BUERaRXcxZHIwZGpDMGhVT0JPbHY2cEpJN2VBMmJKRXJlTnc1MHV2QjZlTGtDaXJ3OElwWFNQL0JvQUtYMEk3Wk01SWpxWkFsSXB6dThjSStNcmlOYjhJRFYxd0hIcDBYL1JBcVgxQTdvS3o0d3JYbTR2cmY3RUc1d1plTllsRlhIQU16NDZjY1dlanF1cUgxd3dUZTdnL3oxM3dyY1dKY2xLRml0aVVqbEFyTEFWTHRvREFtd0I2ZU9Tc2hQMWZNdXd2NWhhdzlaYW9aWnpvcSs3S0tFKy9zS3dDbU5vVDB1Z1RqNXl0bnBEV2NGbnFmV2dWdHhvc0lrTFNvTjhCWGdRUWtmL255RDZVbXFhWkhKMExnVW5BZXNrcThydU9ubTBVSnczTGNjRUFWTDZ6TCtZWm81cGZVcGprTHJqVHVacE1XU0dXTGtJOGpvek1ZcVVmd1BZM1VCNEhmZFJ4UVM1Q09wcWJFUURsTllXWHpFYUl0M3p6TEJQTHRvQ1ltWjBGMENQNy9oUUExVjVGSGdHdysrVVdzSE01dFJVK1JWOFQrRjlBd0M4Zm0yR0ZXTFlJcVNkSXhIMXlFZExaWEZUdHN2SlR2Mmd0RGRKb0haZ2w0K2lCdllDdEoxdlJyK1l1dU1NNDFYbng3alhRRVpjTkYzbjYrSkw2ZXh0aEpTNjRCbnBraE1nbnhkMW43b0k3ZzB0Q1U3aVZZdmtpSkExSEQ0d0JiajFjZlZGdFFzNU9rT0hjQXJZL0I1eFI5Q2Z1ZkVuRHJKYUtwbGhBclB0bEhFQVA3ei9oRXJnUGREaTNnTzNQSVp3V3hKYVphSUxialdOVklxU09NTEVDbll1UWp1SFdFczBSSWRVM0ZRbjAyeU5mQUg3TkNENmZ1K0QyNHdUNWZmZkt4em4wVnlkWUF6VExCU2VncWhVTzc0K0lWUXVUYkxqYk5LN1RYYkJTOC9wTlJYTkVTQldjQlR3Ti9Ma1I5SUdneWg2UVBhRHVTOHd0WUdZNFpkNFZ0Tk1JcCt3cmtPT09xN3U2MVdxeFpoWlFSRTZyNmlrUkNmVEkvcTJvSXNoVHFyckxsdkJnR1QwbTJiQjJhVnpuV0VDZEIxQTRLZWlmSThKYXVkMDRtaTVDWE9FTDRrZFZSVVhNblB0Q2xZdVFUSEVlOXRPWFJkY0pieGJXVG9URUNtRElIUjNaQ2V3RW9DTGZkc0Y3Z1dMdWdsdlF2cWRjd3hhUVJKR25YWmFQeStlT3JkdXVpR3ZwZ3NOQzZEbWUzVjhkTWdpL3pkd0ZyenRuaGRFWW45VXAwMzNXRkdzblF0SXQ0QlJ3SGtEUi8yWmZwTzVWZU1qcWlBem1GbkR0T1lIM2dJckFxNkEvQWxDVmNaZmwwK3RaQm9VbWpHaW9SajBMbUNpWWgwZjJBQ2o4QTBHL1pOa2o5MFhDM3g5ek5CLzZzck4vZnlvOU4vODNBQWRmbWx3azBwcGd2VVJJRGVjVElPSC91UWhaUDhHaFFWWiszT3NyUWxMZDhzY0wrTGtwQy8zLzJ0M2k3eUx5U1FEVTFxSEpncnRONDdMdWdrWEZXN1lUQkJ4WEJlbXYvSmZ3WmZZZFgvWW81bVppWFVWSXVqQjV0Q3B1VlVWWUlodlpETkhRYks1ZFJJaEJ3Mll3NTJPYVh2OWZMdFpYaEtSYndBclJYSUlYUlFEaFBkRFhBRkFPdVd1RDdoTWl0NEExNHNLV3lGRGVBOTV6U2Z5dUs0WnZnYnlwYWorYUxCUSthS0VJYWNUcGN5T2JSU2lwZ3N6Skh3SW9QQ0FpOXpVN3JSMEYxWGxYSUY4RmJIT1QzdG5mYzFkbk9malNpdWR1ckJWYWJ3SFR1T2YySlpvRDdhWWttbVVndDRBMUZsREE5a0gyQ1NYemFMMElXUUlIb0VjTzdCUzNGbzFTK1NQM3BDRlJ0c2FmZmFzVlFOQlJvcDJJL29VN1RuTG9oWEJMMUN5ajVTSmtLUnlBeG9aM0pTclhWVTMzdDVvSThYVzY2alMyQzdMcGd0TXQ0SlRQWTBYL0dFQlU3Z0g4ZHVZUHVtc0RBdUdXRXREK0ZsQVFKOUowRXBoeWozNVZBQkZHY1J1TkV5MFlrTG02WGoxa1VvU2tXc0NxdndIME8vc2ZBclhwb0NMLzBORzczS2VUTUFPZ3F1ZEVPR2ROS1BZakJFWTVkTHp1Wm9CWlI5dFlRSER0aG5FY1BrQ3E3MWxIc2JKT0ZqQjZOaUJKZGRGMEE3S2VhQnNSc21SOC8yQVIzN015Ty9jWkFGUS9oc2c5THNRdnVXTUpKYkVWYmFzS29MbldzTWZpT2F4UXZRSHlKZ0EzeDE1MDF5cjg2cW1XOWx3MEcrMGpRdEpjY0JyM3ZTZHJFMVJ2akZFVEJFd3pSRWpWQTFLWHVLM3BJZW9RdExjTFR1TytmekRlczNMR0JScEg1TFRqM0M3VjNBNXFZa1Zsd04ydGdFalJuZHQ2aDBwa1VYRnJJRXJFaFNvVTVoSGNIcTVPQktodEFxNkFpS3ZId2J3UWh2Tk5KWk1nYnQ5WlJyRUNPT2srRmFEaUNsOG1laSthaWZZV0lhdmhqbzVzQld4ejRBWFo2ZWcreEJjeXRmYkZDcmRobzdaQnhIVUZhcDhmSkFIaUM4VXN3clRqSmhRTlJKa0cvUkNBd0JVMlpRYkVxVlE5Z3hXcUtRNGRiNHQydTJhajh5emdFams5dWgrUlJoWWw3SUtweEdjTHhGN1NqcFYwM3loSVpZbGRFVzB0SWxhTC93OW1xM0hEcHVqR3NBQUFBQUJKUlU1RXJrSmdnZz09Ij48L2ltYWdlPgo8L3N2Zz4K" k="name"/>
            <prop v="0,0" k="offset"/>
            <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
            <prop v="MM" k="offset_unit"/>
            <prop v="35,35,35,255" k="outline_color"/>
            <prop v="0" k="outline_width"/>
            <prop v="3x:0,0,0,0,0,0" k="outline_width_map_unit_scale"/>
            <prop v="MM" k="outline_width_unit"/>
            <prop v="diameter" k="scale_method"/>
            <prop v="40" k="size"/>
            <prop v="3x:0,0,0,0,0,0" k="size_map_unit_scale"/>
            <prop v="Pixel" k="size_unit"/>
            <prop v="1" k="vertical_anchor_point"/>
            <data_defined_properties>
              <Option type="Map">
                <Option type="QString" name="name" value=""/>
                <Option name="properties"/>
                <Option type="QString" name="type" value="collection"/>
              </Option>
            </data_defined_properties>
          </layer>
        </symbol>
      </symbols>
      <rotation/>
      <sizescale/>
    </renderer-v2>
    <symbol force_rhr="0" type="marker" name="centerSymbol" clip_to_extent="1" alpha="1">
      <layer enabled="1" class="SvgMarker" locked="0" pass="0">
        <prop v="0" k="angle"/>
        <prop v="245,75,80,255" k="color"/>
        <prop v="0" k="fixedAspectRatio"/>
        <prop v="1" k="horizontal_anchor_point"/>
        <prop v="base64:PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIGlkPSJteVN2ZyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+Cgk8aW1hZ2UgaGVpZ2h0PSIxNjAiIHdpZHRoPSIxNjAiIHhsaW5rOmhyZWY9ImRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFBS0FBQUFDZ0NBWUFBQUNMejJjdEFBQUFDWEJJV1hNQUFBN0VBQUFPeEFHVkt3NGJBQUFmK1VsRVFWUjRuTzJkYlhCYzEzbmZmOC9GWWdHQ0s1Q0VJQktpUllnbUtlc2xpc1RLa2p4anExT0NyRVVyWTlHSzR6aDFPa2svNUVQZkp0TnBwek9aZkdnelRqdnRkUG9oazhsNDBwbSt1SEVuZFZMSEx5UVZ5WFlaa2FQWXFrYVdGY3BtS0ZvQ0tacWlKQkFDUVpBQ1FYQUI3Tk1QenpuM1pmZnU0bTJCdmJ1OGY4N3lYdnp2T2ZlZWUvYnM4NXovZVJWVjVaYkNrU2UyQTZDRkJ5QjR3TEc3amRNK2tENEFBdG5xcnZXNUQ2Z09BaWphaHhnbkdsUVFVTlVaUVdaQVFabEFBSmhCbUxiYnlBUUtvRE1vc3dnVmhKOENxSEJhTm5TZFJvRlAvOTlySWhLb2FzVWZBVHFWQzVyeXBlYklzVUpJSXdzWUw3bHRneU5QOUNvVUFVUjZIZ1Nnd2lDb1dUVFJYd0JRbFVFQmIrVTJBeWdVQlFvV1RrckdhVUdRSWhhcHo0VXJpTmd6UUN4L2xIbWdiSnpPdUhCbEVlWmR1QmwzanpJWXB6QXVBaWhqSU9NdTd0OGlCS282THNJNEN2UVZ6bURoNXVYSlk1V3NXYkhWY0lWRzMyWGJGVDVERVNpNTg4Y0JGUDBGUWJ5Ny9XUVlVaVFaVXpXRkE2UXF2RWFrcWdZaVlnVlZwTmY5b1B0RkpBeG5uR0xoc0dQNHd4ZUFDc284QWdqSDNLTk9BejkxanprWFMxRjVPWm1SZGVRdU9FZEwwZEFGWng1SERqd0NQQUtBOGx0MjRDNFI3b29IVXpYcnN4YWNQNDhmZ2JYaVJnWGVCQ0RRUDNiSmVWTU9uUmpObW10ZEt0ZlFCYmNaQW9pOFpZNzJRUHRZd0tQN3QrSkZ3d0w3QUZTNFIwUjJBYWl5MXdKcXY0ajB4Nk4yaWdWRWRSS1l0SG9rcjdya25BUE9XbUxrbUl0M1RaNTU0VnJXckYwYTEwNFdjQ3RnUWtMNGJUc3dDQXhBbFQ3b1VDZ01pTWdBcXFpeXgzNEVlaEc0NEFKNHRYd1J1TmJDcEM0WjdTbENURlNpdWNNbDhYc1RrcXE5RFpCTkYzeDAvMDVnR0FDVlAzVHNrUHVFV0V2WHVsUnVuVVhJVXJrM1JjVEVTbGZsZDEyeXgrV3pKeWF5NW9MYjB3TG02QmkwM2dJKy8xU2dTQ0FvbEc4ZUFrRkZQeVp3cjB2aVoxeklFbEVEc3lHMTRYaWRPWDhlUDBLcnVVbEVKaHgzektYNmIwRlBBVkMrNHdmK1ZlU0wzNkNWRnJEbElrUWhFQWhjRDhFdkF3anlFUEJRSWx5YUs2UzJ1clBlbkQrUEgyazlOeUF3WU5ka2owdnBDWVhOTHQxaEFXdzFjaGVjbzZWb25Rdit5MC92QW1CaDRkZFJ2bVFtSmV5dnJVRVdCRWNhbDFFUjBwQVQ0VVZuT3I4QndmOEI0TkN4OFZ5RTVMamxzTDRXOE1qSUVNcFdHOEFwditIc3lsN0U5MkxJWU4yNFdSQWNhVncyUlVoalRxemhXcFdUQ0QrMk41R3Z1YmVia3MrdFh5L0tlb3VRclFnUEFnajhFOGNWOGVQdEdpQUxnaU9OeTZnSWFjd3B3eUtDaUE0QWo0T0N5b2xZcEhYclJjbGRjSTZXWXUxYzhQTlBGV0x0ZS84ZEJJU2E1cFVsSXd2dU5vMXJSeGVjeXZtUjNYb0MwYjhDNEhQSC8wUGJ1bUJGbkVVWE93dDlWb012cng3bk02d2FXZURFK2EzRWtmYmoxQ3Y2K0tzbEM0dUlCQURONUpwdkFRLy9mVGZQb3ZLZ3IrK0IvSlo3NXlFa25JZXhQR1RCMnFWeEhXSUJyWTRvZ0o1WE9DY0F3bGRSQWVFTXlCa1UrTnl4NmF4YndLMUFCZmg3d0JjYzk4Q1NyVjF1QVZ2Q2llZVFuWUx1QkFHbDdDNThHOVdMSUJVUm1XbW1CVndMRVZJaFRkejRGMDhyVkl0eEVQMXlzOFpaL1NsNTdCUk9GS2VLQThUcWlOVUZTRlVycStHYWJ3RkZ2K3hPSHNBUElNM1JubEErNHlyeS9WRDVLR1lPZjZlWmoxZ1RFUko2ejVXNDI5d0ZaNDRMaFNTMWRiaHNpSkREQi9ZQU95MkYrQUdrVzdFaDg4MUJGZ1JIR3RjaElxUXhSelRzUDlCLzdISmhYQTRkWC9VQTEyWlp3SjNBcDkzNTZnUkhiZ0d6eU4wRmVwZHp3V0cxU2xYSHN5aENvc1N2UkhEa0lpVGJYQXpORUNHcmM4R0hSMXd6aS93YUlsOW9ISGlWeUlLN1RlTnVDUmVjNEdidHRmVi9DUHhYQUo0NWZyTFZMamlKM0FWM0x1Y0taanhYVmlOTWxtOEJuOTBmenMzUUJmMERTNHc4aU1pRHk3dlJNcEVGYTVmRzNYb1cwSzMyeGN1b3ZneEFnZDl6M0x3OGZXSityUzFnQ2JkQ2dTRFBPQzU1bjl3Q2RqSlhBRVdWaHhEWkpWQUIvVTh1OEl5cWx0ZERoQVQyVVV0WU5Yemkwd3JRU2poTGVlMXpzc0JsU1NDc0kyZmZUcmg4WDFpTzFyNG5aRUUrRC94VDk3VGVaY2ZQMFNub0Z3bjZVWVVGK1NQSGZRUDQxbkp1c2dJWDdINE5EWVBrTHZpVzRpS1BzSVlpNVBDSUcwZ3F2d0h5bTNhNndxRlZLMEVXQkVjYWQrdUprRFR1TklEQ253akIxeERnMExHeHBvb1FGV3NCRjlnRml4UzgzQUxlYXR3RHpqUHVCcmFpQkNJeTNsUVJJbXFmcFFXVzVIRzFuS1c4OWpsWjRESW9FRm9vVENvb0FVS3pSSWhFQlZSRy9xTTcyOXc0VG81YkZxcFBvcnJML1hWd0tWSHlXWEU1V29yR0l1VFprZTM0TmZrcVlqT2xsRjZGUlBPTHF3MkU1MDJ2OUlKTlRhaEthaFk0bXpJaCtGRno2bkxpbHVSVXA4UXZJYXg2QUROd1V6eHpmSkk2V0dTZkVCa1M1Q0gzc00zdVNhbU5NRFZjayt1QmtxSkdzOERadVN1UThjSjZLM0t3R1pITllvWmpwN3RTRVpHcGVpbzRkOEU1V29wVUM2alBQMVVVQkZIMm9mcmJhUzBST1hJMFJDQmZkbWRmQmI1V045ajZwQ1pIam5TazF3SG55NCs3czNzUXQ1R2Yrc3BtSkRnODFrK0VKSi9jTXE2N2hIVGJhc0U2OElDOS83VzNrUS9Qbzc3NjZ1TzY0eTNJN1hTWGR1dmhmYnM0TWhKdzZQaWJ2aTdvajZrRlVOQkg3VmF5QzlmdWw5QUlxWEdxaVE0V0lkMGw2TFBHQWRtK0QwUXMzSWZuc3lFR3NzRU51OTZTWGFyc2NWbjRaaTVDY21RSzZTNjR3cGV3RnA2N0pGY2dqZEY5bTVuL3JwNlYzeU1vUWxmUnFoeWYrSDFBNE4wWDROMFR4czFmYjFKaVd3QmxyeUFGVjBmN2J2WGwzQUxtYUNraUMvamNTRkg5VHVQSVhXNjlwUDdxbnBKY2hOaTdoajBoMkhYMStiQ1N5dnVXZTVHQkJ5MFBOd3doSXVnZEgwZTZiek51OU90WkVoZkw0MnpMQ05zcTRzZVBGdlRWajFmNDhhTkJyUWhSaWlKdUl4aGh1eDkwblNJdmNoRVMvaGY5NE1MY1drbmxmZlBINEtPSDdGbGUzQlJLc1BsZUJJVzN2cDRsY2JFOERoa0Erc0xNVXkwZ1VoRVJjaEdTbytVSUxhQXVCQStBUGdJZ3RmWXN4MXBpOGczZ20xYmwrTVYvYnR6VWFSaC9OVkVOYVU5b0VaRWlxdkRPYlU4NDhqeHVyWm5jQXVab0tVSUxLS29Ed1AxQU9NUW1EYmVjQ0luMWV0QXpZTnlHUWFUM0RuZDlvNzEvYVFkeSs4T1dkemV2R0RjM2pjeE5XOTVVeXZVcjZyTWZJRmRPVzdqM2Y0QWc2T1JQSXk0V0p6UGlZZ1djcU4rM2ptdXFlaDZTN1lCYmdmc0FGbXY3dTZWRVNLelhnLzdkeHZVT1FPK0F1NzRSRUtTMEl5eGtUTDFsd21SbURCYktkbDh0MTYrbzMvZ0FaaWNzM1BzdkdYZDFGSzZkalg0UVdSTVhLK0ZFN25IdEJ1ZnpucEFjbVVDQkkwODQvMUs4RjJSZlMxUFRLaFEyMm5ITC9URGdsci9iNGFZMEZFcFFkRm5rZXlRV2JrS2xiT2NUcjl1eGZ6ZmM2ZXJZODlPQVFOQnR2UndBNy8rMVdkZkowM0RsakJtQ3l5ZHIwL0xPZDVQVmtEamlQU2FEZSszNjlBV1lmbWUxT2JBdVVDclAyQ2pxeWp2QUM1Q0xrQnd0UmdFSzk3bnpRVnlkc05FOGtZNFJJVDJia09JbSsyUDdpSEY5MnhCZjM1dTFhUXhhZmhzcHU2M1Q3bkxoNW1lUXNsbER2VHFLS0doeEM3TEo1ZDNFNjVZblhSdVFRcSs5UnVsdVJOUzQwdDBtVnJxNnJkZGorbDFrNXIzRksvU2xqeUMzN2JTOEh2cVV4UjEveFlTT0F1WEp6QWlPVkU1bDBCV1FPL1RvdmdHZUhhR0EzMUZiR01SWnhNWGFBVHRDaEJRM1FXbUgvYkhyODhaMTlaaUxBeGo3b1hHVHArSEtHOFlObTF1V3lnTE1mV2puVTJldGtyM0paYU1JZkhEU1JFajNSdWd1MmZOMzIvcWRVcnJiamdCejA0UkR1V2JlVzd4Q3YzRTdiSHZjNHQ2MTMranlORnc5YXowbU55ZXpJempTdVFFclhUcUlXejg4ZDhFNVdvb0NHdndkZHo1MFMzU0FlSEV4OUNtNDgxUEphM1BUVUhZekNILzZGVHZ1ZkJvZSsvTHludUY3TXk1OEQ5NzVudFZQK29iTUNwZDJRR25Zcmp1cnlQWVJzMTZxOE1OL1plRVd5cUJ6eWZ0ZStwR0pIbFdZR28xRXpiV3o3ZFpqTWtTRnZXaHVBWE8wR0FYUVhnQ0ZRb01Pa0JCdEtVTGlnbVByWThadEdFVG1wbzN6OHp0bXhwQ3JaNDNiWUdKRWkvMVdONHpmajZpZUhGYXlVVHY2dVRNaWFPOFdwSCszVmNESGYrVENCVWhwT0JsT3VwQXU2eTdsemlmczFhK09JdGZPSlN2MHVvQlV5cGJYVTI5RXZTaGtVSEEwNExCTnlrc0lRUUczeW9GQW9hYmRxUTdhVG9URUJjYzJtMjhsQ3pkZGV4MWhBWlNaUzNEWnRldHRkTU9paXBzallaSjRWMWVBZkNYYnNmRmVKT2taZ00xNzdNcVovd2tJNHR4dklselFCVjA5bHZZN1AybkNaS0VNMTg1VlZlZ1hvRkt4Y0pPbkl3RWowbXB4c1N3T3BLaWlKVUZ5RjV5anRTZ2didTBYdC9KOVIySEROanZ1T0FoM2Y5Yk96LzZGSFNkZWo2emQ3US9iY1dZTWJseXk4d2YvbVIwck4yR2l1c2NpeFFmY25EUXhBRkNlanVvbGZVTjJuTGxrbHZuY042MkpSNEdyMW1kTTkwYWJXNExDSi8vQTRnWkZ1TTJhYk14NmRoQ1VraWgzUWk1Q2NyUVlCZFR0K1FIRldubFJpN1lTSWM2eTZjYnRrWkR3WE84Z3N1Vis0MmF2R0RkL0EzRTlJSHo0YytNK3ZCRFp1NG8xaXlpUkRkUWJZL2IrSDd5RzNMaGtTZlpEdEtRTGtTNnJnUGNNMkNzRlJXVEJDWWxodHh0cXNSL3AyUnoxamlEb2hpRkUzZXBUWFVVTFYxbEFxR1JDU0t4T2hHZ1JLSUZTd0xsZWdXTEhpWkE3OWhxMzhTT1JrQmgwM0pZSGJGQUJ3TnZmTnU3bTVTaWM2K0NYMlVtNGFRWFVEMGFvWFIzTERiMmFlTTMrM3JRYkVDVG90c0tqUU84VzQxQTNiRXRoeDVNV3Q4ZUdkOFhmUlBxR2pGTkF1cDNRS0lOV01pRWtWaVZDQkZjQWN4ZWNvOFVvZ0hTV0NPa3VoYzBxWWE5SEdycUtOYzByOU4wWmNZLy91L3B4Wjhic0EzRG1hL2FyM25FdzdDdE94Y1RyRnU3U0t6RCtJK00yMzdPMDlBMS9ockRYWStxTituSGFCVW9KdFo2MzNBTG1hQ25DT2lCUVhNcWVJWmtYSWQwbHhQVmkrRUdqU3BjMTlzYkRxVWFOd2RmTm1tblFoZlRjWGorYzUyQnBQU0V1cnFwQ3o1WXduK1RtcEwxYTdIb1lMaTN1YmNNVzkvcTdtUkVTcTV5c1hoQ3hEcEFDRWhiQXdsS25ZMlphaEhTWHdsNE1yMXB0cmY5a0FVd1VxaHRXQUdYREVHeThvMzQ0endGTDZnbVJHTmN6NE1KaGs1YmlRa1lXaVZzYXRyaHVXRmdXaE1UcUpxdmpldUEwZDhFNVdvc0NhanRnQTcxcTdUTU5rWGtYM0RlRURMcWVqYlBmTkc2aGJIMi9BUGYvSStPQ0l1TG5hN2hiYUhFajByY3RlYjltdWVEdWpYYnUyL1FFbUw5dTUwRTNFaFF0M09XZklDaDY1UTAzTFZQZ3NTOWIzSW1UMlhHanErTUtBcjBnRkVodXRjbFNzTGdMOXU0bDdpSlh3L21DbmZMTUdxNjJIaHYrS0dJcGxab0FNVGNSdjFUUEJjY3kxSTZMdUZIU3d5ZTQySHRMR0NybXFsUGpTaHR5NEgvR0JVWGRoQWY2VVRKdUFaUFBUZVc2ZWhBL3k2M2ZOdTNSRDg4ajE5NDN6dlVGYTgrQU5RQkRPTHhlaFNpdXYxODlDNml4YzVaZ0FUMFhDOCtsVit4OG9leUdXYWtiWG8vMW9telk1dVpTYUcxY2ZQSE0wRDRoUytXVVdSR1pBbE1qYmt5U21jU2xJTk1XTU9pRzRtMzJoeHVNSURPWG90NE0xd1lucFdHNHpZMU1udk05SEVSeC9mM1cwZ0w2dE14T3drMmJVT1RiRjJYd1lSamNtN0RlSFdNQmhWbGdTb0ZDdEF4SDB1TFVRK1l0SUxHeGNTNVZpa2FjcG5CaHVKVDdyYVVGOUsrWmtvY2hwOXA1RmpCOFQrc0xIbmM1MlFzTTBFbm91OU9PdTM0bG1uOHg5WllkcjUyRnE2TjJYblpPNE9kSGJiZ1VSSlBWZTI4UDE0UUowVlcwU2VkZ2JZZ0NuUHNXdlBQOVpMaUZjalNCL2Rvb3lhTGxPV3hTKzdiSDdNY3hmTkNDZEJWdDJkLzJtdXV4SklneURZeUJVQkNrWW16NDMrSTNXSlJyc1FpcDVsTGFHT091TFJwWWtNTFZmYTdFZzhYY1kxVzQ4SmgwUlZVdUtVcW5TME9xU3crUEdYQ2pxK0RpS0tCaEhiRGNhRldzNklidDVJSWRGM2VqZm9XclRYdHNrU0d3MldhQWJyZ0QyZUFhb2d1MnFLZDI5VVROTmY1K2M5T0lxemVHU2UwZFJQby9hdmtRdUtZV1hVQjAzcHp6MXNlTW16eUZUSjR5bDdUenMrYVNlcllndlFQMnVsMUY0eVNvZGVsaFhtZkJqYTdLQlpjRkszY0ZpQXBneHpURE5MS0FmbFdyM3BoYjdmMHo0d1llRElkd2VSY3NjVGZxN3pmOVRqUmN5MXV2RFhmQXdQMzI2RUtwOWpYNmQ1dGxlK3ZyTUhuS0xNTE9ROUY3VkwxS3lIV2dCUlNSc3NLMEVGOGhGVHBRaERndVRVakVPUzhvNHZjTHhZb3IxSWxuYU5nQUhpYlY1MFA4TldKSEJCS0xtUk1URjR2MUJYc3VIcGRXVzdHVmN5NDdBSnNKTjJhRTd1eUkrdTdNV0RUWHcvZUlMQlZ6MDJHL2NEaVVLNlcvbWI0N3dTMnhFYzREMlhJL0REMngrSStyZWdqWVVuQmozSDRaYzIyOFgwZ1MwOEQ3a0ZpZ1Vtcnl1UjZ5N1lKVDBwYldscGNRSnU2UThnTmMwM2JBcXV0MTQ3b2UvVTV4d2ZHV2dJSXFNeGFnUTBSSWZGNkg1M1RCNXRSQ3VGNWZVcGhzTVM3b2lpYXJoM0diMUE1WWRzdjJMcFNSb0R1czh0UjN3WlptQlppNVpPNTdicnBUWEhBWjFFU0l3RldYcjUwaFFoWnUyQlRKT0tjTDRkQXNYd0NUd3VSMnh4VnEzRnpUTEtEcmlaR0ZjcWlTRzFwQWwyYUJxSGZFcjhpVkFTdTJ5bWFZTW9HR0toandsV0lXUmVZdElOU09rQUZxaEVSQ2hNUUZCL1hESlo1QklzNlNla0o4bW4xK05iS0ExT2FydXE4eEMxWnN0VDBoUGtjTFNPV2t1L0NMSFNGQ3BpL0FoeGZzM0MrOWNYWFVWcE1DbUoreFkvOXVOM3NOOEVPd3B0K0JTYmZjN2IyLzJkeDArVjRYZ0UxN2t0Zm1yMXRhVmVEVVZ3Q0YyL2RHVFVJWHZtZEhQdytscmFHQVhpVGdaYWphTGJNalhIQ0NjK1pmSlhFdmNIK0dqWGlTRXRkZmFwSUw5cHpHNHNXZml5Q2llSnNxVmZkUGUxYml1VzNCeFR5QkVvaFFLYUNWOHhhMGF3SW9BMmlEZ2FtWmQ4Rng3Z05iVWtPN3VoRzN4UUx2SGpldVBJWDRKVGY4Y3J3M0p4RTNTZDB2UHE3ZEc2TjlRdnd6Ym55QXpGNjI4d1czLzBmNUtqSXpsblNaNFRBcndDL2xlLzFkWkhiU3VMTi9ZUzZwRWd2WE4yVGhDcVVvWDJmYzVQZjJGeUhqcm1oZUZodUZWU2xRdm53T2dPNnRIeUJXQUVXa1lXTlYyMWhBMXg0b3R6OE1XOXpxOTI2d1FidzNJeHkyRmUvMThISDd0a1g3aFBobnpGNk9SSVVMTCtXcmNPTlNWUDhVTVVYdENnMXUyYmZFMEt0ejMwcmtuUURzL2hVN0w1WWl6cTFYMHdFV2NNeForRWwrNllWcllNMHdRZXpsS2hCVnBOUFFWaFl3YmVoVlhIQ0U5NCtIcXhZcktjOUFvcDZRMlB0YlQ0ZDMrMnB4cS9JbUlTNDA1WFZEUVJLUEcxbVJERml4RlhQeENvZEhRYjU0eXVhRUhONS9CdFR2YVAxRk9nRithRlZsRGphNm9WbWYrUGQyblB2UWVqNEFMdi9FanBPbjRjcHBPNy93dkF0M1BRcm5VZnVMczZGVm8zK1d2RkN3UmNwUllIYk1PTCtmaUFMRFQxclFEZHNzZmZFZjRma2o4TE0vV1hVV1pBb3F2bnlGaWl3UWtVQkVBcXJtaHRUN3NBaVhkSi91dUZwT3hFeTR5TXE0bERxRHFHQ2xwOHJOSTRsUGFOSHJQS1BhN1FoeHp1Y25kVGovbXBMSTkrVDlhbDFiOGhudHc2V2g0SGV1NXZEK0NWeko3QmdYN0xscmJ5TVhYN0EvN3JPVlVqWG9zazJoSWR3RFRsV2pvVmRqUHpCdThPRndDNGJ3ZnZIaFdINm0ycWJkeUtZOXRTTEVyNFQxODZQR2xYWWdXeCsxVjl1d3pkeHR3YTJtcFFwalB6U1hOZld6YUFKNzU3aGd2NjdJaE0vTGdyTis2Skg5VThCYlVQc0ZWaU90TENlNWpJZ1F6MTE3RzI1OFlIOTg3TmVOQzdxaHNNRzRvdHZqbzZzWXpRbngrNFRjdmpjVUJ1SDlZZ3RaaXUrbEdIb0NoZzhtSHUzRGlhcXRsZzgyRjJYcjQ4YTVaMFZXVVdEc0pUdS9PaHJ1dWhuWjVscHIwbFpjVURuajZzQmhBUXhVdGFLcUZaU0s0djVwL1ErTGNQYVRsZVJ4dFp4YXV1Si9MNDhEczlIUkorMDM1a1dBTzNIaGFrTjZBWUZHbGo5OGlzK0hNSno5OWhOeVJ4V1Z5TlBFajk3b3grOGJ2WUcyTlFlMXhpdHFpQTQ0SjhpRUJhNDRNdDF2WnhLUC9JNGRQemdaYlFJNDQ1YmJuWitPaE1RUC9xVWRQN0lmUGpKaTU3NlpwYlFqbWlsMzFwcEl1SEVwdEY0TlY5dEt3OFRKYUo2STN6dWtmN2Radm5nMVoreUhadmtVdVBoZG9rcE5HK1YvSGRqOEQ1MFdCWjQ1L25MMTlWQ0V1T3lvQUpWSVlFUVY0OHlMRVAvQ29RK3VGeTVXcmErSkcvdkMvUzFTVEdYaUVTRW40VDNTaFVRc2JyMXdVdXZHc2lZa2xzc2xNNjBXa1FoNTlrQVpQenhmZWM5TXB2U0RKcm9CL0crekhoZCtzZXNoUXJiY2kyeSsxLzd3UXFLck45d0t3VGZENlB3TlpQNkdjVzZrakU2Y2pJWmV1WFg5dEhzVDBsTzFnZUhDamJDZUY4YWR2OUY0TU1LVk4xenk1Nk45UXZwMzIvWHVVclNMdXQ4ZC9jcHA1T3BvNkt5eUlocWF3UUZUd0FYcUlCUWhXRGRjR2FEeW5aR0xMdkpkaU5Rc1hKbFdtSlBjT29tUXpmZkN6cWZ0RDcrYmVXazQ2czF3M1c3Q0pDeTRKWEI4RDhibDE2Tk5DTjBld1ZJQ2ZBRjBPMlBLK0Nzdy9tb3k3a0k1VEV1YUJmU0xTRXBRalBZSjhac1p6azI3TldFMGRNK2hXSW5kTVJPaW9RbWNaVDZ4a1JoSmhDSWsvb2wvejVrV0lTbnUwY0tSVUFvSmNSRVhKbzN1NTBWR3BFY1NsOExyOGVmRzhpdkJFUk1hL29wV0NST3lKeHFhd1MyR1Fpb3JZWXYxUGxTM0wrbE9yY0RsaytBR0JmQUp0NlR1OUR2UlBBMjM4R1ROcG45Z1ZsS2RwWHpsMzlxeGJ5amNvb3U3bmVBb0RjTkRmczhRSHplMlk3cGZsdGNQZHZDY1loYno1aVFnOERmLzJZemIxVkdYdm5pbHBUTUVSeDJNS3ZwOHZiY0xSVWo4RXcrUWJSRkNMSjVMYnpMeHRlRVd2Vi95SnBGYmxOaEJRazRTNFZ4K0tZbm5DaG9tTWU2eVd5MFExa3VFK0o5WUdpSVJFc2VSQTM4Tm9PaDJnWWNBVk5sYzcyWnhMdnl5MTBPRTNMeUsrUHF0RzdTcDE5OUZycjlyM0lKYm9sY1g2cXd0V0hXL3VlbEljTHp2ZWtLS201R2VmdU9LYmxLN2YwK3dmVUlVRzZKMTVRMXpQVE5XbjlNRkV6K0sySEFzc0NGZlJPNHFhNktoaWR3RmwwZHZLcHlTT3V1UkY2b3RIb0QrNVZNdklpQnpzdytoT3VVczNHWi9QYzJjSnJsMUVpRnoxMkRPclM3bmV4cmNjQ2U3MVZ3c2JqSnk2djNtcjRkN2dWUVBnUUlpb1JORUs5aUhGczBONVJJSXF3RFYxakhKeGQ5Tk9wRFQ4NjVBL2t3T0hUOUZIYVNLRUNSVzczWmZYQ1pGU0lJakVnVXI3akZaaEhNUHNXZkVua2Z5Mk9xS2Z4WTRTQmJPZWtnWElVODlWeGFBb3dkZVVIUlNyREI4ZGRHN3RSSys5Nk5SaFdPMThIc0oxOVk1aUJ6eldqMjh6UkJVWE5jVUZ4c0ZTM1hCSG5wa2Z4Q2ExWG9WL1ZSdW5WeHdCcmhxbDVvOVY5ZzZMbDVYcm9kMEVlTHg3RWcwRGFzU2pMdXprcUo5OFdDMUJrSFdSNFJrZ0xOcGxwbXArTGVVQTUwRUpsekJ1K2dLbjE4Q09oV05MYUF5QmxnaFBMemZGMEJFcEs4NmJHNEJzMkYxV3NsaHc2ek9BUERaRXcxZHIwZGpDMGhVT0JPbHY2cEpJN2VBMmJKRXJlTnc1MHV2QjZlTGtDaXJ3OElwWFNQL0JvQUtYMEk3Wk01SWpxWkFsSXB6dThjSStNcmlOYjhJRFYxd0hIcDBYL1JBcVgxQTdvS3o0d3JYbTR2cmY3RUc1d1plTllsRlhIQU16NDZjY1dlanF1cUgxd3dUZTdnL3oxM3dyY1dKY2xLRml0aVVqbEFyTEFWTHRvREFtd0I2ZU9Tc2hQMWZNdXd2NWhhdzlaYW9aWnpvcSs3S0tFKy9zS3dDbU5vVDB1Z1RqNXl0bnBEV2NGbnFmV2dWdHhvc0lrTFNvTjhCWGdRUWtmL255RDZVbXFhWkhKMExnVW5BZXNrcThydU9ubTBVSnczTGNjRUFWTDZ6TCtZWm81cGZVcGprTHJqVHVacE1XU0dXTGtJOGpvek1ZcVVmd1BZM1VCNEhmZFJ4UVM1Q09wcWJFUURsTllXWHpFYUl0M3p6TEJQTHRvQ1ltWjBGMENQNy9oUUExVjVGSGdHdysrVVdzSE01dFJVK1JWOFQrRjlBd0M4Zm0yR0ZXTFlJcVNkSXhIMXlFZExaWEZUdHN2SlR2Mmd0RGRKb0haZ2w0K2lCdllDdEoxdlJyK1l1dU1NNDFYbng3alhRRVpjTkYzbjYrSkw2ZXh0aEpTNjRCbnBraE1nbnhkMW43b0k3ZzB0Q1U3aVZZdmtpSkExSEQ0d0JiajFjZlZGdFFzNU9rT0hjQXJZL0I1eFI5Q2Z1ZkVuRHJKYUtwbGhBclB0bEhFQVA3ei9oRXJnUGREaTNnTzNQSVp3V3hKYVphSUxialdOVklxU09NTEVDbll1UWp1SFdFczBSSWRVM0ZRbjAyeU5mQUg3TkNENmZ1K0QyNHdUNWZmZkt4em4wVnlkWUF6VExCU2VncWhVTzc0K0lWUXVUYkxqYk5LN1RYYkJTOC9wTlJYTkVTQldjQlR3Ti9Ma1I5SUdneWg2UVBhRHVTOHd0WUdZNFpkNFZ0Tk1JcCt3cmtPT09xN3U2MVdxeFpoWlFSRTZyNmlrUkNmVEkvcTJvSXNoVHFyckxsdkJnR1QwbTJiQjJhVnpuV0VDZEIxQTRLZWlmSThKYXVkMDRtaTVDWE9FTDRrZFZSVVhNblB0Q2xZdVFUSEVlOXRPWFJkY0pieGJXVG9URUNtRElIUjNaQ2V3RW9DTGZkc0Y3Z1dMdWdsdlF2cWRjd3hhUVJKR25YWmFQeStlT3JkdXVpR3ZwZ3NOQzZEbWUzVjhkTWdpL3pkd0ZyenRuaGRFWW45VXAwMzNXRkdzblF0SXQ0QlJ3SGtEUi8yWmZwTzVWZU1qcWlBem1GbkR0T1lIM2dJckFxNkEvQWxDVmNaZmwwK3RaQm9VbWpHaW9SajBMbUNpWWgwZjJBQ2o4QTBHL1pOa2o5MFhDM3g5ek5CLzZzck4vZnlvOU4vODNBQWRmbWx3azBwcGd2VVJJRGVjVElPSC91UWhaUDhHaFFWWiszT3NyUWxMZDhzY0wrTGtwQy8zLzJ0M2k3eUx5U1FEVTFxSEpncnRONDdMdWdrWEZXN1lUQkJ4WEJlbXYvSmZ3WmZZZFgvWW81bVppWFVWSXVqQjV0Q3B1VlVWWUlodlpETkhRYks1ZFJJaEJ3Mll3NTJPYVh2OWZMdFpYaEtSYndBclJYSUlYUlFEaFBkRFhBRkFPdVd1RDdoTWl0NEExNHNLV3lGRGVBOTV6U2Z5dUs0WnZnYnlwYWorYUxCUSthS0VJYWNUcGN5T2JSU2lwZ3N6Skh3SW9QQ0FpOXpVN3JSMEYxWGxYSUY4RmJIT1QzdG5mYzFkbk9malNpdWR1ckJWYWJ3SFR1T2YySlpvRDdhWWttbVVndDRBMUZsREE5a0gyQ1NYemFMMElXUUlIb0VjTzdCUzNGbzFTK1NQM3BDRlJ0c2FmZmFzVlFOQlJvcDJJL29VN1RuTG9oWEJMMUN5ajVTSmtLUnlBeG9aM0pTclhWVTMzdDVvSThYVzY2alMyQzdMcGd0TXQ0SlRQWTBYL0dFQlU3Z0g4ZHVZUHVtc0RBdUdXRXREK0ZsQVFKOUowRXBoeWozNVZBQkZHY1J1TkV5MFlrTG02WGoxa1VvU2tXc0NxdndIME8vc2ZBclhwb0NMLzBORzczS2VUTUFPZ3F1ZEVPR2ROS1BZakJFWTVkTHp1Wm9CWlI5dFlRSER0aG5FY1BrQ3E3MWxIc2JKT0ZqQjZOaUJKZGRGMEE3S2VhQnNSc21SOC8yQVIzN015Ty9jWkFGUS9oc2c5THNRdnVXTUpKYkVWYmFzS29MbldzTWZpT2F4UXZRSHlKZ0EzeDE1MDF5cjg2cW1XOWx3MEcrMGpRdEpjY0JyM3ZTZHJFMVJ2akZFVEJFd3pSRWpWQTFLWHVLM3BJZW9RdExjTFR1TytmekRlczNMR0JScEg1TFRqM0M3VjNBNXFZa1Zsd04ydGdFalJuZHQ2aDBwa1VYRnJJRXJFaFNvVTVoSGNIcTVPQktodEFxNkFpS3ZId2J3UWh2Tk5KWk1nYnQ5WlJyRUNPT2srRmFEaUNsOG1laSthaWZZV0lhdmhqbzVzQld4ejRBWFo2ZWcreEJjeXRmYkZDcmRobzdaQnhIVUZhcDhmSkFIaUM4VXN3clRqSmhRTlJKa0cvUkNBd0JVMlpRYkVxVlE5Z3hXcUtRNGRiNHQydTJhajh5emdFams5dWgrUlJoWWw3SUtweEdjTHhGN1NqcFYwM3loSVpZbGRFVzB0SWxhTC93OW1xM0hEcHVqR3NBQUFBQUJKUlU1RXJrSmdnZz09Ij48L2ltYWdlPgo8L3N2Zz4K" k="name"/>
        <prop v="0,0" k="offset"/>
        <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
        <prop v="MM" k="offset_unit"/>
        <prop v="35,35,35,255" k="outline_color"/>
        <prop v="0" k="outline_width"/>
        <prop v="3x:0,0,0,0,0,0" k="outline_width_map_unit_scale"/>
        <prop v="MM" k="outline_width_unit"/>
        <prop v="diameter" k="scale_method"/>
        <prop v="40" k="size"/>
        <prop v="3x:0,0,0,0,0,0" k="size_map_unit_scale"/>
        <prop v="Pixel" k="size_unit"/>
        <prop v="1" k="vertical_anchor_point"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" name="name" value=""/>
            <Option name="properties"/>
            <Option type="QString" name="type" value="collection"/>
          </Option>
        </data_defined_properties>
      </layer>
      <layer enabled="1" class="SimpleMarker" locked="0" pass="0">
        <prop v="0" k="angle"/>
        <prop v="33,150,243,255" k="color"/>
        <prop v="1" k="horizontal_anchor_point"/>
        <prop v="bevel" k="joinstyle"/>
        <prop v="circle" k="name"/>
        <prop v="0,0" k="offset"/>
        <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
        <prop v="MM" k="offset_unit"/>
        <prop v="255,255,255,255" k="outline_color"/>
        <prop v="solid" k="outline_style"/>
        <prop v="0" k="outline_width"/>
        <prop v="3x:0,0,0,0,0,0" k="outline_width_map_unit_scale"/>
        <prop v="MM" k="outline_width_unit"/>
        <prop v="diameter" k="scale_method"/>
        <prop v="25" k="size"/>
        <prop v="3x:0,0,0,0,0,0" k="size_map_unit_scale"/>
        <prop v="Pixel" k="size_unit"/>
        <prop v="1" k="vertical_anchor_point"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" name="name" value=""/>
            <Option name="properties"/>
            <Option type="QString" name="type" value="collection"/>
          </Option>
        </data_defined_properties>
      </layer>
      <layer enabled="1" class="FontMarker" locked="0" pass="0">
        <prop v="0" k="angle"/>
        <prop v="A" k="chr"/>
        <prop v="255,255,254,255" k="color"/>
        <prop v="Arial" k="font"/>
        <prop v="" k="font_style"/>
        <prop v="1" k="horizontal_anchor_point"/>
        <prop v="miter" k="joinstyle"/>
        <prop v="0,-0.40000000000000002" k="offset"/>
        <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
        <prop v="MM" k="offset_unit"/>
        <prop v="255,255,255,255" k="outline_color"/>
        <prop v="0" k="outline_width"/>
        <prop v="3x:0,0,0,0,0,0" k="outline_width_map_unit_scale"/>
        <prop v="MM" k="outline_width_unit"/>
        <prop v="11.8" k="size"/>
        <prop v="3x:0,0,0,0,0,0" k="size_map_unit_scale"/>
        <prop v="Pixel" k="size_unit"/>
        <prop v="1" k="vertical_anchor_point"/>
        <data_defined_properties>
          <Option type="Map">
            <Option type="QString" name="name" value=""/>
            <Option type="Map" name="properties">
              <Option type="Map" name="char">
                <Option type="bool" name="active" value="true"/>
                <Option type="QString" name="expression" value="@cluster_size"/>
                <Option type="int" name="type" value="3"/>
              </Option>
            </Option>
            <Option type="QString" name="type" value="collection"/>
          </Option>
        </data_defined_properties>
      </layer>
    </symbol>
  </renderer-v2>
  <customproperties>
    <property key="dualview/previewExpressions" value="fid"/>
    <property key="embeddedWidgets/count" value="0"/>
    <property key="variableNames"/>
    <property key="variableValues"/>
  </customproperties>
  <blendMode>0</blendMode>
  <featureBlendMode>0</featureBlendMode>
  <layerOpacity>1</layerOpacity>
  <SingleCategoryDiagramRenderer attributeLegend="1" diagramType="Histogram">
    <DiagramCategory penColor="#000000" lineSizeType="MM" maxScaleDenominator="1e+08" spacingUnit="MM" spacing="0" penAlpha="255" lineSizeScale="3x:0,0,0,0,0,0" minimumSize="0" showAxis="0" backgroundColor="#ffffff" scaleBasedVisibility="0" backgroundAlpha="255" minScaleDenominator="0" sizeScale="3x:0,0,0,0,0,0" height="15" spacingUnitScale="3x:0,0,0,0,0,0" rotationOffset="270" sizeType="MM" scaleDependency="Area" penWidth="0" diagramOrientation="Up" barWidth="5" width="15" enabled="0" labelPlacementMethod="XHeight" direction="1" opacity="1">
      <fontProperties style="" description="MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0"/>
      <attribute label="" field="" color="#000000"/>
      <axisSymbol>
        <symbol force_rhr="0" type="line" name="" clip_to_extent="1" alpha="1">
          <layer enabled="1" class="SimpleLine" locked="0" pass="0">
            <prop v="square" k="capstyle"/>
            <prop v="5;2" k="customdash"/>
            <prop v="3x:0,0,0,0,0,0" k="customdash_map_unit_scale"/>
            <prop v="MM" k="customdash_unit"/>
            <prop v="0" k="draw_inside_polygon"/>
            <prop v="bevel" k="joinstyle"/>
            <prop v="35,35,35,255" k="line_color"/>
            <prop v="solid" k="line_style"/>
            <prop v="0.26" k="line_width"/>
            <prop v="MM" k="line_width_unit"/>
            <prop v="0" k="offset"/>
            <prop v="3x:0,0,0,0,0,0" k="offset_map_unit_scale"/>
            <prop v="MM" k="offset_unit"/>
            <prop v="0" k="ring_filter"/>
            <prop v="0" k="use_custom_dash"/>
            <prop v="3x:0,0,0,0,0,0" k="width_map_unit_scale"/>
            <data_defined_properties>
              <Option type="Map">
                <Option type="QString" name="name" value=""/>
                <Option name="properties"/>
                <Option type="QString" name="type" value="collection"/>
              </Option>
            </data_defined_properties>
          </layer>
        </symbol>
      </axisSymbol>
    </DiagramCategory>
  </SingleCategoryDiagramRenderer>
  <DiagramLayerSettings zIndex="0" obstacle="0" priority="0" linePlacementFlags="18" showAll="1" dist="0" placement="0">
    <properties>
      <Option type="Map">
        <Option type="QString" name="name" value=""/>
        <Option name="properties"/>
        <Option type="QString" name="type" value="collection"/>
      </Option>
    </properties>
  </DiagramLayerSettings>
  <geometryOptions geometryPrecision="0" removeDuplicateNodes="0">
    <activeChecks/>
    <checkConfiguration/>
  </geometryOptions>
  <referencedLayers/>
  <referencingLayers/>
  <fieldConfiguration>
    <field name="fid">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="osm_id">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="name">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="amenity">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
    <field name="hstore_to_json">
      <editWidget type="TextEdit">
        <config>
          <Option/>
        </config>
      </editWidget>
    </field>
  </fieldConfiguration>
  <aliases>
    <alias index="0" name="" field="fid"/>
    <alias index="1" name="" field="osm_id"/>
    <alias index="2" name="" field="name"/>
    <alias index="3" name="" field="amenity"/>
    <alias index="4" name="" field="hstore_to_json"/>
  </aliases>
  <excludeAttributesWMS/>
  <excludeAttributesWFS/>
  <defaults>
    <default expression="" applyOnUpdate="0" field="fid"/>
    <default expression="" applyOnUpdate="0" field="osm_id"/>
    <default expression="" applyOnUpdate="0" field="name"/>
    <default expression="" applyOnUpdate="0" field="amenity"/>
    <default expression="" applyOnUpdate="0" field="hstore_to_json"/>
  </defaults>
  <constraints>
    <constraint constraints="3" notnull_strength="1" unique_strength="1" exp_strength="0" field="fid"/>
    <constraint constraints="0" notnull_strength="0" unique_strength="0" exp_strength="0" field="osm_id"/>
    <constraint constraints="0" notnull_strength="0" unique_strength="0" exp_strength="0" field="name"/>
    <constraint constraints="0" notnull_strength="0" unique_strength="0" exp_strength="0" field="amenity"/>
    <constraint constraints="0" notnull_strength="0" unique_strength="0" exp_strength="0" field="hstore_to_json"/>
  </constraints>
  <constraintExpressions>
    <constraint desc="" exp="" field="fid"/>
    <constraint desc="" exp="" field="osm_id"/>
    <constraint desc="" exp="" field="name"/>
    <constraint desc="" exp="" field="amenity"/>
    <constraint desc="" exp="" field="hstore_to_json"/>
  </constraintExpressions>
  <expressionfields/>
  <attributeactions>
    <defaultAction key="Canvas" value="{00000000-0000-0000-0000-000000000000}"/>
  </attributeactions>
  <attributetableconfig actionWidgetStyle="dropDown" sortOrder="0" sortExpression="">
    <columns>
      <column width="-1" hidden="0" type="field" name="fid"/>
      <column width="-1" hidden="0" type="field" name="osm_id"/>
      <column width="-1" hidden="0" type="field" name="name"/>
      <column width="-1" hidden="0" type="field" name="amenity"/>
      <column width="-1" hidden="0" type="field" name="hstore_to_json"/>
      <column width="-1" hidden="1" type="actions"/>
    </columns>
  </attributetableconfig>
  <conditionalstyles>
    <rowstyles/>
    <fieldstyles/>
  </conditionalstyles>
  <storedexpressions/>
  <editform tolerant="1"></editform>
  <editforminit/>
  <editforminitcodesource>0</editforminitcodesource>
  <editforminitfilepath></editforminitfilepath>
  <editforminitcode><![CDATA[# -*- coding: utf-8 -*-
"""
QGIS forms can have a Python function that is called when the form is
opened.

Use this function to add extra logic to your forms.

Enter the name of the function in the "Python Init function"
field.
An example follows:
"""
from qgis.PyQt.QtWidgets import QWidget

def my_form_open(dialog, layer, feature):
	geom = feature.geometry()
	control = dialog.findChild(QWidget, "MyLineEdit")
]]></editforminitcode>
  <featformsuppress>0</featformsuppress>
  <editorlayout>generatedlayout</editorlayout>
  <editable>
    <field name="amenity" editable="1"/>
    <field name="fid" editable="1"/>
    <field name="hstore_to_json" editable="1"/>
    <field name="name" editable="1"/>
    <field name="osm_id" editable="1"/>
  </editable>
  <labelOnTop>
    <field labelOnTop="0" name="amenity"/>
    <field labelOnTop="0" name="fid"/>
    <field labelOnTop="0" name="hstore_to_json"/>
    <field labelOnTop="0" name="name"/>
    <field labelOnTop="0" name="osm_id"/>
  </labelOnTop>
  <dataDefinedFieldProperties/>
  <widgets/>
  <previewExpression>fid</previewExpression>
  <mapTip></mapTip>
  <layerGeometryType>0</layerGeometryType>
</qgis>
